adapters/index.go

@bokelley @asweeney86 for review.

fix user sync macro for index

---

adapters/pubmatic.go

pubmatic already encodes their URL so it got double encoded on the client. 
@asweeney86 @bokelley

Fix pubmatic user sync

---

pbs_light.go

- Switch account metrics to use an RW lock for a read heavy workload.
- Save the result of the map lookup

Account Metrics Locking improvements

---

README.md

I noticed the Dockerfile and wanted to run it in a container, but there weren't any instructions. Added documentation to the README on how to run the binary locally or in a container.

Update README with information on how to use locally and with docker

---

pbs/pbsrequest.go
pbs/usersync.go
prebid_cache_client/prebid_cache.go
prebid_cache_client/prebid_cache_test.go

- json.Decoder accepts an ``io.Reader`` (*http.Request.Body and *http.Response.Body)
- adapters still use io/ioutil for debugging

use json.Decoder when possible

---

README.md

Updating status of Rubicon Adapter to "testing"

Rubicon Project: updating integration status in Readme

---

adapters/rubicon.go

The maximum width and height for rubicon fits into a uint16, by using
a smaller int size we can be nicer to the cache.

Use uint16 for W&H in rubicon sizemap

---

pbs_light.go

we need width and height in the bid cache to properly center an ad in the mobile web view

Add width and height to BidCache object

---

cache/cache.go
cache/postgrescache/postgrescache.go
pbs/cpm_bucketmanager.go
pbs/cpm_bucketmanager_test.go
pbs/pbsrequest.go
pbs/pbsresponse.go
pbs_light.go
static/pbs_request.json

This PR adds ad server targeting keys to the PBSResponse for mobile app requests.
This design allows us to indefinitely expand the functionality of the key generation & granularity settings without app developers having to re-release their apps or us having to simultaneously juggle different versions of the functionality for different versions of Prebid Mobile. Additionally, this allows us to implement the key generation once (on PBS) as opposed to twice (once on iOS, once on Android).
We are adding the ad server targeting keys "hb_pb", "hb_bidder", and "hb_cache_id" to the top bid per ad unit and additionally adding the keys "hb_pb_" + bidder, "hb_bidder_" + bidder, and "hb_cache_id_" + bidder for all of the bids. This mirrors the way it is done on Prebid.js, just moving it to the server …

Generate ad server targeting keys for Prebid Mobile on server

---

pbs/pbsrequest.go
pbs/pbsrequest_test.go

We don't need bidId to be set on the pbs request for mobile. @mkendall07 and I discussed and decided if bidId is ever empty in PBS request that we should generate a UUID to use as bidId when parsing the request. Added unit tests.

If bidder.BidID is empty, set a random UUID for BidId for all PBS requests

---

adapters/adapter.go
adapters/facebook.go
adapters/facebook_test.go
adapters/rubicon.go
adapters/rubicon_test.go

Rubicon adapter appears unable to handle multiple Imp objects per request; splitting them out to send multiple requests with one Imp each.

update rubicon adapter to split requests

---

adapters/adapter.go
adapters/appnexus.go
adapters/facebook.go
adapters/index.go
adapters/pubmatic.go
adapters/pulsepoint.go
adapters/rubicon.go
pbs_light.go

Defaulting to send no-cookies to all adapters; this will help client-side analytics show same numbers as bidders get called.

send requests with no cookies to adapters; allow them to opt out

---

pbs_light.go

This isn't a long term solution, but it doesn't seem that the current metrics library supports adding an influxdb `tag` into a measurement to slice them. So added these for short term as it's critical to have account by bidder metrics.

added account * adapter metrics

---

pbs/pbsrequest.go

This PR removes the code that checks whether app bundle/bundle exists in the database, going forward PBS will forward all the app bundles/domains to bidders.

Remove domain/app whitelisting

---

adapters/openrtb_util.go
adapters/openrtb_util_test.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go
static/pbs_request.json

Needed to request for FB demand. From Prebid Mobile we will pass user object with `buyeruid` field in order to send the bidder token for the FB request.

Add OpenRTB User object for Open RTB mobile requests

---

pbs/pbsrequest.go
pbs/pbsrequest_test.go

In Prebid Mobile v0.0.1 on both iOS and Android user gender is passed as an integer. We recently found out that clients are using v0.0.1 and need to ensure backwards compatibility with that version.
This PR makes the "user" param of PBSRequest a rawJSONParameter so gender can be passed through as a string or integer without throwing an error. If we are not using v0.0.1 of the SDK, we then parse the User object into the openrtb.User object. 
I'm not changing the static pbs_request.json here because we still want the user object to be passed in according to OpenRTB standards.

Ensure backwards compatibility with Prebid Mobile v0.0.1 for User field

---

adapters/facebook.go
adapters/facebook_test.go

This PR moves ~50% of the traffic to non-secure endpoint per FB request.

Fb coin flip

---

pbs_light.go
pbs_light_test.go

We need a new ad server targeting keyword `hb_creative_load_method` to be returned for the winning bid for Prebid Mobile. This keyword will tell us how we need to load the creative, either in html or in native code by the demand SDK. Needed specifically for Facebook demand right now.
Also abstracted out sortBidsAddKeywords functionality to make it easier to unit test and to make the code cleaner.

Add hb_creative_load_method keyword to winning bid.AdServerTargeting in PBSResponse

---

adapters/openrtb_util.go
adapters/openrtb_util_test.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go

This PR addresses the follow up @dbemiller and I discussed [here](https://github.com/prebid/prebid-server/pull/101). Added unit testing to confirm that the new logic works.
I think it still makes the most sense to populate the User BuyerUID for non mobile in `openrtb_util.go` because we're passing the bidderFamily through there, but we can set the User.ID field in parsePBSRequest in `pbsrequest.go`.

Refactor OpenRTB User object in for non-mobile

---

pbs_light.go
pbs_light_test.go

This PR includes changing key hb_creative_load_method to hb_creative_loadtype because DFP only allows 20 chars for the key.

Change hb key chars to be less than 20.

---

adapters/appnexus.go
adapters/appnexus_test.go
adapters/facebook.go
adapters/facebook_test.go
adapters/index.go
adapters/index_test.go
adapters/openrtb_util.go
adapters/openrtb_util_test.go
adapters/pubmatic.go
adapters/pubmatic_test.go
adapters/pulsepoint.go
adapters/pulsepoint_test.go
adapters/rubicon.go
adapters/rubicon_test.go
glide.lock
glide.yaml
pbs/pbsrequest.go

Now that https://github.com/mxmCherry/openrtb is formerly running OpenRTB 2.5, I've updated the various files in prebid-server to import the formal repo instead of the previously created custom fork (prebid/openrtb).  
In addition to the import changes, there were a few var type changes required to use the updated framework; these changes have also been included.

Update references of prebid/openrtb to use mxmCherry/openrtb

---

adapters/openrtb_util.go
adapters/pubmatic.go
pbs/pbsrequest.go
pbs/usersync.go
pbs/usersync_test.go
pbs_light.go

This replaces #91, but incorporates the changes from #106.
When a PBS cookie gets parsed from legacy JSON into a PBSCookie, all UIDs will be considered expired.
When a PBSCookie is asked if a UID exists, it answers "no" if that date has expired.
When a PBSCookie gets written to JSON, it includes the expiration date.
Over time, the legacy cookie JSON will be replaced with the new format, which includes per-bidder TTLs. After 6 months, it'll be safe to delete the logic which reads legacy cookies.

Adding per-bidder TTLs

---

adapters/lifestreet.go
adapters/lifestreet_test.go
pbs_light.go

A Lifestreet adapter for Prebid Server.
Test parameters:
[ { "bidder": "lifestreet", "params": { "slot_tag": "slot178682.159" } } ]
See previous pull requests for more info #125 and #100

Added Lifestreet adapter (3)

---

pbs/pbsrequest.go
pbs/pbsrequest_test.go

Prebid server was only parsing the ip address from non app requests. We also want to parse the ip address for mobile.

Parse ip address from mobile requests to send to bidders

---

adapters/appnexus_test.go
adapters/rubicon.go
adapters/rubicon_test.go

Allow Rubicon Project bidder to respond with KVPs to be passed through to Prebid.js and onto ad server of record.

Rubicon Project server-initiated targeting

---

pbs_light.go

Right now, `prebid-server`drops all existing requests when the process gets killed.
This makes it refuse new requests, and then wait for existing ones to finish before shutting down.

Graceful Server Shutdowns

---

pbs_light.go
prebid_cache_client/prebid_cache.go
prebid_cache_client/prebid_cache_test.go

Use `/cache` instead of `/put` for Prebid Server to cache bids on Prebid Cache for mobile requests. The new endpoint requires `type: "json"` and the value is json instead of a string.

Use new cache endpoint for prebid mobile

---

glide.yaml
pbs/pbsrequest.go
pbs/pbsrequest_test.go

This PR include a fix for a bug that when no SDK value passes in or version 0.0.0 passes in, User object parsing should not be handled.

Gender backwards compatibility bug

---

adapters/openrtb_util.go
adapters/openrtb_util_test.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go
static/pbs_request.json

This PR includes adding a field "instl" on the ad unit, which will be parsed and sent to bidders.
Example of using the field is as the following:
`{  
"max_key_length":20,
"prebid_version":"0.21.0-pre",
"sort_bids":1,
"ad_units":[  
{  
"sizes":[  
{  
"w":300,
"h":250
}
],
"config_id": "3qviqn8hy78bbbubb78y",
"code":"test code",
"instl":1
}
],
"cache_markup":1,
"..."
}`

Add instl on the Ad Unit to be passed to ortb bidders

---

adapters/facebook.go
adapters/index.go
adapters/openrtb_util.go
adapters/openrtb_util_test.go
adapters/pubmatic.go
adapters/pulsepoint.go
adapters/rubicon.go
pbs/pbsrequest.go

We've been seeing more segfaults due to race conditions. [This gist](https://gist.github.com/dbemiller/032abda28d9a577f303da3b3cac0eaef) is a simplified version of the `/auction` code flow. Run it with `go run -race main.go` to see the race condition, and then re-run it after uncommenting the "copy" lines to show it fixed
I _think_ I got all the mutations, and documented which ones are "allowed" on `makeOpenRTBGeneric`... but of course there's no way to be certain.
I do think we need more general improvements so that these race conditions are less likely... but I'll log a separate issue for it shortly.

Fix some race conditions

---

pbs_light.go
pbs_light_test.go

Prior to auction, banner bid objects will now be checked to see if their dimensions (Width & Height) are defined and will induce either of the following reactions if they're not present:
- If the number of ad unit sizes in the bid request is more than one, reject the bid and log a warning message (including details of the rejected bid object)
- If the number of ad unit sizes in the bid request is only one, set the bid object's Width/Height to the corresponding values used in the request and accept the bid
Non-banner type bids (eg video) will not be subjected to this logic and will be handled as normal.

add logic to check for undefined sizes in bids

---

.travis.yml

has been released, and we've been running with it in prod for a little while now.
Updating the `.travis` file so that our CI uses it.

Go version 1.9

---

adapters/openrtb_util.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go
static/pbs_request.json

In case of video request, we expect an `adunit.video` object.

adding missing video property on request.

---

pbs_light.go
pbs_light_test.go

Some publishers want to target hb_size in their line items for custom creative templates that they're using to render the ads.

Add hb_size key for prebid mobile ad server targeting

---

.gitignore
.travis.yml
scripts/check_coverage.sh
scripts/coverage.sh
validate.sh

Added two scripts and a change to the validate.sh script to setup an automatic coverage check on the packages within the PBS framework.  
The coverage.sh file performs the actual coverage check process for each package and then collates the data together into one coverage file.  From the terminal, this script can be ran separately with the --html flag to produce a more detailed coverage report (eg $ ./scripts/coverage.sh --html).
The check_coverage.sh file calls the coverage.sh file and reads through the (coverage) results for each package to detect if any area is below a certain threshold percentage.  Currently this percentage is 20 (to get this implemented and allow for the chance for more unit tests to be written); later, this threshold would ideally be at 80%.
The validate.sh script …

Implement Code Coverage check logic

---

glide.lock
glide.yaml
pbs_light.go

Basically the same as #64... but it looks like that person is unresponsive, and there's a merge conflict.
It's a good change, though. This basically just makes `go get` work on prebid-server.

Fixed the xojoc import. Updated some dependencies

---

adapters/lifestreet.go

Inserting a small change within the LifeStreet adapter to detect if the Imp.Banner object exists before it attempts to nil out the Imp.Banner.Format object.  This is to avoid segfault error when their adapter calls for video adunit.  See RAD-1924

making small change to lifestreet adapater

---

scripts/check_coverage.sh

I think #155 accidentally improved the code coverage in our lowest package... so this raises the bar to match.

Increased the minimum code coverage

---

README.md
docs/endpoints/bidders/params.md

Streamlining the README to be more "normal", and culling lots of scary details that don't need to be the _first_ thing you see.
The link to the `docs/endpoints` directory may be a little premature... but ideally I'd like to add `.md` files in it for every public endpoint. So for example `/bidders/params` is currently documented by `/bidders/params.md`. In the future, `/getuids` would be documented by `docs/endpoints/getuids.md`, etc.

Updating documentation

---

adapters/appnexus.go
adapters/appnexus_test.go
adapters/facebook.go
adapters/facebook_test.go
adapters/lifestreet_test.go
adapters/openrtb_util.go
adapters/openrtb_util_test.go
adapters/pubmatic.go
adapters/pubmatic_test.go
adapters/pulsepoint.go
adapters/pulsepoint_test.go
glide.lock
glide.yaml

This updates to use openrtb v9.0.0 where Banner W,H are now *uint64 instead of uint64. This change is required for us to pass through 0 values for width and height for FB demand for Prebid Mobile.
List of other changes since v6.0.0 are [here](https://github.com/mxmCherry/openrtb/releases)

Update to use openrtb v9.0.0

---

Dockerfile

Found this issue while updating the docs...
In #147, I added a directory to `static`. I tested it locally with the binary... but didn't think to test it inside the docker container. So now, the app immediately crashes because it can't read those files.
This fixes it. According to Docker, `COPY` is preferred over `ADD` anyway: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy

Fixed a bug in the dockerfile

---

docs/developers/contributing.md
docs/developers/deployment.md

Adding some contribution guidelines and info of how to package the app using docker. The latter is slated to be removed from the `README` in #165.

Adding some developer-focused docs

---

glide.lock
glide.yaml
pbs_light.go

Right now, our tests are always failing because of https://github.com/xojoc/useragent/issues/18
This library has caused some other problems in the past (See #64).
Since we're hardly using it, and there are other user agent sniffers out there which allow standard imports, I figured I'd just replace it.

Change useragent parsing library

---

README.md

For a first time setup, Glide fails unless GOPATH is set explicitly.
```bash
enel@enel:~/go/src/github.com/prebid/prebid-server$ glide install
[ERROR]	$GOPATH is not set.
```

Added missing setup step

---

adapters/appnexus/appnexus.go
adapters/legacy.go
endpoints/openrtb2/auction_benchmark_test.go
exchange/adapter_map.go
exchange/exchange.go
exchange/exchange_test.go
pbs_light.go

Fixes #246. Config options are now accessible in `adapter_map`, which is where OpenRTB Bidders are constructed.

Made the config accessible for adapter construction.

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_benchmark_test.go
endpoints/openrtb2/auction_test.go
exchange/adapter_map.go
exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/targeting.go
exchange/utils.go
exchange/utils_test.go
openrtb_ext/bid.go
openrtb_ext/bidders.go
openrtb_ext/bidders_test.go
openrtb_ext/doc.go
openrtb_ext/request.go
openrtb_ext/request_test.go
openrtb_ext/response.go
stored_requests/backends/db_fetcher/fetcher.go
stored_requests/backends/db_fetcher/fetcher_test.go
stored_requests/backends/db_fetcher/postgres.go
stored_requests/backends/db_fetcher/postgres_test.go
stored_requests/backends/empty_fetcher/fetcher.go
stored_requests/backends/empty_fetcher/fetcher_test.go
stored_requests/backends/file_fetcher/fetcher.go
stored_requests/backends/file_fetcher/fetcher_test.go
stored_requests/fetcher.go
validate.sh

I've seen a bunch of PRs lately indicating that `gofmt` is happening unreliably.
This fixes at least one bug in the `./validate.sh` script, and contains the `gofmt` fixes for all the files.

Fixed a bug in the validate script, and then fixed formatting issues.

---

pbs_light.go

using exapi-us-east as an endpoint is better -- staged-by is not meant to handle ongoing production traffic.

changing default rubicon endpoint

---

exchange/cache_test.go

Fixes #290.
This assertion implicitly relies on map iteration orders, which are not deterministic in Go.
I also don't think it actually adds any value. Since the `mockClient` implementation does JSON-compares to assign the the right ID to the right Imp, the `assertStringValue` lines would fail if `cacheBids` didn't forward all the right JSON.

Removed unreliable assertion

---

pbs_light.go

I'm pretty sure @hhhjort told me about this... but I forgot about it until now. Logging the password to the app logs is a security risk, depending on your infrastructure.

Stop logging Postgres password

---

docs/developers/code-reviews.md
docs/developers/contributing.md

Just to formalize things a bit.
I suspect we'll want to change these pretty aggressively once we start trying to follow them. Tough to tell what works without trying it, though.
From what I've seen in Prebid.js so far, that second reviewer tends to cost more than they add in value. And since this is not a client-side library, we can fix critical bugs and release updates much more quickly and easily than in that project.
So I chose here to make that second reviewer optional, introducing a waiting period instead. This idea was cherry-picked from [the Node.js standards](https://medium.com/the-node-js-collection/healthy-open-source-967fa8be7951), because I think it's a good one.

Documenting the code review process

---

openrtb_ext/request.go
pbs_light.go
pbs_light_test.go

1. Fix #288: `"sort_bids": 1` in the request would call `sortBidsAddKeywordsMobile` which would overwrite any existing KVPs in `"ad_server_targeting"`.
2. Cleanup extraneous `ExtRequestTargetingPlain` type and instead use a type alias.

Various Targeting-Related Changes

---

adapters/audienceNetwork/facebook.go

Facebook returns bids however showing the following error:
```"errors": {
"audienceNetwork": [
"invalid BidType: "
]
}
```
The reason is that adapter communicates with FB using ortb but internally transforms it to a PBSBid object during which no creative type is set on the PBSBid, since FB doesn't return any from server.

add creative type on facebook adapter

---

exchange/legacy.go
exchange/legacy_test.go

Another but which @anwzhang surfaced...
Requests sent to a Legacy bidder which include Targeting were not working properly. The root cause was this line, which seems like a simple logic bug.
Regression test included to make sure this doesn't happen again later.

Fixed a bug in Targeting + Legacy Adapters

---

adapters/audienceNetwork/facebook.go
adapters/bidder.go
adapters/legacy.go
exchange/adapter_map.go
pbs_light.go

@anwzhang was missing a config option and got obtuse errors from the facebook adapter. Whenever she tried to run an auction, the response was:
```
{
"id": "blahblah",
"ext": {
"errors": {
"audienceNetwork": [
"json: error calling MarshalJSON for type openrtb.RawJSON: invalid character '}' looking for beginning of value"
]
},
"responsetimemillis": {
"audienceNetwork": 0
}
}
}
```
The root problem is that facebook's adapter requires a `partnerID`, which is set in your app config. During development, it's easy to skip this in your app config... and this is the behavior you'll see. 
I don't think we can assume that every PBS host (and every developer) can has a `partnerID` with facebook... so we can't just `glog.Fatal` and crash the process on bad config. As a next best thing, this improves …

Added an error if audience network is misconfigured

---

docs/developers/stored-requests.md
docs/endpoints/openrtb2/auction.md
endpoints/openrtb2/auction_test.go
exchange/bidder_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/targeting.go
openrtb_ext/request.go
openrtb_ext/request_test.go

Fixes #321.
I thought Prebid.js supported this... but apparently I was wrong. Best to leave this out until there are real use-cases for it.

Removing request.ext.prebid.targeting.lengthmax

---

docs/bidders/audienceNetwork.md
docs/bidders/rubicon.md

This documents some special cases we found while testing the audience network adapter recently.
Also fixes #272, because it's easy.

Added some docs for special adapter rules

---

stored_requests/backends/db_fetcher/fetcher.go
stored_requests/backends/db_fetcher/fetcher_test.go

Fixes #338 ...hopefully. It's tough to say for sure, because it's not really reproducible... but it seems like this should help.

Discard data more liberally on database errors.

---

adapters/appnexus/appnexus.go
adapters/rubicon/rubicon.go
endpoints/openrtb2/race_test.go

High priority changes to fix some race conditions which are crashing us in prod.
Don't pay much attention to `race_test.go`; I'm going to be rewriting it very shortly, building it such that it won't be overlooked by new adapter submissions. I'm including it because it proves that this fixes some real race conditions.
You can verify with `go test -race github.com/prebid/prebid-server/endpoints/openrtb2 -run ^TestRequestConcurrently$ -count 100`. On `master`, it shows a bunch of race conditions. On this branch, it passes cleanly.

Fixing some race conditions

---

adapters/appnexus/appnexus.go
adapters/appnexus/appnexus_test.go
adapters/appnexus/appnexustest/exemplary/simple-banner.json

This fixes a long-standing hack in the appnexus adapter, for both legacy & OpenRTB endpoints.
Previously, there was some logic which basically assumed that the bid was video if possible, and banner otherwise. This is super fragile, because it used insider knowledge of impbus to "guess" which type of response it was. If impbus changed their bidding strategy, this code could easily assign the wrong type to the bid.
I asked impbus to return the bid type in their response `ext`, which they've now finished. This should be more reliable, which I count as a precondition for supporting Native.

Improve appnexus multiformat auctions

---

scripts/check_coverage.sh

This fixes #315
Looks like this was caused by two things:
- `set -e`: makes the script exit immediately if any line errors
- `OUTPUT=./scripts/coverage.sh`: Saves `stdout` of `coverage.sh` to `OUTPUT` (rather than printing it to the terminal). If `coverage.sh` fails, then this line fails too... which triggers `set -e` so that the script exits without printing anything.
I basically just removed `set -e`, and checked the return from `coverage.sh` explicitly.

Fixed #315

---

exchange/bidder_test.go

This fixes #369, I hope.
I'll re-run the Travis builds on this PR a bunch of times to see if any of them fail. Given that this test failure is intermittent, I'm a bit suspicious that there's some lag time between the `cancelFunc()` call and the time when the context is _actually_ cancelled.
If I've guessed the problem correctly, then blocking to wait for the channel to close should solve it.

Block mock server on context cancel

---

scripts/check_coverage.sh

Must have introduced this during that last-minute rewrite in #315. Without `set -e`, we need to check this return code explicitly.

Checked response code of test in --cov mode.

---

docs/endpoints/openrtb2/amp.md
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go

This is part of my attempt to address mass confusion surrounding AMP.
Functionally, this sets defaults for `request.ext.prebid.cache` and `request.ext.prebid.targeting`, which should make AMP easier to use.
I also updated the docs to make it clearer what's expected and what's not, remove AMP implementation details, and link to more thorough documentation.
I will also be looking for ways to improve the `/openrtb2/auction.md` file... but I think that's better left for another PR.

Amp usability improvements

---

endpoints/openrtb2/amp_auction.go

AMP CORS headers should be present on error responses, so set them near the beginning of the handler func.

Ensure AMP CORS headers are present on error responses

---

exchange/auction.go
exchange/exchange.go
exchange/exchange_test.go

This partially reverts #380.
I thought I could guard against `nil` values and filter them out sooner than was actually safe... but apparently it wasn't safe. There just seem to be no unit tests checking to make sure that `ext.debug.httpcalls` is populated properly.
We should beef up the unit tests in `exchange`, because _something_ should have failed as a result of this bug, but... this at least fixes it for now.

Fixing a debugging info bug

---

adapters/appnexus/appnexus.go

Stack trace from the problem is here:
```
panic: runtime error: index out of range
goroutine 119248 [running]:
github.com/prebid/prebid-server/adapters/appnexus.(*AppNexusAdapter).Call(0xc45a04a2c0, 0xd1c520, 0xc4a6395860, 0xc4a6634700, 0xc4a6642780, 0x0, 0x0, 0x0, 0x0, 0x0)
/some/path/prebid-server/adapters/appnexus/appnexus.go:102 +0x1e1d
main.(*auctionDeps).auction.func1(0xd1b020, 0xc45a04a2c0, 0xd1c520, 0xc4a6395860, 0xc4a6634700, 0xc420124700, 0xc4a68b6c80, 0xc4a6577d00, 0xc4a68d7620, 0xc4a6642780)
/some/path/prebid-server/pbs_light.go:370 +0xa2
created by main.(*auctionDeps).auction
/some/path/prebid-server/pbs_light.go:368 +0x62a
```

Quick fix for some segfaults in legacy code

---

endpoints/openrtb2/auction.go

Prebid Server double encodes native request that's sent to bidders, causing bidders unable to bid.
This fix removes one of the encoding so it works fine now.

fix native request double encoding

---

docs/endpoints/openrtb2/amp.md
endpoints/openrtb2/amp_auction.go

fixes #402 , AMP spec requires secure content URLs, so no use cases for insecure ads.

Set secure=1 on AMP requests

---

adapters/appnexus/appnexus.go
adapters/appnexus/appnexustest/exemplary/native-1.1.json
adapters/appnexus/appnexustest/exemplary/optional-params.json
adapters/appnexus/appnexustest/exemplary/simple-banner.json
adapters/appnexus/appnexustest/params/race/banner.json
adapters/appnexus/appnexustest/params/race/video.json
adapters/appnexus/params_test.go
openrtb_ext/imp_appnexus.go
static/bidder-params/appnexus.json

We want to move the appnexus parameters from camelCase to snake_case. This affects 3 parameters (`placementId`, `invCode`, and `trafficSourceCode`). In this PR, the appnexus adapter will accept either version of the parameter name, at some point in the future we will disable the old names. We also add one new parameter: `use_pmt_rule`.

Updates 3 parameter names and adds one new one

---

endpoints/openrtb2/amp_auction.go

Simple little update. Default AMP timeout on the client side is 1000 ms, so if the stored request doesn't set a timeout, we use 900 ms. This gives us 100 ms for transit and PBS overhead.

Adds a reasonable default timeout for AMP auctions

---

.gitignore

Looks like a 19MB binary debug file was accidentally merged in [#248](https://github.com/prebid/prebid-server/pull/248/files#diff-ad42f6697b035b7580e4fef93be20b4d). This removes it and adds it to `.gitignore`.

Remove debug file

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go

OpenRTB lets you specify whether the auction is a first price or second price auction.
Since we're header bidding, we're almost always a first-price auction. As always, this default can be overridden if it's defined by the HTTP Request or Stored Request explicitly.

Default OpenRTB to first-price auction

---

exchange/exchange.go
exchange/validation_test.go

Per #431, we've got to revert this temporarily so that Bidders have a breaking change window to implement this on their servers.
After a month or so, we can revert this and require it again.

Reverted the crid requirement temporarily

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/invalid-whole/bid-adjustment-invalid-bidder.json
endpoints/openrtb2/sample-requests/invalid-whole/bid-adjustment-negative.json
endpoints/openrtb2/sample-requests/valid-whole/bid-adjustments.json
exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go
exchange/exchange_json_test.go
exchange/exchange_test.go
exchange/exchangetest/aliases.json
exchange/exchangetest/bid-consolidation-test.json
exchange/exchangetest/bidadjustmentfactors.json
exchange/legacy.go
exchange/legacy_test.go
openrtb_ext/request.go

Fixes #350.
I also made some "exchange => adapter" JSON tests, because all of our existing ones are pretty fragile. Many of our tests in this package hit a lot of private methods and implementation details... and I've found them really hard to debug and maintain while working on a few of these recent features (aliases, targeting, and now this).
Although I think we can use this framework to replace most of the tests inside `exchange_test.go`, `utils_test.go`, and `targeting_test.go`, I left all those in for now to prove that I haven't broken anything. If you all like the JSON-style tests overall, I can port them in a folllowup PR.

Bid cpm adjustments

---

pbs_light.go

Quick fix for metrics null pointer in legacy auction when JSON parsing fails.

Legacy metrics fix

---

pbs_light.go

One little line got lost. For the lack of a line the legacy exchanges got lost. For lack of the legacy exchanges PBS was lost.

Metrics fix #2

---

config/config.go
config/stored_requests.go
pbs_light.go
pbs_light_test.go
stored_requests/caches/in_memory/lru.go
stored_requests/caches/in_memory/lru_test.go
stored_requests/events/api/api.go
stored_requests/events/api/api_test.go
stored_requests/events/events.go
stored_requests/events/events_test.go
stored_requests/fetcher.go
stored_requests/fetcher_test.go
stored_requests/multifetcher_test.go

Proposed partial solution for #392. Includes implementation of an HTTP endpoint that could be exposed either behind authentication or on a private network to allow cache updates and invalidations.
**Example:** (adding hypothetical implementations for memcached `Cache` and Kafka `EventProducer`)
```go
// fetch from DB
db := db_fetcher.NewPostgresDb(dbCfg)
pgFetcher := db_fetcher.NewFetcher(db, cfg.Postgres.MakeAmpQuery)
// layer in-memory LRU on top of shared memcached instance
lruCache := in_memory.NewLRUCache(lruCfg)
memcachedCache := memcached.NewMemcachedCache(mcCfg)
caches := ComposedCache{lruCache, memcachedCache}
// subscribe caches to updates/invalidations from Kafka stream
kafkaEvents := events.NewKafkaEvents(kafkaCfg) 
listener := Listen(caches, kafkaEvents)
// layer caches on …
```

[Proposal] Rework stored request caches to allow propagation of invalidation/updates

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go

During #452, I noticed that the AMP default targeting doesn't include keys for the winning bids.
This isn't the intended default. I don't know if it's the root cause of #452... but it's something we should fix regardless.

AMP targeting defaults should included the winning targets

---

pbsmetrics/go_metrics.go

This is a spinoff from #456. I moved it into its own PR because it's really a separate changeset.
Basically I needed to add a `blankCounter` there... but then I stumbled on the `NilCounter` in the core go-metrics library. Turns out they had `Nil*` objects for all the other types too... so we may as well use them, unless there's some good reason not to.

Replace Blank Metrics

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go

Also removed `purl` as per #420

Fix bug in AMP query param handling; add test

---

config/config.go
docs/endpoints/status.md
endpoints/status.go
endpoints/status_test.go
pbs_light.go

Following some more requests about this... apparently different types of test frameworks require different responses from the health check.
Making this configurable so we can beef up our CI.

Configure status response

---

.gitignore
openrtb_ext/bidders.go

When trying to run the project on Windows, I received the following error:
```
F0322 22:26:04.060973    9724 pbs_light.go:904] Failed to create the bidder params validator. Failed to load json schema at ./static/bidder-params/adform.json: Reference {0xc042133780 {[]} false true false true false} must be canonical
goroutine 1 [running]:
```
These changes resolve this error.
I also added .vscode/ to the .gitignore file.

Windows - Resolved load json schema error

---

adapters/rubicon/rubicon.go

Propagates GDPR attributes in the rubicon adapter.

Rubicon adapter support for GDPR

---

server/server_test.go

Was looking at general code coverage and noticed this `wait` method wasn't covered... this test (which was intended to cover it) didn't. Seems like a careless mistake.

Made a test useful again

---

adapters/adform/adform.go
adapters/appnexus/appnexus.go
adapters/audienceNetwork/facebook.go
adapters/bidder.go
adapters/conversant/conversant.go
adapters/pubmatic/pubmatic.go
pbs_light.go

Followup changes to #467... some error messages were not getting pruned from the logs because adapters returned errors as a pointer-type, but the type-check in `pbs_light.go` looked for a concrete struct-type.
See https://play.golang.org/p/uHl9SCmD_pw
By changing `func (err BadInputError) Error() string` to `func (err *BadInputError) Error() string`, the code no longer compiles if someone passes back the concrete struct. Apparently the original version let them work either way.

Used the pointer error type consistently everywhere

---

exchange/exchange.go
pbsmetrics/go_metrics.go
pbsmetrics/go_metrics_test.go
pbsmetrics/metrics.go

Pretty self-explanatory... goal here is to capture metrics how frequently Bidders use Adm vs. NURL for each bid type, to help prioritize features.

Collect nurl/adm metrics

---

docs/developers/add-new-bidder.md
exchange/exchange.go
exchange/validation_test.go

This PR includes a breaking change for Bidders.
This was originally added in #414, complained about in #427, and reverted in #432. It is scheduled to be merged sometime in early May, to allow Bidders time to make the necessary changes.
See the `docs/developers/add-new-bidder.md` file in the diff for a summary of the changes.

Require Bid.CrID properties

---

docs/developers/cookie-syncs.md
docs/endpoints/cookieSync.md
docs/endpoints/setuid.md

Beefing up the cookie sync docs.
I started writing GDPR docs, and realized I was describing lots of things which are already happening today. I figured I may as well put them in a separate PR which we can merge sooner.

Added technical docs on cookie syncs

---

adapters/adapterstest/test_json.go
adapters/adform/adform.go
adapters/adform/adform_test.go
adapters/adform/adformtest/supplemental/user-nil.json

Saw some errors about nil-dereferencing in the logs recently... this fixes those.
Also includes some updates to the `test_json` file because the adform request body is empty, and the JSON tests didn't handle that very well.
@volhalink @vstatkevich I'm not sure what request you actually expect on your server if the `User` or `Device` are nil. You should check this and update it. This just stops your code from crashing if they are.

Fixed some nil-pointers in the Adform adapter

---

usersync/adform.go
usersync/appnexus.go
usersync/appnexus_test.go
usersync/conversant.go
usersync/conversant_test.go
usersync/indexExchange.go
usersync/indexExchange_test.go
usersync/lifestreet.go
usersync/lifestreet_test.go
usersync/openx.go
usersync/openx_test.go
usersync/pubmatic.go
usersync/pubmatic_test.go
usersync/pulsepoint.go
usersync/pulsepoint_test.go
usersync/rubicon.go
usersync/rubicon_test.go
usersync/sovrn.go
usersync/sovrn_test.go
usersync/usersync.go
usersync/usersync_test.go

This contributes towards #501 by building a mechanism for Bidders to identify themselves as part of the IAB's [Global Vendor List](https://vendorlist.consensu.org/vendorlist.json).
Existing Bidders who are already on the vendor list should verify that I got the right ID here.
There are no functional changes yet.

GDPR-aware Usersyncers

---

config/config.go
config/config_test.go
pbs_light.go

Fixes #503.
No functional changes here... just getting the app config ready for more GDPR support.

Added GDPR to the app config

---

adapters/openrtb_util.go
adapters/openrtb_util_test.go
exchange/legacy.go
pbs/pbsrequest.go

Please review the following change that passes along the two GDPR parameters for legacy adapters.  Essentially the adapters do not need to change as long as the openrtb request generated by MakeOpenRTBGeneric is used directly.
* Add Regs to PBSRequest
* Pass along Regs in legacy conversion
* In MakeOpenRTBGeneric, picks up User.Ext if available, and also picks up Regs.

GDPR support for legacy adapters

---

pbs_light.go

Switching Conversant adapter to point to a new sub-domain

Update Conversant adapter to use new domain

---

docs/endpoints/openrtb2/auction.md
exchange/exchange.go
exchange/exchangetest/targeting-only-winners.json
exchange/targeting.go
exchange/targeting_test.go
openrtb_ext/request.go

Adds ext.prebid.targeting.includebidderkeys, defaults to true (current behavior) and supports setting it false. You will need includewinners set true (true by default) or no targeting set for a valid request.

Support not sending all bidder keys in targetinng

---

docs/endpoints/setuid.md
endpoints/setuid.go
endpoints/setuid_test.go
gdpr/gdpr.go
gdpr/impl.go
gdpr/impl_test.go
gdpr/vendorlist-fetching_test.go
pbs_light.go
pbsmetrics/go_metrics.go
pbsmetrics/go_metrics_test.go
pbsmetrics/metrics.go

This fixes #504, updating the `/setuid` endpoint. See the issue (or the docs in the PR) for the behavior.

GDPR-friendly /setuid 

---

gdpr/impl.go
gdpr/impl_test.go
gdpr/vendorlist-fetching_test.go

This makes two changes based on recent finds:
1. It removes the logic which lets syncs happen based on legitimate interest.
2. It updates the logic so that bidder syncs happen if they have consent _to access the cookie_--not based on ad personalization.
------------------------------------------------------------------------------------------
There are some [new pubvendors.json docs](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/pubvendors.json%20v1.0%20Draft%20for%20Public%20Comment.md#sspdsp-integration-), which say
> If a publisher whitelists a vendor claiming legitimate interest then Legitimate Interest can take precedence over the information in the Consent String
I thought legitimate interest took precedence over consent... but …

Removed legitimate interest, updated "allow sync" logic

---

docs/endpoints/cookieSync.md
endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
endpoints/setuid_test.go

If `gdpr` is in effect, we can't do anything without a `gdpr_consent` string. This just makes it official with a 400 response.
This is technically a breaking change, but... very low risk, since it these APIs were only released about an hour ago.

Require consent string if gdpr is active

---

config/config.go
config/config_test.go
endpoints/openrtb2/auction.go
pbs_light.go

This adds a configurable max timeout for auction requests. "0" means "no limit".
This lets PBS hosts effectively cap the max auction timeout they're willing to allow, which is important for some technical reasons.
I also found that the `DefaultTimeout` config option was unused throughout the code, so I deleted it.

Made auction max timeout configurable.

---

config/config.go
config/config_test.go
endpoints/openrtb2/auction.go

following up on @hhhjort's suggestion in #524... this separates the "max allowable" timeout from the default which gets used if the caller doesn't give us one.

Added a default auction timeout

---

adapters/adform/adform.go
adapters/appnexus/appnexus.go
adapters/bidder.go
adapters/conversant/conversant.go
adapters/openrtb_util.go
adapters/pubmatic/pubmatic.go
pbs_light.go

This silences some more error messages we can't really do anything about... either because they're errors from the caller or the remote server.
```
W0524 14:34:00.258090       1 pbs_light.go:253] Error from bidder pulsepoint. Ignoring all bids: HTTP status: 500
W0524 14:44:52.729724       1 pbs_light.go:253] Error from bidder districtm. Ignoring all bids: Invalid AdUnit: VIDEO media type with no video data
```

Cleaning up more useless log errors

---

validate.sh

#526 noted that `./validate.sh --nofmt` produced blank output. I got this while running it on their branch:
```
dbemiller-mac:prebid-server dbemiller$ ./validate.sh --nofmt
gofmt needs to be run, 1 files have issues.  Below is a list of files to review:
```
This PR fixes that. Looks like it was still printing a hardcoded list of files, so formatting issues in these new directories wouldn't get printed properly.

Fixed ./validate.sh --nofmt output bug.

---

adapters/adform/adform_test.go
adapters/appnexus/appnexus_test.go
adapters/audienceNetwork/facebook_test.go
adapters/conversant/conversant_test.go
adapters/lifestreet/lifestreet_test.go
adapters/pubmatic/pubmatic_test.go
adapters/pulsepoint/pulsepoint_test.go
adapters/rubicon/rubicon_test.go
adapters/sovrn/sovrn_test.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go
pbs_light.go
pbs_light_test.go

`ParsePBSRequest` (legacy code) had an explicit call to `viper.GetInt("default_timeout_ms")`
This bit me recently, because I assumed that the `Configuration` object was the source of truth, and removed that property from the app config
So... this uses the `Configuration` object and passes it around everywhere.

Remove ad-hoc Config reads

---

endpoints/openrtb2/auction.go

Looks like we forgot to handle these errors... which made some error messages really janky.
For example, on `master` if you make a request with an unknown Stored Imp ID, it gives:
```
Invalid request format: Invalid JSON Document
```
With these changes, it gives:
```
Invalid request: Stored Imp with ID="a36d4986-e8ed-4600-b701-711280205985" not found.
```

Checked for some missing errors

---

static/bidder-params/pulsepoint.json

In https://github.com/prebid/Prebid.js/issues/2623, one of the bidder params uses a capital `X` to separate the width & height of `cf` param.
This looks like it's what the `pulsepoint.md` example in their Prebid.js file expects... so I figured we'd just change it here.
We need to accept both forms, of course, since there may be `x` sizes in the DB. This fixes #535

Make Pulsepoint params accept values like "200X150"

---

adapters/pulsepoint/pulsepoint.go
adapters/pulsepoint/pulsepoint_test.go
static/bidder-info/pulsepoint.yaml

Currently the validation `ParseBidType` in `bid.go`, rejects the bids submitted from the `pulsepoint` bidder. Test page [here](http://projects.contextweb.com/av/gdpr/pb_s2s.html).

pulsepoint bidder: Adding BidType to Bids

---

endpoints/setuid.go
pbs_light.go
pbs_light_test.go

Was looking at our `/setuid` metrics... and it became clear that nearly all the traffic to it was coming from legacy `/auction` requests.
Unlike `/openrtb2/auction` calls, `/auction` calls return cookie syncs (similar to `/cookie_sync`). And while the newest versions of `Prebid.js` ignore these, there must still be a lot of older versions out in the wild.
Although our `/setuid` endpoint rejects these, everyone will see much better performance if we never return them in the first place.

setuid metrics and legacy auction fixes

---

exchange/adapter_map.go
openrtb_ext/bidders.go
usersync/cookie.go
usersync/usersync.go
usersync/usersyncers/somoaudience.go
usersync/usersyncers/somoaudience_test.go
usersync/usersyncers/syncer.go

This PR just has a few minor cleanups.
I alphabetized the various maps, because this reduces the chance of code conflicts when multiple adapters get submitted.
I also noticed in #516 that they were following the docs, but the docs for `FamilyName()` on the `Usersyncer` were outdated. This updates the docs, leaves a TODO there, and updates their usersync key to be the bidder name instead, to be consistent with all the other bidders out there.

Cleaning up some maps and syncer docs

---

.travis.yml

This includes #553, with a few extra changes:
- The API key to one I just made & encrypted
- The repo to `prebid/prebid-server`
- The release branch to `master`
- Moves some commands to `before_deploy` so that they don't slow down normal PR builds
Thanks @benjaminch!
If you have time to test out using `before_deploy` in your fork, I'd definitely appreciate it. If not, not a huge deal.

Include binaries in releases

---

config/stored_requests.go
config/stored_requests_test.go

Bug from #539 which is blocking release... unbounded caches don't require a TTL. In fact they don't support one at all.
I also tightened up the validation on cache size, just because it was a little loose.

Fixed the validation logic on unbounded caches

---

config/config.go
config/stored_requests.go
config/stored_requests_test.go
pbs_light.go

There should be no breaking changes here. Goals are to:
1. Log all the config values which _aren't_ sensitive (e.g. passwords) when the app starts.
2. Validate the entire config at once, and return all the error messages rather than quitting after the first one.
A bad config produces errs like these on app startup:
```bash
I0613 11:35:43.478783   62284 config.go:127] gdpr.host_vendor_id=32
I0613 11:35:43.478787   62284 config.go:128] gdpr.usersync_if_ambiguous=false
I0613 11:35:43.478792   62284 config.go:145] gdpr.timeouts_ms.init_vendorlist_fetches=60000
I0613 11:35:43.478797   62284 config.go:146] gdpr.timeouts_ms.active_vendorlist_fetch=1000
F0613 11:35:43.478809   62284 pbs_light.go:649] Configuration could not be loaded or did not pass validation: validation errors are: …
```

Improve config logging & validation

---

config/structlog.go
config/structlog_test.go

The adaptor configs are stored in a map, so were left out of logging. This fixes #561

Adds map support to config logging.

---

endpoints/version.go
endpoints/version_test.go
pbs_light.go
server/server.go
server/server_test.go

This CL includes:
* Creating a new handler `/version` exposing the current binary
revision
* Update Building scripts
This CL doesn't include:
* The newly created endpoint `/version` is not set in the router, it
will be added in another CL
Add an endpoint exposing binary revision #559

Adding  endpoint exposing prebid-server version

---

adapters/adform/adform_test.go
adapters/appnexus/appnexus_test.go
adapters/audienceNetwork/facebook_test.go
adapters/conversant/conversant_test.go
adapters/lifestreet/lifestreet_test.go
adapters/pubmatic/pubmatic_test.go
adapters/pulsepoint/pulsepoint_test.go
adapters/rubicon/rubicon_test.go
adapters/sovrn/sovrn_test.go
config/config.go
endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/setuid.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go
pbs/usersync.go
pbs_light.go
pbs_light_test.go
usersync/cookie.go
usersync/cookie_test.go

Fixes #582.
The core fix here is moving some logic from `pbs.ParsePBSRequest` into `usersync.ParsePBSCookieFromRequest`.
This changed the method signature a bit... so lots of other little places around the code had to change too.
This also surfaced another wart: `config.HostCookie` is _exactly_ the same as `pbs. HostCookieSettings`.  Rather than converting one into the other, I just deleted `pbs.HostCookieSettings` and replaced those calls with `config.HostCookie`.

Fixes OpenRTB host company cookie sync issue

---

docs/bidders/appnexus.md

@khatibda recently uncovered some weirdness while trying to use the Appnexus keywords through PBS.
This documents it in the best way we have available at the moment.

Document appnexus keywords quirkiness

---

cache/postgrescache/postgrescache.go

This prevents requests from piling up and stalling PBS when the database goes down.
Being pretty lazy about the fix b/c it's in the legacy code... but this should get the job done. This timeout is the same as is used for the DB in `/openrtb2/auction`, and our metrics show that it's plenty of time.

Use a context when fetching legacy stuff from postgres

---

exchange/exchange.go

`defer` statements still evaluate the function arguments immediately--even though the function doesn't actually execute with them until later.
This is obfuscating the data we need to understand what's going on in #592.

Fixed a bug in the adapter metrics

---

adapters/bidder.go
adapters/info.go
adapters/info_test.go

This contributes to #555.
Goal here is to make an object which wraps a Bidder and screens invalid bids before calling it.
In a future PR, this can be used to simplify adapter code. For example, in the APN adapter, we have:
```
if imp.Audio != nil {
return "", &adapters.BadInputError{
Message: fmt.Sprintf("Appnexus doesn't support audio Imps. Ignoring Imp ID=%s", imp.ID),
}
}
```
Other adapters do similar. This offers a way to consolidate that logic into one place and standardize the error messages.

Adding a decorator which enforces the {bidder}.yaml info files

---

adapters/conversant/conversant.go
config/config.go

Remove 'http:' from the conversant user sync URL so it works with both secure and non-secure protocols.

Update conversant usersync url to be protocol relative

---

Dockerfile

In old Dockerfile, you build go binary outside of the docker. Because of this, the binary can be linked with glibc and it will crash when it starts inside the alpine container (alpine uses musl, that not compatible with glibc).
Solution: build the go binary in an alpine environment.

Build go binary inside alpine container

---

adapters/beachfront/beachfront.go

I noticed this while working on #604.
`pkg/errors` is a third-party lib... which we're not using. It's a transient dependency... so PBS doesn't build unless you run `dep ensure` again to pick it up. But when you do, it changes your lockfile.
So... this reverts it to plain old `errors`.

Fixed beachfront imports

---

server/server.go

b/c it called `newPrometheusServer` without checking the config, and triggered:
```
if proMetrics == nil {
glog.Fatal("Prometheus metrics configured, but a Prometheus metrics engine was not found. Cannot set up a Prometheus listener.")
}
```
Fixes #614

PBS crashes on startup if prometheus isn't configured

---

stored_requests/config/config.go

Tiny bugfix for an issue I found while debugging something else.
This has pretty minimal impact... if the app config doesn't include a database connection, then there's a nil dereference when trying to shut down the server.
Still... a little annoying.

Close the database safely

---

exchange/exchange_test.go

Because we run tests before release, and this test is broken because of external dependencies.
I can confirm that it's due to external dependencies because `./validate.sh` still hangs if I, `git checkout 0.35.3`, and that version was definitely working in the past.

Commented out the broken test.

---

adapters/appnexus/appnexus.go
adapters/audienceNetwork/facebook.go
adapters/beachfront/beachfront.go
adapters/conversant/conversant.go
adapters/indexExchange/index.go
adapters/lifestreet/lifestreet.go
adapters/openrtb_util.go
adapters/openrtb_util_test.go
adapters/pubmatic/pubmatic.go
adapters/pulsepoint/pulsepoint.go
adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go
adapters/sovrn/sovrn.go

Fixes #603.
We'll have to release this careful and watch the bid responses when we do. It changes `/auction` behavior for all bidders, and `/openrtb2/auction` for bidders who haven't updated yet (see #603 for the list).
but... I have to imagine that the risk is worth it. In OpenRTB, you can't interpret bid responses unless each Imp had a unique ID. The code path which I deleted here was splitting a single legacy AdUnit into two Imps with the same ID... which should cause some nonsense to happen.

Handle legacy => openrtb multiformat imps better.

---

adapters/conversant/conversant.go
static/bidder-info/conversant.yaml

Seeing some nil-pointer dereferences related to this:
```
goroutine 2066291 [running]:
github.com/prebid/prebid-server/adapters/conversant.(*ConversantAdapter).Call(0xc4203f5400, 0x55dd7cb97640, 0xc45496a5a0, 0xc45850f1d0, 0xc448d88c80, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/prebid/prebid-server/adapters/conversant/conversant.go:82 +0x45b
```

The conversant adapter doesn't work on app requests

---

cache/postgrescache/postgrescache_test.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
pbsmetrics/go_metrics_test.go
pbsmetrics/metrics.go

Capturing some metrics on network errors, so we can see how frequently they're happening.
Also downgrading them to `warning`, because they're not unexpected. They're basically all `i/o timeout` or `broken pipe` messages... which just means the network is slow or the browser closed the connection before we could respond. Neither really means that PBS is in critical trouble.

Added a metric type for network errors

---

exchange/exchange.go
exchange/exchange_test.go
pbs_light.go
pbs_light_test.go

Today, bad Bidder code can cause the server to crash (e.g. nil-pointer dereferences).
The root cause is `panics`, which crash the process if they're not caught. Although Go's HTTP Server catches panics from the handlers, there's nothing to recover inside the goroutines we create ourselves.
This adds some safeguards so they get logged as errors rather than crashing the process.
I do plan to add this to the metrics... but was undecided on whether to do it in this PR or another one. Let me know either way.

Recover from panics inside goroutines

---

adapters/adform/adform.go
adapters/adtelligent/adtelligent.go
adapters/appnexus/appnexus.go
adapters/audienceNetwork/facebook.go
adapters/beachfront/beachfront.go
adapters/bidder.go
adapters/brightroll/brightroll.go
adapters/conversant/conversant.go
adapters/eplanning/eplanning.go
adapters/indexExchange/index.go
adapters/info_test.go
adapters/lifestreet/lifestreet.go
adapters/openrtb_util.go
adapters/openx/openx.go
adapters/pubmatic/pubmatic.go
adapters/pulsepoint/pulsepoint.go
adapters/rubicon/rubicon.go
adapters/somoaudience/somoaudience.go
adapters/sovrn/sovrn.go
errortypes/errortypes.go
exchange/bidder.go
exchange/exchange.go
pbs_light.go

This is being done in anticipation of being able to define error codes and return them as part of the PBS return. Should be helpful for some monitoring and automatic debugging applications.

Moves adapter error types into its own module.

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go

Per the `/openrtb2/auction` docs:
> "includewinners": false // Optional param defaulting to true
> "includebidderkeys": false // Optional param defaulting to true
AMP should probably be consistent with these.

Fix AMP targeting defaults

---

static/bidder-params/sovrn.json

Reverts prebid/prebid-server#633
@rachelrj we actually saw on release that this breaks things for some publishers.
If you want to change this, it'll have to be backwards-compatible.  You can add `tagId` as a separate param, document `tagid` as deprecated, and then use `oneOf` to guarantee that one of the two exists.

Revert "Fix tagid param for Sovrn"

---

docs/endpoints/openrtb2/auction.md
errortypes/errortypes.go
exchange/bidder.go
exchange/exchange.go
openrtb_ext/response.go

This expands the reporting of errors in debug requests to include error codes. This will allow for some automation in analyzing debug reports, as scripts can focus on the error codes rather than trying to pattern match against error messages.

Adds error code output to openrtb auction debugs.

---

Gopkg.lock
Gopkg.toml

This switches our project to a `jsonparser` fork which includes https://github.com/buger/jsonparser/pull/137, because that project's maintainer hasn't responded in a while.
I also tried replacing `jsonparser` with [gjson](https://github.com/tidwall/gjson)... but our benchmark showed an extra millisecond of overhead, so... *shrugs*.
I believe this should fix some panics we've been seeing in the app logs. Once it merges we can switch back to the main project.
It upgrades lots of other packages too. Honestly this happened by accident when I deleted `Gopkg.lock` and ran `dep ensure`. If you think that's too risky, I can go back and update _just_ this package... but IMO we're due for some dependency upgrades anyway.

Use jsonparser fork

---

errortypes/errortypes.go
exchange/bidder.go
exchange/exchange.go
pbsmetrics/metrics.go

Adapters should either generate one or more http requests to their bidder to get bids, or return errors indicating why they could not bid on the supplied bid request (or both). However this is not enforced. This PR adds a failedToBid error to catch this case, and signal that an adapter is misbehaving in this manner. This should hopefully never happen, but now we will be able to catch and debug if it ever does.

Creat a Fail-To_Bid error

---

static/bidder-info/audienceNetwork.yaml

@mjacobsonny tells me that mobile doesn't work with audience network... so removing it here.

Removed mobile support listing from audience network.

---

docs/endpoints/openrtb2/amp.md
docs/endpoints/openrtb2/auction.md
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go

AMP should ignore the field, but allows for debugging without trying to turn the request into an openrtb request. Fixes #616

Add adapter errors to the AMP response

---

.travis.yml

I'm not sure how this line ended up in both the `before_install` and `before_deploy` sections... but we we don't use `gox` unless we're deploying. We shouldn't fetch it on every build if we don't need it.

Removed gox until the before_deploy phase.

---

pbs_light.go

Fixes #648.
Lots of documentation, because it's a tricky subject and took a lot of digging before I even convinced myself that it was ok.

Fixing CORS error

---

exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go
exchange/validation_test.go

This CL allows prebid server to reject any bids having a currency mismatch between allowed
currencies in the bid request and the currency declared in bids.
For the time being, if allowed currencies are not declared in bid request or in bid
the currency is implicitly set to `USD` to prevent from any breaking changes.
This CL includes:
- Prebid server to reject bids having currency mistmatch
Tnis CL doesn't include:
- Changing the default currency (which is USD)
More details in #280

Currency support #280 - step 1

---

pbs_light.go
pbs_light_test.go

Cors regression test

---

adapters/adform/info.yaml

`static/bidder-info/{bidder}.yaml` is important. `adapters/{bidder}/info.yaml` isn't used anywhere.
This file confused a new adapter submission, so... deleting it: https://github.com/prebid/prebid-server/pull/655#discussion_r211582885

Removed a stray/misleading info.yml file.

---

.travis.yml
Gopkg.lock
Gopkg.toml
adapters/pubmatic/pubmatic.go
stored_requests/events/postgres/polling.go

Go 1.11 was recently released. Begin testing all PRs/builds against it. Update to recent version of `dep` in travis-ci, went back to upstream jsonparser, and updated some deps.
Leaving go 1.9 in travis for now, we should figure out when we want to stop officially supporting go 1.9. The builds are 2x slower than 1.10.

Test go 1.11, update dep

---

exchange/exchange.go

Fixes metrics, we want to report on the number of valid bids, not the number of bids the adapter sends

Better adapter bid metrics

---

exchange/exchange.go
exchange/exchange_test.go
validate.sh

We use the `chBids` channel to collect all the bids from the adapters. However if an adapter goroutine panics, we never send a result. This causes the whole request to hang waiting for the bids from this adapter.
This change has the `recoverSafely()` function send an empty bid response on the `chBids` channel so that the main thread knows to continue.

Fixes requests hanging on adapter panic

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go

Taking another pass looking for low-hanging fruit to clean up the app logs.
Virtually all of these are either `i/o timeout` or `broken pipe`. We always _expect_ some baseline level of these errors... for example, if the client has a slow client connection, or the connection gets closed before we can respond.
I definitely see some value in logging them for metrics/analytics, so we can see major error spikes... but I don't see much value in spewing them to the app logs. If we remove them, this should cut our app logs in half.

Stop logging client write errors

---

pbs_light.go
router/router.go
router/router_test.go

I found these during a last-minute review of #673.
Rather than bug @zachbadgett I just figured I'd change them right after merging. This fixes two issues:
1. `router.Shutdown()` was never called.
2. The schema directory only worked in tests, but not at runtime.
(2) is an issue because the tests run in the directory where they're defined, but the static binary gets output to the root directory... so the paths are actually different for each case.
Those changes stop PBS from crashing on startup.

Fixing a few stray issues

---

exchange/gdpr.go
exchange/gdpr_test.go
exchange/utils.go

DONT MERGE UNTIL #682 HAS BEEN TESTED AND DOES NOT RESOLVE THE ISSUE
AMP currently does not support generating/sending IAB consent strings. After merging #658 AMP performance tanked in the EU. This is likely due to the PR removing `user.buyerid` where consent is not set, and being impossible to set consent on AMP requests. We still leave in place the other PI information cleaning code.
This is intended as a patch for the AMP consent issue until AMP supports sending full consent information to 3rd party requests. Ideally they will support the IAB consent string, but we cannot discount that they may roll their own format.
The motivation behind allowing `user.buyerid` to go through is that we cannot know the user's consent, however if the ID exists then the user must have given consent for …

Allows sending user.buyerid for AMP requests

---

.travis.yml
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/openrtb2_go111_test.go
endpoints/openrtb2/openrtb2_test.go
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-consent-int.json

Unfortunately, the build flags (at least from what I can tell), do not allow specifying minor versions. When `go1.11.1` is released we can remove the hack and possibly add a warning in the README explaining why `go1.11` is not supported/why the tests fail on that specific version.

Add message_go1.11 to fix test failing on go1.11

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/invalid-whole/banner-h-only.json
endpoints/openrtb2/sample-requests/invalid-whole/banner-h-zero.json
endpoints/openrtb2/sample-requests/invalid-whole/banner-w-only.json
endpoints/openrtb2/sample-requests/invalid-whole/banner-w-zero.json
endpoints/openrtb2/sample-requests/invalid-whole/format-empty-array.json

In #644, I found this test which wasn't testing what it thought it was.
It intended to make sure we reject sizeless banners... but it was failing for other reasons.
Unfortunately, this is now a breaking change :(. Still probably better late than never. We can measure its true impact whenever we release it.

Required some size to exist on banner requests

---

currencies/rate_converter.go
currencies/rate_converter_test.go
currencies/rates.go
currencies/rates_test.go

This CL introduces a mechanism to fetch currencies rates
periodically from a remote source.
Those rates are stored in `CurrencyConverter` struct which
can be injected in PBS to get rates.
This doesn't introduce any changes in PBS workflow just yet, but in another CL later for clarity.
#280

Introduce currency converter mechanism #280

---

docs/endpoints/openrtb2/auction.md
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/invalid-whole/site-ext-amp.json
endpoints/openrtb2/sample-requests/valid-whole/supplementary/site-amp.json
openrtb_ext/site.go
openrtb_ext/site_test.go

This fixes #708
Technically the `ext` was already going to the bidders... so this just adds input validation & documents it.
Along the way, I found that our AMP tests were testing lots of payloads with `request.app` defined. Since AMP implies `site`, these tests don't make sense. I added an explicit check for `request.app` in the code.
This seems like a breaking change... but I don't think it is, because a _real_ AMP page would send the `curl` query param, and there was already code which defined `site` in that case. If the Stored Request already defined `app`, then it would cause both to be defined, which would make the request invalid anyway.

Formalizing support for `site.ext.amp`

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_benchmark_test.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/invalid-whole/unknown-bidder.json
errortypes/errortypes.go
router/router.go

This will allow us to not 4xx on receiving params for disabled/deprecated bidders. This will allow #657 to go through without causing current requests to start returning 4xx errors.

Enables proper processing for deprecated (disabled) bidders.

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go

Fixes not being able to mutate the `imp` in the validation code.

Fixes deprecated bidders not being removed from request.imp.ext

---

currencies/rate_converter.go
currencies/rate_converter_test.go
currencies/rates.go
currencies/rates_test.go

This CL introduces a mechanism to fetch currencies rates periodically from a remote source.
Those rates are stored in `CurrencyConverter` struct which can be injected in PBS to get rates.
This doesn't introduce any changes in PBS workflow just yet.
It also address issues described in #722 regarding httptestClient overload in tests generating
errors while running `validate.sh` script.
Issue: #280

Introduce currency converter mechanism

---

adapters/beachfront/beachfront.go

When I did git diff to origin, there where problems. The Gopkg.lock was formatted differently. I just did a fresh clone from origin, and redid my trivial change in beachfront.go. A diff with origin now looks right.

Corrected redundant append bug, and fixed Gopkg.lock corruption from previous PR

---

adapters/adkernelAdn/usersync.go
adapters/adkernelAdn/usersync_test.go

Fixes #736.
This is subtle... but apparently Viper manages all config options as lowercase. I left some `// Fixes` and `// Prevents` comments because this looks like an easy bug to re-introduce later.

Fixed aAdkernelAdn usersync bug

---

Dockerfile

`mtr` helps collect and report on latency stats between two machines. Some docs are here: https://www.linode.com/docs/networking/diagnostics/diagnosing-network-issues-with-mtr/
It can be used to help debug latency issues, narrowing down whether a latency problem is caused by the code/config or the hardware/network.

Install mtr in the runtime container

---

adapters/ix/ix.go
adapters/ix/ix_test.go
pbs/pbsrequest.go
pbs/pbsrequest_test.go

* added support for sending multiple bid requests to IX for multiple slots and sizes
* resolves issue mentioned in https://github.com/prebid/prebid-server/pull/712#issuecomment-429364695
* resolves comment https://github.com/prebid/prebid-server/pull/712#discussion_r227107967
* resolves comment https://github.com/prebid/prebid-server/pull/712#discussion_r227108009

Update ix adapter to make multiple bid requests for multiple slots and sizes

---

adapters/ix/ix.go
adapters/ix/ix_test.go
static/bidder-params/ix.json

Fixing a bug identified in the IX adapter where requests were being sent for sizes that were not present in the adapter config.
Additionally, some validation code was moved outside the loop containing it, because it did not need to be inside the loop.

Check size match as per config before creating request

---

docs/endpoints/openrtb2/amp.md
endpoints/auction.go
endpoints/auction_test.go
exchange/exchangetest/targeting-cache-vast-banner.json
exchange/exchangetest/targeting-cache-vast.json
exchange/exchangetest/targeting-cache-zero.json
exchange/exchangetest/targeting-mobile.json
exchange/exchangetest/targeting-no-winners.json
exchange/exchangetest/targeting-only-winners.json
exchange/exchangetest/targeting-with-winners.json
exchange/targeting.go
openrtb_ext/bid.go

Fixes #749.
Prebid Mobile says they've given up trying to integrate Facebook in the SDK... so this key really doesn't serve any purpose anymore.

Deleted the loadtype targeting key

---

openrtb_ext/bidders.go

If you're adventurous, like I am, and want to run prebid-server on windows, you need to handle windows backward slashes in file paths. Adding .ToSlash in the included PR will make it possible to run prebid-server under windows at least for testing purposes.

Handle file paths in windows

---

exchange/exchange.go
exchange/exchangetest/tmax.json
openrtb_ext/response.go

This was a request from @anwzhang over on Prebid Mobile.
The issue they need to solve is: "how long should the client wait for a response before it cancels the request?"
Ideally they want this to be `tmax + {buffer for latency}`... but  if `tmax` is defined on the server in a Stored Request, then the Mobile client has no way of accessing it today.
Their request was that we return this so that they can make a single auction request with a "long" timeout, and then use the value we return to tune future calls.

Added the timeout to the response

---

endpoints/cookie_sync.go
endpoints/cookie_sync_test.go

Small bugfix... we never set the `Content-Type` to `application/json` on the `/cookie_sync` URL.
I added some regression tests... but also noticed that these tests came from the days before `testify`. Figured I'd clean up some of the duplicate helper methods while I was in there.

Set the /cookie_sync Content-Type to application/json

---

adapters/33across/33across.go
adapters/conversant/conversant_test.go
currencies/rate_converter.go
currencies/rates.go
pbsmetrics/metrics.go

Thanks to @dbmiller report, fixing the following errors:
https://goreportcard.com/report/github.com/prebid/prebid-server#misspell
not fixed in this commit:
https://github.com/prebid/prebid-server/pull/765/commits/b596fc90adf359fd1ce4f95a6b90ff56150d24f4

[Spelling] Fix spelling issues

---

adapters/ix/ix_test.go

This CL just to fix a spelling issue, allowing the Go report card to show 100% spelling report

[Spelling fix] Fix spelling for go report card

---

.travis.yml

hey @benjaminch, this one's for you.
A long while back, I remember you looking for ways to run CI in your fork without stray commits.
I stumbled on this in another repo, and it looks like a pretty clean solution: https://docs.travis-ci.com/user/languages/go#go-import-path
If you want to test it at some point, please let me know if it works. We can merge it and you can drop the `TRAVIS_REPO_SLUG` nastiness that you had to add to your fork. Official Go Modules will be coming very soon... so the Dep-specific solution will break in the near future anyway.

Added a go import path to travis

---

config/config.go
config/config_test.go
server/prometheus.go

Two changes here:
1. Make the prometheus timeout configurable rather than hardcoded
2. Fixes some bogus tests. These are in the same vein as the other ones @josephveach pointed out. They tested _that_ an error occurred... but not _which_ error occurred. Turns out that they _were_ passing for the wrong reasons. There were only a few of them, so... I fixed those too.

Configurable prometheus endpoint timeout

---

currencies/rates.go

Following PrebidJS change regarding currenncy rates URL, any references
to it need to be updated to
`https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json`
More details at #785

[Currency] Changing the default currency rates URL

---

usersync/cookie.go

This should lead to more predictable cookie behavior.

Sets an explicit path on the cookies

---

config/config.go
config/config_test.go
currencies/constant_rates.go
currencies/constant_rates_test.go
currencies/rate_converter.go
currencies/rate_converter_test.go
currencies/rates.go
currencies/rates_test.go
docs/developers/currency-converter.md
docs/endpoints/openrtb2/auction.md
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_benchmark_test.go
endpoints/openrtb2/auction_test.go
exchange/bidder.go
exchange/bidder_test.go
exchange/bidder_validate_bids.go
exchange/bidder_validate_bids_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/legacy.go
exchange/legacy_test.go
exchange/targeting_test.go
router/router.go

This CL allows to start using the rates converter.
The default currency remains `USD`.
By default, the rate converter will fetch every 30 minutes the official
prebid.org currencies rates at http://currency.prebid.org/latest.json.
The rate converter can be disabled by setting `rates_converter.fetch_url` to 0.
I will also do another PR to add a new endpoint in order to expose the rate converter settings along with the actual rates to ease debug and such if it's ok for you.
For more details on this feature, please refer to #280

[Currency] Introduce currencies conversions in PBS workflow

---

adapters/beachfront/beachfront.go
adapters/beachfront/beachfronttest/exemplary/minimal-banner.json
adapters/beachfront/beachfronttest/supplemental/minimal-mobile-banner.json
adapters/beachfront/beachfronttest/supplemental/minimal-site-banner.json
adapters/beachfront/beachfronttest/supplemental/multi-banner.json
config/config.go

This is a usable default for live users until we get a new sync endpoint set up. The new sync endpoint will behave as expected, reading the redirect url from the query string. The pid=155 is a temporary measure to make this work with the current sync endpoint, defaulting to point at https://prebid.adnxs.com/pbs/v1/setuid. The rest of the query parameters are ignored for now, but they are representative of what the new sync endpoint will be looking for.

Beachfront bidder - stop gap measure for cookie syncs for  live users

---

endpoints/cookie_sync.go
pbsmetrics/config/metrics.go
pbsmetrics/go_metrics.go
pbsmetrics/go_metrics_test.go
pbsmetrics/metrics.go
pbsmetrics/prometheus/prometheus.go

We can see per adapter how often an adapter user sync is GDPR blocked in the `/cookie-sync` endpoint.

Implements metrics to record GDPR status of cookie sync requests

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go

CL:
- Copy XAPI response.bidid to openrtb_response.seatbid.bid.bidid

Copy Rubicon XAPI response.bidid to openrtb_response.seatbid.bid.bidid

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-tpid-empty.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-tpid-source-empty.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-tpid-uid-empty.json
openrtb_ext/user.go

The **Universal User ID** module supports multiple ways of establishing pseudonymous IDs for users, which is an important way of increasing the value of header bidding. Instead of having several exchanges sync IDs with dozens of demand sources, a publisher can choose to integrate with one of these ID schemes:
- **Unified ID** – a simple cross-vendor approach – it calls out to a URL that responds with that user’s ID in one or more ID spaces (e.g. TradeDesk). The result is stored in the user’s browser for future requests and is passed to bidder adapters to pass it through to SSPs and DSPs that support the ID scheme.
- **PubCommon ID** – an ID is generated on the user’s browser and stored for later use on this publisher’s domain.
The OpenRTB request example:
```
{
"user": {
"ext": {
"tpid": …
```

Add support for Universal ID module (user.ext.tpid)

---

Gopkg.toml
config/config.go
server/server.go

I would like to optionally add gzipped responses.
With this PR it's possible to set enable_gzip: true in the pbs.yml, which makes the server gzip the response when possible.
the default behavior is unchanged.

* added gzip support

---

endpoints/auction.go

Simply a change of all the **blabel** and **blable** variable names passed as in the function argument to _recoverSafely_(), lines 202-252, to **adapterlabels**.
Since you're reviewing this, please consider the merits of the idea of moving this 50-line function call into a separate function.  I think this code is very confusing in its current form, which is that the call to _recoverSafely_() serves to simply insert some defer() code into the 50-line function passed to it, and then returns the same function.  Why not simply write a separate function with the defer() code already in place?  I can't spot a technical reason to not move the function out of calling function _auction_().  The benefits of moving it out are (1) the problem being fixed by this change would have been caught by the …

PBS-336: correct bad variable name

---

adapters/yieldmo/params_test.go
adapters/yieldmo/yieldmotest/exemplary/simple-banner.json
openrtb_ext/imp_yieldmo.go
static/bidder-params/yieldmo.json

The Yieldmo js adapter uses the bidder param placementId, and the Yieldmo server to server adapter to use placementid. This branch corrects that mistake and unifies them to both use placementId.

renaming yieldmo bidder param from placementid to placementId

---

currencies/constant_rates.go
currencies/converter_info.go
currencies/rate_converter.go
currencies/rates.go
docs/developers/currency-converter.md
docs/endpoints/currency_rates.md
endpoints/currency_rates.go
endpoints/currency_rates_test.go
pbs_light.go
router/admin.go
router/router.go

This CL introduces a new admin endpoint exposing current currency rate
converter internals such as:
- Sync source URL
- Internal rates
- Update frequency
- Last update
It will help for the future rollout of currencies support.
More details: #280

[Currency support] Adding a debug endpoint

---

Gopkg.lock
config/config.go

Currently, following errors occur in CI.
I fixed it with replacing it with a dummy ID.
P.S. I also add back the omitted `gziphandler` dependency
```
Unable to resolve user sync URL: https://rtb.gamoshi.io/pix/{{.supplyPartnerId}}/scm?gdpr={{.GDPR}}&consent={{.GDPRConsent}}&rurl=http%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dgamoshi%26gdpr%3D{{.GDPR}}%26gdpr_consent%3D{{.GDPRConsent}}%26uid%3D%5Bgusr%5D for adapter: gamoshi. template: userSyncTemplate:1:29: executing "userSyncTemplate" at <.supplyPartnerId>: can't evaluate field supplyPartnerId in type macros.UserSyncTemplateParams
```

Fix `gamoshi` bidder's CI failure

---

exchange/exchange.go
exchange/exchange_test.go

Using the NewEncoder function that will help correct all '&', '<', and '>' characters.

PBS-64: Fix HTML-encoding errors

---

Gopkg.lock
exchange/utils.go
exchange/utils_test.go

PBS-335: Fix GDPR info lookup to use core bidder when aliases are used

---

Gopkg.lock
Gopkg.toml
adapters/beachfront/beachfront.go
adapters/brightroll/brightroll.go
adapters/eplanning/eplanning.go
adapters/gamoshi/gamoshi.go
adapters/rhythmone/rhythmonetest/exemplary/banner-and-video-app.json
adapters/somoaudience/somoaudience.go
adapters/somoaudience/somoaudiencetest/exemplary/no-bid.json
adapters/somoaudience/somoaudiencetest/supplemental/gdpr.json
adapters/sovrn/sovrn.go
adapters/sovrn/sovrn_test.go
adapters/sovrn/sovrntest/exemplary/no-bid.json
adapters/sovrn/sovrntest/exemplary/simple-banner.json
adapters/sovrn/sovrntest/supplemental/blank-device.json
adapters/sovrn/sovrntest/supplemental/camel-case-tagId.json
adapters/sovrn/sovrntest/supplemental/gdpr.json
adapters/sovrn/sovrntest/supplemental/no-user.json
config/config.go
exchange/exchange_test.go

I updated mxmCherry to the latest stable version for better OpenRTB support in the future.
v11 fixed the empty Lmt&Dnt problem which is required to identify if `LMT`/`DNT` are 0 or empty.
I'll close the previous one and update it till v12 consolidated.
https://github.com/prebid/prebid-server/pull/828
This pull depends on the following fix: https://github.com/prebid/prebid-server/pull/837

Update mxmCherry from v10 to v11

---

exchange/auction.go
exchange/cachetest/defaultbanner.json
exchange/cachetest/defaultvideo.json
exchange/cachetest/multibid.json

This became more complicated than anticipated for a two-line fix.  The tests associated with the errant code were based on the same misunderstanding (using bid ID instead of imp ID) so they had to be updated as well.  I fixed all three tests even though only two (the tests with an impression expiration) were failing after the fix.  I also reformatted the test files for readability (there were tabs on some lines, not on others).

PBS-348: fix cache expiration calculation

---

Gopkg.lock
Gopkg.toml
exchange/auction.go
exchange/auction_test.go
exchange/cachetest/customcachekey.json
exchange/customcachekeytest/customcachekey.json
exchange/exchange.go
prebid_cache_client/client.go

When using category exclusion for video, force cache key for winning bids to be <pb>_<cat>_<dur>_<hb_cache_id> where:
pb == price bucket
cat == brand category
dur == ad duration
hb_cache_id == random cache id shared by all impressions in request
Separate changes will ensure:
- no duplicated bid IDs from separate bidders
- do duplicated categories among impressions

Custom cache key support

---

exchange/auction.go
exchange/cachetest/customcachekey.json
exchange/customcachekeytest/customcachekey.json

Two functional changes:
- back out the doCache() change that add pb portion of custom cache key
- save only the hbCacheID portion of the custom cache key in a.vastCacheIds[]
Had to update one of the tests to allow for doCache() no longer adding pb, so updated its sister test with a matching, more meaningful variable.

PBS-353: caching changes for Sahara

---

exchange/bidder_test.go

This CL only introduces a change in couple tests having test cases
comments moving those comments in a dedicated field in the test case so
it will be printed by assert on fail which ease the debug
investigations.

[Tests] Moving test cases comments to dedicated field

---

exchange/bidder.go
exchange/bidder_test.go

This CL aims to take into account `request.Cur. It's yet another step forward the full currency support CF #280.
Please let me know what you think about this one and whether I forgot anything.
Cheers :)

[Currency support] Map currency from bid request

---

adapters/ix/ix.go
adapters/ix/ix_test.go

Hello!
The Index Exchange endpoint can now dynamically bid on all slot sizes provided. The non-standard ext.size attribute has been deprecated for server integrations. Please let us know how to ensure this is included in the next prebid-server release as it is approved.
Thank-you kindly
--
IX Prebid Support Team

removed filtering requests from ix.size param

---

endpoints/info/bidders.go
endpoints/info/bidders_test.go

- Add a fake bidderName "all" that responds with all bidder details
- Modify bidder_test file to use "testify/assert" package to do assertions
Docs PR for the same: https://github.com/prebid/prebid.github.io/pull/1297

Modify bidder info endpoint to be able to get all bidder details

---

pbsmetrics/prometheus/prometheus.go
pbsmetrics/prometheus/prometheus_test.go

Cache performance metric for prometheus was using `standardLabels` where it should have been using only the `cache_result` label with values `hit` and `miss`. This PR rectifies that, adds a dimension for the cache performance metric with the cache_result label and unit tests to verify everything works as expected.

Use the correct labels for cache performance metric

---

adapters/pubmatic/params_test.go
adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatictest/supplemental/invalidparam.json
openrtb_ext/imp_pubmatic.go
static/bidder-params/pubmatic.json

Make AdSlot as optional parameter and make changes in adslot validation. The valid format for the optional string adslot are :  'adslot@WxH' and 'adslot'
If Width and Height parameters are not present for Banner, assign them to the Banner object from the first size in the array format sizes.

PubMatic Adslot validation

---

config/config.go
exchange/exchange.go
exchange/exchange_test.go
stored_requests/backends/db_fetcher/fetcher.go
stored_requests/backends/empty_fetcher/fetcher.go
stored_requests/backends/file_fetcher/fetcher.go
stored_requests/backends/file_fetcher/fetcher_test.go
stored_requests/backends/http_fetcher/fetcher.go
stored_requests/fetcher.go
stored_requests/fetcher_test.go
stored_requests/multifetcher.go

-Added code to fetch data using http
-Added previously loaded categories to run http request just at the first time

Implementation of Categories Http fetcher

---

adapters/beachfront/beachfront.go
adapters/beachfront/beachfronttest/exemplary/minimal-banner.json
adapters/beachfront/beachfronttest/exemplary/simple-video.json
adapters/beachfront/beachfronttest/supplemental/minimal-banner-empty_array-200.json
adapters/beachfront/beachfronttest/supplemental/minimal-mobile-video.json
adapters/beachfront/beachfronttest/supplemental/minimal-site-banner.json
adapters/beachfront/beachfronttest/supplemental/multi-banner.json
adapters/beachfront/beachfronttest/supplemental/multi-mix.json
adapters/beachfront/beachfronttest/supplemental/multi-video.json

Checking http statuses, in particular the possibility of a 200 with a empty array which should be treated as an empty response.

Improved error handling on Beachfront adapter

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go

Rubicon XAPI prefers single media type impression.
This PR leaves either banner or video if both income in prebid request. So, video will be chosen if it has fields:
- Mimes
- Protocols
- Maxduration
- Linearity
- Api
Otherwise, video should be removed.

Fix Rubicon bidder for multi-format impression processing

---

adapters/lifestreet/lifestreet.go

On the live traffic, we figured out that a client receives an error from our adapter:
`"errors": { "lifestreet": [{ "code": 999, "message": "invalid BidType: " }] },`
This change should fix the issue

Fixed "invalid BidType: " error for lifestreet adapter

---

config/config.go
config/config_test.go

This CL is the last piece to activate currency conversion support in
PBS. It activates currency support per default.
Currency rates will be fetched once per hour (PrebidJS file is updated
once a day).
Issue: #280

[Currency support] Activate multi-currencies support

---

config/config.go
config/config_test.go
endpoints/auction_test.go
endpoints/cookie_sync_test.go
endpoints/setuid_test.go
exchange/utils.go
exchange/utils_test.go
gdpr/gdpr.go
gdpr/impl.go
gdpr/impl_test.go

PBS internally determines if the impression from a sender includes the `publisher_id` RTB parameter, and if `publisher_id` is present in an ENV/config variable set by the PBS owner, skip the GDPR check internally but leave the gdpr=1/0 flag intact. This ticket is intended to substitute **PBS-372** since it was rejected in favor of this approach.

Add a PI exemption environment variable to PBS

---

endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
exchange/exchange.go

if no bids returned - don't throw cache error, just return empty result

Cache validation fix

---

endpoints/auction.go
endpoints/auction_test.go
endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
exchange/auction.go
exchange/targeting.go
openrtb_ext/bid.go
openrtb_ext/bid_response_video.go

This is a clean up PR that:
- Removes hardcoded targeting keys 
- Removes targeting key constants defined in multiple places
- Rename `VideoTargeting` struct fields to adhere to GoLang naming convention

Remove hard coded targeting keys

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/video_auction.go
pbsmetrics/metrics.go

Currently we only track account for legacy requests. We are seeing issues now where it would be good to track accounts in `openrtb`. Unfortunately `openrtb` doesn't have this as a required field, but we can grab `request.site.publisher.id` or `request.app.publisher.id` as the account. We can use "UNKNOWN" for when this field is not populated.

Using Site publisher or app publisher as account in openrtb

---

.travis.yml
README.md
validate.sh

This CL deprecates Go 1.9 version removing it from the CI along updating
the installation instructions.
This PR probably needs to be flagged as important change so people using Go 1.9 will be aware of this change from now on.
Issue: #920

[Go 1.9] deprecate 1.9 & 1.10 versions and introduce 1.12

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-eids-eids-uids-empty.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-eids-empty.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-eids-id-uids-empty.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-eids-source-empty.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-eids-source-unique.json
endpoints/openrtb2/sample-requests/invalid-whole/user-ext-eids-uids-id-empty.json
openrtb_ext/user.go

Added mapping:
- Loop through user.ext.eids[]
- If user.ext.eids[n].source is "adserver.org" and user.ext.eids[n].uids[0].ext.rtiPartner =="TDID", then copy user.ext.eids[n].uids[0].id to a new array entry in user.ext.tpid[] with this structure:
```
"source": "tdid", // hardcoded
"uid": "19cfaea8-a429-48fc-9537-8a19a8eb4f0c" // copy from user.ext.eids.uids[0].id
```
Example OpenRTB request:
```
"user": {
"ext": {
"eids": [
{
"source": "adserver.org",
"uids": [
{
"id": "cd96870f-f53d-4986-a08e-cd1612fb13b0",
"ext": {
"rtiPartner": "TDID"
}
}
]
},
{
"source": "pubcid",
"id": "29cfaea8-a429-48fc-9537-8a19a8eb4f0d"
}
]
}
}
```
To Rubicon XAPI request:
```
"user": {
"ext": {
"tpid": [
{
"source": "tdid",
"uid": "cd96870f-f53d-4986-a08e-cd1612fb13b0"
}
],
"eids": [
{
"source": "adserver.org", …
```

Add mapping of user.ext.eids[] for TDID in Rubicon bidder

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/video_auction.go
exchange/utils.go
openrtb_ext/publisher.go

This lets a PBS host have a "parent Account" to track the entity they do business with when `publisher.id` may be too granular.

Adds support for parentAccount property

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
adapters/sharethrough/sharethrough.go
adapters/sharethrough/utils.go
adapters/sharethrough/utils_test.go

This is forwarding more data to the Sharethrough ad server in order to bid more accurately:
- add scheme to `Origin` header
- add `X-Forwarded-For` header
- add `User-Agent` header

[Sharethrough] Improved Headers in ad server request

---

adapters/rubicon/rubicon.go
openrtb_ext/bid_response_video.go
openrtb_ext/imp_rubicon.go

If a target was not provided for the Rubicon adapter then it's value is set to an empty string which is invalid json. Resulting in an invalid request. Omitting the field if it's empty fixes this issue. 
#967

Omit empty on 'Target json.RawMessage' to avoid sending invalid json in bid request

---

docs/bidders/appnexus.md

First pass at providing an example for other adapters to follow.

Documenting the Appnexus test placement

---

.github/stale.yml

Will automatically close inactive issues or PRs after 14 days unless one of the exclusion labels is applied.

add stale bot configuration

---

pbs_light_test.go

Following #991, fixing a mispelling found in log.

[fix][mispelling] fix mispelling in log

---

pbs_light.go

Setup Field name into the comment so it's properly interpreted by godoc

[godoc] properly format `Rev` doc

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
adapters/sharethrough/sharethrough.go
adapters/sharethrough/sharethrough_test.go
adapters/sharethrough/utils.go
adapters/sharethrough/utils_test.go
config/config.go
openrtb_ext/imp_sharethrough.go

- Change Cookie Sync Sharethrough URL with an actual URL (`config.go`)
- Send `request.User.BuyerUID` to the ad server
- Changing from `1.0.x` format to simple integer (here from `1.0.3` to `4`) for internal reason
Before:
- Unmarshal JSON based on hardcoded ad payload schema (`imp_sharethrough.go`)
- Then re-Marshal it to JSON + B64 to put it in the ad markup
Now:
- JSON schema only has fields that actually matter in the adapter code
- the ad payload is kept raw so we can just B64-encode whatever we got back from the ad server

[Sharethrough] Implement Cookie Sync + misc improvements

---

config/config.go

Noticed we do some config processing after dumping the config to the log. This delays the logging until after we finish processing.

Log the config after we are finished processing it

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
adapters/sharethrough/utils.go
adapters/sharethrough/utils_test.go

This provides a fix to issues raised after merging #1016 
- Extract user.BuyerId from `parseUserInfo` (renamed from `parseUserExt`)
- Handle case where `request.User` is `nil`
- Change `TestSuccessRequestFromOpenRTB` to have no `request.User` instead of empty object
@hhhjort @guscarreon FYI

[Sharethrough] Handle requests without User

---

config/config.go
config/config_test.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/account-required/no-acct.json
endpoints/openrtb2/sample-requests/account-required/with-acct.json
endpoints/openrtb2/sample-requests/blacklisted/blacklisted-acct.json
endpoints/openrtb2/video_auction.go
errortypes/errortypes.go

Adds feature to create a config option (boolean) to turn on/off enforcement of publisher/account ID in the resolved request for openrtb2 endpoint.

Implement ability to require a publisher/account ID

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatic_test.go
adapters/pubmatic/pubmatictest/exemplary/video.json

This PR has the fix for issue #862 .
The changes here include using the bid.ext.bidType field to set the bid type in PubMatic adapter response. Default value is "banner".

fix for using bid.ext.bidType field to set bid type in PubMatic adapter response

---

stored_requests/events/http/http.go

The incremental endpoint is created as `thisEndpoint` but it was still using the `fetchAll()` endpoint every `refreshRate` interval so the server never pulled in any changes.

Wrong endpoint for HTTP incremental updates

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
adapters/sharethrough/sharethrough.go
adapters/sharethrough/sharethrough_test.go
adapters/sharethrough/utils.go
adapters/sharethrough/utils_test.go

Send json body to the ad server with:
- a list of blocked domains under `badv`
- the max time allowed by the exchange to get a response (tmax and deadline)
```
{
"badv": ["domain1.com", "domain2.com"],
"tmax": 500,
"deadline": "2019-09-12T11:29:00.000123456Z"
}
```
- bid request new param: `adRequestAt`
- s2s-win beacon new param: `adReceivedAt`

[Sharethrough] Add support for Blocked Advertiser Domains & TMax

---

pbs_light.go

Go 1.13 includes the following change:
> Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail.
This is partially responsible for introducing an init flow bug when compiling against Go 1.13, causing tests to fail. It doesn't look like `flag.Parse()` needs to be performed during init and everything seems to work fine when its moved to the start of the main method.

[Go 1.13] Testing Flags Refactor

---

config/config.go
config/config_test.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction_benchmark_test.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/video_auction_test.go
exchange/exchange_test.go
pbsmetrics/config/metrics.go
pbsmetrics/config/metrics_test.go
pbsmetrics/go_metrics.go
pbsmetrics/go_metrics_test.go
server/listener_test.go

This PR improves upon and substitutes PR #1053 by implementing the ability to disable the collection of account-specific metrics in prebid-server by setting the boolean variable `account_adapter_details` to `true` in the configuration environment of prebid-server

Disable account-specific metrics with boolean value in config

---

adapters/verizonmedia/verizonmedia.go

Prebid allows for a zero seatbid adapter to be returned. The verizonmedia adapter is throwing an uneccessary error when a zero seatbid request gets processed.

Correct Verizonmedia adapter zero seatbid bug

---

docs/endpoints/openrtb2/auction.md

code already ignores min, bringing docs in line

remove min from price granularity example

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
adapters/sharethrough/sharethrough.go
adapters/sharethrough/utils.go
adapters/sharethrough/utils_test.go

List of changes:
- Provide `bidfloor` to ad server
- Fix Native demand (null pointer exception) when no iframe size provided
- Change bid type to `banner`
- Accept `gzip` encoding

[Sharethrough] Support bidfloor

---

config/config.go
config/config_test.go

In order for adapters to be able to switch between endpoints based on the media type of the request, we are adding an extra field for adapters to pass additional info in JSON format. This allows for adapters to implement not only endpoint switching but also added functionality if needed.

Support configurable endpoints for adapters

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
adapters/sharethrough/sharethrough.go
openrtb_ext/imp_sharethrough.go
static/bidder-params/sharethrough.json

Couple of fixes:
- get `bidfloor` from custom impression params
- remove `gzip` header

[Sharethrough] Adapter fixes

---

endpoints/setuid.go
endpoints/setuid_test.go

Fixes #1054 
Also, refactors some existing tests for better readability and organization of test cases.

Restrict /setuid for Prebid supported bidders only

---

static/bidder-params/rubicon.json

Want the field names in /bidder/params to follow the exactly what the code expects when deserializing the JSON request. Its misleading the the /bidder/params say that they key is called VideoSizeID when it really needs to be passed as size_id in the request

update static bidder params for rubicon video to follow the json marshaling names

---

config/config.go

A one character change to move the yieldmo auction endpoint from http to https.

Switching yieldmo auction endpoint from http to https

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
errortypes/errortypes.go

Currency handling fix

---

usersync/cookie.go
usersync/cookie_test.go

Set "Secure" on Same SIte cookies

---

endpoints/auction.go
endpoints/auction_test.go

Refactored `endpoints/auction.go` to correct issues found in the sonarcloud scan

[SonarCloud] Legacy auction endpoint

---

currencies/rates.go
currencies/rates_test.go

This CL allows the currency rate currency to deduce a currency rate even
if not directly defined in the table but the reverse rate is present.
E.q.
USD => EUR is 1.0897
EUR => USD is not set
Old behavior when asking rate from EUR to USD will not be found,
New behavior is using the known reverse rate to deduce the rate.
Rate for 2 USD will be 2 * (1 / 1.0897)

[currency converter] allow to deduce reverse rate

---

endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go

This is a change to change the metrics recording on the video endpoint. Currently, the labels and analytics objects aren't being updated to show errors.

Updated handleError arguments to be pointers for video endpoint

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
openrtb_ext/regs.go
privacy/ccpa/ccpa.go
privacy/ccpa/ccpa_test.go
privacy/gdpr/gdpr.go
privacy/gdpr/gdpr_test.go
privacy/policies.go
privacy/policies_test.go

Implements: prebid/prebid-server#1107
Parses the CCPA 'us_privacy' signal from the AMP request URL and inserts it into the OpenRTB request.

CCPA Phase 1: AMP Endpoint

---

stored_requests/events/http/http.go

Updates to master to fix issue #1065 where the update event is blindly appending the `last-modified` query param to the `stored_requests.http_events` endpoints.  Added error handling for failed parse and an info log event when the http refresh event is called.

Update http refresh to use url builder. Fixes #1065

---

endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
openrtb_ext/bid_request_video.go

Just to note, this will need a small update when PR #1138 is merged

Adding the passing of CCPA value to the bid request for video endpoint

---

static/bidder-params/triplelift.json

After being advised by Hans, this PR tries to simplify the file `static/bidder-params/triplelift.json` in order to be leaner by eliminating the unnecessary complexity of the `oneOf` and `not` objects.

TripleLift's Inventory Code Parameter is Required

---

static/bidder-params/triplelift_native.json

This is part 2 of PR #1137 `TripleLift's Inventory Code Parameter is Required`. This PR tries to simplify the file static/bidder-params/triplelift_native.json in order to be leaner by eliminating the unnecessary complexity of the oneOf objects and have the UI show `Inventory Code` not under the "Optional parameters list.

TripleLift Native endpoint's Inventory Code Parameter is Required 

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go
adapters/rubicon/rubicontest/supplemental/required-video-size-id.json
go.mod
go.sum

cc: @bretg 
Based on conversations with Michael Moschovas over at Rubicon, it seems like video.size_id needs to be defined in every video request sent to rubicon

enforce video.size_id for video imps in rubicon adapter

---

currencies/rate_converter.go
currencies/rate_converter_test.go

This CL fixes the null ref on `RateConverter.GetInfo()` when rates
are nil.
Issue: #1136

[currencies] fix GetInfo() null ref issue

---

prebid_cache_client/client.go
prebid_cache_client/client_test.go

Adds cache item count and size to error messages. Refactored error message code a bit.

Enhance Message For Cache Errors

---

adapters/eplanning/eplanning_test.go
adapters/eplanning/eplanningtest/exemplary/simple-banner-2.json
adapters/eplanning/eplanningtest/exemplary/simple-banner.json
adapters/eplanning/eplanningtest/exemplary/two-banners.json
adapters/eplanning/eplanningtest/supplemental/banner-no-size-sends-1x1.json
adapters/eplanning/eplanningtest/supplemental/invalid-response-no-bids.json
adapters/eplanning/eplanningtest/supplemental/invalid-response-unmarshall-error.json
adapters/eplanning/eplanningtest/supplemental/server-bad-request.json
adapters/eplanning/eplanningtest/supplemental/server-error-code.json
adapters/eplanning/eplanningtest/supplemental/server-no-content.json
adapters/eplanning/eplanningtest/supplemental/site-domain-and-url-correctly-parsed.json
config/config.go

I'm replacing all http calls from E-Planning adapter to https as all non-secure requests will be returning a 301 code to redirect to https

Remove all non-secure calls from eplanning adapter

---

adapters/appnexus/appnexus.go
adapters/appnexus/appnexusplatformtest/exemplary/simple-auction.json
adapters/appnexus/appnexusplatformtest/video/simple-video.json
adapters/appnexus/appnexustest/amp/simple-banner.json
adapters/appnexus/appnexustest/amp/simple-video.json
adapters/appnexus/appnexustest/exemplary/native-1.1.json
adapters/appnexus/appnexustest/exemplary/simple-banner.json
adapters/appnexus/appnexustest/exemplary/simple-video.json
adapters/appnexus/appnexustest/exemplary/video-invalid-category.json
adapters/appnexus/appnexustest/supplemental/displaymanager-test.json
adapters/appnexus/appnexustest/supplemental/multi-bid.json
adapters/bidder.go
endpoints/openrtb2/video_auction.go
exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go
exchange/exchange_test.go
openrtb_ext/bid_request_video.go
openrtb_ext/request.go

Opening PR to get an early start on review comments. We have a couple questions remaining on our end. One major change that may need to be added is implementing the `pmp` object for targeting deals in the impressions. I will update this PR with any action items regarding this.

Adding support for deal prefixes

---

adapters/zeroclickfraud/usersync.go
adapters/zeroclickfraud/usersync_test.go
adapters/zeroclickfraud/zeroclickfraud.go
adapters/zeroclickfraud/zeroclickfraud_test.go
adapters/zeroclickfraud/zeroclickfraudtest/exemplary/multi-request.json
adapters/zeroclickfraud/zeroclickfraudtest/exemplary/native.json
adapters/zeroclickfraud/zeroclickfraudtest/exemplary/simple-banner.json
adapters/zeroclickfraud/zeroclickfraudtest/exemplary/simple-video.json
adapters/zeroclickfraud/zeroclickfraudtest/params/race/banner.json
adapters/zeroclickfraud/zeroclickfraudtest/params/race/native.json
adapters/zeroclickfraud/zeroclickfraudtest/params/race/video.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/bad-host.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/bad-response-body.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/bad-server-response.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/bad-sourceId.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/missing-ext.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/missing-extparam.json
adapters/zeroclickfraud/zeroclickfraudtest/supplemental/no-content-response.json
config/config.go
exchange/adapter_map.go
openrtb_ext/bidders.go
openrtb_ext/imp_zeroclickfraud.go
static/bidder-info/zeroclickfraud.yaml
static/bidder-params/zeroclickfraud.json
usersync/usersyncers/syncer.go
usersync/usersyncers/syncer_test.go

Zeroclickfraud's S2S adapter. Has user-sync and 91.8% code coverage with tests.

add zeroclickfraud adapter

---

endpoints/openrtb2/sample-requests/video/video_valid_sample_with_device_user_agent.json
endpoints/openrtb2/sample-requests/video/video_valid_sample_without_device_user_agent.json
endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go

Cannot come up with unit tests for this change. Do we want it?

If Device.UA is not present in request body, init it with user-agent from header

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
exchange/auction.go
exchange/auction_test.go
exchange/cachetest/debuglog_disabled.json
exchange/cachetest/debuglog_enabled.json
exchange/exchange.go
exchange/exchange_test.go
exchange/exchangetest/debuglog_disabled.json
exchange/exchangetest/debuglog_enabled.json
exchange/targeting_test.go
router/router.go

Redo of the previous PR. Caching now occurs during VAST caching. If the request fails, a new cache call is made. Unit tests to be added.

Added logging to cache for video endpoint

---

gdpr/gdpr.go
gdpr/impl.go
gdpr/impl_test.go
gdpr/vendorlist-fetching.go
gdpr/vendorlist-fetching_test.go
go.mod
go.sum

This will require updating the go-gdpr library first.

First pass at phase 1 TCF 2.0 support

---

openrtb_ext/request.go
openrtb_ext/request_test.go

Original issue: https://github.com/prebid/prebid-server/issues/1215
Updated the unmarshal for price granularity to use the default object if the request object is empty, or contains no ranges.

Updated price granularity unmarshal to accept empty values and ranges

---

exchange/exchange.go
exchange/exchange_test.go

This change is to fix a bug related to caching bids that contained deals. Originally, the caching occurred before the `hb_pb_cat_dur` was updated, so the UUID in the cache was still using the price instead of the deal prefix and priority. This change moves the modification so that if the key is modified, then the cache key matches the new `hb_pb_cat_dur`.

Moved hb_pb_cat_dur modification to be before caching

---

static/bidder-info/appnexus.yaml
static/bidder-info/audienceNetwork.yaml
static/bidder-info/ix.yaml
static/bidder-info/pulsepoint.yaml

info@prebid.org received email for one of these adapters. Fixing the addresses.

replacing info@prebid.org maintainer email addrs

---

adapters/sharethrough/butler_test.go
adapters/tappx/tappxtest/supplemental/banner-impression-badhost.json

Go 1.14 introduces a change to the formatting of error message. This broke two tests which rely on the platform error message. Per the release notes, the change is:
https://golang.org/doc/go1.14
> net/url
> When parsing of a URL fails (for example by Parse or ParseRequestURI), the resulting Error message will now quote the unparsable URL. This provides clearer structure and consistency with other parsing errors.
I changed the affect tests to regex comparisons for compatibility with at least 1.14, 1.13, and 1.12.

Fix Go 1.14 Error Message Changes

---

endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go

Fixes https://github.com/prebid/prebid-server/pull/1297

Bugfix for missing fields in imp.video

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go
openrtb_ext/imp_rubicon.go

Enabled `request.ext.rubicon.debug.cpmOverride` and `request.imp[].ext.rubicon.debug.cpmOverride` processing.
Updates tests

Add cpmOverride

---

adapters/consumable/consumable.go
adapters/consumable/consumable/supplemental/simple-banner-gdpr-2.json
adapters/consumable/consumable/supplemental/simple-banner-gdpr-3.json
adapters/consumable/consumable/supplemental/simple-banner-gdpr.json
adapters/consumable/consumable/supplemental/simple-banner-us-privacy.json

This change passes GDPR and US Privacy consent information through to Consumable.
I am proposing this change on behalf of Consumable, cc @naffis.

Consumable: Support GDPR and US Privacy consent

---

config/config.go
endpoints/auction_test.go
endpoints/cookie_sync_test.go
endpoints/setuid_test.go
exchange/utils.go
exchange/utils_test.go
gdpr/gdpr.go
gdpr/impl.go
privacy/enforcement.go
privacy/enforcement_test.go
privacy/scrubber.go
privacy/scrubber_test.go

Also note I have restored the ScrubStrategyUserNone even though it is not used in this code. It can be a source of confusion that some things are "silently" scrubbed and will be useful for the TCF 2 PR. The old (recently merged) code depended on the fact that if the scrubber was invoked at all, there were some things we would always scrub. This creates confusion when trying to extend the privacy scrubber, as you have to check in an unexpected place if there are more things that you may or may not want scrubbed in your new use case.

Restore the AMP privacy exception as an option.

---

adapters/consumable/usersync.go
adapters/consumable/usersync_test.go

Corrects Consumable’s GDPR vendor ID from 65535 to 591.
Fixes #1299.
CC @naffis.

consumable: Correct GDPR vendor ID to 591.

---

privacy/ccpa/policy.go
privacy/ccpa/policy_test.go
privacy/gdpr/policy.go
privacy/gdpr/policy_test.go

`privacy/ccpa/policy.go` and `privacy/gdpr/policy.go` include code that attempts to generate JSON by concatenating strings. If the `us_privacy` or `consent` fields contain the character `"`, this can produce malformed JSON, or JSON with an unintended structure.
This PR fixes the problem by encoding all JSON using the `json` module.
The included tests demonstrate that an attacker could exploit this bug to trick Prebid Server into mutating an OpenRTB bid request to contain arbitrary data, bypassing validation. These tests fail against the existing code.

privacy: Potential JSON injection

---

.travis.yml

Step 1: Fix Go 1.14 compilation and test cases. (Completed By https://github.com/prebid/prebid-server/pull/1271)
Step 2: Add Go 1.14 build target. <- This PR :)
Step 3: Remove Go 1.12 build target. Update Docker image to use 1.14.2. Update docs.

Add Go 1.14 Build Target

---

adapters/adtelligent/adtelligent.go
adapters/adtelligent/adtelligent_test.go
adapters/adtelligent/adtelligenttest/exemplary/media-type-mapping.json
adapters/adtelligent/adtelligenttest/exemplary/simple-banner.json
adapters/adtelligent/adtelligenttest/exemplary/simple-video.json
adapters/adtelligent/adtelligenttest/supplemental/explicit-dimensions.json
adapters/adtelligent/adtelligenttest/supplemental/wrong-impression-mapping.json
adapters/adtelligent/usersync_test.go
config/config.go

Update ortb endpoint for Adtelligent bidder
Extend Adtelligent csync url to accept gdpr and usp  consents

Update adtelligent ortb endpoint

---

adapters/eplanning/eplanning.go
adapters/eplanning/eplanning_test.go
adapters/eplanning/eplanningtest/exemplary/simple-banner-2.json
adapters/eplanning/eplanningtest/exemplary/simple-banner.json
adapters/eplanning/eplanningtest/exemplary/two-banners.json
adapters/eplanning/eplanningtest/supplemental/app-domain-and-url-correctly-parsed.json
adapters/eplanning/eplanningtest/supplemental/banner-no-size-sends-1x1.json
adapters/eplanning/eplanningtest/supplemental/invalid-response-no-bids.json
adapters/eplanning/eplanningtest/supplemental/invalid-response-unmarshall-error.json
adapters/eplanning/eplanningtest/supplemental/server-bad-request.json
adapters/eplanning/eplanningtest/supplemental/server-error-code.json
adapters/eplanning/eplanningtest/supplemental/server-no-content.json
adapters/eplanning/eplanningtest/supplemental/site-domain-and-url-correctly-parsed.json
config/config.go

I'm doing a minor change into E-Planning (eplanning) endpoint.
We will be using a new handler called /pbs instead of /hb. For compatibility purposes with older Prebid Server versions, both handlers will continue working after this switch.

Change on eplanning endpoint

---

endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/video/video_invalid_sample.json
endpoints/openrtb2/sample-requests/video/video_valid_sample.json
endpoints/openrtb2/sample-requests/video/video_valid_sample_ccpa_malformed.json
endpoints/openrtb2/sample-requests/video/video_valid_sample_ccpa_valid.json
endpoints/openrtb2/sample-requests/video/video_valid_sample_different_durations.json
endpoints/openrtb2/sample-requests/video/video_valid_sample_with_device_user_agent.json
endpoints/openrtb2/sample-requests/video/video_valid_sample_without_device_user_agent.json
endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
privacy/ccpa/policy.go
privacy/ccpa/policy_test.go

CCPA validation errors should result in warnings, not fatal errors. The video endpoint is missing the filter to ignore warnings. This PR also removes the invalid CCPA consent string from the request in further processing.

CCPA Video Bug

---

adapters/triplelift/triplelift_test.go
adapters/triplelift/triplelifttest/exemplary/optional-params.json
adapters/triplelift/triplelifttest/exemplary/simple-banner.json
adapters/triplelift/triplelifttest/exemplary/simple-video.json
adapters/triplelift/triplelifttest/supplemental/badresponseext.json
adapters/triplelift/triplelifttest/supplemental/badstatuscode.json
adapters/triplelift/triplelifttest/supplemental/notgoodstatuscode.json
adapters/triplelift_native/triplelift_native_test.go
config/config.go

- Adds SRA support by appending `sra=1` param to Triplelift endpoint in config.go for /s2s endpoint
- Edits all references to include `sra=1`

Triplelift: Add SRA Support

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go

This resolves #827.
I added a test case to make sure it works as expected.

Avoid overriding AMP request original size with mutli-size

---

exchange/bidder.go
exchange/bidder_test.go

More complete coverage of timeout notification issues.

Extra logging for timeout notifications

---

adapters/consumable/consumable.go

I am raising this PR on behalf of Consumable, CC @naffis.
This PR (hopefully) fixes issue #862 for Consumable, where the Consumable adapter would respond incorrectly when bidding on multi-format slots.
My understanding is that `BidTypeVideo` is for VAST units.
Consumable units are always HTML, never VAST. Sometimes the HTML unit itself embeds video, but my understanding is that from Prebid's point of view the `BidType` for that unit is still `BidTypeBanner`.
Therefore my understanding is that Consumable units are always `BidTypeBanner`.
Please let me know if my understanding is incorrect. I found the documentation for this quite difficult to understand.

Consumable: Correct bid type, should always be "banner".

---

.travis.yml
Dockerfile
README.md
go.mod

All PRs are now building with Go 1.14, so it's time for the final phase and build our release binaries with 1.14.

Build With Go 1.14

---

config/config.go

Update IPv6 private network list to include the documentation range. We're reportedly seeing it in the wild.

Add IPv6 Non-Public Network

---

docs/endpoints/openrtb2/auction.md
exchange/exchange.go
exchange/targeting.go
exchange/targeting_test.go
openrtb_ext/bid.go
openrtb_ext/request.go

Adds keyvalue hb_format support

---

analytics/clients/http.go
analytics/config/config.go
analytics/config/config_test.go
analytics/pubstack/README.md
analytics/pubstack/config.go
analytics/pubstack/config_test.go
analytics/pubstack/eventchannel/eventchannel.go
analytics/pubstack/eventchannel/eventchannel_test.go
analytics/pubstack/eventchannel/sender.go
analytics/pubstack/eventchannel/sender_test.go
analytics/pubstack/helpers/json.go
analytics/pubstack/helpers/json_test.go
analytics/pubstack/mocks/mock_openrtb_request.json
analytics/pubstack/mocks/mock_openrtb_response.json
analytics/pubstack/pubstack_module.go
analytics/pubstack/pubstack_module_test.go
config/config.go
go.mod
go.sum

Add a new logger module: Pubstack
Ability for users to send bid events directly to Pubstack.

feat: Add new logger module - Pubstack Analytics Module

---

endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
exchange/auction.go
exchange/impcustomcachekeytest/multiImpVideo.json
exchange/impcustomcachekeytest/multiImpVideoNoIncludeBidderKeys.json
exchange/targeting.go
exchange/targeting_test.go

Video endpoint bid selection enhancement: return all winning bids from all bidders per impression instead of one overall winning bid

Video endpoint bid selection enhancements

---

gdpr/vendorlist-fetching.go
gdpr/vendorlist-fetching_test.go

Fixes a bug in 0.124.0 where the TCF1 vendor list fetcher will never attempt lazy loading.

Fix TCF1 Fetcher Fallback

---

adapters/bidder.go
exchange/bidder.go

Updating comment for deal priority per issue #1445

Fixing comment for usage of deal priority field

---

exchange/exchange.go
exchange/exchange_test.go

In case we find bids with same category or pb_dur we randomly deduplicate one of them. This can a bid that was previously processed or bid on current iteration. In case we deduplicate bid from previous iteration and this is the only one bid in bidder - we need to remove the entire bidder from processing. Without this fix we removed "current iteration" bidder instead of "previously processed" . bidder.

Fix bid dedup

---

adapters/consumable/consumable.go

This PR corrects the width and height specified in the bid response.
After this change, Prebid Server uses the width and height specified in the **bid response** from Consumable.
Previously, Prebid Server would reuse the width and height specified in the **bid request**. That older behaviour was ported from an older version of the prebid.js adapter but is no longer valid.
I am submitting this PR on behalf of Consumable, cc @naffis.

consumable: Correct width and height reported in response

---

adapters/info.go
adapters/info_test.go

Sometimes an `openrtb.BidRequest`'s `[]Imp` slice gets completely emptied after filtering out imps with wrong media types in `adapters/info.go` as defined in the bidder's `static/bidder-info/*.yaml` file. This pull request modifies the `InfoAwareBidder`'s filtering process to not send requests with an empty `Imp` slice to any adapter to avoid panics in case the bidder's adapter de-references an slice element.
**Test request:**
```
{
"id": "some-request-id",
"site": {
"page": "prebid.org"
},
"imp": [{
"id": "some-impression-id",
"video": {
"mimes": ["video/mp4"],
"w": 640,
"h": 480
},
"ext": {
"33across": {
"siteId": "fake-site-id",
"productId": "inview"
}
}
}],
"tmax": 100000
}
```
**Test request output before this PR's changes:**
Client
```
╰─➤  curl --data …
```

Panics happen when left with zero length []Imp

---

analytics/pubstack/eventchannel/eventchannel.go
analytics/pubstack/eventchannel/eventchannel_test.go

We've spotted an issue on our side. This PR fixes it.

fix: avoid unexpected EOF on gz writer

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go

should translate the "liveramp.com" id from the "user.ext.eids" array to "user.ext.liveramp_idl" as follows:
```
{
"user": {
"ext": {
"eids": [{
"source": 'liveramp.com',
"uids": [{
"id": "T7JiRRvsRAmh88"
}]
}]
}
}
}
```
to XAPI:
```
{
"user": {
"ext": {
"liveramp_idl": "T7JiRRvsRAmh88"
}
}
}
```

Rubicon liveramp param

---

config/config.go
config/config_test.go
config/stored_requests.go
config/stored_requests_test.go
stored_requests/config/config.go
stored_requests/config/config_test.go

- Includes #1446 
- Drop the "Slim" versions of stored request configuration
- Unify stored_requests, categories, stored_video_req configuration
- Add stored_amp, still built from stored_requests but moved to config. Should eventually be its own section.
- Added validation for categories and stored_video_req (previously missing).
- Net fewer lines of code than before
Testing validation for stored_video_req with this bad config
```yaml
stored_video_req:
in_memory_cache:
type: none
cache_events:
enabled: true
endpoint: "/foo"
postgres:
connection:
dbname: "blah"
fetcher:
query: "blah"
poll_for_updates:
query: "blah"
timeout_ms: 0
```
Before the change, prebid-server starts and can crash:
```
I0821 18:22:59.943387   50156 config.go:50] Connecting to Postgres for Stored Video. DB=blah, host=, …
```

Consolidate StoredRequest configs, add validation for all data types

---

analytics/pubstack/eventchannel/eventchannel_test.go

`TestEventChannel_OutputFormat` found in `analytics/pubstack/eventchannel/eventchannel_test.go` is sometimes failing, specially when run by Travis, very likely because of the concurrent functionality of the `EventChannel`methods. This PR corrects said test case and adds assertions.

Fix Test TestEventChannel_OutputFormat

---

.github/workflows/validate.yml

Add github-actions PR and master validation checker.
This works everywhere the repo was forked or mirrored without any additional configuration, unlike the Travis setup.
Reference: https://github.com/mvdan/github-actions-golang
Example results because it's not running in the main prebid repo:
https://github.com/openx/prebid-server-openx/pull/7

github-actions validation checker for PRs and master branch

---

stored_requests/caches/cachestest/reliable.go
stored_requests/caches/memory/cache.go
stored_requests/caches/memory/cache_test.go
stored_requests/caches/nil_cache/nil_cache.go
stored_requests/config/config.go
stored_requests/config/config_test.go
stored_requests/events/api/api_test.go
stored_requests/events/events.go
stored_requests/events/events_test.go
stored_requests/fetcher.go
stored_requests/fetcher_test.go

This PR makes the caches generic and reusable. 
There should be no functionality changes visible from a fetcherWithCache user.
Reason: Cache has Fetcher-like functionality to handle both requests and
imps together, and is only usable for these objects. Internally, it still uses two 
caches configured and searched separately. 
The PR moves out the request-specific part into fetcherWithCache only,
which handles separate caches for each object type.
Keeping the req/imp code repetition in fetcher and out of cache allows for
simpler code while preserving existing fetcher functionality.
Changes in this set:
- Cache is now a simple generic id->RawMessage store called CacheJSON
- fetcherWithCache handles the separate req and imp caches
- ComposedCache handles single caches - but it does not …

Cache refactor

---

exchange/utils.go
privacy/enforcement.go
privacy/enforcement_test.go
privacy/scrubber.go
privacy/scrubber_test.go

We currently remove the device ID information (ifa, mac hash, device hash) for GDPR when a TCF2 consent string only triggers Geo enforcement but allows IDs to be passed.

Fixed TCF2 Geo Only Enforcement

---

exchange/exchange.go
exchange/exchange_test.go
exchange/utils.go
exchange/utils_test.go
openrtb_ext/request.go

This PR implements the ability to return empty ad markup strings in bidResponses when `ext.prebid.cache.vast.returnCreative` or `ext.prebid.cache.bids.returnCreative` is set to false in the incoming bid request. Please let me know your thoughts.
In summary:
**Bid request**
Note the new `returnCreative` field in the bid request extension: 
```
{
"id":"an-id",
"imp":[
{...}
],
"site":{...},
"user": {...},
"ext": {
"prebid":{
"cache":{
"bids":{
"returnCreative":false //<-- new
}
}
}
}
},
```
**Bid Response**
Given the `returnCreative` field in the bid request extension value set to false, an empty `AdM` value is returned in the bid response:
```
{
"status" : 200,
"body": {
"id":"an-id",
"seatBid":[
{
"bid": [
{
"id": "video1AdmVideo",
"impid": "video1",
"price": 20,
"adm": "",  //<-- empty …
```

Implement returnCreative

---

config/config.go
exchange/exchange.go
exchange/exchange_test.go
gdpr/impl_test.go

Resolves Gus' unresolved comment in #1427

Refactor EEAC map to be more in line with the nonstandard publisher map

---

adapters/adgeneration/adgeneration.go
adapters/adgeneration/adgeneration_test.go
adapters/adgeneration/adgenerationtest/exemplary/single-banner.json
adapters/adgeneration/adgenerationtest/supplemental/204-bid-response.json
adapters/adgeneration/adgenerationtest/supplemental/400-bid-response.json
adapters/adgeneration/adgenerationtest/supplemental/no-bid-response.json

fix: add UA to RequestHeader.
fix: fix sizes query.
　　　　　　　　　　　
Change currency of ad-generation's bidResponse according to bidRequest
Maintainer: ssp-ope@supership.jp

Fix missing Request parameter for Adgeneration Adapter

---

config/stored_requests.go
config/stored_requests_test.go
stored_requests/caches/memory/cache.go
stored_requests/config/config.go
stored_requests/config/config_test.go
stored_requests/fetcher.go
stored_requests/fetcher_test.go

Summary
=======
Optional cache for Accounts. This cache is not necessary for the current static file fetcher, it is intended to support upcoming http API and db fetchers.
Implementation
===========
Added [cache support for account fetcher](https://github.com/prebid/prebid-server/compare/master...openx:account-cache?expand=1#diff-c705d31b368d04ad30e87727936db388R194-R204). 
Add [new `size_bytes` parameter for `in_memory_cache`](https://github.com/prebid/prebid-server/compare/master...openx:account-cache?expand=1#diff-64d858641d4b8eb33576093f89ca1c21R400-R401) to control single cache.
Add necessary config validation so `accounts` uses `size_bytes` while the rest have `request_cache_size_bytes`
and `imp_cache_size_bytes`.
Removed some redundant tests and refactored others a little.
Example …

Add Account cache

---

config/config_test.go
config/stored_requests.go
stored_requests/backends/http_fetcher/fetcher.go
stored_requests/backends/http_fetcher/fetcher_test.go

This works the same way as the API for stored requests,
preserving the ability to query multiple ids, so the
same API endpoint can be extended to support accounts.

Add http api for fetching accounts

---

adapters/yieldmo/yieldmo.go
adapters/yieldmo/yieldmotest/exemplary/app-banner.json
adapters/yieldmo/yieldmotest/exemplary/app_video.json
adapters/yieldmo/yieldmotest/exemplary/simple_video.json
static/bidder-info/yieldmo.yaml

add app and video support in static/bidder-info/yieldmo.yaml

Yieldmo app support in yaml file

---

pbsmetrics/config/metrics.go
pbsmetrics/config/metrics_test.go
pbsmetrics/go_metrics.go
pbsmetrics/metrics.go
pbsmetrics/metrics_mock.go
pbsmetrics/prometheus/preload.go
pbsmetrics/prometheus/prometheus.go
pbsmetrics/prometheus/prometheus_test.go
stored_requests/fetcher.go
stored_requests/fetcher_test.go

Follow-up on #1519, issue #1395 
Testing:
At server start:
```
$ curl -s http://localhost:8001/ | egrep ^account
account_cache_performance{cache_result="hit"} 0
account_cache_performance{cache_result="miss"} 0
```
After first request (publisher.id=valid_acct)
```
$ curl -s http://localhost:8001/ | egrep ^account
account_cache_performance{cache_result="hit"} 0
account_cache_performance{cache_result="miss"} 1
account_requests{account="valid_acct"} 1
```
After next 2 requests
```
$ curl -s http://localhost:8001/ | egrep ^account
account_cache_performance{cache_result="hit"} 2
account_cache_performance{cache_result="miss"} 1
account_requests{account="valid_acct"} 3
```

Add metrics for account cache

---

exchange/exchange.go
exchange/exchange_test.go
openrtb_ext/deal_tier.go
openrtb_ext/deal_tier_test.go
openrtb_ext/imp.go

The code which implements DealTiers (largely for long form video auctions) doesn't check the newly preferred `imp.ext.prebid.bidder.{bidder}` section. This fixes that.

Add Support For imp.ext.prebid For DealTiers

---

stored_requests/events/api/api_test.go
stored_requests/events/events.go
stored_requests/events/events_test.go
stored_requests/events/http/http.go
stored_requests/events/http/http_test.go

I just added Accounts alongside Requests and Imps in the events for minimal impact change.
We should consider replacing the event with a more generic `{dataType, data}` message in the future though, to support other data types through the same mechanism.

Add Accounts to http cache events

---

config/accounts.go
config/accounts_test.go
exchange/utils.go
exchange/utils_test.go

Similar to what we are doing for GDPR, as described in issue #1323 and PR #1564, this adds account-level CCPA configuration.
The order of precedence for determining whether CCPA is enabled is the same as for GDPR:
1. Use account-level request type setting if specified
2. Use account-level general setting if specified
3. Use host-level general setting

Add account CCPA enabled and per-request-type enabled flags

---

Dockerfile

The Dockerfile exposes port 8080 that is not in use by the default prebid-server configuration. 
I guess this should expose the default admin port which is 6060 and which is not exposed in the file.

Bugfix: default admin port is 6060

---

adapters/consumable/consumable.go
adapters/consumable/consumable_test.go

Fixes a bug with the consumable adapter that I introduced with https://github.com/prebid/prebid-server/pull/1532

Fix Missing Consumable Clock

---

hooks/pre-push

The `/hooks` folder predates my involvement with the project. It looks like git hooks, but needs to be copied into the `.git` folder to be meaningful. I'm not aware of anyone using these currently. We discussed this internally and propose it's complete removal.
This is unrelated to the validate script or the validate GitHub Action.

Remove Hook Scripts

---

config/adapter.go
config/config.go

This is purely a move of code with no other changes. I'm setting up a future PR for adding adapter config merge code.

Move Adapter Config To Its Own File

---

.github/workflows/validate-merge.yml
.github/workflows/validate.yml
.travis.yml
README.md
go.mod

- Formatting updated.
- Validate workflow no longer runs on release creation. I don't see a need for this.
- Validate workflow now validates just the branch to match what TravisCI did.
- Validate Merge workflow added to validate things are still good after the auto-merge occurs.
- Dropped Go 1.13 build targets / support.
- Upgraded go.mod to 1.14.

Improve GitHub Actions Validation

---

exchange/utils.go
exchange/utils_test.go

I'm leaving this as a draft until #1591 is merged, at which point I'll rebase this and make it ready for review.

Enforce GDPR privacy if there's an error parsing consent

---

adapters/emx_digital/emx_digital.go

The adapter changes a shared video pointer without first making a copy. We have reason to believe this is causing occasional memory corruption issues when marshaling a request targeting multiple adapters.
@EMXDigital Can you please review?

Fix Shared Memory Corruption In EMX_Digital

---

adapters/eplanning/eplanning.go
adapters/eplanning/eplanningtest/supplemental/banner-2-sizes-in-priority-list-mobile.json
adapters/eplanning/eplanningtest/supplemental/banner-3-sizes-in-priority-list-desktop.json
adapters/eplanning/eplanningtest/supplemental/banner-3-sizes-in-priority-list-mobile.json
adapters/eplanning/eplanningtest/supplemental/banner-3-sizes-inout-priority-list-mobile.json
adapters/eplanning/eplanningtest/supplemental/banner-4-sizes-in-priority-list-desktop.json

Feature
New prioritization metric for adunit sizes
chino117@hotmail.com

Eplanning: new prioritization metric for adunit sizes

---

adapters/amx/amx.go
adapters/amx/amxtest/exemplary/app-simple.json
adapters/amx/amxtest/exemplary/display-multiple.json
adapters/amx/amxtest/exemplary/video-simple.json
adapters/amx/amxtest/supplemental/204-response.json
adapters/amx/amxtest/supplemental/400-response.json
adapters/amx/amxtest/supplemental/500-response.json

This is a bugfix for an issue affecting the AMX Bid adapter. When the AMX RTB server responds with multiple (N) bids, the adapter will parse this as the first bid, repeated N times.
This is due to the fact that we store a pointer to the `bid` variable in the `TypedBid` which is changed with each iteration of the loop.
- added test `display-multiple.json` to reproduce
- refactored to add temporary loop variable
- bumped amx version string

AMX Bid Adapter: Loop Variable Bug

---

exchange/bidder.go
exchange/bidder_test.go
exchange/exchange_test.go
exchange/exchangetest/request-multi-bidders-debug-info.json
openrtb_ext/response.go

httpcalls.\<BIDDER>.**_requestheaders_** - New Debug parameter
@SyntaxNode, Please review and approve this PR.
It will be useful to log a set of request headers sent to the actual Bidder. This will help in verifying if required request headers are correctly getting sent to the actual Bidder.
This parameter will be visible only when query parameter _debug=1_ is set. For example,
> http://localhost:8000/openrtb2/video?debug=1
> <img width="1355" alt="image" src="https://user-images.githubusercontent.com/9314645/105181655-16a09280-5b52-11eb-9a61-1bb377b7d535.png">
In above example **requestheaders** indicating 2 headers are sent to appnexus bidder.
1.  "Accept": ["application/json"],
2. "Content-Type": ["application/json;charset=utf-8"]
****

requestheaders: new parameter inside debug.httpcalls.<BIDDER> to log request header details

---

adapters/info.go
config/accounts.go
config/config.go
endpoints/openrtb2/video_auction.go
exchange/adapter_util.go
exchange/adapter_util_test.go
exchange/bidder.go
exchange/bidder_test.go
exchange/bidder_validate_bids.go
exchange/bidder_validate_bids_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/exchangetest/append-bidder-names.json
exchange/exchangetest/debuglog_disabled.json
exchange/exchangetest/debuglog_enabled.json
exchange/legacy.go
exchange/legacy_test.go
exchange/targeting_test.go

- Added Bidder level debug variable
- Added Account level debug variable

Debug disable feature implementation:

---

adapters/adform/adform.go
adapters/adform/adform_test.go
adapters/adform/adformtest/exemplary/multiformat-impression.json
adapters/adform/adformtest/exemplary/single-banner-impression.json
adapters/adform/adformtest/exemplary/single-video-impression.json
adapters/adform/adformtest/supplemental/user-nil.json
config/config.go

Removed digitrust user-id support in Adform adapter.
Default endpoint changed to secure one.

Adform adapter: digitrust cleanup

---

gdpr/gdpr.go
gdpr/vendorlist-fetching.go
gdpr/vendorlist-fetching_test.go

Partially addresses https://github.com/prebid/prebid-server/issues/1689 and separates the TCF1 vs TCF2 fetchers for easy removal of TCF2 in the near future and removal now for TCF1 url construction.

Don't Load GVL v1 for TCF2 (+ TCF1 Cleanup)

---

adapters/adform/adform.go
adapters/adform/adformtest/supplemental/regs-ext-nil.json

The standard Go JSON parser will return an error if the input is nil. Adding a nil check and a test case.
@braizhas Could you please review?

AdForm: Fix Regs Parsing

---

adapters/33across/33across.go

Copies of reference fields needed to be made inside `adapters/33across/33across.go` in order to avoid a data race on shared memory. Authors of source code should be notified and encourage to make any changes to this PR if they disagree with the proposed approach.

33Across: Fix Shared Memory Overwriting

---

adapters/33across/33across.go

This reverts commit bdf1e7b3e13bdf87d3282bf74472fc66504537d5. I merged it in too early.

Revert "Fix race condition in 33across.go (#1757)"

---

adapters/pubmatic/pubmatic.go

Copy of reference field Banner needed to be made inside `adapters/pubmatic/pubmatic.go` in order to avoid a data race on shared memory. Authors of source code should be notified and encourage to make any changes to this PR if they disagree with the proposed approach.

Pubmatic: Fix Shared Memory Overwriting

---

adapters/beachfront/beachfront.go

The Beachfront adapter seems to be writting to shared memory inside the `getVideoRequests` function, particulartly to the `bfReqs[i].Request.Device` and the `bfReqs[i].Request.Site` fields. This pull request proposes changes to stop the race conditions, but authors of the beachfront adapter source code should be notified and encouraged to make any changes to this PR if they disagree with the proposed approach.

Beachfront: Fix Shared Memory Overwriting

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/first-party-data/valid-fpd-allowed-with-ext-bidder.json
endpoints/openrtb2/sample-requests/first-party-data/valid-fpd-allowed-with-prebid-bidder.json
exchange/exchangetest/firstpartydata-imp-ext-multiple-bidders.json
exchange/exchangetest/firstpartydata-imp-ext-multiple-prebid-bidders.json 
exchange/exchangetest/firstpartydata-imp-ext-one-bidder.json
exchange/exchangetest/firstpartydata-imp-ext-one-prebid-bidder.json
exchange/utils.go
exchange/utils_test.go
openrtb_ext/request.go

All json fields within `request.imp[].ext` are expected to be bidder names. Exemptions need to be made for special cases, such as for First Party Data. Other parts of code enforce the bidder name "data" is forbidden making this a safe operation.
Implements https://github.com/prebid/prebid-server/issues/1768

FPD: Allow imp.ext.data To Passthrough To Adapters

---

adapters/smaato/smaato.go
adapters/smaato/smaatotest/exemplary/simple-banner-app.json
adapters/smaato/smaatotest/exemplary/simple-banner-richMedia-app.json
adapters/smaato/smaatotest/exemplary/simple-banner-richMedia.json
adapters/smaato/smaatotest/exemplary/simple-banner.json
adapters/smaato/smaatotest/exemplary/video-app.json
adapters/smaato/smaatotest/exemplary/video.json
adapters/smaato/smaatotest/supplemental/bad-adm-response.json
adapters/smaato/smaatotest/supplemental/bad-imp-banner-format-req.json
adapters/smaato/smaatotest/supplemental/no-consent-info.json
adapters/smaato/smaatotest/supplemental/status-code-204.json
adapters/smaato/smaatotest/supplemental/status-code-400.json

This PR allows the Smaato adapter to send app bid requests to the Smaato bidder endpoint.

Smaato: Add support for app

---

adapters/yeahmobi/yeahmobi.go

Copy of reference field `Native` needed to be made inside `adapters/yeahmobi/yeahmobi.go` in order to avoid a data race on shared memory. Authors of source code should be notified and encourage to make any changes to this PR if they disagree with the proposed approach.

Yeahmobi: Fix Shared Memory Overwriting

---

adapters/pubnative/pubnative.go

Copy of reference field `Banner` needed to be made inside `adapters/pubnative/pubnative.go` in order to avoid a data race on shared memory. Authors of source code should be notified and encourage to make any changes to this PR if they disagree with the proposed approach.

Pubnative: Fix Shared Memory Overwriting

---

adapters/ix/ix.go
adapters/ix/ix_test.go

- Update IX adapter to set bidVideo if category and duration is available from response for video supply.

IX: Set bidVideo when category and duration is available

---

config/config.go

Adds IX user sync endpoint and disables adapter by default.
Currently, we'll plan to provide endpoints to PBS operators who want to enable our adapter with aims to provide a default endpoint in the future.

Update IX adapter defaults

---

adapters/openx/openx.go
adapters/openx/openxtest/exemplary/optional-params.json

- Fixes bug that set bidfloor to 0 when customFloor not given (so almost always)
- Implements behavior in https://github.com/prebid/Prebid.js/blob/master/modules/openxBidAdapter.js#L495
- for #1787

Openx: use bidfloor if set - prebid.js adapter behavior 

---

static/bidder-params/kidoz.json

Remove definitions object from schema and define types and other parameters directly in properties objects to ensure compatibility with more downstream systems that use this schema.

Kidoz: Update JSON Schema Reference To Type String

---

static/bidder-params/bidmachine.json

Remove definitions object from schema and define types and other parameters directly in properties objects to ensure compatibility with more downstream systems that use this schema.

Bidmachine: Update JSON Schema Reference To Type String

---

adapters/outbrain/outbrain.go
adapters/outbrain/outbraintest/exemplary/native.json

Since the PUC native-trk library doesn't support eventtrackers, this PR transforms them to the deprecated imptrackers and jstracker for the outbrain adapter.

Outbrain: transform native eventtrackers to imptrackers and jstracker

---

adapters/appnexus/appnexus.go
adapters/appnexus/appnexustest/supplemental/reserve-ignored.json
adapters/appnexus/appnexustest/supplemental/reserve-test.json

Set Appnexus to prefer the openrtb bid floor if it is supplied.
RE: https://github.com/prebid/prebid-server/issues/1787

AppNexus: reform bid floor handling

---

adapters/ix/ix.go
adapters/ix/ix_test.go

From context in https://prebid.slack.com/archives/C7UCUKKB8/p1619639305041100, we should be setting bid.cat, not PrimaryCategory in order to utilize category translation.
Update adapter to accept both for compatibility as we fully migrate to bid.cat in exchange response.

IX: Set category in bid.cat

---

adapters/adf/adf.go
adapters/adf/adftest/exemplary/multi-format.json
adapters/adf/adftest/exemplary/single-banner.json
adapters/adf/adftest/exemplary/single-video.json
adapters/adf/adftest/supplemental/invalid-imp-mediatype.json
static/bidder-info/adf.yaml

Docs: https://github.com/prebid/prebid.github.io/pull/2941
Prebid.js PR: https://github.com/prebid/Prebid.js/pull/6726

Adf: banner and video media type support added

---

adapters/beachfront/beachfront.go
adapters/beachfront/beachfronttest/supplemental/adm-video-schain.json
adapters/beachfront/beachfronttest/supplemental/banner-204-with-body.json
adapters/beachfront/beachfronttest/supplemental/banner-204.json
adapters/beachfront/beachfronttest/supplemental/banner-and-adm-video-by-explicit.json
adapters/beachfront/beachfronttest/supplemental/banner-and-adm-video-expected-204-response-on-banner.json
adapters/beachfront/beachfronttest/supplemental/banner-and-adm-video.json
adapters/beachfront/beachfronttest/supplemental/banner-and-nurl-video.json
adapters/beachfront/beachfronttest/supplemental/banner-bad-request-400.json
adapters/beachfront/beachfronttest/supplemental/banner-schain.json
adapters/beachfront/beachfronttest/supplemental/bidder_response_unmarshal_error_banner.json
adapters/beachfront/beachfronttest/supplemental/bidfloor-below-min.json
adapters/beachfront/beachfronttest/supplemental/six-nine-combo.json
adapters/beachfront/beachfronttest/supplemental/two-four-combo.json

This adds schain data to the back end banner call, and fixes test cases to match.

Beachfront: Add schain support

---

adapters/pangle/pangle.go
adapters/pangle/pangletest/exemplary/app_banner.json
adapters/pangle/pangletest/exemplary/app_native.json
adapters/pangle/pangletest/exemplary/app_video_instl.json
adapters/pangle/pangletest/exemplary/app_video_rewarded.json
adapters/pangle/pangletest/params/race/banner.json
adapters/pangle/pangletest/params/race/native.json
adapters/pangle/pangletest/params/race/video.json
adapters/pangle/pangletest/supplemental/appid_placementid_check.json
adapters/pangle/pangletest/supplemental/missing_appid_or_placementid.json
adapters/pangle/pangletest/supplemental/pangle_ext_check.json
adapters/pangle/pangletest/supplemental/response_code_204.json
adapters/pangle/pangletest/supplemental/response_code_400.json
adapters/pangle/pangletest/supplemental/response_code_non_200.json
adapters/pangle/pangletest/supplemental/unrecognized_adtype.json
adapters/pangle/param_test.go
openrtb_ext/imp_pangle.go
static/bidder-params/pangle.json

doc PR: https://github.com/prebid/prebid.github.io/pull/2942
changes:
- add the optional appid and placementid (which when used, must be used in conjunction) to bidder param, then use them to form networkids in imp.ext
- add a true is_prebid flag for the auto recognition of prebid requests on our side

Pangle: add appid & placementid to bidder param

---

static/bidder-info/smaato.yaml

Updating the Bidder Info file with the Smaato TCF 2.0 vendor id
https://iabeurope.eu/vendor-list-tcf-v2-0/

Smaato: Add TCF 2.0 vendor id

---

adapters/bidder.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/video_auction.go
exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go

Implements https://github.com/prebid/prebid-server/issues/1712

Pass Global Privacy Control header to bidders

---

static/bidder-info/interactiveoffers.yaml

dev@interactiveoffers.com bounced. Confirmed with interactiveoffers that support is the right address

interactiveoffers: Updating contact info

---

adapters/criteo/criteotest/supplemental/multislots-alt-case.json
adapters/criteo/params_test.go
static/bidder-params/criteo.json

Our PBS adapter has been released initially accepting both **zoneid** and **networkid** (with that specific case).
However, our public Prebid documentation states that we are accepting **zoneId** and **networkId**, causing issues for publishers using both adapters.
So, we want our PBS adapter to accept both cases.

Criteo: accept zoneId and networkId alternate case

---

config/config.go
config/config_test.go
endpoints/auction_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/targeting_test.go
exchange/utils.go
exchange/utils_test.go
gdpr/gdpr.go
gdpr/impl.go
gdpr/impl_test.go
main_test.go

`gdpr.default_value` is now required and may be specified through a config file or as an env var. If it is not provided, we will fail hard reporting a validation error to the host.
All other validation looks at the unmarshaled viper data but I didn't want to convert `default_value` to a pointer so I made use of the viper `IsSet` method to detect presence.
Given the need for the viper instance now to perform validation, I originally tried to keep things simple by placing this validation logic at the top of the top-level config validate function instead of passing the viper instance down into the GDPR validate method. Ultimately I ended up passing the viper instance down so that all GDPR-related config validation is kept together.

GDPR: require host specify default value

---

main.go

Small change to omit the stack trace when startup errors are found. The stack trace just points to `main.go`, and is therefore useless. `glog.Exitf` exists immediately with a status code of 1. Previously the status code was 255.

Friendlier Startup Error Messages

---

adapters/outbrain/outbrain.go
adapters/outbrain/outbraintest/supplemental/general_params.json
adapters/outbrain/outbraintest/supplemental/optional_params.json

Hey,
this PR changes the adapter so that the the imp tagid is overwritten with the ext tagid only if it exists.

Outbrain adapter: overwrite tagid only if it exists

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicontest/supplemental/no-site-content-data.json
adapters/rubicon/rubicontest/supplemental/no-site-content.json

Fixes an unchecked nil reference from #1909 and adds related json test coverage.

Rubicon: Fix Nil Reference Panic From #1909

---

adapters/criteo/criteo.go
adapters/criteo/criteotest/exemplary/simple-banner-cookie-uid.json
adapters/criteo/criteotest/exemplary/simple-banner-inapp.json
adapters/criteo/criteotest/exemplary/simple-banner-uid.json
adapters/criteo/criteotest/supplemental/ccpa-with-consent-simple-banner-inapp.json
adapters/criteo/criteotest/supplemental/ccpa-with-consent-simple-banner-uid.json
adapters/criteo/criteotest/supplemental/gdpr-with-consent-simple-banner-inapp.json
adapters/criteo/criteotest/supplemental/gdpr-with-consent-simple-banner-uid.json
adapters/criteo/criteotest/supplemental/multislots-alt-case.json
adapters/criteo/criteotest/supplemental/multislots-simple-banner-inapp.json
adapters/criteo/criteotest/supplemental/multislots-simple-banner-uid.json
adapters/criteo/criteotest/supplemental/simple-banner-with-direct-size-and-formats-not-included.json
adapters/criteo/criteotest/supplemental/simple-banner-with-direct-size-and-formats.json
adapters/criteo/criteotest/supplemental/simple-banner-with-direct-size.json
adapters/criteo/criteotest/supplemental/simple-banner-with-ipv6.json
adapters/criteo/models.go

We've detected an error in our adapter as the field mapped when handling bid responses from our bidder are not consistent with the actual naming of the fields used in our production bidder bid responses.

Criteo: Fix fields mapping error when building bid from bidder response

---

exchange/bidder_validate_bids.go
exchange/bidder_validate_bids_test.go

Addressing this issue https://github.com/prebid/prebid-server/issues/1308

Allowed $0.00 price bids if there are deals

---

config/config.go
config/config_test.go
gdpr/impl.go
gdpr/impl_test.go

- Updated GDPR TCF2 config defaults test to assert using object compare
- Added host-level per-purpose bool enforce vendors config flags that indicate whether to skip consent string vendor checks
- Refactored `impl.go` consent and legit interest conditional statements into methods to improve readability and to ensure test code coverage. These methods also check whether to bypass the consent string vendor check based on the enforce vendor config flag
- Created helper function `allPurposesEnabledPermissions` in `impl_test.go` that returns a ready-made permissions object for use across tests
- Updated `impl_test.go` `TestAllowActivitiesBidRequests` to achieve code coverage of enforce vendor checks

GDPR: host-level per-purpose enforce vendor signals config

---

adapters/sharethrough/butler.go
adapters/sharethrough/butler_test.go
openrtb_ext/imp_sharethrough.go
static/bidder-params/sharethrough.json

Sharethrough: Add support for GPID

---

adapters/admixer/admixer.go
adapters/admixer/admixertest/exemplary/optional-params.json
adapters/admixer/params_test.go
static/bidder-params/admixer.json

- use admixerExt.CustomBidFloor only if imp->bidfloor was zero
- added testcase 
- fixed ZoneId pattern

Admixer: Fix for bid floor issue#1787

---

adapters/yieldmo/yieldmo.go
adapters/yieldmo/yieldmotest/exemplary/with_gpid.json

add support for reading pbadslot in imp[].ext.data and outputting it as imp.ext.gpid in yieldmo request

Yieldmo: Add gpid support

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
exchange/exchange.go
exchange/exchange_test.go
openrtb_ext/bid.go
util/jsonutil/jsonutil.go
util/jsonutil/jsonutil_test.go

Implements https://github.com/prebid/prebid-server/issues/1075

Mirror stored imp data to bid response

---

currency/aggregate_conversions_test.go
currency/rate_converter_test.go
currency/rates.go
currency/rates_test.go
endpoints/openrtb2/auction_test.go
exchange/bidder_test.go
exchange/exchange.go

The `DataAsOf time.Time` field of the `Rates struct` found in `currency/rates.go` has no use in practice because `(rc *RateConverter) update()` method sets the `RateConverter`'s `lastUpdated` field to `time.Now()` in line 82 shown below and ignores the `rates.DataAsOf` field that the `fetch()` function unmarshals in line 79. This pull request removes the `DataAsOf` field entirely which is useful in order to simplify the code specially in the numerous `NewRates()` calls throughout the codebase.
```
77 // Update updates the internal currencies rates from remote sources
78 func (rc *RateConverter) update() error {
79     rates, err := rc.fetch()
80     if err == nil {
81         rc.rates.Store(rates)
82         rc.lastUpdated.Store(rc.time.Now())
83     } else {
84         if …
```

Remove time.Now() as the first parameter of NewRates()

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/valid-whole/supplementary/imp-info-invalid.json
openrtb_ext/imp.go

Due to upcoming stored response integration, amount of `jsonparser.Get` usages will be dramatically increased. It makes more sense to unmarshal `imp.ext.prebid`to access stored requests and stored responses data without using `jsonparser.Get`more than 3 times in a row.

processStoredRequests refactoring

---

config/config.go
config/config_test.go

Hey!
This PR fixes the external cache host validation to support having a host with a port (useful for local development)

Fix external cache host validation

---

config/config.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_benchmark_test.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
router/router.go
util/uuidutil/uuidutil.go

Addressing this issue here https://github.com/prebid/prebid-server/issues/1507
I've added a configuration boolean flag, `GenerateRequestId`, which when set to true, will generate a uuid for auction bid requests, which can be used to solve the amp auction issue found here https://github.com/prebid/prebid-server/issues/1507
This generation can occur in two different functions:
1. In amp_auction.go/loadRequestJSONForAmp( ) -- where we load the stored openRTB request for an incoming AMP request. Here we can check our boolean flag, and generate an ID if necessary.
2. In auction.go/processStoredRequests() -- we check here if `GenerateRequestId` is true, and if so, we generate a uuid and patch it into the request

Generate Unique Bidrequest IDs for Amp Auctions

---

router/router.go
router/router_test.go

Fixes an issue where the host configured user sync override is ignored due to a case sensitivity issue between the adapter config (always lower case) and bidder info config (potentially mixed case).

Fix UserSync Config Case Sensitivity Issue

---

adapters/yieldlab/yieldlab.go
adapters/yieldlab/yieldlabtest/exemplary/multiple_impressions.json

Fixes a bug where when requesting bids for more than one ad unit, the resulting bids could be associated with the wrong ad unit.
This bug was due to the returned bids being dealt with in a for-loop whose index was being used to step through the configured ad units (see lines 215+232). If the returned bids for the ad units were not in the same order as the configured ad units, they would be matched wrongly.  
The fix uses the respective Yieldlab adslot ID to find the correct impression and ad unit for a given bid.

Yieldlab: Fix ad unit handling

---

exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/utils.go
exchange/utils_test.go

Back when PR #1387 was coded, we decided to store the `debugInfo` boolean value (now renamed to `requestDebugInfo`) inside the `ctx context.Context` in order to keep the number of parameters passed to functions `getAllBids` and `requestBids` short:
```
92 func (e *exchange) HoldAuction(ctx context.Context, bidRequest *openrtb.BidRequest, usersyncs IdFetcher, labels pbsmetrics.Labels, categoriesFetcher *stored_requests.CategoryFetcher, debugLog *
.
.
105     debugInfo := getDebugInfo(bidRequest, requestExt)
106     if debugInfo {
107         ctx = e.makeDebugContext(ctx, debugInfo)
108     }
109
exchange/exchange.go
```
Since then, changes have been coded and we are currently passing a debug boolean flag to both `getAllBids` and `requestBids`. This pull request consolidates the …

Stop storing requestDebugInfo boolean value in context

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go

In the original issue https://github.com/prebid/prebid-server/issues/1507, there was a request to add support for a macro ID, where if Prebid Server sees {{UUID}} then resolve to a UUID.
I didn't include this feature in the already merged issue https://github.com/prebid/prebid-server/pull/1938
So this pull request is to add support for that feature.

Adding Support for Macro {{UUID}} to Support Feature: Generate Unique Bidrequest ID

---

endpoints/version.go
endpoints/version_test.go
router/router.go

Implements https://github.com/prebid/prebid-server/issues/1172

Version Endpoint

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go

Addressing the bug issue brought up here: https://github.com/prebid/prebid-server/issues/2045
The issue came with how the conditionals were set up when deciding when to generate a UUID. Since we first check whether the GenerateRequestId flag is true or if the macro {{"UUID"}} is set, if either of those conditions are true, and then the request is a site request, we won't generate an id, but we also won't perform any of the stored request merging operations. By re-arranging the conditionals, we now can avoid this bug. 
Tests were added as well to check for this bug.

Address stored request not merging with UUID bug

---

config/config.go
config/config_test.go
main.go

Pull request #2049 removed the legacy `/auction` endpoint. An unintended consequence of removing the legacy code was an increase in CPU time caused by garbage collection overhead. After a thorough investigation of the performance of the system, the Prebid Server Team found out that the initialization of a very large slice in the old code was preventing the garbage collection to be called repeatedly, saving CPU time. This pull request puts back a soft memory limit to save CPU performance and makes this value configurable.
Issue [#48409](https://github.com/golang/go/issues/48409) posted in the go development project better explains what happens behind the scenes, in summary, we are setting an amount of memory that is going to be held garbage before a garbage collection cycle gets triggered.

Add a garbage collection threshold

---

config/bidderinfo.go
config/bidderinfo_test.go
config/config.go
usersync/syncer.go
usersync/syncer_test.go

Allows a host to override the external url at the syncer level in addition to the existing syncer endpoint level. This will make it easier for the host to configure an override since the endpoint type is no longer required, but is still available if different endpoints require different values.

Syncer Level ExternalURL Override

---

static/bidder-info/unruly.yaml

there was a mistake in the url for the user sync last time here is a fix for it to the correct one

Unruly: changes to the correct user sync url

---

adapters/adf/adf.go
adapters/adf/adftest/exemplary/single-banner-pricetype-gross-extend-ext.json
adapters/adf/adftest/exemplary/single-banner-pricetype-gross.json
adapters/adf/adftest/exemplary/single-banner-pricetype-net.json
adapters/adf/adftest/exemplary/two-banners-different-pricetypes-extend-ext.json
adapters/adf/adftest/exemplary/two-banners-different-pricetypes.json
adapters/adf/params_test.go
openrtb_ext/imp_adf.go
static/bidder-params/adf.json
static/bidder-params/adform.json

The client version of the Adform adapter supports choosing between returning gross or net via the priceType parameter.
As the new "adf" adapter defaults to net while the old "adform" adapter defaulted to gross, this can make the transition to the new adapter become quite a challenge if you are using plenty of bid conversion functions and the PBS adapter doesn't support selecting gross or net.
This PR adds the same priceType support as the client has.

Adform adapter lacked gross/net parameter support

---

metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go
server/prometheus.go

This pull request modifies Prebid Server's Prometheus metrics adapter. It adds the ability to collect data about the system's Go process such as memory stats that Prometheus' `GoCollector` provides (documentation of Prometheus GoCollector [here](https://github.com/prometheus/client_golang/blob/6d5cf25fcc344ed30a0623e36c73639bfac112b4/prometheus/go_collector.go)). In a similar fashion to Prebid Server custom-defined metrics, these newly added Go process metrics will also come prefixed with `prebid_server_`.
Prometheus endpoint output after changes implemented in this PR:
```
prebid_server_account_cache_performance{cache_result="hit"} 0
prebid_server_account_cache_performance{cache_result="miss"} 0
prebid_server_adapter_bids{adapter="33across",delivery="adm"} 0 …
```

Collect Prometheus Go process metrics

---

adapters/compass/compass.go
adapters/compass/compass_test.go
adapters/compass/compasstest/exemplary/endpointId.json
adapters/compass/compasstest/exemplary/simple-banner.json
adapters/compass/compasstest/exemplary/simple-native.json
adapters/compass/compasstest/exemplary/simple-video.json
adapters/compass/compasstest/exemplary/simple-web-banner.json
adapters/compass/compasstest/supplemental/bad_media_type.json
adapters/compass/compasstest/supplemental/bad_response.json
adapters/compass/compasstest/supplemental/status-204.json
adapters/compass/compasstest/supplemental/status-not-200.json
adapters/compass/params_test.go
config/config.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_compass.go
static/bidder-info/compass.yaml
static/bidder-params/compass.json

doc - https://github.com/prebid/prebid.github.io/pull/3441

New Adapter: Compass

---

adapters/adot/adot.go
adapters/adot/adot_test.go
adapters/adot/adottest/exemplary/simple-banner.json
adapters/adot/adottest/exemplary/simple-interstitial.json
adapters/adot/adottest/exemplary/simple-native.json
adapters/adot/adottest/exemplary/simple-video.json

Hello,
This PR is about adding OpenRTB macros resolution in Adot adapter, as discussed here [https://github.com/prebid/prebid-server/issues/1804](https://github.com/prebid/prebid-server/issues/1804)
Sincerely,

Adot: Add OpenRTB macros resolution

---

config/config.go
config/config_test.go
gdpr/impl.go
gdpr/impl_test.go
gdpr/vendorlist-fetching_test.go

This PR fixes a GDPR bug and depends on https://github.com/prebid/go-gdpr/pull/34.
We currently determine if geo information should be passed in a bid request based on whether special purpose 1 is set in the GVL for the vendor which is incorrect. Instead we should be looking at whether special feature 1 is set for the vendor. The main change is here in `impl.go` on line 137:
`passGeo = vendorException || (consentMeta.SpecialFeatureOptIn(1) && (vendor.SpecialFeature(1) || weakVendorEnforcement))`
Special purposes are defined in the TCF2 spec but they are not used by PBS. As a result, all references to special purpose 1 have been renamed to eliminate confusion.

GDPR: pass geo based on special feature 1 opt-in

---

go.mod
go.sum

**github.com/coocood/freecache**
Was 2 releases behind. Release notes indicate a small number of bug fixes and new features.
**github.com/gofrs/uuid** (Highest Risk In This PR)
Was 5 releases behind. Release notes indicate new fmt.Formatter support, some changes to error message strings, and the removal of UUID V2. Do we rely on UUID v2? 
**github.com/golang/glog**
Was 1 release behind with the only difference being added support for Go Modules.
**github.com/mxmCherry/openrtb**
Was 1 release behind which the release notes describe as "Basically this is a housekeeping/info release, no code changes."

Update Some Dependencies

---

account/account.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/video_auction.go
exchange/events.go
firstpartydata/first_party_data.go
go.mod
go.sum

**github.com/asaskevich/govalidator**
We were 4 releases behind. Release notes indicate a lot of updates, but we only use two methods from this library so the risk seems minimal.
**github.com/evanphx/json-patch** (Highest Risk In This PR)
We were 14 releases behind. Release notes are not detailed and there are a lot of [commits](https://github.com/asaskevich/govalidator/compare/f9ffefc3facf...master). There is a lot of test coverage for this library and its programmed against a well defined specification, so I'm not terribly concerned.
**github.com/rs/cors**
We were 5 releases behind. Release notes are not provided but the [changes](https://github.com/rs/cors/compare/v1.5.0...v1.8.2) look reasonable.
**github.com/DATA-DOG/go-sqlmock**
We were 6 releases behind. Release notes indicates …

Update Some Dependencies - Part 2

---

adapters/invibes/invibes.go
adapters/invibes/invibes_test.go
adapters/invibes/invibestest/exemplary/advanced-ad.json
adapters/invibes/invibestest/exemplary/test-ad.json
config/config.go

Invibes Bid Adapter update for prebid-server
Removed {Host} macro and replaced with {ZoneID}
No documentation update necessary since this is internal use only.
Maintainer: system_operations@invibes.com

Invibes Bid Adapter - replaced Host macro with ZoneID

---

static/bidder-info/synacormedia.yaml

This updates the synacormedia adapter with:
- contact email uses the new email domain after Synacor Media was acquired by iMedia Brands Inc. In September 2021
- updates the iframe usersync URL

synacormedia - Update YAML with new contact email and usersync endpoint

---

Dockerfile

Updated Dockerfile to use `RUN` command for `chmod` rather than the `--chmod` flag on the `COPY` command as the latter is a relatively new feature and requires Docker Buildkit.

Update Dockerfile to use run command for chmod

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/valid-whole/supplementary/imp-with-stored-resp.json
endpoints/openrtb2/sample-requests/valid-whole/supplementary/req-imp-stored-response.json
endpoints/openrtb2/sample-requests/valid-whole/supplementary/req-two-imps-missing-stored-response.json
endpoints/openrtb2/sample-requests/valid-whole/supplementary/req-two-imps-one-stored-response.json
endpoints/openrtb2/sample-requests/valid-whole/supplementary/req-two-imps-stored-response.json
endpoints/openrtb2/video_auction.go
exchange/exchange.go
exchange/exchange_test.go
openrtb_ext/imp.go
router/router.go

Issue: https://github.com/prebid/prebid-server/issues/861
Implementation of Single Stored Auction Response

Single stored auction response

---

.github/workflows/security.yml
.github/workflows/validate.yml

The default Dependabot is not comprehensive. Adding Trivy to the build pipeline as a stronger defense against CVE security issues throughout the entire dependency hierarchy.

New GitHub Action: Trivy Security Scan

---

adapters/adkernelAdn/adkernelAdn.go
adapters/adkernelAdn/adkernelAdn_test.go
adapters/adkernelAdn/adkerneladntest/exemplary/multiformat-impression.json
adapters/adkernelAdn/adkerneladntest/exemplary/single-banner-impression.json
adapters/adkernelAdn/adkerneladntest/exemplary/single-video-impression.json
adapters/adkernelAdn/adkerneladntest/supplemental/204status.json
adapters/adkernelAdn/adkerneladntest/supplemental/http-err-status.json
adapters/adkernelAdn/adkerneladntest/supplemental/two-impressions-two-seatbids.json
config/config.go
openrtb_ext/imp_adkernelAdn.go
static/bidder-params/adkernelAdn.json

Switched to static adkernel host instead of publisher-side configured domains to address https://github.com/prebid/prebid-server/issues/2127

AdkernelAdn: static endpoint host

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatic_test.go
adapters/pubmatic/pubmatictest/exemplary/banner.json
adapters/pubmatic/pubmatictest/exemplary/video.json
adapters/pubmatic/pubmatictest/supplemental/app.json
openrtb_ext/imp_pubmatic.go
static/bidder-params/pubmatic.json

Add support to 'kadfloor' bid param in PubMatic adapter. (Already supported in client side Prebid).
Documentation https://docs.prebid.org/dev-docs/pbs-bidders.html#pubmatic

Support kadfloor param in PubMatic adapter

---

exchange/targeting.go
exchange/targeting_test.go
openrtb_ext/bid.go
openrtb_ext/bid_test.go

This PR is a follow up to https://github.com/prebid/prebid-server/pull/2181
In this PR, I update the `addKeys` function to also apply the truncation to the Targeting Key itself

Apply new Truncate Targeting Config to Key

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go

This PR is a follow to two previous PRs https://github.com/prebid/prebid-server/pull/1938 and https://github.com/prebid/prebid-server/pull/2000
In those PRs, the goal was to generate a UUID for when an **app** or amp request had a stored bid request and that stored bid request had an ID = {{UUID}} or a config flag `GenerateRequestId` was set to true. 
This update removes the restriction where the auction endpoint would check if the request was an app request, and instead, as long as the request has a stored request, and the macro {{UUID}} or the config flag is set to true, the UUID would be generated.

Remove Restrictions for UUID Generation For Stored Bid Requests

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatic_test.go
adapters/pubmatic/pubmatictest/exemplary/banner.json
adapters/pubmatic/pubmatictest/exemplary/video.json
static/bidder-params/pubmatic.json

Add support to 'act' request ext param in PubMatic adapter.
Documentation https://docs.prebid.org/dev-docs/pbs-bidders.html#pubmatic (https://github.com/prebid/prebid.github.io/pull/3657)
PBJS: https://github.com/prebid/Prebid.js/pull/8246

PubMatic: add "acat" parameter

---

adapters/yieldlab/yieldlab.go

We do want to send the consent string even though we are not getting a gdpr flag (We will default to 1 internally and respect the gdpr consent). This problems currently exists when requested via AMP.

Yieldlab: Fix GDPR handling for AMP

---

adapters/amx/amx.go
adapters/amx/amx_test.go
adapters/amx/amxtest/exemplary/app-simple.json
adapters/amx/amxtest/exemplary/display-multiple.json
adapters/amx/amxtest/exemplary/simple-native.json
adapters/amx/amxtest/exemplary/video-simple.json
adapters/amx/amxtest/exemplary/web-simple.json
adapters/amx/amxtest/supplemental/204-response.json
adapters/amx/amxtest/supplemental/400-response.json
adapters/amx/amxtest/supplemental/500-response.json
static/bidder-info/amx.yaml

This PR adds support for native ads & removes unnecessary legacy code that was used for interpolating pixels into ad markup:
- add support for native requests, checking bid type based on bid.ext
- update AMX adapter internal version to 1.2
- add test of bid.ext / bid type logic in MakeBids

AMX Adapter: support native format

---

config/config.go
server/listener.go
server/server.go
server/server_test.go

REF : issue #2147 [feature request]
Allow users to listen unix_socket's file of main_server's handlers.

Allow http support for unix_socket

---

endpoints/cookie_sync_test.go
endpoints/setuid_test.go
exchange/utils.go
exchange/utils_test.go
gdpr/gdpr.go
gdpr/impl.go
gdpr/impl_test.go
gdpr/permissions.go

This is the first of a several refactor PRs that will eventually lead to the incorporation of the basic enforcement algorithm that can be used instead of the full algorithm for specific purposes. No additional logic has been introduced here. This simply alters the `AuctionActivitiesAllowed` GDPR function signature to return a permissions struct instead of three bool values.

GDPR: Refactor AuctionActivitiesAllowed to return struct

---

endpoints/cookie_sync.go

This PR fixes a recently introduced bug in the cookie sync endpoint. A recent change to the endpoint made the account required which is not the desired behavior. This fix makes the account optional by following the approach in the auction flows. Now if the account is not specified on the cookie sync endpoint it will be set to "unknown", which will result in the `GetAccount` function returning an account object consisting only of host config account defaults.
I believe `endpoints/cookie_sync_test.go#TestCookieSyncParseRequest` and `account/account_test.go#TestGetAccount` provide adequate testing for the scenario where the account ID is not provided.
This was also tested manually E2E with the account parameter omitted and the account parameter set to an empty string.

Set account id to publisher unknown on cookie sync endpoint

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_benchmark_test.go
endpoints/openrtb2/test_utils.go
endpoints/openrtb2/video_auction.go
exchange/exchange.go
exchange/exchange_test.go
exchange/targeting_test.go
exchange/utils.go
exchange/utils_test.go
gdpr/gdpr.go
router/router.go

This refactor serves as a prerequisite for a future refactor. This just moves the TCF2 config and GDPR permissions object instantiations from `exchange.go` to the `CleanOpenRTBRequests` function in `exchange/utils.go`. The future refactor will involve putting request-specific GDPR data (e.g. consent, alias GVL IDs, etc) on the permissions object and these pieces of data are extracted in `CleanOpenRTBRequests` so we want to instantiate the permissions object after we have that information in hand.
~~Note that this is a draft PR that is built off of #2244 so I will rebase once that has been merged.~~
This PR now also does the following:
- it moves the two builders off of the `AuctionRequest` and onto the exchange
- it introduces a builder maker defined in `gdpr.go` which is then used in the …

GDPR: Defer permissions object instantiation refactor

---

pbs/usersync.go
router/router.go

This PR addresses this issue: #2245  
This change sets the http.ProxyFromEnvironment as Proxy function in all custom http.Transport used in the prebid-server as the http.DefaultTransport does.
https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/net/http/transport.go;l=43
With this change it is possible using prebid-server with an external proxy.

The http.ProxyFromEnvironment as Proxy func in custom http.Transport

---

endpoints/setuid.go
endpoints/setuid_test.go
router/router.go

This PR adds the optional account query parameter to the setuid endpoint. Each time we hit the endpoint, an attempt is made to fetch the account. If a valid account was not provided, the account fetcher will return a valid account object consisting of the host-specified account defaults.
Note that the fetched account is not used in this PR. It will be used in a follow up PR in the GDPR calculations.

Add account query parameter to setuid endpoint

---

endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
endpoints/openrtb2/test_utils.go
endpoints/setuid.go
endpoints/setuid_test.go
exchange/utils.go
exchange/utils_test.go
gdpr/gdpr.go
gdpr/gdpr_test.go
gdpr/impl.go
gdpr/impl_test.go
router/router.go

~~This PR is in draft. I'll rebase it and put it up for formal review once the open PRs it depends on are merged.~~
This PR moves request-specific GDPR data (signal, consent, alias GVL IDs and publisher ID) onto the permissions object. The auction flow is updated accordingly.
Also the cookie sync and setuid endpoints have been updated as follows:
- the GDPR object is instantiated on a per-request basis in each endpoint rather than being instantiated once for these endpoints at startup
- the fetched account is now used to generate an aggregated config (host GDPR TCF2 config + account GDPR config)
- the aggregated config is passed into the per-request GDPR permissions object

GDPR: move request-specific data onto permissions object

---

endpoints/openrtb2/auction.go
exchange/utils.go
exchange/utils_test.go
openrtb_ext/bidders.go
openrtb_ext/bidders_test.go
openrtb_ext/request.go

Added changes to read and mark `imp[].ext.tid` as special field and not a bidder code.
With https://github.com/prebid/Prebid.js/pull/8591 (https://github.com/prebid/Prebid.js/issues/8543) PBJS 7.3.0 sends `imp[].ext.tid` to PBS where PBS interprets `tid` as bidder code. Hence, blocking PBS adapter from using with PBJS 7.3.0.
Below is the error response from PBS.
```
Invalid request: request.imp[0].ext contains unknown bidder: tid. Did you forget an alias in request.ext.prebid.aliases?
```

Read imp[].ext.tid, fix PBJS 7.3.0 compatibility

---

openrtb_ext/device.go

I was sending an request to the auction endpoint to test interstitial functionality for a separate issue, and noticed there was a typo in the definition of the json field at `device.ext.prebid.interstitial.minwidtheperc.` When you send a request utilizing that naming, it would cause this error `Invalid request: request.device.ext.prebid.interstitial.minwidthperc must be a number between 0 and 100`. 
In short: `minwidtheperc` needs to just be `minwidthperc`, so this PR provides that typo fix.
I'm leaving this in draft mode, because the team spoke about adding json tests in relation to this typo, but I need to ask a few clarifying questions regarding this on Monday before I add them.

Fix interstitial.minwidtheperc typo

---

config/config.go
config/config_test.go
config/stored_requests.go
exchange/exchange.go
metrics/config/metrics.go
metrics/go_metrics.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/metrics_mock.go
metrics/prometheus/preload.go
metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go
stored_requests/events/postgres/database.go

Implementation for Stored bid responses metrics:
1) Number of requests that have stored bid responses or stored auction responses - new metric
2) Time to fetch stored response and fetching errors. These use new metrics and existing functionality to track it: `RecordStoredDataFetchTime` and `RecordStoredDataError `

Stored responses metrics

---

config/accounts.go
config/accounts_test.go
exchange/bidder_test.go

Rename `adapters` to `bidders` in alternate bidder codes config w.r.t https://github.com/prebid/prebid-server/issues/2174
Old pbs.yaml example:
```
account_defaults:
alternatebiddercodes:
enabled: true
adapters:
pubmatic:
allowedbiddercodes: [groupm]
appnexus:
allowedbiddercodes: [*]
```
New pbs.yaml example:
```
account_defaults:
alternatebiddercodes:
enabled: true
bidders:
pubmatic:
allowedbiddercodes: [groupm]
appnexus:
allowedbiddercodes: [*]
```

Rename adapters to bidders in alternate bidder codes config

---

endpoints/openrtb2/auction.go
openrtb_ext/app.go
openrtb_ext/request_wrapper.go
openrtb_ext/request_wrapper_test.go
privacy/ccpa/policy_test.go

This PR change the behavior of the RequestWrapper to only create new objects if there a non-empty extension object. I also fixed some misc marhsal issues that I discovered through the rebuild ext methods.

Request Wrapper: Only Create Elements If Needed

---

config/accounts.go
config/accounts_test.go
exchange/bidder_test.go

This change introduces bidder level toggle in alternatebiddercodes config https://github.com/prebid/prebid-server/issues/2174 (similar to that in PBJS).  
The bidder level toggle needs to be explicitly enabled with below config combinations (pfa).
Old pbs.yaml example:
```
account_defaults:
alternatebiddercodes:
enabled: true
bidders:
pubmatic:
allowedbiddercodes: [groupm]
appnexus:
allowedbiddercodes: [*]
```
New pbs.yaml example:
```
account_defaults:
alternatebiddercodes:
enabled: true
bidders:
pubmatic:
enabled: true
allowedbiddercodes: [groupm]
appnexus:
enabled: true
allowedbiddercodes: [*]
```

Add bidder level toggle for alternatebiddercodes config

---

static/bidder-info/ix.yaml

This PR is to add iframe usersync support for ix bid adapter.
This has been confirmed using the cookie_sync endpoint locally.

IX Adapter - Add iframe usersync support

---

endpoints/setuid.go
endpoints/setuid_test.go
metrics/metrics.go

This PR makes the setuid endpoint consistent with the cookie sync endpoint in how it reports account-related error metrics. Instead of always reporting "bad request" when there is an account error, we now indicate whether the account was blocked, or invalid before defaulting to "bad request".
Also a few changes were made to ensure any errors encountered by the setuid endpoint are appropriately logged when calling the analytic adapter `LogSetUIDObject` function.

Add account-specific error metrics to setuid endpoint

---

exchange/bidder.go
metrics/config/metrics.go
metrics/go_metrics.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/metrics_mock.go
metrics/prometheus/preload.go
metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go

New metrics are added to track AdsCert signing:
`RecordAdsCertReq` - record requests with AdsCert header, tracks number of successful and failed requests.
`RecordAdsCertSignTime` - time to sign AdsCert request
Local test with Prometheus passed, all metrics are correctly displayed in Prometheus data

AdsCert signer metrics

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatictest/supplemental/native_invalid_adm.json

In followup to the PR comments received on https://github.com/prebid/prebid-server/pull/2334, this PR changes will report native ads related errors back to PBS core.

pubmatic adapter: report MakeBids errors

---

metrics/prometheus/prometheus.go

When no _metrics.prometheus.namespace_ and no _metrics.prometheus.subsystem_ are set, it adds "__" as prefix. eg: "__go_goroutines" (Actual behaviour).
But to make it compatible with standard Go dashboards (in Grafana), we expect metrics to be exported without any prefix. eg: "go_goroutines".
This PR adds the namespace or the subsystem only if they are set.
Please, let me know if it's not the right approach.
Thanks

Fix the default prefix for Prometheus metrics

---

adapters/adnuntius/adnuntius.go
adapters/adnuntius/adnuntiustest/supplemental/check-noCookies-parameter.json
openrtb_ext/imp_adnuntius.go
static/bidder-params/adnuntius.json

This will allow prebid server partners to be able to tell the ad server not to set cookies as a parameter with the ad request.

Adnuntius Adapter: Set no cookies as a parameter

---

static/bidder-info/adkernel.yaml
static/bidder-info/improvedigital.yaml
static/bidder-info/invibes.yaml
static/bidder-info/kargo.yaml
static/bidder-info/mobilefuse.yaml
static/bidder-info/onetag.yaml
static/bidder-info/triplelift.yaml

Now that GZIP Compression support has been added/merged https://github.com/prebid/prebid-server/pull/2347, this PR merely updates the yaml files of the bidders who support GZIP compression (supported bidders taken from who supports it from PBS Java)

Update yaml files for gzip supported bidders

---

adapters/consumable/consumable.go
adapters/consumable/consumable/supplemental/simple-banner-coppa.json
adapters/consumable/consumable/supplemental/simple-banner-gdpr-2.json
adapters/consumable/consumable/supplemental/simple-banner-gdpr-3.json
adapters/consumable/consumable/supplemental/simple-banner-gdpr.json
adapters/consumable/consumable/supplemental/simple-banner-no-impressionUrl.json
adapters/consumable/consumable/supplemental/simple-banner-schain.json
adapters/consumable/consumable/supplemental/simple-banner-us-privacy.json
static/bidder-info/consumable.yaml

This PR adds support for schain and coppa in the Consumable Adapter, as well as updating the maintainer email for Consumable.

consumable adapter: add schain and coppa support

---

config/bidderinfo.go
config/bidderinfo_test.go
exchange/adapter_util.go
exchange/adapter_util_test.go
exchange/exchange_test.go

Bugfix: modified code to load bidder names from the file system in lowercase

Load bidders names from file system in lowercase

---

adapters/infoawarebidder.go
adapters/infoawarebidder_test.go

This PR addresses this issue: https://github.com/prebid/prebid-server/issues/2178
The goal of this PR is: In the situation when an adapter doesn't support the format indicated from the request imp, an error is thrown that we want downgraded to a warning since this error is unnecessary to be written to analytics
This error is thrown from the bidder wrapper `InfoAwareBidder`'s call too `MakeRequests()`. So for all the error checks that check  if an adapter doesn't support the imp format (i.e. `{&errortypes.BadInput{Message: "this bidder does not support site requests"}`), we downgrade those to a warning (i.e. `{&errortypes.Warning{Message: "this bidder does not support site requests"}`)
Tests were updated with this change.

Downgrade errors to warnings when adapter doesn't support imp format

---

exchange/exchange_test.go

The imp wrapper commit updated the bidder param logic so that all bidder params defined at `imp.ext.BIDDER` are now mapped to the official location `imp.ext.prebid.bidder.BIDDER` further upstream. The alternate bidder code exchange test needed to be updated to define the bidder params in the official location.

Fix alt bidder code test broken by imp wrapper commit

---

adapters/aja/aja.go
adapters/logicad/logicad.go
adapters/pubmatic/pubmatic.go
adapters/rubicon/rubicon.go
adapters/yieldone/yieldone.go

Some Adapters in use do not have their currency set, resulting in unnecessary currency conversions.
Adapters with no currency set have been changed so that the currency is set.

Set Currency to bidResponse

---

adapters/consumable/consumable.go
adapters/consumable/consumable/supplemental/simple-banner-content-meta.json

This PR adds support for content metadata in the bid request

consumable adapter: add content metadata support

---

endpoints/openrtb2/auction_test.go
openrtb_ext/request.go

I moved the logic in this method to validation code in the ImpWrapper PR, but left the unmarshal code because I wasn't sure of the bit about infinite loops. I understand now. This code does nothing and can be removed.

ExtRequestPrebidCache: Unnecessary UnmarshalJSON

---

openrtb_ext/request_wrapper.go

In pull request #2378 we decided to put request wrapper keys into constants. This is the second part of said endevour, coverts `"consent"`, `"amp"`, `"eids"`, `"gdpr"`, `"prebid"`, `"schain"` and `"us_privacy"`.

Declare request wrapper keys as constants

---

adapters/ix/ix.go
adapters/ix/ix_test.go

This update to the IX Adapter is to pass Prebid Server Version information and PBJS version information as part of a new "IXDiag" field. This field will be used to pass any diagnostic information as needed.
Changes include changese to ix.go and ix_test.go.

IX Adapter: Pass version information in Request.Ext field

---

adapters/improvedigital/improvedigital.go
adapters/improvedigital/improvedigitaltest/supplemental/dealid.json
adapters/improvedigital/improvedigitaltest/supplemental/rewarded-inventory.json

- Handle Rewarded inventory flag
- Add dealid

Improve Digital adapter: Add deal id and rewardred inventory logic

---

adapters/ix/ix.go
adapters/ix/ix_test.go

Recent changes at https://github.com/prebid/prebid-server/pull/2449 cause panic when ext.prebid.channel is nil.
Fixing this with nil check and added test case to cover.

IX Adapter: Fix panic when ext.prebid.channel is nil

---

config/config.go
config/config_test.go

This PR fixes an issue introduced in v0.234.0. In that release we added support for MySQL which resulted in deprecating the `postgres` config and adding a generic `database` config for stored requests, stored video requests and stored responses. In order to avoid a breaking change, PBS was made backwards compatible. If hosts are still using the `postgres` config, the values are mapped to `database` at start-up. The migration works correctly if the `postgres` config is specified in a config file but if it is specified via environment variables the migration does not run. This issue can be traced back to our attempt to detect presence of the `postgres` and `database` configurations by performing partial path lookups of `{stored_responses/requests/video_reqs}.postgres` and …

Perform full path host db config lookups in migration to detect presence

---

exchange/bidder.go
exchange/bidder_test.go

Fixed below scenario:
In alternatebiddercodes feature, if the request currency is non-USD, the extra-bids are being omitted from the response with below error 
```
"errors": {
"pubmatic": [
{
"code": 999,
"message": "Bid currency is not allowed. Was 'USD', wants: ['INR']"
}
]
},
```
This is because the response currency for the extra-bids is wrongly set to default USD.

fix extra-bid's multicurrency scenario

---

endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/video_auction.go
openrtb_ext/request_wrapper.go
openrtb_ext/request_wrapper_test.go

This PR is to update the logic SourceTID logic when enabled to fill source tid. This is related to https://github.com/prebid/prebid-server/issues/2381.
Logic is outlined in this issue: https://github.com/prebid/prebid-server/issues/2381#issuecomment-1284533924
Changes in this PR:
- Logic update in validateAndFillSourceTid to support the logic outlined above
- Changes to ImpWrapper to support accessing and setting tid in imp.ext
- Unit tests added to support the above changes

Per Impression TID Generation and Source TID Logic Updated

---

adapters/visx/params_test.go
static/bidder-params/visx.json

Updating UID to support both integer and string.
- Updated schema to support string and integer types
- Added regex to schema for UID format validation
- Added new test params

VISX: Add string support to UID

---

exchange/exchange_test.go

As pointed out by @laurb9 in the Bid Response Validation PR https://github.com/prebid/prebid-server/pull/2450, on line 2302 in `exchange/exchange_test.go`, the validation flag that is used for the JSON tests, wasn't being set. So we were getting a false pass in the tests, without actually asserting what's within the validation flag code block.
The reason it wasn't being set is because I changed how I wanted my validation flag to work, and implemented this change elsewhere in this test file, but forgot to change this line. To fix this, I updated the line so that the proper validation object is being utilized.
This validation object is set based on the info that's present in the `bid_response` json files specified at `host_bid_validations` within the json file.

Bid Response Validation Test Fix

---

adapters/ix/ix_test.go

Adds test for GPP passthrough support to make sure IX adapter passes the GPP string to the Exchange.

IX Adapter: add test for regs gpp support

---

endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
exchange/targeting_test.go
openrtb_ext/bid_response_video.go

Greetings, we recently found out that the /video endpoint of PBS doesn't add `hb_deal` targeting to the response. This is a small change to add `hb_deal` to targeting response as well if it exists in bid response from bidders. I also understand that the /video endpoint is going to be deprecated sometime soon. We would like to make this change though since we're planning to use the /video endpoint in the meantime for some testing purposes.
with `dealID` in bidder response:
without `dealID` in bidder response:

PBS core: add hb_deal targeting to video endpoint response 

---

.github/workflows/security.yml

- Trivy checks whether any dependency mentioned in the go.mod file needs any security patch upgrade.
- Github action runs Trivy scans on pull request changes or the newly merged commit in the master branch.
- Pull requests may not make changes to the go.mod file. So we can skip Trivy scans for such cases. For this, commit adds the [paths filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) check for pull request event.

skip Trivy scan for PRs with no go.mod changes

---

config/bidderinfo.go
config/config.go
endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
macros/macros.go
privacy/gpp/gpp.go
privacy/policies.go
usersync/syncer.go
usersync/syncer_test.go

Allows GPP strings to pass through cookie sync endpoints.

GPP passthrough for cookiesync

---

openrtb_ext/convert_down.go
openrtb_ext/convert_down_test.go

Tried to avoid needing to clear out OpenRTB 2.6-x when downgrading to 2.5, but we are now aware of some bidders which fail on the new fields.

OpenRTB 2.6: Remove 2.6-x Fields

---

adapters/unruly/params_test.go
adapters/unruly/unrulytest/exemplary/banner-and-video-app.json
adapters/unruly/unrulytest/exemplary/banner-and-video-gdpr.json
adapters/unruly/unrulytest/exemplary/banner-and-video-site.json
adapters/unruly/unrulytest/exemplary/banner-and-video.json
adapters/unruly/unrulytest/exemplary/simple-banner.json
adapters/unruly/unrulytest/exemplary/simple-video.json
adapters/unruly/unrulytest/supplemental/no-matching-impid.json
adapters/unruly/unrulytest/supplemental/status-code-204.json
adapters/unruly/unrulytest/supplemental/status-code-400.json
adapters/unruly/unrulytest/supplemental/status-code-401.json
openrtb_ext/imp_unruly.go
static/bidder-params/unruly.json

Currently, unruly.json supported only "siteid" but our ssp now supports "siteId" with a capital I.
We need to add this property to the unruly.json.

Unruly: Add support for "siteId" bidder parameter (different casing)

---

adapters/openx/openx.go
adapters/openx/openxtest/exemplary/imp-ext-passthrough.json

OpenX adapter: pass all of incoming `imp.ext` through to endpoint, except for `prebid` and `bidder` fields.
This should not impact existing functionality (`customParams` are still merged into `imp.ext`) but allows reading `gpid` and a host of other `data` of interest server-side while keeping the adapter code simple.
Resolves #2604 
PBS-Java implementation is at https://github.com/prebid/prebid-server-java/pull/2180

Openx: Pass through imp.ext wholesale except prebid, bidder

---

.github/workflows/release.yml

Github has deprecated set-output and save-state commands and announced to end their support after 31st May 2023. Refer https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/for more details.
PR updates script to replace set-output with recommended command.

Handle set-output command deprecation

---

endpoints/openrtb2/sample-requests/amp/valid-supplementary/imp-with-stored-resp.json
exchange/exchange.go
exchange/exchange_test.go

Fix for https://github.com/prebid/prebid-server/issues/2614

Fix for storedauctionresponse bid type

---

adapters/pwbid/params_test.go
adapters/pwbid/pwbid.go
adapters/pwbid/pwbid_test.go
adapters/pwbid/pwbidtest/exemplary/banner.json
adapters/pwbid/pwbidtest/exemplary/native.json
adapters/pwbid/pwbidtest/exemplary/optional-params.json
adapters/pwbid/pwbidtest/exemplary/video.json
adapters/pwbid/pwbidtest/supplemental/response-200-without-body.json
adapters/pwbid/pwbidtest/supplemental/response-204.json
adapters/pwbid/pwbidtest/supplemental/response-400.json
adapters/pwbid/pwbidtest/supplemental/response-500.json
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_pwbid.go
static/bidder-info/pwbid.yaml
static/bidder-params/pwbid.json

Docs PR: https://github.com/prebid/prebid.github.io/pull/4428

New Adapter: pwbid

---

adapters/taboola/params_test.go
adapters/taboola/taboola.go
adapters/taboola/taboola_test.go
adapters/taboola/taboolatest/exemplary/banner.json
adapters/taboola/taboolatest/exemplary/bannerResolveMacro.json
adapters/taboola/taboolatest/exemplary/multiFormatImpressionsRequest.json
adapters/taboola/taboolatest/exemplary/native.json
adapters/taboola/taboolatest/exemplary/nativeResolveMacro.json
adapters/taboola/taboolatest/exemplary/withPageType.json
adapters/taboola/taboolatest/exemplary/withPosition.json
adapters/taboola/taboolatest/supplemental/bidParamsOverrideRequestFields.json
adapters/taboola/taboolatest/supplemental/bidderServerError.json
adapters/taboola/taboolatest/supplemental/emptyReponseFromBidder.json
adapters/taboola/taboolatest/supplemental/emptySiteInRequest.json
adapters/taboola/taboolatest/supplemental/incorrectResponseImpMapping.json
adapters/taboola/taboolatest/supplemental/multiImpressionsRequest.json
adapters/taboola/taboolatest/supplemental/optionalParamsProvided.json
adapters/taboola/taboolatest/supplemental/unexpectedStatusCode.json
macros/macros.go
openrtb_ext/imp_taboola.go
static/bidder-info/taboola.yaml
static/bidder-params/taboola.json

Two changes that the first one is a bug fix: 
- Make the bidder param "tagId" case insensitive, already live publishers pass it as "tagid" and we expect it in the guide and prebid.js adapter to be "tagId" - we would to support both if any passed to not hurt live publisher and align the documentation and the bidder param with Prebid.js adapter 
- Passing gvlID instead of the host "top domain"  
- resolve AUCTION_PRICD macro

Taboola Bid Adapter: Support insensitive tagId, gvlID as host name

---

endpoints/openrtb2/auction_test.go
stored_responses/stored_responses.go
stored_responses/stored_responses_test.go

Fix for https://github.com/prebid/prebid-server/issues/2487

Reject request if stored auction or stored bid response not found

---

metrics/config/metrics_test.go
metrics/go_metrics.go
metrics/metrics.go
metrics/prometheus/prometheus.go

Removing metrics for the legacy endpoint which we missed.

Remove Legacy Endpoint Metrics

---

adapters/axis/axis.go

PR checks are failing after I merged [2655](https://github.com/prebid/prebid-server/pull/2655) . The reason is that PR is using v17 of openrtb instead of the latest one. This PR fixes that.

fix workflow error

---

adapters/bidstack/bidstack.go
adapters/conversant/conversant.go
adapters/sharethrough/sharethrough.go
adapters/vidoomy/vidoomy.go

Interface values in Go are represented as a pair of pointers, one pointing to information about the type stored in the interface and another pointing to the associated data. The pointer is then used to access the methods on that interface. So if you have implementations of the interface where the methods have a value receiver, Go autogenerates functions that has a pointer receiver. This function then creates a derefrence and then calls the original method with the value receiver. In order to avoid creating unnecessary value copy in such cases, it's best to use pointer receiver for methods that are always or almost always called by an interface value. See more info [here](https://utcc.utoronto.ca/~cks/space/blog/programming/GoInterfacesAutogenFuncs).

Update all bidder interface implementations to have pointer receivers

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/valid-whole/supplementary/empty-gppsid-conflict.json

Inside the `validateRegs(req *openrtb_ext.RequestWrapper, gpp gpplib.GppContainer)` function found in `endpoints/openrtb2/auction.go` we can `break` after we find the first occurrence of `constants.SectionTCFEU2` is found. This is a small optimization to not traverse the entire `GPPSID` array.
Additionally, test case `"empty-gppsid-conflict.json"` was added to test the scenario when the incoming request has a non-nil, empty `GPPSID` array.

Optimize GPPSID array traversal

---

adapters/richaudience/richaudience.go
adapters/richaudience/richaudiencetest/exemplary/single-banner-app.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-defaultCurrency.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-deviceConfig.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-extUser.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-floorPrice.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-iPv6.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-nil-device.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-nosecure.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-setCurrency.json
adapters/richaudience/richaudiencetest/exemplary/single-banner-sitePage.json
adapters/richaudience/richaudiencetest/exemplary/single-banner.json
adapters/richaudience/richaudiencetest/exemplary/single-video.json

Adapters receive a shallow copy of a request In MakeBids. It means this request has shared pointer values: site, app and other pointer structures are shared between all adapters in request. In order to modify pointer structures you need to create own copy of it and set it back to request. 
The reason why previous unit tests didn't show it is because `imp.tagid` was empty and result `app/site.keywords` didn't change. 
Please review. @richaudience

Richaudience: Shared memory fix

---

exchange/bidder.go
exchange/bidder_test.go
metrics/config/metrics.go
metrics/go_metrics.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/metrics_mock.go
metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go

Add new metric to record amount of time PBS has to wait to receive a response back from the bidder server. Data points recorded will help to set bidder_response_duration_min for PSP.

Add overhead metric for bidder_response_duration_min

---

analytics/core.go
analytics/filesystem/file_module.go
analytics/filesystem/file_module_test.go
analytics/filesystem/model.go
analytics/pubstack/helpers/json.go
analytics/pubstack/helpers/model.go

Each analytics adapter should use it's own model for serialization, such that the core data model objects are free to evolve as needed.
FYI: @gpolaert

Separate Analytics Data Model

---

privacy/lmt/ios.go
privacy/lmt/ios_test.go

Addressing update in requirements for #1699

Set lmt to 1 if device.ext.atts is 0 for ios versions 14.2 or greater

---

endpoints/cookie_sync.go
exchange/gdpr.go
gdpr/signal.go
gdpr/signal_test.go
privacy/ccpa/policy.go
privacy/ccpa/policy_test.go
privacy/gpp/gpp.go
privacy/gpp/gpp_test.go
util/stringutil/stringutil.go
util/stringutil/stringutil_test.go

In preparation to complete GPP phase 2 (more info in [this document](https://docs.google.com/document/d/1dRxFUFmhh2jGanzGZvfkK_6jtHPpHXWD7Qsi6KEugeE/edit#) and issue #2380)), it is useful to refactor a couple of functions in order to not have repetitive code when GPP parsing is done in the `/cookie_sync` and `/setuid` endpoints.

Refactor GPP functions

---

floors/enforce_test.go

**Current behaviour:** Floors test case fail at random since floor enforcement is based on `rand.Intn`. 
```
--- FAIL: TestEnforce (0.00s)
enforce_test.go:665: 
Error Trace:	/home/runner/work/prebid-server/prebid-server/floors/enforce_test.go:665
Error:      	rejected bids don't match
Test:       	TestEnforce
```
**Expected behaviour:** Unit tests should be consistent for all runs 
**Solution:** Removed the unit test dependency on `rand.Intn` using `EnforceFloorsRate=0`

Fix: floors flakey test

---

adapters/xeworks/xeworks.go

httputil/responseutil was moved to adapters/util. This commit updates the code to use adapters/util instead of httputil/responseutil functions for response checks.

Fix xeworks workflow

---

adapters/imds/imds.go
adapters/imds/imds_test.go
adapters/imds/imdstest/exemplary/simple-banner.json
adapters/imds/imdstest/exemplary/simple-video.json
adapters/imds/imdstest/supplemental/audio_response.json
adapters/imds/imdstest/supplemental/bad_response.json
adapters/imds/imdstest/supplemental/native_response.json
adapters/imds/imdstest/supplemental/one_bad_ext.json
adapters/imds/imdstest/supplemental/status_204.json
adapters/imds/imdstest/supplemental/status_400.json
adapters/imds/imdstest/supplemental/status_500.json
static/bidder-info/imds.yaml
static/bidder-info/synacormedia.yaml

imds: Changes the imds/synacormedia adapter hostname to be static (see: https://github.com/prebid/prebid-server/issues/2612) for connection efficiency. Also adds adapter names and version metrics in the request so we can evaluate when to remove the deprecated `synacormedia` adapter based upon usage. Endpoint also utilized https now so HTTP/2 may be negotiated.

imds: Change imds/synacormedia adapter hostname to be static

---

endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/hooks/auction_reject_with_error.json
endpoints/openrtb2/test_utils.go
hooks/hookexecution/execution.go

**Issue:** `handleHookResponse` function does not reject a request when a module sets both the `error` and `hook.Result.Reject` to true.
**Expected behaviour**: Request should be rejected regardless of whether an error is returned or not, as long as `hook.Result.Reject` is set to true.
Discussion thread at https://prebid.slack.com/archives/C01ALRKJFQ8/p1684302151644009

Modularity: Reject request when hook reject and error both are set

---

exchange/utils_test.go
privacy/enforcement.go
privacy/enforcement_test.go
privacy/scrubber.go
privacy/scrubber_test.go

Updates user privacy scrubbing such that the stricter approach of removing year of birth and gender apply to all privacy policies, no longer just for COPPA. Implemented per https://github.com/prebid/prebid-server/issues/2686 (follow the link for the full spec).

Standardize Privacy User Scrubbing

---

static/bidder-info/smartadserver.yaml

SmartAdServer is now owned by Equativ.

Update smartadserver contact info

---

static/bidder-info/pubmatic.yaml

enabling `gpp-support` flag in bidderinfo.yaml under `openrtb`

Enable GPP support for PubMatic adapter

---

exchange/exchange_test.go
openrtb_ext/deal_tier.go
openrtb_ext/deal_tier_test.go

Fix: deal tiers no longer ignored due to presence of tid

---

static/bidder-info/ix.yaml

Update  cookie-sync URLs to pass &gpp and &gpp_sid parameters

 IX Bid Adapter - gpp support for user sync urls

---

README.md

- Fixing links to valid prebid urls

fix: update links in readme

---

adapters/improvedigital/improvedigital.go
adapters/improvedigital/improvedigitaltest/supplemental/foreign-currency.json

This is to fix the bug where bid price currency is not passed to PBS and PBS assumed all bids were in USD

Improve Digital adapter: Set currency in bid response

---

adapters/sharethrough/sharethrough.go
adapters/sharethrough/sharethroughtest/supplemental/multiformat-impression.json

For an ad unit that supports multiple formats (e.g. banner, video and native), our adapter would send a single request towards Sharethrough that included all the formats. Sharethrough's adserver couldn't handle it
We split the single request into multiple requests by media type (format). For each format, the adapter sends 1 request and receives 1 response.
From the point of view of Prebid, we have 2 responses corresponding to the same ad unit and it picks a winner as usual.
EDIT: Now there's a 3rd format, but you get the idea

Sharethrough: Support multiformat bid request impression

---

exchange/exchange_test.go
exchange/utils_test.go

Unit test set up function `getTestBuildRequest` had invalid imp.ext: `{"ext_field":"value}"}` and no bid requests were returned from `cleanOpenRTBRequests` func in `TestCleanOpenRTBRequestsWithFPD`. 
`imp.ext` should have a valid bidder in order to return requests.

Exchange unit test fix

---

.github/workflows/helpers/pull-request-utils.js
.github/workflows/semgrep.yml
.semgrep/adapter/builder-struct-name.yml

- PR #2833 introduced two Semgrep rules for adapters i.e  [builder-struct-name.yml](https://github.com/prebid/prebid-server/blob/f1787d4a1da2dc632de7e4afaec9ff71734e146f/.semgrep/adapter/builder-struct-name.yml) and  [type-bid-assignment.yml](https://github.com/prebid/prebid-server/blob/f1787d4a1da2dc632de7e4afaec9ff71734e146f/.semgrep/adapter/type-bid-assignment.yml)
- This PR adds a GitHub action script and some helper to run above Semgrep rules as PR checks. These checks are conditioned to run only  if new PR makes some adapter related changes
- Findings from above semgrep rules will be reported as PR code review comment.  To avoid duplication, previous comments will not be added again
- Script only considers findings that are relevant to the changes made in the PR. For example, if the …

script to run semgrep tests against adapter PRs

---

.semgrep/adapter/package-import.go
.semgrep/adapter/package-import.yml

PR adds semgrep rule to flag undesirable package imports in adapter code. Plan here is to run this rule as adapter PR checks. Refer #2907 for more details.
Semgrep uses import metavariable to match package imports - https://semgrep.dev/docs/writing-rules/pattern-syntax/#import-metavariables
- Sample playground example: https://semgrep.dev/playground/s/QBlo
- Semgrep unit tests passing
```
~ » semgrep --test ./                              
3/3: ✓ All tests passed
No tests for fixes found.
```
- Found following instances in repo
```
~ » semgrep --config=./.semgrep/adapter/package-import.yml ./adapters/
┌─────────────┐
│ Scan Status │
└─────────────┘
Scanning 2539 files tracked by git with 1 Code rule:
Scanning 194 files.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 …
```

semgrep rule to flag undesirable package imports in adapter code

---

adapters/bidder.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/video_auction.go
exchange/bidder.go
exchange/bidder_test.go
exchange/bidder_validate_bids.go
exchange/bidder_validate_bids_test.go
exchange/exchange.go
exchange/exchange_test.go

PR refactors refactor requestBid and getAllBids methods. This refactor makes its easier to pass new input to downstream functions and return new params without affecting signature of requestBid and getAllBids methods

refactor `requestBid` and `getAllBids` signature

---

.github/workflows/semgrep.yml

`pull_request_target` event is similar to pull_request, except that it runs in the context of the base repository of the pull request, rather than in the merge commit.  For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload.

use `pull_request_target` event in semgrep

---

.github/workflows/semgrep.yml

This is needed when PR is raised from fork branch. In this case repository will be fork repo and correct version of code will be checkout
Testing: 
- https://github.com/onkarvhanumante/prebid-server/pull/6
PR raised on `onkarvhanumante/prebid-server` from `onkarhanumante30/prebid-server` repo. This mimics scenario where adapter forks raise PR against main prebid-server repo
```
fetch-depth: 0
ref: patch-2
repository: onkarhanumante30/prebid-server
```

semgrep script:  specify repository during checkout step

---

adapters/mobilefuse/mobilefuse.go
adapters/mobilefuse/mobilefusetest/exemplary/skadn.json

This is a change to forward imp.ext.skadn whereas previously anything under imp.ext was not forwarded.

Mobilefuse: Added support for skadn. Forwarding imp.ext.skadn

---

gdpr/consent_parser.go
gdpr/consent_parser_test.go
gdpr/full_enforcement.go
gdpr/full_enforcement_test.go
gdpr/impl.go
gdpr/impl_test.go

This PR addresses https://github.com/prebid/prebid-server/issues/2809.
If a bidder does not have a GVL ID, the only scenarios where they pass a purpose are:
- if a bidder code is a vendor exception
- if a bidder code is entered as a soft vendor exception (which means they are listed as a basic enforcement vendor in the account config), and the user has consented at the purpose level
- if enforcing the purpose and enforcing the vendor for that purpose are disabled in the config
While investigating this issue, I realized that the logic in `impl.go` could be simplified. There was no need to create a `vendorTrue` instance anymore, nor do we need to check if the bidder is a `basicEnforcementVendor`. As a result, I refactored `impl.go` a bit, extracting anything that involves parsing the …

GDPR: support bidders without a GVL ID

---

config/bidderinfo.go
config/bidderinfo_test.go
exchange/adapter_util.go
exchange/adapter_util_test.go

We already have [a piece of code that reads all bidder-info/*.yaml files. ](https://github.com/prebid/prebid-server/blob/543f288dc854361724d4a658dce31b81bb864d33/config/bidderinfo.go#L233-L247). This code already un-marshals bidder yaml config into BidderInfo struct. Presently, this function returns map[String]BidderInfos. But we would need a way to also identify aliases so that we can run the validations checks etc.
- This PR introduces `aliasOf` of type string in BidderInfo struct. 
- Also adds a simple validation check that if adapter is an alias then make sure that it's parent is an actual adapter and not an alias else raise a validation error.
- Also throw a validation check if `aliasOf` is defined in BidderInfo struct saying that do not use this as this feature is currently under …

introduce aliasOf in bidderInfo struct

---

adapters/bidder_test.go
bidadjustment/apply_test.go
endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/test_utils.go
server/server.go

- As of now, the `validate.sh` script has been executed as part of the PR checks. However, there was an issue with how the `go vet` command was invoked in the script.
https://github.com/prebid/prebid-server/blob/95c269f3740c4c0e1bf82b481ca78f52e634cb17/validate.sh#L59-L63
- Currently, the `go vet` command is not checking all the files. This resulted to errors/ warnings not being captured during the PR checks. 
- The solution is to modify the command to `go vet ./...` which will ensure that all files are thoroughly checked during the PR checks.
```
% (go vet ./... 2>&1) | grep -v -E "composite literal uses unkeyed fields"
adapters/huaweiads/huaweiads.go:905:14: result of fmt.Errorf call not used
adapters/rubicon/rubicon_test.go:293:9: GetRate passes lock by value: github.com/prebid/prebid- …
```

fix errors reported by go vet 

---

adapters/mobilefuse/mobilefuse.go
adapters/mobilefuse/mobilefusetest/exemplary/multi-imps-multi-format.json

Previously our adapter was passing only the first imp to us (whichever imp type it was).
Updated the pre-existing _multi-imps.json_ test file to expect the test's multiple imps.
Added the test file _multi-imps-multi-format.json_ to test that all imps and imp types are being passed through.
Adapter code updated to support multiple imps and multiple imp types.

mobilefuse adapter: Added support for multiple imps and multiple imp types

---

config/bidderinfo.go
config/config.go
endpoints/setuid.go
endpoints/setuid_test.go
usersync/syncer.go
usersync/syncer_test.go
usersync/syncersbuilder.go
usersync/syncersbuilder_test.go

Redirect urls for bidders user sync now have `bidder={bidderName}` not `bidder={syncerKey}`. 
`user_sync` endpoint now returns urls with redirect urls with bidder name instead of syncer key. 
`setuid` endpoint now accepts bidder name, not syncer key: `setuid?bidder=appnexus` not `setuid?bidder=adnxs`
`getuids` endpoint returns ids by syncer key.

Use bidder name instead of syncer key

---

Makefile
README.md
scripts/format.sh
validate.sh

Resolves https://github.com/prebid/prebid-server/issues/2925

Added format script to simplify avoiding .semgrep directory

---

exchange/exchangetest/request-ext-prebid-filtering.json
exchange/utils.go
exchange/utils_test.go
openrtb_ext/bid.go
openrtb_ext/request.go

For our Prebid SDK friends, per https://github.com/prebid/prebid-server/issues/2908.

Prebid SDK Rendering API Extensions

---

validate.sh

- As of now, the `validate.sh` script has been executed as part of the PR checks. However, there was an issue with how the `go vet` command was invoked in the script.
- Currently, the `go vet` command is not checking all the files. The solution is to modify the command to `go vet ./...` which ensure that all files are thoroughly checked during the PR checks.
Testings:
- go vet reports error: https://github.com/prebid/prebid-server/actions/runs/5690443652/job/15423793885?pr=2984
- no errors: https://github.com/prebid/prebid-server/actions/runs/5690525560/job/15424024371?pr=2984

update validate.sh: run go vet command correctly

---

.semgrep/README.md
.semgrep/adapter/bid-type-if-check.go
.semgrep/adapter/bid-type-if-check.yml
.semgrep/adapter/bid-type-switch-check.go
.semgrep/adapter/bid-type-switch-check.yml
.semgrep/adapter/parse-bid-type-check.go
.semgrep/adapter/parse-bid-type-check.yml

Currently, adapters identify bidType based on request imps or bid extensions in the response. Now that we have bid.MType available as part of openrtb 2.6, which can be used to set bid type in adapter response on the adapter server side, we recommend using MType. This PR adds semgrep rule to add warning to use MType.

Semgrep rule to add warning to use MType

---

exchange/exchange.go
exchange/exchange_test.go

PR includes following refactor in HoldAuction and its related code:
- [buildBidResponse: remove unused err var](https://github.com/prebid/prebid-server/commit/e12764ff7b530354211e91ee62ee80201bed3599)
- [HoldAuction: set seatNonBid only if has no error](https://github.com/prebid/prebid-server/commit/647ccfda38d8c3c2e508dd26b2e011ba5c1af474)

minor refactor in HoldAuction 

---

adapters/adocean/adocean.go
adapters/adocean/adocean_test.go
adapters/adocean/adoceantest/exemplary/multi-banner-impression.json
adapters/adocean/adoceantest/exemplary/single-banner-impression.json
adapters/adocean/adoceantest/supplemental/app.json
adapters/adocean/adoceantest/supplemental/bad-response.json
adapters/adocean/adoceantest/supplemental/emiter-param-error.json
adapters/adocean/adoceantest/supplemental/encode-error.json
adapters/adocean/adoceantest/supplemental/network-error.json
adapters/adocean/adoceantest/supplemental/no-bid.json
adapters/adocean/adoceantest/supplemental/no-sizes.json
adapters/adocean/adoceantest/supplemental/requests-merge.json
adapters/adocean/params_test.go
openrtb_ext/imp_adocean.go
static/bidder-info/adocean.yaml
static/bidder-params/adocean.json

As requested at https://github.com/prebid/prebid-server/issues/2612 this pull request changes usage of fully dynamic hostnames in AdOcean adapter to partially dynamic. At the moment it's not possible for us to use one domain for all requests so instead we will use one domain with dynamic subdomains.

AdOcean: Use partially dynamic hostnames instead of fully dynamic.

---

endpoints/openrtb2/auction_test.go
endpoints/openrtb2/test_utils.go
exchange/adapter_util.go
exchange/adapter_util_test.go
router/router.go

We ask that bidders removed form Prebid Server remain known to the server for the purposes of nice warning messages. The current implementation doesn't scale as it requires too many test updated when a change is made. Refactoring to make the tests sane again.

Refactor Disabled Bidders List

---

adapters/adhese/adhese.go
adapters/gamoshi/gamoshi.go
adapters/pubmatic/pubmatic.go
adapters/yeahmobi/yeahmobi.go

- Adding log lines in adapters incurs additional risk of flooding PBS host logs. Therefore their usage is discouraged in adapter code
- PR makes changes to remove `github.com/golang/glog` log lines from adapter code
```
% semgrep --config=.semgrep/adapter/package-import.yml ./adapters
adapters/adhese/adhese.go
semgrep.adapter.package-import-check
Usage of "github.com/golang/glog" package is prohibited in adapter code
13┆ "github.com/golang/glog"
adapters/gamoshi/gamoshi.go
semgrep.adapter.package-import-check
Usage of "github.com/golang/glog" package is prohibited in adapter code
9┆ "github.com/golang/glog"
adapters/pubmatic/pubmatic.go
semgrep.adapter.package-import-check
Usage of "github.com/golang/glog" package is prohibited in adapter code
13┆ "github.com/golang/glog" …
```

Remove log lines from adapter

---

endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
endpoints/setuid.go
exchange/utils.go
privacy/enforcer.go
privacy/enforcer_test.go

Because of we return bool instead of activity result we need to check result is not a Deny.

Fix for blocked user sync if activities config is not specified.

---

config/bidderinfo.go
config/bidderinfo_test.go

This PR makes the following changes - 
- It introduces a new struct `bidderInfoNullableFields` to maintain any nullable fields from BidderInfo struct. For example - the default value of `Disabled` in BidderInfo struct is always false and not `nil`.
- It may be the case where `Disabled` value of parent adapter is `true` but no value is set for an aliased adapter(default is false). In this case, we cannot just outright replace `Disabled` value of alias adapter with parent. Consider the case where aliased adapter `Disabled` value is actually set.
- To handle cases like above, we have introduced `bidderInfoNullableFields` struct.
- The approach is to maintain a map of bidderName to `bidderInfoNullableFields`. 
- Loop information from that map to determine if `Disabled` is actually set in …

inherit fields for an alias from parent adapter

---

endpoints/openrtb2/auction.go
stored_requests/backends/db_provider/mysql_dbprovider.go

Go 1.16 has deprecated `ioutil.ReadAll` and `ioutil.ReadFile` functions and recommended to use implementation from `io` and `os` package
Refer:
- https://pkg.go.dev/io/ioutil#ReadAll
- https://pkg.go.dev/io/ioutil#ReadFile

replace deprecated ioutil function calls

---

.github/workflows/adapter-code-coverage.yml
.github/workflows/helpers/pull-request-utils.js

PR introduces github action script that,
- Runs `go tool cover` command 
- Uploads coverage summary on pull request. Summary includes,
- function wise stats
- link to access heat map coverage report

github action to post adapter code coverage summary

---

static/bidder-info/smaato.yaml

Updates bidder-info for Smaato adapter to add Gdpr macros in userSync url

Smaato: Update userSync url

---

static/bidder-info/amx.yaml

Updates bidder-info for AMX adapter / amx.go to:
- indicate support for GZIP requests
- add GPP macros  in sync & indicate support for GPP
- add iframe sync, which will be the default sync. We've also deployed fixes to the redirect sync on our side that should resolve #2832 (iframe sync as default of course also helps reduce risk of future issues)

AMX RTB: indicate support for GZIP, GPP, and add iframe sync

---

.semgrep/adapter/parse-bid-type-check.yml

`$ORTBTYPE` is not declared in `parse-bid-type-check.yml`. So message seems bit misleading

Fix semgrep error message

---

endpoints/cookie_sync.go
endpoints/setuid.go
exchange/utils.go
privacy/activitycontrol.go
privacy/activitycontrol_test.go
privacy/component.go
privacy/component_test.go
privacy/rules.go
privacy/rules_test.go

Breaking out thee Privacy Activity Control feature into separate files, as a follow-up PR will begin adding complexity for passing requests to the rules.

Activity Control: Refactor To Separate Files

---

adapters/flipp/flipp.go
adapters/flipp/flipptest/exemplary/simple-banner-native.json
openrtb_ext/imp_flipp.go

Based on the discussion here https://github.com/prebid/prebid.github.io/pull/4551#discussion_r1222098377, we are removing ip as a bidder request parameter. IP will be retrieved from `request.Device.IP`.

Flipp: remove IP as a bidder request parameter

---

exchange/adapter_util.go
exchange/adapter_util_test.go

This PR updates the builder map to associate alias name with the parent builder in the buildBidders function

map alias bidder name to its parent builder

---

config/config.go
config/config_test.go

Changes planned for tmax are implemented. So tmax feature development flag check is no longer needed.

Remove tmax feature development flag check

---

config/bidderinfo.go
config/bidderinfo_test.go
openrtb_ext/bidders.go
openrtb_ext/bidders_test.go
openrtb_ext/bidders_validate_test.go

Currently, we have adapter aliases that defines Bidder params explicitly using json file. However, after the adapter aliases feature, we will have the bidder params inherited from its parent adapter.
To accomplish this, we had to do some refactoring and remove the unnecessary code. We also refactored NewBidderParamsValidator function so that we can write the test cases.

inherit bidder params from parent for an alias

---

exchange/exchangetest/request-ext-prebid-filtering.json
openrtb_ext/bid.go
openrtb_ext/request.go

This PR adds a new field `data` to renderers object as discussed in the related [thread](https://github.com/prebid/prebid-server/issues/2908)
I switched to a more complex data type `raw object` instead of `string` to allow passing more datas into it.
Then all data related to the renderer SDK could be passed through this field.
Here is an example of how it could go:
```json
{
"name": "myRenderer",
"version": "2.4",
"data": {
"uiRendereringVersion": "1.2",
"resizable": true
}
}

Add data field for custom renderers

---

static/bidder-info/taboola.yaml

changes in the server endpoint, using query params for publisher id and exchange params instead of path params

Taboola Bidder Adapter:  Change Endpoint 

---

adapters/huaweiads/huaweiads.go
adapters/huaweiads/huaweiadstest/exemplary/nativeIncludeVideo.json
adapters/huaweiads/huaweiadstest/exemplary/nativeSingleImage.json
adapters/huaweiads/huaweiadstest/exemplary/nativeThreeImage.json
adapters/huaweiads/huaweiadstest/exemplary/nativeThreeImageIncludeIcon.json
adapters/huaweiads/huaweiadstest/supplemental/bad_response_not_native.json

fix cta text empty and low fill rate issue

Huawei Ads: fix cta text empty and fill rate issue

---

adapters/response.go
adapters/response_test.go

As of now,  `CheckResponseStatusCodeForErrors` simply returns error when non 200 status is returned from bidder server
https://github.com/prebid/prebid-server/blob/01bd679d1fca8f30a831258c0690747081e7191f/adapters/response.go#L17-L21
However, `errortypes.BadServerResponse` should be used for bad server response.  PR implements fixes `CheckResponseStatusCodeForErrors` to return `errortypes.BadServerResponse`
https://github.com/prebid/prebid-server/blob/8ffa1c66082f1d289aa17206e9b54668afb14741/adapters/bidder.go#L39-L41

Fix CheckResponseStatusCodeForErrors adapter response util

---

openrtb_ext/bid.go

Implements https://github.com/prebid/prebid-server/issues/3085. There is no test coverage for just changes to the metadata object structure.

Prebid Meta Data: Add RendererUrl

---

endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/video_auction.go
endpoints/openrtb2/video_auction_test.go
endpoints/setuid.go
exchange/exchange_test.go
exchange/utils_test.go
privacy/activitycontrol.go
privacy/activitycontrol_test.go
privacy/component.go
privacy/component_test.go
privacy/rule.go
privacy/rule_condition.go
privacy/rule_condition_test.go

The componentName matching was built for an earlier draft where the format was "scope.name". This PR updates to just "name". This also means parsing an Activity Config can no longer return an error. The code is simplified as a result.

Activities: Back To Spec

---

.github/workflows/release.yml

Github actions `release.yml` is tagging before verifying whether or not the code compiles sucessfully. This led to tags `0.268.0`  and `0.269.0` to both point to the same commit when the former's release failed. This pull request makes `release.yml` pull from current `master` branch and perform a build before moving on to create a new tag.

release.yml run build before creating new tag

---

endpoints/setuid.go

I noticed in the `/setuid` endpoint, that the error handling seemed repetitive and could be consolidated. So I wrote a function to simplify the `NewSetUidEndpoint()` functions error handling.

SetUID Error Handling Refactor

---

errortypes/code.go
errortypes/errortypes.go
exchange/bidder.go
exchange/bidder_test.go
exchange/exchange.go
metrics/metrics.go

We have a [bidderRequest loop](https://github.com/prebid/prebid-server/blob/2e056bfbc071292361b6c399ed8176ff369babc3/exchange/exchange.go#L675), which goes through each bidder request. Inside this loop, PBS sends a request to the bidder server and handles the bidder's response or any errors that may occur.
Within this loop, we gather all errors related to bidders using [errorsToMetric()](https://github.com/prebid/prebid-server/blob/2e056bfbc071292361b6c399ed8176ff369babc3/exchange/exchange.go#L719) and then record these errors into `AdapterErrors` metric using [RecordAdapterRequest()](https://github.com/prebid/prebid-server/blob/2e056bfbc071292361b6c399ed8176ff369babc3/exchange/exchange.go#L687-L689)
PR makes changes to handle tmax timeout error. This means that if a tmax timeout error …

record tmax timeout error in adapter error metric

---

metrics/prometheus/preload.go
metrics/prometheus/type_conversion.go

Use generics to eliminate boilerplate code in Prometheus preload type conversions.

Cleanup Prometheus Type Conversions

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext-case-insensitive.json
endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext.json
endpoints/openrtb2/sample-requests/valid-whole/exemplary/simple-case-insensitive.json
endpoints/openrtb2/sample-requests/valid-whole/exemplary/simple.json
exchange/exchange_test.go
exchange/utils.go

We need to make case insensitive comparison in the request while in the response we should return the same bidder name(with whatever case) from the request.
By doing case insensitive comparison in the request, we are not making any changes in our current auction flow. Our current auction flow will work the same way as it is today.

make case insensitive comparison in auction request

---

adapters/silvermob/silvermob.go
adapters/silvermob/silvermobtest/supplemental/invalid-host.json

Second level domains are being validated before usage. Allowed only eu.silvermob.com, us.silvermob.com and apac.silvermob.com

Silvermob: host validation (us, eu, apac)

---

endpoints/info/bidders_detail.go
endpoints/info/bidders_detail_test.go

This PR makes `/info/bidders/:bidderName` endpoint as case insensitive. Now, we will be able to make the call to this endpoint using `/info/bidders/APPNEXUS` for example.
There is special `all` case that is also handled in this PR.

make bidderInfo endpoint case insensitive

---

.github/workflows/adapter-code-coverage.yml
.github/workflows/helpers/pull-request-utils.js

PR updates code-coverage github action script to execute only if,
- all files all not removed
- file belongs to the 'adapters' directory
Testings:
- all files are removed: https://github.com/onkarvhanumante/prebid-server/pull/9
- adapter code is updated: https://github.com/onkarvhanumante/prebid-server/pull/10
PR changes will resolve failing code coverage test from PRs - https://github.com/prebid/prebid-server/pull/3143 https://github.com/prebid/prebid-server/pull/3142 https://github.com/prebid/prebid-server/pull/3134 https://github.com/prebid/prebid-server/pull/3133 https://github.com/prebid/prebid-server/pull/3132 https://github.com/prebid/prebid-server/pull/3131 https://github.com/prebid/prebid-server/pull/3130 https://github.com/prebid/prebid-server/pull/3129

fix adapter code-coverage github action

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/valid-whole/supplementary/imp-with-stored-bid-resp-insensitive-bidder-name.json
stored_responses/stored_responses.go

PR makes changes to support case insensitive bidder names in `ext.prebid.storedbidresponse.bidder`
As shown below bidder name appnexus is known name to PBS. But APPNEXUS is unknown. Prior to PR changes PBS would have error out with unknown APPNEXUS bidder name messgae. PR has implemented insensitive bidder name comparison in ext.prebid.storedbidresponse.bidder
```
"ext": {
"appnexus": {
"placementId": 12883451
},
"prebid": {
"storedbidresponse": [
{
"bidder": "APPNEXUS",
"id": "bidResponseId3"
}
]
}
}
```

Support case insensitive bidder name in storedbidresponse

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/valid-whole/exemplary/bidder-adjustment-factors-case-insensitive.json

PR makes changes to support case insensitive bidder names in adjustment factors. 
As shown below bidder name `appnexus` is known name to PBS. But `APPNEXUS` is unknown. Prior to PR changes PBS would have error out with unknown `APPNEXUS` bidder name messgae.  PR has implemented insensitive bidder name comparison in `bidadjustmentfactors`
```
{
"imp": [
{
"ext": {
"prebid": {
"bidder": {
"APPNEXUS": { // sensitive appnexus
}
}
}
}
}
],
ext: {
"prebid": {
"bidadjustmentfactors": {
"APPNEXUS": 1 // sensitive appnexus
}
}
``` 

Support case insensitive bidder name in bidadjustmentfactors

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/valid-whole/exemplary/eidpermissions-insensitive-bidder-name.json

PR makes changes to support case insensitive bidder names in `ext.prebid.data.eidpermissions.bidders`.
As shown below bidder name appnexus is known name to PBS. But APPNEXUS is unknown. Prior to PR changes PBS would have error out with unknown `APPNEXUS` bidder name messgae. PR has implemented insensitive bidder name comparison in `ext.prebid.data.eidpermissions.bidders`
```
"ext": {
"prebid": {
"data": {
"eidpermissions": [
{
"source": "source1",
"bidders": [
"APPNEXUS" //  sensitive bidder name
]
}
]
}
}
```

Support case insensitive bidder name in eidpermissions

---

openrtb_ext/bidders.go
openrtb_ext/bidders_test.go

Now - normalizeBidderName function is being used in the auction flow so we need to make sure that it does faster lookups.
This PR makes changes to not call `bidderNameLookup` function on every normalizeBidderName. Instead, `bidderNameLookup` now returns static map instead of function and that will be used to do lookups. 
To handle alias cases - map is being updated while calling `SetAliasBidderName` function.

make NormalizeBidderName to do faster lookup

---

config/config.go
config/config_test.go

The upcoming 2.0 release will remove backwards compatibility for deprecated host and account configuration options. This PR removes support for the following host options:
`stored_requests.filesystem`
`stored_requests.directorypath`
Instead, hosts should use the following respectively:
`stored_requests.filesystem.enabled`
`stored_requests.filesystem.path`

Remove Config Backwards Compatibility: File System Stored Requests

---

account/account.go
account/account_test.go
config/account.go
config/config.go
config/config_test.go
config/events.go
config/events_test.go
endpoints/events/event.go
exchange/events.go
exchange/exchange_test.go

The upcoming 2.0 release will remove backwards compatibility for deprecated host and account configuration options. This PR removes support for the following host options:
`events_enabled`
Instead, hosts should use `account_defaults.events.enabled` in the host config and `events.enabled` in account configs.

Remove Config Backwards Compatibility: Enable Events

---

static/bidder-info/orbidder.yaml

User sync redirect config added for orbidder adapter.

ORBIDDER: add user sync redirect url

---

adapters/adnuntius/adnuntius.go
adapters/adnuntius/adnuntiustest/supplemental/check-gross-bids.json
adapters/adnuntius/adnuntiustest/supplemental/check-net-bids.json
adapters/adnuntius/adnuntiustest/supplemental/check-price-type-error.json
openrtb_ext/imp_adnuntius.go
static/bidder-params/adnuntius.json

This PR will allow Prebid server to request a price type. The ad will be returned with either net, or gross bid depending on what you specify.

Adnuntius: Add Price Type

---

config/bidderinfo.go
config/bidderinfo_test.go
config/config_test.go

The upcoming Prebid Server 2.0 release will remove backwards compatibility configuration options. This includes the adapter `usersync_url ` config, which used to the the only way to configure a user sync url before we refactored and introduced more granular options. Hosts may have needed to override this value to enable user sync for some bidders.
Instead, please use the `userSync.iframe.url` and or `userSync.redirect.url` config of the new adapter `usersync` config.

Remove Config Backwards Compatibility: User Sync URL

---

static/bidder-info/orbidder.yaml

Our Endpoint supports HTTP-OPTION requests and CORS handling.
Sorry for overseen this config possibility.

orbidder: add supportCors to user sync config

---

endpoints/events/vtrack.go
endpoints/events/vtrack_test.go

- PR makes changes to support case insensitive adapter name in `/vtrack` endpoint. 
- The `/vtrack` endpoint takes adapter name as input. Adapter name from request is looked up on `bidderInfos` to decide whether to include adapter name in vastXML.
- For example, `appnexus` is known adapter name to PBS. PR makes changes to ensure any casing of appnexus i.e `APPNEXUS, ApPnExUs, appNexus` is mapped to PBS known  `appnexus` adapter name.
```
{
Type:       prebid_cache_client.TypeXML,
BidID:      "bidId1",
Bidder:     "APPNEXUS", // case sensitive name
Data:       d,
TTLSeconds: 3600,
Timestamp:  1000,
},
{
Type:       prebid_cache_client.TypeXML,
BidID:      "bidId2",
Bidder:     "ApPnExUs", // case sensitive name
Data:       d,
TTLSeconds: 3600,
Timestamp:  1000,
}
```

Adapter Name Case Insensitive: /vtrack endpoint

---

metrics/prometheus/preload.go
metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go
metrics/prometheus/type_conversion.go

- As of now, following are the prometheus metrics which have bidder name as label
```
RecordAdapterRequest(labels AdapterLabels)
RecordAdapterConnections(adapterName openrtb_ext.BidderName, connWasReused bool, connWaitTime time.Duration)
RecordAdapterPanic(labels AdapterLabels)
RecordAdapterBidReceived(labels AdapterLabels, bidType openrtb_ext.BidType, hasAdm bool)
RecordAdapterPrice(labels AdapterLabels, cpm float64)
RecordAdapterTime(labels AdapterLabels, length time.Duration)
RecordAdapterGDPRRequestBlocked(adapterName openrtb_ext.BidderName)
RecordBidValidationCreativeSizeError(adapter openrtb_ext.BidderName, account string)
RecordBidValidationCreativeSizeWarn(adapter openrtb_ext.BidderName, account string)
RecordBidValidationSecureMarkupError(adapter openrtb_ext.BidderName, account …
```

Prometheus metrics:  bidder name should be in lowercase

---

metrics/config/metrics_test.go
metrics/go_metrics.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/prometheus/prometheus_test.go

- As of now, following are the prometheus metrics which have bidder name as label.
```
RecordAdapterRequest(labels AdapterLabels)
RecordAdapterConnections(adapterName openrtb_ext.BidderName, connWasReused bool, connWaitTime time.Duration)
RecordAdapterPanic(labels AdapterLabels)
RecordAdapterBidReceived(labels AdapterLabels, bidType openrtb_ext.BidType, hasAdm bool)
RecordAdapterPrice(labels AdapterLabels, cpm float64)
RecordAdapterTime(labels AdapterLabels, length time.Duration)
RecordAdapterGDPRRequestBlocked(adapterName openrtb_ext.BidderName)
RecordBidValidationCreativeSizeError(adapter openrtb_ext.BidderName, account string)
RecordBidValidationCreativeSizeWarn(adapter openrtb_ext.BidderName, account string)
RecordBidValidationSecureMarkupError(adapter openrtb_ext.BidderName, account …
```

InfluxDB metrics : bidder name should be in lowercase

---

endpoints/cookie_sync_test.go
openrtb_ext/bidders.go
usersync/bidderfilter.go
usersync/bidderfilter_test.go
usersync/chooser.go
usersync/chooser_test.go

Tested locally with `/cookie_sync` POST endpoint with following body - 
```
{
"bidders": ["AppnexUs"],
"coopsync": false,
"limit": 1
}
```
and got this sample response - 
```
{
"status" : "no_cookie",
"bidder_status" : [
{
"no_cookie" : true,
"bidder" : "AppnexUs",
"usersync" : {
"url" : "https://ib.adnxs.com/getuid?http%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dappnexus%26gdpr%3D%26gdpr_consent%3D%26gpp%3D%26gpp_sid%3D%26f%3Di%26uid%3D%24UID",
"type" : "redirect"
}
}
]
}
```

update cookie sync endpoint to be case insensitive

---

adapters/yeahmobi/params_test.go
adapters/yeahmobi/yeahmobi.go
adapters/yeahmobi/yeahmobi_test.go
adapters/yeahmobi/yeahmobitest/exemplary/no-bid.json
adapters/yeahmobi/yeahmobitest/exemplary/simple-banner.json
adapters/yeahmobi/yeahmobitest/exemplary/simple-native-1.1.json
adapters/yeahmobi/yeahmobitest/exemplary/simple-native.json
adapters/yeahmobi/yeahmobitest/exemplary/simple-video.json
adapters/yeahmobi/yeahmobitest/supplemental/bad_imp_ext.json
adapters/yeahmobi/yeahmobitest/supplemental/bad_imp_ext_bidder.json
adapters/yeahmobi/yeahmobitest/supplemental/bad_response.json
adapters/yeahmobi/yeahmobitest/supplemental/status_400.json
adapters/yeahmobi/yeahmobitest/supplemental/status_500.json
exchange/adapter_builders.go
exchange/adapter_util.go
openrtb_ext/bidders.go
openrtb_ext/imp_yeahmobi.go
static/bidder-info/yeahmobi.yaml
static/bidder-params/yeahmobi.json

Reverting removal of the Yeahmobi adapter. This adapter was remove due to an unreachable email address. They've provided an updated email address which we've verified is actively monitored.
Per #3194 from @solinary06

Welcome Back: yeahmobi

---

exchange/exchange.go
exchange/exchange_test.go
exchange/exchangetest/multi-bids-mixed-case.json
exchange/utils.go

Normalization was done in `buildMultiBidMap(prebid *openrtb_ext.ExtRequestPrebid)` inside file `exchange/exchange.go`. Let me know your thoughts.

Adapter Name Case Insensitive: ext.prebid.multibid

---

.github/workflows/release.yml

- PR updates release workflow to support major version release
- PBS-GO skipped the v1.0.0 major release - https://github.com/prebid/prebid-server/issues/3068
- If the current tag is v0.x.x, the script sets the next release tag to v2.0.0
- Otherwise, the script increments the major version by 1 and sets the minor and patch versions to zero. For example, v2.x.x will be incremented to v3.0.0
```
Tested on fork repo - https://github.com/onkarvhanumante/prebid-server/actions/workflows/release.yml
```
Major:
Minor:
Patch:
Docker images were built based on release type

Update release workflow to support major version release

---

static/bidder-info/adform.yaml
static/bidder-info/quantumdex.yaml
static/bidder-info/valueimpression.yaml

Some of the alias migrations removed the user sync section if it's set in the parent. However, this change the syncer key (cookie family in PBS-Java) and has side affects. Reverting this for now and will discuss next steps in the PMC.

Restore Hardcoded Alias User Syncs

---

adapters/definemedia/definemedia.go
adapters/definemedia/definemedia_test.go
adapters/definemedia/definemediatest/exemplary/sample-conative-banner.json
adapters/definemedia/definemediatest/exemplary/sample-conative-native.json
adapters/definemedia/definemediatest/supplemental/nobid-response.json
adapters/definemedia/definemediatest/supplemental/nocontent-response.json
adapters/definemedia/definemediatest/supplemental/status_400.json
adapters/definemedia/definemediatest/supplemental/status_418.json
adapters/definemedia/definemediatest/supplemental/unmarshal-error.json
adapters/definemedia/definemediatest/supplemental/unsupported-type.json
adapters/definemedia/params_test.go
exchange/adapter_builders.go
exchange/adapter_util.go
openrtb_ext/bidders.go
openrtb_ext/imp_definemedia.go
static/bidder-info/definemedia.yaml
static/bidder-params/definemedia.json

Dear PBS-Team,
at first sorry for the late reaction from our side. There were a lot of holidays and we just didn't see your messages on github.
In our repo I've reverted the commit, changed the email and made the pull request. Hope that was correct and that you can add us again soon.
Thanks.

Revert "Remove Adapter: Define Media"

---

config/bidderinfo.go
config/bidderinfo_test.go

Fix for https://github.com/prebid/prebid-server/issues/3177

Fix: BidderInfo OpenRTB field data lost on start up

---

config/bidderinfo.go
config/bidderinfo_test.go
config/config.go
config/config_test.go

This is one way we can fix the bidder info config override logic issue where information in the base config (file system) is lost when override data is provided (pbs.yaml, env vars, etc). This implementation avoids a previously discussed approach of changing bools to bool pointers and instead mimics an approach taken to handle aliases where a nillable fields struct is introduced to assist in detecting the presence of certain fields in an override config.
Some of the team met this morning and agreed to favor this approach over the pointer approach.

Fix: use bidder info fs config as base when merging overrides

---

router/router.go

As part of the v2.0.0 release we switched the JSON library from the standard library `encoding/json` to `json-iter` throughout PBS core, however, it had the unintended consequence of changing the response output on the `/bidders/params `endpoint from a compacted single-line response to a formatted multi-line response. This PR reverts that logic so that `encoding/json` is used to marshal the response on that endpoint.
All other endpoints were checked for a similar problem and were not affected. The `/bidders/params` endpoint prepares its response in a different way from all other endpoints by marshaling `map[string]json.RawMessage` while other endpoints build their response by marshaling structs.
There does not appear to be a way to explicitly compact JSON using `json-iter` at this time so …

Fix: revert JSON lib used to prepare /bidders/params response

---

adapters/gumgum/gumgum.go
adapters/gumgum/gumgumtest/supplemental/banner-with-pubId-product-params.json
adapters/gumgum/params_test.go
openrtb_ext/imp_gumgum.go
static/bidder-params/gumgum.json

In these changes, we are starting to pass the product param from Prebid Server to GG Ad Server under the impressions.ext param.
For any questions/comments pls feel free to reach out.
Thanks
Natalia Castiglioni

GumGum: Add product parameter

---

adapters/flipp/flipp.go
adapters/flipp/flipp_test.go
adapters/flipp/flipptest/exemplary/simple-banner-native-param-transmit-eids.json
adapters/flipp/flipptest/exemplary/simple-banner-native-param-user-coppa.json
adapters/flipp/flipptest/exemplary/simple-banner-native-param-user-gdpr.json
go.mod
go.sum

Based on the discussion here https://github.com/prebid/prebid.github.io/pull/4551#discussion_r1222097913, we will not use userKey from Flipp bidder params if any of the following conditions are true:
- COPPA is in effect
- The Global Privacy Control is set
- TCF purpose 4 is in scope and doesn't have consent
- The Prebid "transmitEids" activity is disallowed

Flipp: abide by privacy concerns when using flippExt userKey

---

adapters/oms/oms.go
adapters/oms/oms_test.go
adapters/oms/omstest/exemplary/simple-banner-cookie-uid.json
adapters/oms/omstest/exemplary/simple-banner-multiple-bids.json
adapters/oms/omstest/exemplary/simple-banner-uid.json
adapters/oms/omstest/exemplary/simple-multi-type-banner.json
adapters/oms/omstest/supplemental/204-response-from-target.json
adapters/oms/omstest/supplemental/400-response-from-target.json
adapters/oms/omstest/supplemental/500-response-from-target.json
adapters/oms/omstest/supplemental/simple-banner-with-ipv6.json
adapters/oms/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_oms.go
static/bidder-info/oms.yaml
static/bidder-params/oms.json

Golang code (including tests) for Online media solutions(OMS) server adaptor.

New Adapter: oms

---

adapters/adquery/adquery.go
adapters/adquery/adquery_test.go
adapters/adquery/adquerytest/exemplary/empty.json
adapters/adquery/adquerytest/exemplary/many-imps.json
adapters/adquery/adquerytest/exemplary/ok.json
adapters/adquery/adquerytest/exemplary/single-imp-banner-format.json
adapters/adquery/adquerytest/supplemental/data-null.json
adapters/adquery/adquerytest/supplemental/invalid-numerical-values.json
adapters/adquery/adquerytest/supplemental/malformed-resp.json
adapters/adquery/adquerytest/supplemental/mediatype-unknown.json
adapters/adquery/adquerytest/supplemental/mediatype-video.json
adapters/adquery/adquerytest/supplemental/no-device.json
adapters/adquery/adquerytest/supplemental/no-imp-banner-measures.json
adapters/adquery/adquerytest/supplemental/no-imp-banner.json
adapters/adquery/adquerytest/supplemental/no-site.json
adapters/adquery/adquerytest/supplemental/resp-bad-request.json
adapters/adquery/adquerytest/supplemental/resp-no-content.json
adapters/adquery/adquerytest/supplemental/resp-server-error.json
adapters/adquery/types.go
static/bidder-info/adquery.yaml

* adquery: added device ip and ua to bidder request
* adquery: passing client ip as x-forwarded-for header
* adquery: updated adapter endpoint
* adquery: passing ipv6 to bidder, updated user sync config
* adquery: passing page url to bidder

adquery: added device ip and ua to bidder request

---

adapters/ix/ix.go
adapters/ix/ix_test.go
adapters/ix/ixtest/exemplary/fledge.json
adapters/ix/ixtest/supplemental/bad-fledge.json
adapters/ix/ixtest/supplemental/fledge-no-bid.json

This MR adds privacy sandbox support to the IX Bid Adapter

IX: add privacy sandbox support

---

openrtb_ext/deal_tier_test.go

We're seeing occasional test suite failures related to the deal tier test `TestReadDealTiersFromImp`. The test case with description `imp.ext.prebid.bidder - same bidder listed twice but with different case the last one prevails` sometimes fails. This test case was recently added as part of the adapter name case insensitive initiative. The problem traces back to the fact that the function under test, `ReadDealTiersFromImp`, attempts to unmarshal `imp.ext.prebid.bidder` into type `map[string]struct` and then iterates over the map, normalizing each bidder name and ultimately selecting the deal tier information for the last occurrence of a given normalized bidder name. However, a map does not guarantee order so the order in which the keys are read from the map when iterating over it is …

Fix: flakey deal tier test

---

endpoints/setuid.go
endpoints/setuid_test.go

Possible fix for - https://github.com/prebid/prebid-server/issues/3166

Fix: setuid endpoint sets cookie when both GDPR and GPP are set

---

exchange/exchange.go
exchange/exchange_test.go

In alternatebiddercodes feature (https://github.com/prebid/prebid-server/issues/2174) it it possible that prebid-server gets a bid only from alternatebidder and not the primary bidder. Ex. For PubMatic-GroupM setup, PubMatic adapter would return a GroupM bid only.
For the above scenario, 
1. [L769](https://github.com/prebid/prebid-server/blob/v2.0.2/exchange/exchange.go#L769) , extraRespInfo.bidsFound is  set to 'false' because 'brw.bidder' is 'pubmatic' but seatBid.Seat is 'groupm'
2. [L377](https://github.com/prebid/prebid-server/blob/v2.0.2/exchange/exchange.go#L377), anyBidsReturned flag is set to false .
3. if anyBidsReturned=false then Floor-enforcement + category-mapping + deal-support etc are not being applied to the bid-response.Even targetting-keys + event-trackers are missing …

Fix: single bid processing from alternatebiddercode

---

adapters/relevantdigital/params_test.go
adapters/relevantdigital/relevantdigital.go
adapters/relevantdigital/relevantdigital_test.go
adapters/relevantdigital/relevantdigitaltest/exemplary/simple-audio.json
adapters/relevantdigital/relevantdigitaltest/exemplary/simple-banner.json
adapters/relevantdigital/relevantdigitaltest/exemplary/simple-native.json
adapters/relevantdigital/relevantdigitaltest/exemplary/simple-video.json
adapters/relevantdigital/relevantdigitaltest/supplemental/invalidBidMType.json
adapters/relevantdigital/relevantdigitaltest/supplemental/invalidBidMTypeParsesExt.json
adapters/relevantdigital/relevantdigitaltest/supplemental/invalidBidType.json
adapters/relevantdigital/relevantdigitaltest/supplemental/invalidParam.json
adapters/relevantdigital/relevantdigitaltest/supplemental/invalidRequestCount.json
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_relevantdigital.go
static/bidder-info/relevantdigital.yaml
static/bidder-params/relevantdigital.json

Greetings Prebid team, I have the pleasure of submitting this adapter on `relevantdigital`s behalf.
This adapter is consistent with the .js adapter so please see previous documentation for `relevantdigital` js adapter here: https://docs.prebid.org/dev-docs/bidders/relevantdigital.html
This PR is also dependant on the following PRs:
s2s support for .js adapter: https://github.com/prebid/Prebid.js/pull/10610
s2s documentation: https://github.com/prebid/prebid.github.io/pull/4931

New Adapter: Relevant Digital

---

static/bidder-info/rubicon.yaml

The Magnite exchange accepts compressed requests.

Rubicon: enable endpoint compression

---

adapters/nextmillennium/nextmillennium.go
adapters/nextmillennium/nextmillennium_test.go
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-empty-group-id.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-group-id.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-group-id_app.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-only-width.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-wh.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-wo-domain.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner-wo-size.json
adapters/nextmillennium/nextmillenniumtest/exemplary/banner.json
adapters/nextmillennium/nextmillenniumtest/exemplary/empty-banner-obj.json
adapters/nextmillennium/nextmillenniumtest/supplemental/empty-seatbid.json
adapters/nextmillennium/nextmillenniumtest/supplemental/error-response.json
adapters/nextmillennium/nextmillenniumtest/supplemental/no-content.json

Added the ability for users to pass custom flags using extra_info,

Nextmillennium: add extra_info support

---

endpoints/openrtb2/sample-requests/hooks/auction_bidder_reject.json
endpoints/openrtb2/sample-requests/hooks/auction_bidder_response_reject.json
endpoints/openrtb2/sample-requests/hooks/auction_entrypoint_reject.json
endpoints/openrtb2/sample-requests/hooks/auction_processed_auction_request_reject.json
endpoints/openrtb2/sample-requests/hooks/auction_raw_auction_request_reject.json
endpoints/openrtb2/test_utils.go

The tmax values for the test cases in `endpoints/openrtb2/auction_test.go#TestValidResponseAfterExecutingStages` appear to be too small such that they're causing occasional deadline exceeded errors when attempting to retrieve bids from the mock bidders.

Fix: increase tmax in flakey modularity test

---

adapters/sovrnXsp/params_test.go
adapters/sovrnXsp/sovrnXsp.go
adapters/sovrnXsp/sovrnXsp_test.go
adapters/sovrnXsp/sovrnXsptest/exemplary/banner.json
adapters/sovrnXsp/sovrnXsptest/exemplary/native.json
adapters/sovrnXsp/sovrnXsptest/exemplary/video.json
adapters/sovrnXsp/sovrnXsptest/supplemental/request-no-matching-imp.json
adapters/sovrnXsp/sovrnXsptest/supplemental/response-empty-seat.json
adapters/sovrnXsp/sovrnXsptest/supplemental/response-http-error.json
adapters/sovrnXsp/sovrnXsptest/supplemental/response-invalid-crtype.json
adapters/sovrnXsp/sovrnXsptest/supplemental/response-nobid.json
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_sovrnXsp.go
static/bidder-info/sovrnXsp.yaml
static/bidder-params/sovrnXsp.json

This adapter works alongside the existing Sovrn adapter, covering in-app video, banner, and native specifically.

New Adapter: SovrnXSP

---

adapters/bizzclick/bizzclick.go
adapters/bizzclick/bizzclick_test.go
adapters/bizzclick/bizzclicktest/exemplary/banner-app.json
adapters/bizzclick/bizzclicktest/exemplary/banner-web.json
adapters/bizzclick/bizzclicktest/exemplary/default-host-param.json
adapters/bizzclick/bizzclicktest/exemplary/native-app.json
adapters/bizzclick/bizzclicktest/exemplary/native-web.json
adapters/bizzclick/bizzclicktest/exemplary/video-app.json
adapters/bizzclick/bizzclicktest/exemplary/video-web.json
adapters/bizzclick/bizzclicktest/supplemental/empty-seatbid-array.json
adapters/bizzclick/bizzclicktest/supplemental/invalid-response.json
adapters/bizzclick/bizzclicktest/supplemental/status-code-bad-request.json
adapters/bizzclick/bizzclicktest/supplemental/status-code-no-content.json
adapters/bizzclick/bizzclicktest/supplemental/status-code-other-error.json
adapters/bizzclick/bizzclicktest/supplemental/status-code-service-unavailable.json
adapters/bizzclick/params_test.go
openrtb_ext/imp_bizzclick.go
static/bidder-info/bizzclick.yaml
static/bidder-params/bizzclick.json

Hi, the adapter was updated with new sourceId and host params. 
Related [PR](https://github.com/prebid/prebid.github.io/pull/5026) in prebid.github.io

Bizzclick: adapter update, add new host param

---

adapters/adkernel/adkernel_test.go
adapters/adkernel/adkerneltest/exemplary/multiformat-impression.json
adapters/adkernel/adkerneltest/exemplary/single-banner-impression.json
adapters/adkernel/adkerneltest/exemplary/single-video-impression.json
static/bidder-info/adkernel.yaml

Make the endpoint URL unsecured to reduce latency.

Adkernel: Unsecured endpoint url

---

exchange/exchange.go
exchange/exchange_test.go
openrtb_ext/deal_tier.go
openrtb_ext/deal_tier_test.go

This PR solves issue mentioned in https://github.com/prebid/prebid-server/issues/3362

Fix: Enable deals for soft aliases

---

static/bidder-info/kargo.yaml

Adds ortb.multiformat_supported and ortb.gpp_supported for Kargo's bidder info

Kargo: Update bidder-info

---

static/bidder-info/yahooAds.yaml

This pull request updates the maintainer email address to [prebid-tech-team@yahooinc.com](mailto:prebid-tech-team@yahooinc.com).
Details:
Maintainer Email Address: [prebid-tech-team@yahooinc.com](mailto:prebid-tech-team@yahooinc.com)

yahooAds: Update maintainer email address

---

exchange/exchange_test.go
hooks/hookexecution/mocks_test.go

Possible fix for race condition in TestModulesCanBeExecutedForMultipleBiddersSimultaneously
It seems that in this test, there were two possible sources of problems:
1. There appeared to be a typo where a bidder name was duplicated.
2. `bidderImpl` object was shared between bidder requests.
The bidder requests are being tested in separate, concurrent goroutines, causing concurrent reads and writes to the `Headers` map.
The fix is to fix the typo, and to create separate objects.
One thing that is not entirely clear to me is that the `Headers` map is being cloned inside of the `getAllBids` function, and according to my investigation with breakpoints and the debug log, the error was happening in an `Add` method *after* the clone. Nonetheless, upon repeated testing, I cannot reproduce the bug …

Fix race condition in modularity test

---

.github/workflows/adapter-code-coverage.yml

PR updates [adapter-code-coverage.yml](https://github.com/prebid/prebid-server/compare/update-coverage-check?expand=1#diff-c4f0bb987be62acfd3c8b040dee1111ddf7c2bdfeb3c0b3d48c0cafbc9859970) to run coverage tests for max 2 adapter directories
**Test details**
Coverage tests were skipped for https://github.com/onkarvhanumante/prebid-server/pull/11 PR on forked repo 
https://github.com/onkarvhanumante/prebid-server/actions/runs/7628791242/job/20780684209?pr=11

Skip coverage tests if more than two adapters were modified

---

exchange/bidder.go
exchange/bidder_test.go

By utilizing Golang Sync Pools, I was able to optimize the process of GZIP Compression within PBS.
Benchmark tests are added in this PR to test the difference between how GZIP used to be compressed, and the updated version.
Here are the results (After Latest Refactor):
Non-Optimized:
**BenchmarkCompressToGZIPNotOptimized-8**   	   11616	    100384 ns/op	  813992 B/op	      19 allocs/op
Optimized:
**BenchmarkCompressToGZIPOptimized-8**  	   84913	     12657 ns/op	     128 B/op	       3 allocs/op
From left to right, each value represents the following: Operations per Second, Average Time per Operation, Bytes Allocated per Operation, and Allocations per Operations
The optimized version shows significant improvements across the board

Optimize GZIP Compression

---

floors/fetcher.go
floors/fetcher_test.go
floors/floors.go
floors/floors_test.go
openrtb_ext/floors.go

Changes proposed in https://github.com/prebid/prebid-server/issues/2755 are implemented in this PR

Introduced FetchRate field to select source of floors from request or dynamically fetched

---

.github/workflows/adapter-code-coverage.yml

- As of now, warning related to node 16 usage were seen on `prebid/prebid-server` for code coverage workflow.
- As per, https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20 Node 16 has reached its end of life and it is recommended to transition to use Node 20 by Spring 2024. 
- PR makes changes in code coverage workflow to use actions with node 20 support.
- Tested by running  code coverage workflow on forked repo.
https://github.com/onkarvhanumante/prebid-server/actions/runs/7811209264

update code coverage workflow to use actions with node 20 support

---

adapters/improvedigital/improvedigital.go
adapters/improvedigital/improvedigitaltest/supplemental/addtl-consent-multi-tilda.json

EDIT: Forward fix for https://github.com/prebid/prebid-server-java/issues/2942
Original issue is found & reported on pbs java. As the pbs go adapters are continuously being ported to java version, we want to fix this here first and then provide fix in the java version.
Please review & merge kindly at your earliest convenience.
TIA

ImproveDigital: Bad-Input Error 

---

.github/workflows/validate-merge.yml
.github/workflows/validate.yml

- As per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20 support for Node version 16 has reached its end of life and it is recommended to transition all actions to run on Node version 20 by Spring 2024.
- The `validate` and `validate-merge` workflow uses `actions/setup-go@v4` and `actions/checkout@v3` actions.  These actions have dependency on Node version 16.
- PR updates both workflows, to use `setup-go` action of version 5 and the `checkout` action of version 4. These updated versions use Node version 20.

Update validate pull request workflows to use node 20 actions

---

.github/workflows/issue_prioritization.yml

As per, https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20 Node 16 has reached its end of life and it is recommended to transition all actions to run on Node 20 by Spring 2024.
Issue tracking workflow makes use of `tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0`.  PR makes changes to use `tibdex/github-app-token@v2.1.0`. Maintainers of tibdex/github-app-token has added support for node version 20 in v2.1.0 of tibdex/github-app-token.

Update issue tracking workflow to use actions with node version 20 support

---

static/bidder-info/medianet.yaml

Enable gzip compression and update usersync url for Medianet adapter

Medianet: enable gzip and update usersync url

---

.github/workflows/helpers/pull-request-utils.js
.github/workflows/release.yml

- As per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20 support for Node version 16 has reached its end of life and it is recommended to transition all actions to run on Node version 20 by Spring 2024.
- Currently release workflow  uses  `actions-cool/check-user-permission@v2.2.0` and `actions/checkout@v3` actions. 
- Maintainers of `actions-cool/check-user-permission` haven't added support for Node version 20. Therefore, PR makes changes to replace `actions-cool/check-user-permission@v2.2.0` by `actions/github-script@v7`.  The `actions/github-script@v7` uses Node version 20 and has api to check if user has permission to release. Note that helper method was added in [helpers/pull-request-utils.js](https://github.com/prebid/prebid-server/compar …

Update release workflow to use actions with node 20 support

---

.github/workflows/security.yml

- As of now, warning related to node 16 usage were seen on `prebid/prebid-server` for trivy check workflow.
- As per, https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20 Node 16 has reached its end of life and it is recommended to transition to use Node 20 by Spring 2024. 
- PR makes changes in code trivy check workflow to use actions with node 20 support.
- Tested by running  semgrep workflow on forked repo.
https://github.com/onkarvhanumante/prebid-server/actions/runs/7815116030

Update trivy check workflow to use node 20 actions

---

adapters/bidder.go

PR fixes an error in the function comment.  See https://go.dev/doc/comment regarding the documentation standards for the Go code comments.
The Goland IDE says about the current version:
```
Comment should have the following format 'MakeTimeoutNotification ...' (with an optional leading article) 
Inspection info: Reports comments that do not start with the name of the exported element.
According to Comment Sentences at github.com/golang, this is a convention to begin a comment with the name of the exported element.
Example:
// represents a request to run a command.
type Request struct {}
The comment starts with the struct description, not with the struct name. To stick to the convention rules, you can apply the Add prefix to comment quick-fix. After the quick-fix is applied, the comment …
```

Fix function godoc comment

---

.github/workflows/helpers/pull-request-utils.js
.github/workflows/release.yml

As of now release workflow gets aborted at `check permission` step.  Refer https://github.com/prebid/prebid-server/actions/runs/7911722094. PR adds log lines to help debug why the workflow is getting aborted.
Tested changes on fork - https://github.com/onkarvhanumante/prebid-server/actions/runs/7911745638

Add log lines in release workflow

---

.github/workflows/helpers/pull-request-utils.js
.github/workflows/release.yml

Release workflow has `check user permission` step. To check permission workflow makes call to permission api with repo owner and username as input.
Currently repo owner i.e `prebid` is used as username to check collaborator permission. However, `github.actor` i.e user who runs workflow should be used to check user permission. PR makes changes to use github.actor as username.
Earlier this workflow was tested on fork repository (https://github.com/onkarvhanumante/prebid-server/actions/runs/7842711148). However on fork repository, value for owner and username were same. Therefore this issue was not seen on fork repository.
Tested new changes on fork - https://github.com/onkarvhanumante/prebid-server/actions/runs/7913227266/job/21600444085

Fix: Release workflow permissions

---

exchange/bidder.go
exchange/bidder_test.go

Through some comments left in this GZIP [commit](https://github.com/prebid/prebid-server/commit/0c2865730d948b3d14f2527f0c32820c5935aafa#comments), there was a realization that there's unnecessary extra buffer utilized by returning bytes from `getRequestBody()`, and creating a new buffer for `NewRequest()`
So this PR makes updates to remove this extra buffer.

Remove Extra Buffer from GZIP Compression

---

exchange/auction.go
exchange/auction_test.go
exchange/exchange.go
exchange/exchange_test.go
exchange/exchangetest/targeting-always-include-deals.json
exchange/targeting.go
exchange/targeting_test.go
exchange/utils.go
openrtb_ext/request.go

Addresses this issue #2214
The goal is to add a new flag on the request at `ext.prebid.targeting.alwaysincludedeals`, that if true: PBS-core would generate targeting key-value pairs for all bids with a dealid. This is independent of which other ext.prebid.targeting flags are present.

Targeting: Add alwaysincludedeals flag

---

amp/parse.go
amp/parse_test.go

Fix go vet 'composite literals with unkeyed fields' issue by applying `gopls fix -a -w <file.go>` and some reformatting the structure initialization to be multiline with multiple fields. Part of the fix for #3481.
Reference: https://github.com/golang/go/issues/53062

Fix go vet composite literals with unkeyed fields

---

adapters/adoppler/adoppler.go
adapters/adquery/adquery.go

Fix go vet 'composite literals with unkeyed fields' issue by applying `gopls fix -a -w <file.go>`. Follow-up on https://github.com/prebid/prebid-server/pull/3507. Part of the fix for prebid#3481.
Reference: golang/go#53062

Fix go vet 'composite literals with unkeyed fields'

---

errortypes/code.go
exchange/exchange.go
exchange/exchange_test.go
exchange/non_bid_reason.go

Seat nonbid code 305 has not been formally approved yet so we will use 300 until then.
This PR also adds a DSA specific warning code as I don't think the invalid bid response error code makes sense since this is not a server error nor is it a malformed bid response. Instead it is a validation error.

DSA: Use seat nonbid code 300

---

adapters/stroeerCore/stroeercore.go
adapters/stroeerCore/stroeercoretest/exemplary/dsa.json

Support for Digital Services Act (DSA)

Stroeercore: Support DSA

---

static/bidder-info/bmtm.yaml

spoke with a member of this team who informed me that 'dev' is no longer monitored.

BMTM: Update maintainer address

---

Makefile

PR adds the `formatcheck` makefile target to run the `format.sh` script with `-f false` - to check if the Go files are properly formatted and exit with a non-zero error code. Intended for CI usage to enforce `gofmt`
compliance and fail builds on deviations.
Fix #3475.

Add formatcheck make target

---

analytics/pubstack/eventchannel/sender.go

Memory leak in the HttpSender module of PubStack caused by neglecting to close the response body.

Fix: Pubstack memory leak

---

modules/generator/builder.tmpl
modules/generator/buildergen.go

I have several modules organized in this way
```
modules/
├── vendor1
│   ├── module1
│   ├── module2
│   └── module3
├── generator
├── moduledeps
└── prebid
└── ortb2blocking
```
But `make build-modules` produces a generated file with duplicate keys in map
```
func builders() ModuleBuilders {
return ModuleBuilders{
"vendor1": {
"module1": vendor1Module1.Builder,
},
"vendor1": {
"module2": vendor1Module2.Builder,
},
"vendor1": {
"module3": vendor1Module3.Builder,
},
"prebid": {
"ortb2blocking": prebidOrtb2blocking.Builder,
},
}
}
```
With the fix:
```
func builders() ModuleBuilders {
return ModuleBuilders{
"vendor1": {
"module1":   vendor1Module1.Builder,
"module2":   vendor1Module2.Builder,
"module3":   vendor1Module3.Builder,
},
"prebid": {
"ortb2blocking": prebidOrtb2blocking.Builder, …
```

Fix: Module template & builder produces duplicate map keys

---

endpoints/info/bidders_detail_test.go
exchange/exchange_test.go
hooks/hookexecution/execution_test.go
router/aspects/request_timeout_handler_test.go
stored_requests/backends/db_fetcher/fetcher.go
stored_requests/backends/empty_fetcher/fetcher.go
stored_requests/backends/file_fetcher/fetcher_test.go
util/stringutil/stringutil_test.go

Fix go vet 'composite literals with unkeyed fields' issue by applying gopls fix -a -w <file.go>. Follow-up on https://github.com/prebid/prebid-server/pull/3507 and https://github.com/prebid/prebid-server/pull/3522. Part of the fix for https://github.com/prebid/prebid-server/issues/3481.
NB: I haven't changed the one-line struct initialization to multiline (yet).  Would you require it?  So far, I couldn't fine an automated way to do it.
Reference: https://github.com/golang/go/issues/53062

Reformat structures to use key names

---

adapters/adnuntius/adnuntius.go
adapters/adnuntius/adnuntiustest/supplemental/site-ext.json
adapters/adnuntius/adnuntiustest/supplemental/user-ext.json

This PR is meant to allow Adnuntius to do targeting on site Ext and also pick the first external ID from EIDs until we allow for multiple IDs in our adserver.

Adnuntius: site.ext targeting

---

validate.sh

PR changes the `go vet` not to require exceptions since it is possible now, after #3524 and other fixes for https://github.com/prebid/prebid-server/issues/3481.

do normal 'go vet' as it works now

---

analytics/agma/README.md
analytics/agma/agma_module.go
analytics/agma/agma_module_test.go
analytics/agma/model.go
analytics/agma/model_test.go
analytics/agma/sender.go
analytics/agma/sender_test.go
analytics/build/build.go
analytics/build/build_test.go
config/config.go
config/config_test.go

Following up on https://github.com/prebid/prebid-server/pull/3299#issuecomment-1881194517, this is a refactored version of the HTTP analytics PR, scoped to the data used by [agma](https://www.agma-mmc.de/). 
As requested by @bretg, I've limited the data collection to our GVLID and Propose 7.
Since I'm not entirely familiar with the entire codebase, I have some questions regarding whether there is a better way to do things:
* I'm parsing the `consent` in the `userExt`, as this was the only place I found the user consent in my environment. Is this the correct approach, or is the consent also available in the OpenRTB user object?
* Does this require more publicly available documentation than the provided README ?
Thank you for your review.

New Analytics Adapter: agma

---

config/config_test.go
exchange/utils_test.go
openrtb_ext/request.go

I'd like to have some bid adjustment rules for all accounts but due to missing `mapstructure` structure tags Viper doesn't load wildcard fields. https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#unmarshaling-doesnt-work
```
account_defaults:
bidadjustments:
mediatype:
'*':     # media type
'*':   # bidder name
'*': # deal id
- adjtype: multiplier
value: 1.03
currency: USD
```

Fix loading of default bid adjustments for "account_defaults"

---

adapters/aso/aso.go
adapters/aso/aso_test.go
adapters/aso/asotest/exemplary/app-banner.json
adapters/aso/asotest/exemplary/app-multi-impressions.json
adapters/aso/asotest/exemplary/app-native.json
adapters/aso/asotest/exemplary/app-video.json
adapters/aso/asotest/exemplary/site-banner.json
adapters/aso/asotest/exemplary/site-native.json
adapters/aso/asotest/exemplary/site-video.json
adapters/aso/asotest/supplemental/bad-request-no-bidder.json
adapters/aso/asotest/supplemental/bad-request-no-ext.json
adapters/aso/asotest/supplemental/bad-request.json
adapters/aso/asotest/supplemental/empty-response.json
adapters/aso/asotest/supplemental/media-type-absent.json
adapters/aso/asotest/supplemental/media-type-mapping.json
adapters/aso/asotest/supplemental/server-error.json
adapters/aso/asotest/supplemental/unparsable-response.json
adapters/aso/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_aso.go
static/bidder-info/aso.yaml
static/bidder-info/bcmint.yaml
static/bidder-info/bidgency.yaml
static/bidder-params/aso.json

Aso server adapter added.
Docs PR: https://github.com/prebid/prebid.github.io/pull/5194

New Adapter: Aso

---

static/bidder-params/yandex.json

OneOf cannot be used at properties level. This was overlooked during initial PR review. Issuing a quick fix here.

yandex: Fix yandex properties file

---

bidadjustment/build_rules.go
bidadjustment/build_rules_test.go

If auction request doesn't have bidadjustments object, but the adjustment has been enabled in the stored requests for the account there will be a panic
https://github.com/prebid/prebid-server/issues/3543
```
{
...
"ext": {
"prebid": {
"bidadjustments": {},
}
}
}
```

Fix: Panic in bid adjustments

---

endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext.json

Description in
[endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext.json](https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext.json#L2)
says: "This demonstrates all of the OpenRTB extensions supported by Prebid Server."
This PR adds `ext.prebid.debug` and `ext.prebid.integration`, documented in https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html#prebid-server-ortb2-extension-summary, to the [valid-whole/exemplary/all-ext.json](https://github.com/prebid/prebid-server/blob/master/endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext.json) sample request for completeness and illustration.

add 'debug' and 'integration' to sample requests

---

endpoints/events/event.go
endpoints/events/vtrack.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
usersync/cookie.go

Fix most of the semgrep issues with the
http://semgrep.dev/r/dgryski.semgrep-go ruleset
(`semgrep --config http://semgrep.dev/r/dgryski.semgrep-go`). Left the issue with Content-Type text/plain on json.Encode in endpoints/openrtb2/amp_auction.go since changing to application/json breaks the AMP unit tests, and issues with the pointer receiver for MarshalJSON in usersync/cookie.go.
Fix #3509.

Fix semgrep dgryski.semgrep-go issues

---

config/config.go
server/server.go

Admin listener is made configurable by adding  an `Admin` sub-object with `Enabled` field. 
`admin.enabled` is enabled by default.
Making it configurable allows a host company to not run the listener on admin port if they desire to do so.

Make admin listener configurable

---

floors/floors_test.go
floors/validate.go
floors/validate_test.go
openrtb_ext/floors.go
openrtb_ext/floors_test.go

Prebid Documentation [https://docs.prebid.org/dev-docs/modules/floors.html#schema-2]  is updated for data type of data.floorsSchemaVersion from string to integer

Updated FloorsSchemaVersion data type from string to int

---

static/bidder-info/sharethrough.yaml

* Adding GDPR and GPP info to user sync url.

Sharethrough: adding GDPR and GPP info to user sync url

---

adapters/conversant/conversant.go
adapters/conversant/conversanttest/exemplary/video.json

The backend server rejects any requests that don't have request.cur set to USD.  For now, make the Conversant request, and floors in USD

Conversant: Make requests in USD

---

adapters/cpmstar/cpmstar.go
adapters/cpmstar/cpmstartest/exemplary/multiple-banners.json

We fixed a for loop index reference bug in CPMStar Adapter, per: https://go.dev/blog/loopvar-preview

CPMStar: Fixed for loop index reference bug

---

adapters/alkimi/alkimi.go
adapters/flipp/flipp.go
adapters/flipp/flipp_test.go

I was reviewing the code to see if any new adapters needed to have ImpIDs added. We're all good though, thanks very much to @pmsaurabh-narkhede.
It was harder for me to quickly see the ImpIDs implementation for Flipp + Alkimi, so I'm proposing a minor refactor to make it easier. Also noticed some policy violations in Flipp and are correcting them here.
Flipp: @hasan-kanjee
Alkimi: @kalidas-alkimi

Flipp + Alkimi: Minor Refactoring

---

adapters/playdigo/params_test.go
adapters/playdigo/playdigo.go
adapters/playdigo/playdigo_test.go
adapters/playdigo/playdigotest/exemplary/endpointId.json
adapters/playdigo/playdigotest/exemplary/multi-format.json
adapters/playdigo/playdigotest/exemplary/multi-imp.json
adapters/playdigo/playdigotest/exemplary/simple-banner.json
adapters/playdigo/playdigotest/exemplary/simple-native.json
adapters/playdigo/playdigotest/exemplary/simple-video.json
adapters/playdigo/playdigotest/exemplary/simple-web-banner.json
adapters/playdigo/playdigotest/supplemental/bad_media_type.json
adapters/playdigo/playdigotest/supplemental/bad_response.json
adapters/playdigo/playdigotest/supplemental/no-valid-impressions.json
adapters/playdigo/playdigotest/supplemental/status-204.json
adapters/playdigo/playdigotest/supplemental/status-not-200.json
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_playdigo.go
static/bidder-info/playdigo.yaml
static/bidder-params/playdigo.json

doc - https://github.com/prebid/prebid.github.io/pull/5274

Playdigo: new adapter

---

adapters/unruly/unruly.go
adapters/unruly/unrulytest/exemplary/simple-video.json

Builds the BidVideo.Duration object if video.dur is present.

Unruly: BidVideo.Duration Support

---

adapters/yieldmo/yieldmo.go
adapters/yieldmo/yieldmotest/exemplary/valid_currency_conversion.json
adapters/yieldmo/yieldmotest/supplemental/unsupported_currency.json

This change adds bid floor currency conversion for the Yieldmo adapter. I didn't see any documentation around this functionality, so I largely based this change on the implementations I saw across other adapters. If anyone reviewing this is aware of any documentation or known issues/edge cases with this feature, I would love to hear about them. Thanks!

Yieldmo: Add bid floor currency conversion

---

exchange/exchangetest/imp-fpd-multiple-imp.json
exchange/utils_test.go

A recent change to the `util/jsonutil#merge.go` function fixed a problem where arrays were being merged instead of overwritten. Recently added Imp FPD tests were expecting merges instead of overwrites and needed to be updated as such.

Fix: Expect Array Overwrites in Imp FPD Tests

---

endpoints/openrtb2/auction.go
endpoints/openrtb2/sample-requests/invalid-whole/invalid-bidder-params.json
exchange/exchange_test.go
exchange/exchangetest/imp-fpd-multiple-imp.json
exchange/exchangetest/imp-fpd-skipped-validation.json
exchange/utils.go
ortb/request_validator.go
ortb/request_validator_test.go

This PR allows the imp validation logic used to both validate an incoming request and revalidate imps after merging FPD to be executed while skipping the expensive bidder params and native string validation.

Imp FPD: Skip bidder params and native validation

---

util/jsonutil/merge.go

PR fixes the semgrep issue with the [dgryski ruleset](https://github.com/dgryski/semgrep-go), rule https://github.com/dgryski/semgrep-go/blob/master/returnnil.yml by restructuring the error handling: return `nil` if the `err` from `jsonConfigMergeClone.Unmarshal`, otherwise make the return value as now.
```sh
┌────────────────┐
│ 1 Code Finding │
└────────────────┘
util/jsonutil/merge.go
❯❯❱ Users.dsavints.gh.dgryski.semgrep-go.return-nil
return nil instead of nil value
34┆ if err != nil {
35┆   return &errortypes.FailedToUnmarshal{
36┆           Message: tryExtractErrorMessage(err),
37┆   }
38┆ }
39┆ return err
```

Fix semgrep issue with dgryski Go ruleset

---

adapters/ix/ix.go
adapters/ix/ix_test.go

Currently running `go test -v [github.com/prebid/prebid-server/v2/adapters/ix](http://github.com/prebid/prebid-server/v2/adapters/ix) -count=2 -run 'TestJsonSamples|TestBuildIxDiag/Base_Test'` - that is, running each of the tests twice - produces errors due to mutating the global variable:
https://gist.github.com/dmitris/4e0ab9f24d4ba57537be448ed97a80c2
I think being able to execute tests multiple times is valuable to find the state mutation in the code under test or the tests themselves.
PR fixes the test failure.  The fix is based on what @radubarbos has done in the internal version of the code.

IX: save/restore global var in test

---

adapters/criteo/criteotest/exemplary/simple-native.json
static/bidder-info/criteo.yaml

- Added native media type in list of capabilities for criteo.yaml
- Added test for simple native case for criteo adapter

Criteo: Add support for native

---

static/bidder-info/cpmstar.yaml

CPMStar Bidder Adapter - Added GVL / TCF Vendor ID to bidder-info

CPMStar: add gvlVendorID

---

adapters/smaato/banner.go
adapters/smaato/banner_test.go
adapters/smaato/smaato.go
adapters/smaato/smaatotest/exemplary/multiple-impressions-skadn.json
adapters/smaato/smaatotest/exemplary/multiple-media-types-skadn.json
adapters/smaato/smaatotest/exemplary/multiple-media-types.json
adapters/smaato/smaatotest/exemplary/native.json
adapters/smaato/smaatotest/exemplary/simple-banner-app.json
adapters/smaato/smaatotest/exemplary/simple-banner-dooh.json
adapters/smaato/smaatotest/exemplary/simple-banner-eids.json
adapters/smaato/smaatotest/exemplary/simple-banner-skadn.json
adapters/smaato/smaatotest/exemplary/simple-banner.json
adapters/smaato/smaatotest/exemplary/video-app.json
adapters/smaato/smaatotest/exemplary/video-dooh.json
adapters/smaato/smaatotest/supplemental/bad-adtype-header-response.json
adapters/smaato/smaatotest/supplemental/bad-expires-header-response.json
adapters/smaato/smaatotest/supplemental/bad-status-code-response.json
adapters/smaato/smaatotest/supplemental/banner-w-and-h.json
adapters/smaato/smaatotest/supplemental/curl-nil-response.json
adapters/smaato/smaatotest/supplemental/expires-header-response.json
adapters/smaato/smaatotest/supplemental/no-app-site-dooh-request.json
adapters/smaato/smaatotest/supplemental/no-bid-response.json
adapters/smaato/smaatotest/supplemental/no-consent-info-request.json
adapters/smaato/smaatotest/supplemental/outdated-expires-header-response.json
adapters/smaato/smaatotest/video/multiple-adpods-skadn.json
adapters/smaato/smaatotest/video/multiple-adpods.json
adapters/smaato/smaatotest/video/single-adpod-skadn.json
adapters/smaato/smaatotest/video/single-adpod.json
adapters/smaato/smaatotest/videosupplemental/bad-adtype-header-response.json
adapters/smaato/smaatotest/videosupplemental/bad-bid-ext-response.json

Adding DOOH support for Smaato adapater

Smaato: DOOH support

---

adapters/openx/openx.go
adapters/openx/openxtest/exemplary/simple-video.json

Add `BidVideo` to adapter response containing the duration and category. They are used by PBS to build the value of `hb_pb_cat_dur` and `hb_pb_cat_dur_openx` targeting keys.

OpenX: return BidVideo object for hb_pb_cat_dur targeting 

---

static/bidder-info/felixads.yaml

-> FelixAds Docs PR https://github.com/prebid/prebid.github.io/pull/5521

SmartHub: add alias FelixAds

---

adapters/taboola/taboola.go
adapters/taboola/taboolatest/exemplary/bannerAppRequest.json

supporting `app` RTB traffic by passing the object as expected

Taboola: app support 

---

static/bidder-info/vidazoo.yaml

Extended the user sync URL to include GPP parameters.

Vidazoo: Update bidder info for GPP support

---

static/bidder-info/rubicon.yaml

This was done a while ago in https://github.com/prebid/prebid-server/pull/2536

Rubicon adapter: declare support for ORTB 2.6

---

static/bidder-info/kargo.yaml

Indicates support for openrtb 2.6 for Kargo adapter.

Kargo: Indicate support for OpenRTB 2.6

---

analytics/agma/README.md
analytics/agma/agma_module.go
analytics/agma/agma_module_test.go

This update enables users of our adapter to use `app.bundle` for selecting an app, in addition to the existing `app.id` option. This enhancement allows configuration when hosting providers share stored requests between apps.
edit: there was an unrelated build fail, I've rebased master and the CI looks fine now

Agma: Allow app.bundle to be used as selector for apps

---

go.mod
go.sum

update github.com/rs/cors to v1.11.0
Related: https://github.com/prebid/prebid-cache/pull/177
> Middleware causes a prohibitive amount of heap allocations when processing malicious preflight requests that include an Access-Control-Request-Headers (ACRH) header whose value contains many commas. This behavior can be abused by attackers to produce undue load on the middleware/server as an attempt to cause a denial of service.

Update github.com/rs/cors to v1.11.0

---

adapters/adapterstest/test_json.go
adapters/freewheelssp/freewheelssptest/exemplary/multi-imp.json
adapters/pubmatic/pubmatictest/exemplary/video.json
adapters/yeahmobi/yeahmobitest/exemplary/simple-video.json
openrtb_ext/bid.go

Adapter json test framework appears to ignore the `expectedBid.video` object and so the related tests do not test anything. 
Add `expectedBid.Video` and diff function to validate this part of the adapter response. There are a few tests that only have `video.duration` and no `video.primary_category` and those would fail; we can update the tests or update the `ExtPrebidVideo` structure to make them optional.
Here I update the structure assuming that the tests show the intention, but if that's not desirable we could update the tests instead.
There's a similar issue with exchange tests that I will look to address separately.
Fixes the existing adapter tests including the one added in #3834 so they actually do validate the expected response.

Update adapter json test framework to validate BidVideo

---

exchange/exchange_test.go
exchange/exchangetest/append-bidder-names.json
exchange/exchangetest/debuglog_disabled.json
exchange/exchangetest/debuglog_enabled.json
exchange/exchangetest/generate-bid-id-error.json
exchange/exchangetest/generate-bid-id-many.json
exchange/exchangetest/generate-bid-id-one.json
exchange/exchangetest/include-brand-category.json

Some exchange json tests define the `bidVideo` response component but do not actually load it, so they validate `hb_pb_cat_dur` values that are different from what PBS would generate. The difference is that PBS adds `_30s` when that duration is given in `BidVideo`, but the tests use `_0s`.
This change updates `bidderBid` definition so `bidVideo` is deserialized into the mock response as `BidVideo`.
It also updates the json tests with the correct value for `hb_pb_cat_dur`. Alternatively, we could preserve the current values and remove BidVideo from the tests that don't need it.
A solution to the same issue in adapter tests was proposed in #3835 
I am not sure why `BidVideo` is still necessary though. `Bid.Cat[0]` and `Bid.Dur` are available to be passed back in the Bid response, so the …

Update exchange json tests with correct hb_pb_cat_dur 

---

adapters/adtonos/adtonos.go
adapters/adtonos/adtonos_test.go
adapters/adtonos/adtonostest/exemplary/simple-audio-with-mtype.json
adapters/adtonos/adtonostest/exemplary/simple-audio.json
adapters/adtonos/adtonostest/exemplary/simple-video.json
adapters/adtonos/adtonostest/supplemental/wrong-impression-mapping.json
adapters/adtonos/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_adtonos.go
static/bidder-info/adtonos.yaml
static/bidder-params/adtonos.json

Hi! Meet AdTonos, an audio ad exchange and Prebid member :wave: 
Docs: https://github.com/prebid/prebid.github.io/pull/5543

New Adapter: AdTonos

---

adapters/lemmadigital/lemmadigital_test.go
adapters/lemmadigital/lemmadigitaltest/exemplary/banner.json
adapters/lemmadigital/lemmadigitaltest/exemplary/multi-imp.json
adapters/lemmadigital/lemmadigitaltest/exemplary/video.json
adapters/lemmadigital/lemmadigitaltest/supplemental/empty-seatbid-array.json
adapters/lemmadigital/lemmadigitaltest/supplemental/invalid-response.json
adapters/lemmadigital/lemmadigitaltest/supplemental/status-code-bad-request.json
adapters/lemmadigital/lemmadigitaltest/supplemental/status-code-no-content.json
adapters/lemmadigital/lemmadigitaltest/supplemental/status-code-other-error.json
static/bidder-info/lemmadigital.yaml

Related PR: https://github.com/prebid/prebid-server/pull/3750
One of them should be merged.

LemmaDigital: change endpoint

---

adapters/connectad/connectad.go
openrtb_ext/imp_connectad.go

fix to support string and int values as SiteID/NetworkID

ConnectAd: String/int fix

---

adapters/rubicon/rubicon.go
adapters/rubicon/rubicon_test.go
adapters/rubicon/rubicontest/exemplary/25-26-transition-period.json
adapters/rubicon/rubicontest/exemplary/app-imp-fpd.json
adapters/rubicon/rubicontest/exemplary/bidonmultiformat.json
adapters/rubicon/rubicontest/exemplary/flexible-schema.json
adapters/rubicon/rubicontest/exemplary/hardcode-secure.json
adapters/rubicon/rubicontest/exemplary/non-bidonmultiformat.json
adapters/rubicon/rubicontest/exemplary/simple-banner.json
adapters/rubicon/rubicontest/exemplary/simple-native.json
adapters/rubicon/rubicontest/exemplary/simple-video.json
adapters/rubicon/rubicontest/exemplary/site-imp-fpd.json
adapters/rubicon/rubicontest/exemplary/user-fpd.json
adapters/rubicon/rubicontest/supplemental/no-site-content-data.json
adapters/rubicon/rubicontest/supplemental/no-site-content.json

Changes from https://github.com/prebid/prebid-server-java/pull/3377

Rubicon: Pass PBS host info to XAPI

---

exchange/utils.go

This is the second `CleanOpenRTBRequests` refactoring step in preparation for ORTB2.6 support. We should merge #3957 first and then I will rebase this off master as it contains the logic in that first refactor PR.
The bidder-agnostic privacy initialization logic can be moved up before the two bidder-specific loops that iterate over `impsByBidder` and `allBidderRequests`. The two loops will be consolidated in a future PR.

Refactor: Move privacy init up

---

static/bidder-info/yieldmo.yaml

Updating Yieldmo's yaml file to indicate that we support ortb 2.6

Yieldmo: Indicate support for ORTB 2.6

---

adapters/rtbhouse/rtbhouse.go
adapters/rtbhouse/rtbhousetest/exemplary/banner-resolve-macros.json

The adapter is now able to resolve OpenRTB macro: `${AUCTION_PRICE}`
PBS-Java counterpart PR: https://github.com/prebid/prebid-server-java/pull/3421
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTB House: Resolve AUCTION_PRICE macro

---

endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-ccpa-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-legacy-tcf2-consent-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-tcf1-consent-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-tcf2-consent-through-query.json
exchange/exchangetest/ccpa-featureflag-on.json
exchange/utils.go
exchange/utils_test.go
openrtb_ext/request_wrapper.go
openrtb_ext/request_wrapper_test.go

This PR does the following:
- temporarily removes the 2.5 down convert logic
- pushes the request wrapper down into `buildRequestExtForBidder`, `applyBidAdjustmentToFloor`, `applyPrivacy`, `removeImpsWithStoredResponses`
- pushes the wrapper's bid request instead of a copy of the wrapper's bid request down into remaining functions in the `CleanOpenRTBRequests` loop (which will eventually be updated to receive the wrapper instead in future PRs)
~~- always makes modifications to the imps of a bidder's request wrapper copy using the imp wrapper~~
- fixed imp wrapper bug so that the request wrapper bid request imps point to the same object as the imp wrapper imps when calling the request wrapper `RebuildRequest` function
- makes the test suite pass

ORTB 2.6: Temporarily remove down convert and make test suite pass

---

.devcontainer/devcontainer.json
README.md

In the [README](https://github.com/prebid/prebid-server/blob/v2.31.0/README.md?plain=1#L47), it is written that:
> Prebid Server requires Go version 1.21 or newer.
However, in the [Dev Containers configuration](https://github.com/prebid/prebid-server/blob/v2.31.0/.devcontainer/devcontainer.json#L9), Go 1.20 is configured:
> 			"VARIANT": "1.20",
A natural consequence of that is the following compile error is obtained when one opens the project with Dev Containers with Visual Studio Code (tested with VS Code 1.93.1):
> could not import maps (no required module provides package "maps") compiler BrokenImport
The package "maps" does not exist in Go 1.20. See https://pkg.go.dev/maps?tab=versions
If there is a table with nothing on it and you ask someone to eat the apple that is on the table, …

Bump Go version to 1.22 in dev containers config

---

sample/001_banner/pbjs.html

There is a bug on sample html page:
```
prebid.js:12 
Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
at U (prebid.js:12:9881)
at $.processQueue (prebid.js:12:99684)
at prebid.js:631:11
```
This is caused by `appendChild()` method call (inside pbjs) on a DOM element that doesn't exist yet .
This can be fixed by simply by deferring javascript scripts loading, and that is what i did in this pr.

Sample: fix prebid js loading bug on sample html page

---

endpoints/openrtb2/amp_auction_test.go
endpoints/openrtb2/auction_test.go
endpoints/openrtb2/sample-requests/amp/valid-supplementary/ortb-2.5-to-2.6-upconvert.json
endpoints/openrtb2/sample-requests/valid-whole/exemplary/ortb-2.5-to-2.6-upconvert.json
endpoints/openrtb2/sample-requests/valid-whole/exemplary/ortb-2.6-to-2.5-downconvert.json
endpoints/openrtb2/test_utils.go
exchange/bidder.go
exchange/bidder_test.go

…and allows specifying bidder ortb version

ORTB 2.6: Endpoint JSON test framework captures mock bidder requests

---

endpoints/cookie_sync.go
endpoints/cookie_sync_test.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/prometheus/prometheus_test.go
usersync/chooser.go
usersync/chooser_test.go

This PR updates a debug message that can be returned during the cookie sync choose process, where we determine which bidders will be synced, and if any bidder is rejected, we log a debug message in debug mode.
We're updating the debug message "Type Not Supported", to be "Rejected by Filter", to match the naming convention in java
This message is trigged by `syncTypeFilter` which is on the request, and it specifies which sync types a bidder is allowed to use. 
If the syncer doesn't support the sync type for that bidder, we then return this debug message.
Overall, this message is being updated to match Java.

Update Cookie Sync Chooser Debug Message to match Java

---

endpoints/cookie_sync.go
endpoints/cookie_sync_test.go

Addresses #3537
The limit code was refactored with the following notable changes:
- zero cannot be used as the default value for limits since it means use max and we need to detect presence so the limits were changed to pointers
- if no limit is specified, a 32 bit max int is used as the limit
The logic should match PBS-Java behavior as described in the linked issue.

Cookie Sync: Use max when limit is 0

---

endpoints/openrtb2/sample-requests/valid-whole/exemplary/user-ext-prebid-buyeruids.json
exchange/utils.go
exchange/utils_test.go

A problem was introduced in v3.0.0 where `user.ext.prebid.buyeruids` are not being scrubbed for bidder requests containing at least one `user` field that needs to be converted down to its 2.5 location. For example, if the incoming request contains either `user.consent` or `user.ext.consent` and some bidder only supports ORTB 2.5 (no explicit 2.6 support declaration in their YAML), the buyeruids are not scrubbed.

Fix: Delete user.ext.prebid.buyeruids after extraction

---

stored_requests/events/database/database.go

There are redundant conversions to interval in milliseconds which duplicates the same in initialization of the config.
https://github.com/prebid/prebid-server/blob/df58baff01da6946cd7f075a10790cd1c52ea1f0/stored_requests/config/config.go#L208
https://github.com/prebid/prebid-server/blob/df58baff01da6946cd7f075a10790cd1c52ea1f0/stored_requests/config/config.go#L210

Fix cache init and update timeouts in stored requests

---

hooks/hookexecution/executor.go
hooks/hookexecution/mocks_test.go
hooks/hookstage/rawbidderresponse.go
hooks/hookstage/rawbidderresponse_mutations.go
modules/prebid/ortb2blocking/hook_raw_bidder_response.go
modules/prebid/ortb2blocking/module_test.go

Currently, there is no way to determine the currency of the bids returned in the bidder-response during the raw_bidder_response_stage.
There are several use cases where it is important to know the currency of the bidder-response at this stage.
This PR addresses the issue by introducing the bidder-response itself, rather than just bidder-response.Bids, at this stage.

Modules: Add bidder response to raw bidder response stage payload

---

static/bidder-info/sharethrough.yaml

This work just involves updating our config file (`sharethrough.yaml`) to indicate that our exchange has support for oRTB 2.6-compliant bid requests.

Sharethrough: Declare support for OpenRTB 2.6

---

static/bidder-info/adf.yaml
static/bidder-info/adform.yaml

Adform migrates cookie matching to new domain - c1.adform.net
The current one will still be available for some time.

Adf: Update cookie matching endpoint domain

---

static/bidder-info/rxnetwork.yaml

Added alias for partner network to resolve an issue with multiple connected networks via same adkernel bidder.

Adkernel: rxnetwork alias

---

adapters/conversant/conversant.go
adapters/conversant/conversanttest/exemplary/simple_audio_app.json
adapters/conversant/conversanttest/exemplary/simple_audio_site.json
static/bidder-info/conversant.yaml

Update yaml file to allow audio media type requests

Conversant: Enable audio requests

---

adapters/adnuntius/adnuntius.go
adapters/adnuntius/adnuntiustest/exemplary/simple-banner.json
adapters/adnuntius/adnuntiustest/supplemental/check-dealId.json
adapters/adnuntius/adnuntiustest/supplemental/check-dsa-advertiser-legalName-omitted.json
adapters/adnuntius/adnuntiustest/supplemental/check-dsa-advertiser-legalName.json
adapters/adnuntius/adnuntiustest/supplemental/check-dsa-advertiser-omitted.json
adapters/adnuntius/adnuntiustest/supplemental/check-gdpr.json
adapters/adnuntius/adnuntiustest/supplemental/check-gross-bids.json
adapters/adnuntius/adnuntiustest/supplemental/check-net-bids.json
adapters/adnuntius/adnuntiustest/supplemental/check-noCookies-parameter.json
adapters/adnuntius/adnuntiustest/supplemental/check-noCookies.json
adapters/adnuntius/adnuntiustest/supplemental/check-order-multi-imp.json
adapters/adnuntius/adnuntiustest/supplemental/check-userId.json
adapters/adnuntius/adnuntiustest/supplemental/empty-regs-ext.json
adapters/adnuntius/adnuntiustest/supplemental/empty-regs.json
adapters/adnuntius/adnuntiustest/supplemental/height-error.json
adapters/adnuntius/adnuntiustest/supplemental/max-deals-test.json
adapters/adnuntius/adnuntiustest/supplemental/send-header-information.json
adapters/adnuntius/adnuntiustest/supplemental/site-ext.json
adapters/adnuntius/adnuntiustest/supplemental/size-check.json
adapters/adnuntius/adnuntiustest/supplemental/status-400.json
adapters/adnuntius/adnuntiustest/supplemental/test-networks.json
adapters/adnuntius/adnuntiustest/supplemental/user-ext.json
adapters/adnuntius/adnuntiustest/supplemental/width-error.json

Instead of `format=json`, use `format=prebidServer` in adserver requests.

Adnuntius: Use format=prebidServer on adserver requests

---

adapters/metax/metax.go
adapters/metax/metax_test.go
adapters/metax/metaxtest/exemplary/simple-app-video.json

Add duration and category data to TypedBid

MetaX: Add BidVideo for video ads

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatic_test.go
adapters/pubmatic/pubmatictest/exemplary/banner.json
adapters/pubmatic/pubmatictest/exemplary/fledge.json
adapters/pubmatic/pubmatictest/exemplary/native.json
adapters/pubmatic/pubmatictest/exemplary/video.json
adapters/pubmatic/pubmatictest/supplemental/app.json
adapters/pubmatic/pubmatictest/supplemental/dctrAndPmZoneID.json
adapters/pubmatic/pubmatictest/supplemental/extra-bid.json
adapters/pubmatic/pubmatictest/supplemental/gptSlotNameInImpExt.json
adapters/pubmatic/pubmatictest/supplemental/gptSlotNameInImpExtPbAdslot.json
adapters/pubmatic/pubmatictest/supplemental/impExt.json
adapters/pubmatic/pubmatictest/supplemental/invalidparam.json
adapters/pubmatic/pubmatictest/supplemental/multiplemedia.json
adapters/pubmatic/pubmatictest/supplemental/native_invalid_adm.json
adapters/pubmatic/pubmatictest/supplemental/nilReqExt.json
adapters/pubmatic/pubmatictest/supplemental/noAdSlot.json
adapters/pubmatic/pubmatictest/supplemental/pmZoneIDInKeywords.json
adapters/pubmatic/pubmatictest/supplemental/reqBidderParams.json
adapters/pubmatic/pubmatictest/supplemental/trimPublisherID.json

Hi Team,
The PubMatic Adapter is currently not utilizing the `req.ext.prebid` object from the backend. As this parameter is not being used, we can safely skip passing it in the PubMatic Adapter requests.
To address this, I am raising a PR to remove the `req.ext.prebid` parameter from PubMatic requests.
Let me know if you have any concerns or require further input.

PubMatic: Remove req.ext.prebid from bid requests

---

adapters/pubmatic/pubmatictest/supplemental/displayManagerInAppExt.json
adapters/pubmatic/pubmatictest/supplemental/displayManagerInAppExtPrebid.json

Fixes tests introduced in #4000 that were not updated in accordance with #4092.

PubMatic: Remove empty prebid object from failing tests

---

.github/workflows/slack-stale-pr.yml
.github/workflows/slack_stale_pr.yml

This has been tested over in the sourcecred repo.
The goal is to slack a summary of stale PRs to the #prebid-server-dev channel once/week.

Adding stale PR workflow

---

adapters/smarthub/smarthub_test.go
adapters/smarthub/smarthubtest/exemplary/banner.json
adapters/smarthub/smarthubtest/exemplary/native.json
adapters/smarthub/smarthubtest/exemplary/video.json
adapters/smarthub/smarthubtest/supplemental/bad-response.json
adapters/smarthub/smarthubtest/supplemental/empty-seatbid-0-bid.json
adapters/smarthub/smarthubtest/supplemental/empty-seatbid.json
adapters/smarthub/smarthubtest/supplemental/status-204.json
adapters/smarthub/smarthubtest/supplemental/status-400.json
adapters/smarthub/smarthubtest/supplemental/status-503.json
adapters/smarthub/smarthubtest/supplemental/unexpected-status.json
adapters/smarthub/smarthubtest/supplemental/wrong-bidtype.json
static/bidder-info/felixads.yaml
static/bidder-info/jdpmedia.yaml
static/bidder-info/markapp.yaml
static/bidder-info/smarthub.yaml
static/bidder-info/tredio.yaml
static/bidder-info/vimayx.yaml
static/bidder-params/smarthub.json

We change adapter name from Smarthub to Attekmi,
changing endpoints but keep biddercode 'smarthub'
Docs PR https://github.com/prebid/prebid.github.io/pull/5699

Smarthub: Update to Attekmi Endpoint

---

.devcontainer/devcontainer.json
.github/workflows/adapter-code-coverage.yml
.github/workflows/validate-merge.yml
.github/workflows/validate.yml
Dockerfile
README.md
go.mod

Updates the main build from 1.22 to 1.23. Upgrades the minimum feature set from 1.21 to 1.22.

Upgrade to Go 1.23

---

adapters/rubicon/rubicontest/exemplary/segtax-attributes.json

#3919 was merged a few weeks ago which removed logic that copies `pagecat` to `imp[].ext.rp.target`. Then #3915 was merged which added a new test that expected `imp[].ext.rp.target.pagecat` to exist. This PR rectifies this by removing the new test expectation.

Fix: Rubicon segtax test

---

adapters/kueezrtb/kueezrtb.go
adapters/kueezrtb/kueezrtb_test.go
adapters/kueezrtb/kueezrtbtest/exemplary/banner.json
adapters/kueezrtb/kueezrtbtest/exemplary/multi-imp.json
adapters/kueezrtb/kueezrtbtest/exemplary/video.json
adapters/kueezrtb/kueezrtbtest/supplemental/bad-request.json
adapters/kueezrtb/kueezrtbtest/supplemental/internal-error.json
adapters/kueezrtb/kueezrtbtest/supplemental/no-content.json
adapters/kueezrtb/kueezrtbtest/supplemental/unknown-bid-type.json
adapters/kueezrtb/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_kueezrtb.go
static/bidder-info/kueezrtb.yaml
static/bidder-params/kueezrtb.json

https://github.com/prebid/prebid.github.io/pull/5814

New Adapter: Kueez

---

adapters/rubicon/rubicontest/exemplary/segtax-attributes.json

This reverts commit 02048f2062c539a94b7123c470ea917d33ec4147.
This is the first of two Rubicon segtax related reverts.
The segtax behavior is unpredictable and is suspected to be attributed to the use of an unmaintained library that was introduced as part of this effort.

Revert "Fix: Rubicon segtax test (#4143)"

---

adapters/cwire/cwiretest/exemplary/app-imp-ext.json
adapters/cwire/cwiretest/exemplary/app.json
adapters/cwire/params_test.go
openrtb_ext/imp_cwire.go
static/bidder-info/cwire.yaml
static/bidder-params/cwire.json

This updates the CWire adapter:
1. adds 'domainId'
2. adds the 'app' capability.
The docs are already updated since we did the analogous change for Prebid.js.

CWire: Add domainId param and app capability

---

adapters/yieldlab/yieldlab.go
adapters/yieldlab/yieldlabtest/exemplary/dsa.json
adapters/yieldlab/yieldlabtest/exemplary/gdpr.json
adapters/yieldlab/yieldlabtest/supplemental/dsa_empty.json
adapters/yieldlab/yieldlabtest/supplemental/dsa_empty_transparency.json

consent should be forwarded under the param gdpr_consent to Yieldlab bidder
A review and approval from a member of the Yieldlab team are required. (@brushmate, @flanaras, @nkloeber or @william-harris)

Yieldlab: Forward consent under param gdpr_consent

---

.github/workflows/code-path-changes.yml
.github/workflows/scripts/codepath-notification
.github/workflows/scripts/send-notification-on-change.js

Closes https://github.com/prebid/prebid-server/issues/4075
This is a port of the PR that was merged in the PBS-Java repo https://github.com/prebid/prebid-server-java/pull/3645
the goal is to let bidders/modules register an email address so that when a PR is opened that affects one of their files, they're at least aware of it.

Add codepath alerts

---

sample/README.md

Adding a note to the README file for the "sample" directory to alert readers that it might, depending upon their system setup, be necessary to invoke `docker compose` rather than `docker-compose` when running the examples.

Docker example updates

---

.github/workflows/code-path-changes.yml

turns out that github won't send environmental secrets for the 'pull_request' action, but it will on 'pull_request_target'.
Sorry, didn't know this for the first round. 
Tested in the sourcecred repo.

Update code-path-changes workflow

---

adapters/aduptech/aduptech.go
adapters/aduptech/aduptech_test.go
adapters/aduptech/aduptechtest/exemplary/simple-banner-convert-currency-intermediate.json
adapters/aduptech/aduptechtest/exemplary/simple-banner-convert-currency.json
adapters/aduptech/aduptechtest/exemplary/simple-banner-full-params.json
adapters/aduptech/aduptechtest/exemplary/simple-banner.json
adapters/aduptech/aduptechtest/exemplary/simple-native.json
adapters/aduptech/aduptechtest/supplemental/broken-response.json
adapters/aduptech/aduptechtest/supplemental/currency-conversion-failure.json
adapters/aduptech/aduptechtest/supplemental/currency-conversion-intermediate-failure.json
adapters/aduptech/aduptechtest/supplemental/currency-conversion-invalid-currency.json
adapters/aduptech/aduptechtest/supplemental/status-204.json
adapters/aduptech/aduptechtest/supplemental/status-400.json
adapters/aduptech/aduptechtest/supplemental/status-500.json
adapters/aduptech/aduptechtest/supplemental/unsupported-mtype.json
adapters/aduptech/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_aduptech.go
static/bidder-info/aduptech.yaml
static/bidder-params/aduptech.json

Hello,
We as AdUp Technology want to add our own Prebid Server Adapter.
We already have a PrebidJS Adapter.
Docs: https://github.com/prebid/prebid.github.io/pull/5728

New Adapter: AdUp Tech

---

static/bidder-info/152media.yaml

Alias for partner network to resolve an issue with multiple connected networks via same adkernel bidder.
https://github.com/prebid/prebid.github.io/pull/5835

New Adapter: 152 Media - Adkernel alias

---

util/jsonutil/jsonutil.go

Add JSON RawMessage alias, vars to consts and fix godoc comments

---

adapters/connatix/connatix.go
adapters/connatix/connatixtest/supplemental/success-build-display-manager-version.json
adapters/connatix/models.go
openrtb_ext/imp_connatix.go
static/bidder-params/connatix.json

Add ViewabilityPercentage for connatix adaptor

Connatix: Add viewability field

---

static/bidder-info/sspBC.yaml

Hi. This PR updates the current SSPBC endpoint to a new one.

sspBC: Endpoint update

---

.github/workflows/code-path-changes.yml

The PBS-Java team did some research and found that there are some potential vulnerabilities with pull_request_trigger workflows that allow GITHUB_TOKEN writes. This update limits this action to read activities.

Tighten security on code-path-changes workflow

---

adservertargeting/requestlookup.go
adservertargeting/respdataprocessor.go
adservertargeting/utils.go
go.mod
modules/fiftyonedegrees/devicedetection/config.go
modules/fiftyonedegrees/devicedetection/device_detector.go
modules/fiftyonedegrees/devicedetection/device_info_extractor.go
modules/fiftyonedegrees/devicedetection/evidence_extractor.go
modules/fiftyonedegrees/devicedetection/module.go

github.com/pkg/errors is obsolete. https://pkg.go.dev/fmt#Errorf supports `%w` for wrapped errors

Remove deprecated github.com/pkg/errors

---

config/account.go
exchange/exchange.go
exchange/exchange_test.go
exchange/exchangetest/gdpr-geo-eu-on-with-account-eea-countries.json
exchange/gdpr.go
exchange/gdpr_test.go

EEA countries account-level override

---

static/bidder-info/rtbhouse.yaml

Declaring support for Open RTB 2.6
Ported from PBS-Java: https://github.com/prebid/prebid-server-java/pull/3755
Our bidder support Open RTB 2.6 requests.
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTB House: Declare OpenRTB 2.6 support

---

.devcontainer/devcontainer.json
.github/workflows/adapter-code-coverage.yml
.github/workflows/validate-merge.yml
.github/workflows/validate.yml
Dockerfile
README.md
go.mod

Updates the main build from 1.23 to 1.24. Upgrades the minimum feature set from 1.22 to 1.23.

Upgrade to Go 1.24

---

adapters/seedtag/params_test.go
adapters/seedtag/seedtag.go
adapters/seedtag/seedtag_test.go
adapters/seedtag/seedtagtest/exemplary/banner.json
adapters/seedtag/seedtagtest/exemplary/bidfloor_converted.json
adapters/seedtag/seedtagtest/exemplary/video.json
adapters/seedtag/seedtagtest/supplemental/invalid_bidfloor_conversion.json
adapters/seedtag/seedtagtest/supplemental/invalid_mtype.json
adapters/seedtag/seedtagtest/supplemental/response_unmarshal_error.json
adapters/seedtag/seedtagtest/supplemental/status_bad_request.json
adapters/seedtag/seedtagtest/supplemental/status_no_content.json
adapters/seedtag/seedtagtest/supplemental/status_not_ok.json
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_seedtag.go
static/bidder-info/seedtag.yaml
static/bidder-params/seedtag.json

documentation PR - https://github.com/prebid/prebid.github.io/pull/5866

New Adapter: Seedtag

---

currency/aggregate_conversions_test.go
currency/rates.go
currency/rates_test.go

https://github.com/prebid/prebid-server/issues/3566
The Prebid.js currency module is able to cross convert currencies using USD (or GBP) as a common currency reference. This feature is not currently implemented in PBS Go, so the following error exists:
`Unable to convert from currency NOK to desired ad server currency SEK`.
In this PR we implement the common currency reference conversion logic (`FindIntermediateConversionRate` method) in the `currency` package.
[Related change in PBS Java](https://github.com/prebid/prebid-server-java/pull/3084)
New functionality is covered by `TestGetRate_FindIntermediateConversionRate` unit test in `currency/rates_test.go`.

Currency: Common currency reference conversion

---

static/bidder-info/smilewanted.yaml

In order to improve the security and compliance of our communications, we request that Prebid Server be updated to use HTTPS by default.

Smilewanted: change endpoint to HTTPS

---

adapters/openx/openx.go
adapters/openx/openxtest/exemplary/fledge.json
adapters/openx/openxtest/exemplary/simple-banner.json
adapters/openx/openxtest/exemplary/simple-native.json
adapters/openx/openxtest/exemplary/simple-video.json
adapters/openx/openxtest/exemplary/video-rewarded.json
adapters/openx/openxtest/supplemental/missing-mtype.json

OpenX started to return mtype field for bids in bid response, so now bid type can be determined based on this property in OpenX bidder adapter.
We want to determine bid type based on bid mtype from bid response, to be able to process multi-format requests.

OpenX: Determine bid type from bid.mtype

---

.devcontainer/Dockerfile
Dockerfile

Local Trivy run suggested to add next fixes: 
```
AVD-DS-0002 (HIGH): Specify at least 1 USER command in Dockerfile with non-root user as argument
════════════════════════════════════════════════════════════
Running containers with 'root' user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a 'USER' statement to the Dockerfile.
```
And 
```
AVD-DS-0029 (HIGH): '--no-install-recommends' flag is missed: 'apt-get update &&     apt-get -y upgrade &&     apt-get install -y wget'
════════════════════════════════════════════════════════════
'apt-get' install should use '--no-install-recommends' to minimize image size.
```
For all `apt-get` commands. 
This PR solves these warnings.

Dockerfile vulnerabilities fixes

---

.github/workflows/release.yml
.github/workflows/security.yml
.github/workflows/validate-merge.yml
.github/workflows/validate.yml

Run security, validate and release jobs on ubuntu-latest

Run actions workflow jobs on ubuntu-latest

---

adapters/madsense/madsense.go
adapters/madsense/madsense_test.go
adapters/madsense/madsensetest/exemplary/banner-app.json
adapters/madsense/madsensetest/exemplary/banner-web.json
adapters/madsense/madsensetest/exemplary/mixed-imp-types.json
adapters/madsense/madsensetest/exemplary/video-app.json
adapters/madsense/madsensetest/exemplary/video-web-pod.json
adapters/madsense/madsensetest/exemplary/video-web.json
adapters/madsense/madsensetest/supplemental/bad-request-example.json
adapters/madsense/madsensetest/supplemental/bad-request-imp-ext-bidder.json
adapters/madsense/madsensetest/supplemental/bad-request-imp-ext.json
adapters/madsense/madsensetest/supplemental/bad-response-error.json
adapters/madsense/madsensetest/supplemental/bad-response-mtype.json
adapters/madsense/madsensetest/supplemental/bad-response-status-400.json
adapters/madsense/madsensetest/supplemental/bad-response-status-500.json
adapters/madsense/madsensetest/supplemental/no-content-response.json
adapters/madsense/madsensetest/supplemental/test-response.json
adapters/madsense/params_test.go
adapters/madsense/utils.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_madsense.go
static/bidder-info/madsense.yaml
static/bidder-params/madsense.json

doc - https://github.com/prebid/prebid.github.io/pull/5824

New Adapter: MadSense

---

static/bidder-info/adtg_org.yaml
static/bidder-info/embimedia.yaml

https://github.com/prebid/prebid.github.io/pull/5880

New Adapter: AdTarget.org - Limelight Alias

---

.github/workflows/scripts/codepath-notification

Changed the email in codepath-notification from prebid-support@media.net to prebid@media.net

Medianet: Update codepath-notification email

---

adapters/appnexus/appnexus_test.go
modules/prebid/rulesengine/cache_entry.go
modules/prebid/rulesengine/hook_processed_auction.go
modules/prebid/rulesengine/hook_processed_auction_test.go
modules/prebid/rulesengine/module.go
modules/prebid/rulesengine/tree_manager.go
modules/prebid/rulesengine/tree_test.go
util/randomutil/randomutil.go

- Select model group based on weights
- Adds enabled flag to cache entry, and if false, rule sets are not processed 
- Delete cache entry if account has disabled the module

Rules Engine Module: Select model group based on weights

---

modules/modules.go
modules/modules_test.go
modules/prebid/rulesengine/module.go
modules/prebid/rulesengine/tree_builder_test.go
modules/prebid/rulesengine/tree_manager.go
modules/prebid/rulesengine/tree_test.go
modules/shutdown.go
modules/shutdown_test.go
router/router.go
rules/schema_functions_test.go

- Use glog directly in tree manager to log validation errors. The tree manager runs outside of the request flow via a go routine spawned at startup during the module build process. In the future we will pass a global logger object that implements the logger interface as a module dependency at startup instead. All logging via hooks takes place by adding warnings, errors and debug messages to the hook result which is then sent to the logger by the modularity infrastructure. This option is not available because there are no hook results outside of the request flow.
- Updated the modularity infrastructure so modules that need to shutdown go routines they spawn may be able to do so. This was accomplished by adding a `Shutdowner` interface to the modularity infrastructure with a single function …

Rules Engine Module: log validation errors, graceful tree mgr shutdown

---

adapters/optidigital/optidigital.go
adapters/optidigital/optidigital_test.go
adapters/optidigital/optidigitaltest/exemplary/banner.json
adapters/optidigital/optidigitaltest/supplemental/bad_request.json
adapters/optidigital/optidigitaltest/supplemental/bad_response.json
adapters/optidigital/optidigitaltest/supplemental/no_response.json
adapters/optidigital/optidigitaltest/supplemental/other_error.json
adapters/optidigital/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_optidigital.go
static/bidder-info/optidigital.yaml
static/bidder-params/optidigital.json

This PR introduces the Optidigital bidder adapter for Prebid Server.
Related PR: https://github.com/prebid/prebid.github.io/pull/5976
Maintainer Contact: [prebid@optidigital.com](mailto:prebid@optidigital.com)

New Adapter: Optidigital

---

static/bidder-info/sharethrough.yaml

Adding a `geoscope` entry to the Sharethrough PBS adapter's YAML file.

Sharethrough: Add geoscope to config

---

static/bidder-info/ttd.yaml

Prebid.js has uses `ttd` as bidder code. Adding a alias to allow this seamless lookup.

New Adapter: ttd - TheTradeDesk alias

---

static/bidder-info/dianomi.yaml

Hi,
We spotted an error in our prebid adapter default config, we really expect gdpr_consent as standard rather than consent.

Dianomi: Update user syncs to send gdpr_consent

---

modules/prebid/rulesengine/config/config.go
modules/prebid/rulesengine/config/config_test.go

We can accept empty `modelgroups[i].schema`, `modelgroups[i].rules`, and `modelgroups[i].rules[j].conditions`, but a valid tree must get built with an equal number of `modelgroups[i].schemas` and `modelgroups[i].rules[j].conditions`, which implies that, if there are any `modelgroups[i].schemas`, we must have at least one `modelgroups[i].rules` entry to consider an input to be valid.  This pull request closes a loophole in `validateRuleSet(r *RuleSet)` that was allowing us to pass as valid a `modelgroup` with `modelgroups[i].schemas` but zero entries in `modelgroups[i].rules` and viceversa.

Rules Engine Module: Fix validateRuleSet bug

---

adapters/seedtag/seedtag.go
adapters/seedtag/seedtagtest/exemplary/banner.json
adapters/seedtag/seedtagtest/exemplary/bidfloor_converted.json
adapters/seedtag/seedtagtest/exemplary/video.json

We were missing to add the required content-type headers to request Seedtag server-to-server endpoint. This situation lead to unparsed body payloads for the first integrations.

Seedtag: Fix required content-type header on http calls

---

adapters/kobler/kobler.go
adapters/kobler/koblertest/supplemental/user-data-is-removed.json
adapters/kobler/koblertest/supplemental/user-ip-is-removed.json

Small change to the Kobler adapter to remove any sensitive data from the requests

Kobler: Remove sensitive device and user data

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatic_test.go
adapters/pubmatic/pubmatictest/exemplary/banner.json
adapters/pubmatic/pubmatictest/exemplary/fledge.json
adapters/pubmatic/pubmatictest/exemplary/native.json
adapters/pubmatic/pubmatictest/exemplary/video.json
adapters/pubmatic/pubmatictest/supplemental/app.json
adapters/pubmatic/pubmatictest/supplemental/bid_ext_ibv_true.json
adapters/pubmatic/pubmatictest/supplemental/dctrAndPmZoneID.json
adapters/pubmatic/pubmatictest/supplemental/displayManagerInAppExt.json
adapters/pubmatic/pubmatictest/supplemental/displayManagerInAppExtPrebid.json
adapters/pubmatic/pubmatictest/supplemental/extra-bid.json
adapters/pubmatic/pubmatictest/supplemental/gptSlotNameInImpExt.json
adapters/pubmatic/pubmatictest/supplemental/gptSlotNameInImpExtPbAdslot.json
adapters/pubmatic/pubmatictest/supplemental/impExt.json
adapters/pubmatic/pubmatictest/supplemental/multiplemedia.json
adapters/pubmatic/pubmatictest/supplemental/native_invalid_adm.json
adapters/pubmatic/pubmatictest/supplemental/nilReqExt.json
adapters/pubmatic/pubmatictest/supplemental/noAdSlot.json
adapters/pubmatic/pubmatictest/supplemental/pmZoneIDInKeywords.json
adapters/pubmatic/pubmatictest/supplemental/reqBidderParams.json
adapters/pubmatic/pubmatictest/supplemental/trimPublisherID.json

This PR restores the `bid.ext.prebid.type` field in the PubMatic response, which was unintentionally removed in the previous [PR](https://github.com/prebid/prebid-server/pull/4189).

PubMatic: Fix missing bid type in bid response

---

config/config.go
config/config_test.go
endpoints/openrtb2/amp_auction.go
endpoints/openrtb2/auction.go
endpoints/openrtb2/video_auction.go
go.mod
ortb/default.go
ortb/default_test.go

TMax default is currently set via the default stored request. This PR provides the option to set the default on the host config. This can be beneficial to host companies that do not use the default stored request for other purposes but still want to set a default tmax since there is a performance hit associated with using the default stored request.

TMax: Add default host config

---

adapters/rtbhouse/rtbhouse.go
adapters/rtbhouse/rtbhousetest/exemplary/simple-banner-paapi.json

As part of our ongoing efforts to prioritize development resources and align with current strategic goals, we have decided to pause further development for PAAPI requests.
This decision does not reflect a lack of interest or commitment to the feature, but rather a temporary shift in focus. PAAPI support is being parked at this time, and while it will no longer receive updates or enhancements in the near term, we remain open to revisiting it as priorities evolve.
This PR modifies the bid request by removing the following keys from `imp[].ext`: `ae`, `igs`, `paapi`
Related PRs: https://github.com/prebid/Prebid.js/pull/13214 and https://github.com/prebid/prebid.github.io/pull/6078
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with …

RTB House: Remove PAAPI signals from imp[].ext

---

adapters/adagio/adagiotest/exemplary/banner-web.json
adapters/adagio/adagiotest/exemplary/multi-formats-app.json
adapters/adagio/adagiotest/exemplary/multi-formats-web.json
adapters/adagio/adagiotest/exemplary/multi-imps-app.json
adapters/adagio/adagiotest/exemplary/multi-imps-web.json
adapters/adagio/adagiotest/exemplary/native-web.json
adapters/adagio/adagiotest/exemplary/request-with-rtd-module.json
adapters/adagio/adagiotest/exemplary/video-web.json
adapters/adagio/params_test.go
openrtb_ext/imp_adagio.go
static/bidder-info/adagio.yaml
static/bidder-params/adagio.json

[x] Updated bidder adapter
This PR introduces the core logic required for handling web inventory in our Prebid Server adapter. Although the functionality is in place, web inventory is **disabled by default** (this is intentional). We’ll assist our alpha partners in configuring their `adagio.yaml` files to enable it.

Adagio: Add site bidder param and web inventory tests

---

hooks/hookexecution/execution.go
hooks/hookstage/invocation.go

[Fixes #4035] Add the hook.Code to the ModuleInvocationContext.

Modularity: Add hook code to module invocation context

---

adapters/thetradedesk/thetradedesk.go
adapters/thetradedesk/thetradedesk_test.go
adapters/thetradedesk/thetradedesktest/supplemental/auction-price-macro-replacement.json

https://github.com/prebid/prebid-server-java/pull/4081

TheTradeDesk: Resolve AUCTION_PRICE macro

---

config/config.go
errortypes/code.go
errortypes/errortypes.go
exchange/bidder.go
exchange/bidder_health_test.go
exchange/bidder_validate_bids.go
exchange/bidder_validate_bids_test.go
exchange/exchange_test.go
metrics/config/metrics.go
metrics/go_metrics.go
metrics/metrics.go
metrics/metrics_mock.go
metrics/prometheus/prometheus.go

This code will throttle requests to bidders that are experiencing issues to improve general prebid performance and give the bidder some breathing room to recover. If a bidder's health is poor, we will reject some fraction of requests to a bidder to preserve resources on both the PBS side and the bidder side. We always allow at least 10% of requests through, so we can quickly see signs of recovery.
Health is measured in two ways. Successfully returning a request (no network errors or timeouts, we are not considering HTTP status codes beyond explicit server error (<200 or 500+) in judging a successful request) are a sign of good health, errors are a sign of bad health. On top of this, spending a long time in the queue waiting for an HTTP connect to use is a sign of bad health. Waiting a …

Bidder throttling code to increase network stability.

---

endpoints/openrtb2/sample-requests/amp/consent-through-query/addtl-consent-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-ccpa-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-legacy-tcf2-consent-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-tcf1-consent-through-query.json
endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-tcf2-consent-through-query.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/aliased-buyeruids-case-insensitive.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/aliased-buyeruids.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/aliases.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/buyeruids-camel-case.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/buyeruids-case-insensitive.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/gdpr-no-consentstring.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/gdpr.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/imp-with-stored-resp.json
endpoints/openrtb2/sample-requests/amp/valid-supplementary/ortb-2.5-to-2.6-upconvert.json
endpoints/openrtb2/sample-requests/hooks/amp.json
endpoints/openrtb2/sample-requests/hooks/amp_bidder_reject.json
endpoints/openrtb2/sample-requests/hooks/amp_bidder_response_reject.json
exchange/exchange.go
exchange/exchange_test.go
exchange/targeting.go
exchange/targeting_test.go
openrtb_ext/bid.go

https://github.com/prebid/prebid-server/issues/3812
https://github.com/prebid/prebid-server/issues/3095
As per requirements stated in the above-mentioned issues, `hb_env` targeting attribute should be equal to `amp` in the targeting for AMP responses similar to what's done now setting `hb_env=mobile-app` for PBSDK requests.
New functionality is covered by `TestSetTargeting` unit test in `exchange/targeting_test.go`.

Request: Add hb_env=amp targeting to AMP responses

---

adapters/pubmatic/pubmatic.go
adapters/pubmatic/pubmatictest/supplemental/app.json
adapters/pubmatic/pubmatictest/supplemental/impExt.json

**Feature:** Pass `skadn` object in `imp.ext` to PubMatic SSP
**Summary:**
This PR updates the PubMatic bidder adapter in Prebid Server to forward the `imp.ext.skadn` object (if present in the incoming OpenRTB request) to the PubMatic SSP endpoint.
**Changes in this PR:**
- Updates PubMatic bidder code to support `imp.ext.skadn`
- Ensures the `skadn` object is passed as-is without alteration
- Maintains backward compatibility if skadn is absent
Adds unit tests:
- Validates skadn is passed when present
- Skadn object is excluded when missing

Pubmatic: Forward skadn object in bid request

---

adapters/smartadserver/smartadserver.go
adapters/smartadserver/smartadservertest/exemplary/multi-banner-programmatic-guaranteed.json
adapters/smartadserver/smartadservertest/exemplary/simple-banner-programmatic-guaranteed.json
openrtb_ext/imp_smartadserver.go

This PR updates the behavior of the SmartAdServer adapter.
The adapter now is able to send bidrequest to 2 different endpoints depending on the presence and value of `programmaticGuaranteed` key in the extension.
There is only 2 different endpoints, no more. We based our implementation on [this issue](https://github.com/prebid/prebid-server/issues/3538) to comply with your expectations.

Smartadserver: Add second endpoint for programmatic guaranteed

---

adapters/afront/afront.go
adapters/afront/afront_test.go
adapters/afront/afronttest/exemplary/banner-app.json
adapters/afront/afronttest/exemplary/banner-web.json
adapters/afront/afronttest/exemplary/default-host-param.json
adapters/afront/afronttest/exemplary/native-app.json
adapters/afront/afronttest/exemplary/native-web.json
adapters/afront/afronttest/exemplary/video-app.json
adapters/afront/afronttest/exemplary/video-web.json
adapters/afront/afronttest/supplemental/empty-seatbid-array.json
adapters/afront/afronttest/supplemental/invalid-afront-ext-object.json
adapters/afront/afronttest/supplemental/invalid-response.json
adapters/afront/afronttest/supplemental/status-code-bad-request.json
adapters/afront/afronttest/supplemental/status-code-no-content.json
adapters/afront/afronttest/supplemental/status-code-other-error.json
adapters/afront/afronttest/supplemental/status-code-service-unavailable.json
adapters/afront/params_test.go
exchange/adapter_builders.go
openrtb_ext/bidders.go
openrtb_ext/imp_afront.go
static/bidder-info/afront.yaml
static/bidder-params/afront.json

https://github.com/prebid/prebid.github.io/pull/6097

New Adapter: Afront

---

gdpr/gdpr.go
gdpr/gdpr_test.go
gdpr/impl.go
gdpr/impl_test.go
gdpr/vendorlist-fetching.go
gdpr/vendorlist-fetching_test.go
metrics/config/metrics.go
metrics/go_metrics.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/metrics_mock.go
metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go
router/router.go

```
pbs_sub_go_sync_mutex_wait_total_seconds_total 0.177076376
pbs_sub_go_threads 16
+ # HELP pbs_sub_gvl_list_requests Count number of times GVL list is fetched
+ # TYPE pbs_sub_gvl_list_requests counter
+ pbs_sub_gvl_list_requests 0
pbs_sub_impressions_requests{audio="false",banner="false",native="false",video="false"} 0
```

Metrics: Record GVL fetch count

---

exchange/bidder.go
exchange/bidder_test.go
metrics/config/metrics.go
metrics/go_metrics.go
metrics/go_metrics_test.go
metrics/metrics.go
metrics/metrics_mock.go
metrics/prometheus/prometheus.go
metrics/prometheus/prometheus_test.go

```
pbs_sub_connections_error{connection_error="accept"} 0
pbs_sub_connections_error{connection_error="close"} 0
+ # HELP pbs_sub_connections_got Count number of times client trace calls GotConn.
+ # TYPE pbs_sub_connections_got counter
+ pbs_sub_connections_got 0
pbs_sub_connections_opened 1
+ # HELP pbs_sub_connections_want Count number of times client trace calls GetConn.
+ # TYPE pbs_sub_connections_want counter
+ pbs_sub_connections_want 0
```

Metrics: Record HTTP connections wanted and obtained

---

adapters/eplanning/eplanning.go
adapters/eplanning/eplanning_test.go
adapters/eplanning/eplanningtest/exemplary/simple-banner-2.json

Adding a new, optional, response field adom/adomain to the e-planning adapter to comply with Microsoft Monetize requirements

e-planning: Add support for adomain

---

config/config.go
config/config_test.go
pbs/usersync.go
router/router.go
server/ssl/ssl.go
server/ssl/ssl_test.go

Following guidance from [this Medium article](https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07), the original developers of PBS embedded CA certificates in this project instead of using them from the OS. We've kept the embedded CA certificates updated to match the Ubuntu version targeted by the dockerfile.
This PR introduces the config option `certificates_use_system` will use the OS certs instead. It defaults to false, so PBS will continue to use the embedded certs by default.
Please let us know if you want to continue using the embedded certs or prefer to only use OS certs.

Host Option To Use OS Certs
