prebid/prebid-server

cache/dummycache.go, cache/dummycache_test.go, cache/filecache.go, cache/filecache_test.go, pbs_light.go
- Add support for loading dummy, postgres, and filecache via config
- Add tests for dummycache and filecache
- Minor cleanup of the datacache loading/config options
=> Config driven datacache selection and configuration

adapters/appnexus.go, adapters/facebook.go, adapters/facebook_test.go, adapters/index.go, adapters/openrtb_util.go, adapters/pubmatic.go, adapters/rubicon.go, pbs/pbsrequest.go
First version based on initial Facebook OpenRTB spec. Parallelizes requests per FB recommendation.
=> Initial cut of facebook integration

adapters/appnexus.go, adapters/appnexus_test.go, adapters/facebook.go, adapters/facebook_test.go, adapters/index.go, adapters/index_test.go, adapters/openrtb_util.go, adapters/pubmatic.go, adapters/pubmatic_test.go, adapters/rubicon.go, adapters/rubicon_test.go, cache/cache.go, cache/dummycache.go, cache/dummycache_test.go, cache/filecache.go, cache/filecache_test.go, cache/postgres.go, glide.lock, glide.yaml, pbs/pbsrequest.go, pbs/pbsrequest_test.go, pbs/pbsresponse.go, pbs_light.go, prebid_cache_client/prebid_cache.go, prebid_cache_client/prebid_cache_test.go, static/pbs_request.json
update request syntax to support openrtb device and geo. don't require cookies. update adapters to at least not crash on mobile app requests.
=> initial support for mobile apps. 

adapters/pulsepoint.go, adapters/pulsepoint_test.go, pbs_light.go
Official adapter submission for [PulsePoint](http://pulsepoint.com).
Test Page: http://projects.contextweb.com/av/prebid/s2s/
=> PulsePoint adapter

static/index.html
=> fix issue 32

pbs/pbsrequest.go, pbs_light.go, prebid/prebid.go
- prebid package for shared functionality to use with http requests
- Check X-Forwarded-For and X-Real-IP headers to parse the RealIP and
GetForwardIP
- IsSecure checks headers, TLS, and request protocol
- https://github.com/prebid/prebid-server/issues/47
=> RealIP parsing

pbs_light.go
/ip loads plain text instead of html so ``<p>...</p>`` is not creating new lines/paragraphs
=> use \n instead of <p> tags

adapters/rubicon.go, adapters/rubicon_test.go
- Adding more sizes
- Adding tk_xint
- Adding tests
=> Rubicon Project adapter update - sizes, tracking, tests

adapters/index.go, adapters/index_test.go, config/config_test.go, pbs_light.go
add ability for index to have dynamic endpoints
=> Index endpoints

cache/postgrescache/postgrescache.go, cache/postgrescache/postgrescache_test.go, glide.lock, glide.yaml
Use sql.NullString to read in price granularity from db. Unit test using mock db
=> Read price granularity in properly from db

adapters/appnexus.go, adapters/appnexus_test.go, cache/cache.go, cache/postgrescache/postgrescache.go, cache/postgrescache/postgrescache_test.go, config/config_test.go, pbs_light.go
Support invcode+member
Improved testing framework
Support some new params (keywords, trafficSourceCode, reserve, position)
=> update appnexus adapter to support new params

pbs/pbsresponse.go, pbs/pbsresponse_test.go
Sort method sorts from lowest to highest, we want top bid in position 0 in the array so we need to reverse sorting order. Added unit tests.
=> Reverse sorting order of bids to properly sort from highest to lowest

adapters/adapter.go, pbs/pbsresponse.go
This PR is mainly my way of trying to learn about the project.
Rather than ask questions, I thought I'd write comments. If they're accurate, the project becomes easier to understand for the next guy. If they're inaccurate, someone who knows the project can let me know.
I did also delete an unused field, because cognitive resources spent understanding dead code are resources not spent understanding live code. This is my first time seeing Go, though, so let me know if there was some reason for it.
=> Adding godocs

cache/cache.go, cache/dummycache/dummycache.go, cache/dummycache/dummycache_test.go, cache/filecache/filecache.go, cache/filecache/filecache_test.go, cache/postgrescache/postgrescache.go, cache/postgrescache/postgrescache_test.go
Removes code that was used for domain/app whitelist. related to https://github.com/prebid/prebid-server/pull/93
=> drop unused cache code

README.md
Just update the status of the adapters.
=> update readme status

pbs/pbsrequest.go, pbs/usersync.go, pbs_light.go
If there are good standards for when to log what, I don't know them... so I just made some guesses. Lemme know if I'm off the mark.
=> Reduce logging

adapters/rubicon.go, adapters/rubicon_test.go, config/config.go, pbs_light.go
Making the source tracker configurable.
=> Adding configurable rubicon project prebid tracker

adapters/facebook.go, adapters/facebook_test.go
Should be merged after Fb endpoint updates.
=> update to accept dollars instead of cents per fb endpoint update

adapters/appnexus.go, adapters/appnexus_test.go, adapters/facebook.go, adapters/facebook_test.go, adapters/index.go, adapters/index_test.go, adapters/openrtb_util.go, adapters/openrtb_util_test.go, adapters/pubmatic.go, adapters/pubmatic_test.go, adapters/pulsepoint.go, adapters/pulsepoint_test.go, adapters/rubicon.go, adapters/rubicon_test.go, glide.lock, glide.yaml, pbs/pbsrequest.go
Reverts prebid/prebid-server#115
Looks like this was causing some segfaults.
=> Revert "Update references of prebid/openrtb to use mxmCherry/openrtb"

adapters/appnexus.go, adapters/appnexus_test.go, adapters/facebook.go, adapters/facebook_test.go, adapters/index.go, adapters/index_test.go, adapters/openrtb_util.go, adapters/openrtb_util_test.go, adapters/pubmatic.go, adapters/pubmatic_test.go, adapters/pulsepoint.go, adapters/pulsepoint_test.go, adapters/rubicon.go, adapters/rubicon_test.go, glide.lock, glide.yaml, pbs/pbsrequest.go
Reverts prebid/prebid-server#121. Re-implements #115 
I reverted #115 prematurely. The real cause of the issues is being addressed in #122.
=> Un-revert "Update references of prebid/openrtb to use mxmCherry/openrtb""

adapters/index.go, adapters/index_test.go, pbs_light.go
Should be merged after index updates their endpoint.
=> Update usersync URL plus add to configuration.

adapters/appnexus.go, adapters/appnexus_test.go, adapters/facebook.go, adapters/facebook_test.go, adapters/index.go, adapters/index_test.go, adapters/openrtb_util.go, adapters/openrtb_util_test.go, adapters/pubmatic.go, adapters/pubmatic_test.go, adapters/pulsepoint.go, adapters/rubicon.go, adapters/rubicon_test.go, pbs/pbsrequest.go, pbs/pbsrequest_test.go, pbs/pbsresponse.go, static/pbs_request.json
This is a new PR for adding video support to the Prebid server. The old PR   #92 somehow  got the commits messed up.
=> Added video support (see issue #76)

pbs_light.go
introduced by #146.
We've gotta refactor this global, mutable state away...
=> Fixed a cookie sync bug

static/pbs_request.json
parsing was choking due to some invalid encoded characters in the whitespace.
=> remove invalid json sequence

docs/endpoints/bidder-params.md, docs/endpoints/bidders/params.md, pbs_light.go, pbs_light_test.go, static/bidder-params/appnexus.json, static/bidder-params/facebook.json, static/bidder-params/index.json, static/bidder-params/lifestreet.json, static/bidder-params/pubmatic.json, static/bidder-params/pulsepoint.json, static/bidder-params/rubicon.json
=> Added adapter param schemas & endpoint

adapters/adapter.go, adapters/appnexus/appnexus.go, adapters/appnexus/appnexus_test.go, adapters/facebook/facebook.go, adapters/facebook/facebook_test.go, adapters/index/index.go, adapters/index/index_test.go, adapters/lifestreet/lifestreet.go, adapters/lifestreet/lifestreet_test.go, adapters/openrtb_util.go, adapters/openrtb_util_test.go, adapters/pubmatic/pubmatic.go, adapters/pubmatic/pubmatic_test.go, adapters/pulsepoint/pulsepoint.go, adapters/pulsepoint/pulsepoint_test.go, adapters/rubicon/rubicon.go, adapters/rubicon/rubicon_test.go, pbs_light_test.go
Had some spare time... decided to fix #158 because it was easy
=> Make adapter packages

adapters/appnexus/appnexus.go, adapters/appnexus/appnexus_test.go
Fixes for issues #160 and #161
=> Added NURL to bid; fixed return imp type

pbs_light_test.go
I'm looking to test our build & release automation script.
This PR adds a test for some untested code, so that we have a new commit since the last release.
=> Added a unit test

.travis.yml, adapters/lifestreet/lifestreet_test.go, pbs_light_test.go, validate.sh
=> Add vet command to validation

prebid_cache_client/prebid_cache.go, prebid_cache_client/prebid_cache_test.go
=> Remove unnecessary cache calls

pbs_light.go, pbs_light_test.go
New targeting keys example
```"hb_bidder": "appnexus",
"hb_bidder_appnexus": "appnexus",
"hb_cache_id": "3241a284-106f-4448-a74e-14182864b065",
"hb_cache_id_appnexus": "3241a284-106f-4448-a74e-14182864b065",
"hb_creative_loadtype": "html",
"hb_deal": "391174",
"hb_deal_appnexus": "391174",
"hb_pb": "5.00",
"hb_pb_appnexus": "5.00",
"hb_size": "300x250",
"hb_size_appnexus": "300x250"```
=> Add deals ad server targeting keys prebid mobile

adapters/pubmatic/info.yaml
Updated contact information for PubMatic Adapter.
=> Updated PubMatic contact info

adapters/lifestreet/info.yaml
This fixes #219 using the email given in #209
=> Used the lifestreet maintainer email

docs/developers/add-new-bidder.md
=> Added the info.yaml file to the docs.

adapters/conversant/conversant.go, adapters/conversant/conversant_test.go, adapters/conversant/info.yaml, openrtb_ext/bidders.go, pbs_light.go, static/bidder-params/conversant.json
Conversant prebid server adapter
Supports banner and videos
Maintainer: mediapsr@conversantmedia.com
[Pull request for proper type conversion for parameters](https://github.com/prebid/Prebid.js/pull/1863)
=> Conversant s2s adapter

docs/developers/add-new-bidder.md
Because of your questions in #221... hopefully this clarifies for people in the future.
=> Added links to JSON schema docs.

openrtb_ext/request.go
=> Fixed a docs mistake in the contracts

docs/developers/stored-requests.md
Noticed these shortly after actually trying to share the docs with someone.
=> Fixed some broken links

stored_requests/backends/db_fetcher/fetcher.go, stored_requests/backends/db_fetcher/postgres.go
While testing legacy configs, I found some gaps in our postgres error handling.
These few small changes should make it easier in the future.
=> Improved postgres error handling

pbs_light.go
Updated PubMatic Adapter Endpoint.
=> Updated Pubmatic Adapter Endpoint

exchange/exchange.go, exchange/exchange_test.go
Thanks @anwzhang!
Core bug is a typing issue. I thought `e.cacheTime` was an int, and multiplied it by `time.Millisecond`... but it had already been turned into a `Duration` in `NewExchange`.
Multiplying it by an extra 1000 made the deadline in the past, which caused auctions to time out.
=> Fixed a bug with the timeout computation

config/stored_requests.go
=> Improve error message for bad configs

stored_requests/fetcher.go, stored_requests/fetcher_test.go
=> Prevent Fetcher calls on duplicate Stored Request IDs

endpoints/openrtb2/amp_auction.go, pbs_light.go
Fixes #263 
Oops, missed the CORS headers in the AMP PR.
=> Adds CORS headers needed for AMP responses

pbs_light.go
I've never once used this endpoint, and it looks like debugging code more than anything to me.
Does anybody care if we delete it?
The main motivation here is because it doesn't have unit tests, and brings down the code coverage %. We can add tests if it has value... but if nobody cares about it, there's no reason we should maintain it.
=> Deleted the /ip endpoint

pbs_light.go
Not sure how this made it through CI on other PRs...
=> Removed unused import

endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go
=> Set the content-type on the auction endpoint

usersync/indexExchange.go
=> Fixed family name of index usersyncer.

adapters/appnexus/appnexus_test.go, adapters/audienceNetwork/facebook_test.go, adapters/conversant/conversant_test.go, adapters/lifestreet/lifestreet_test.go, adapters/pubmatic/pubmatic_test.go, adapters/pulsepoint/pulsepoint_test.go, adapters/rubicon/rubicon_test.go, config/config.go, pbs/usersync.go, pbs/usersync_test.go, pbs_light.go, pbs_light_test.go
=> Modifies the user ID cookie to have a configurable TTL

docs/endpoints/openrtb2/auction.md
This is a required param... will fix the sample payload.
=> Added site to the sample payload

docs/endpoints/cookieSync.md, endpoints/openrtb2/amp_auction.go, pbs_light.go, pbs_light_test.go
Partially implements the solution to #341. Takes care of the original request, but none of the extra features discussed in the thread.
=> Cookie sync 341

exchange/legacy.go
=> Supported video sizes for legacy bidders

docs/endpoints/openrtb2/auction.md, endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, exchange/utils.go, exchange/utils_test.go, openrtb_ext/user.go
=> Allow explicit userids

docs/endpoints/openrtb2/auction.md, endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, openrtb_ext/regs.go, openrtb_ext/user.go
Fixes #371.
I tested this manually... but I'm going lighter than usual on the automated tests because they'll cause merge conflict with #353. When this looks approvable, let me know and I'll add the test cases over in that PR.
=> Adding GDPR extensions

endpoints/openrtb2/amp_auction.go
Because of the confusion in #376.
=> Better AMP error message

exchange/targeting.go
Stupid carelessness leftover from #380
=> Finished a missing TODO

exchange/auction.go, exchange/exchange.go, exchange/targeting.go, exchange/targeting_test.go, openrtb_ext/bid.go
Fixes #382.
This also contains some followup changes based on a comment by @cirla on #380... rather than add yet another argument to that bloated function, I broke it up into smaller pieces.
=> Adding hb_env, and some more minor cleaning

adapters/indexExchange/index.go, adapters/pubmatic/pubmatic.go, adapters/pulsepoint/pulsepoint.go, adapters/rubicon/rubicon.go, adapters/sovrn/sovrn.go
Analogous fixes to #400 for other adapters making the same false assumption.
=> Fixed similar segfaults in several other adapters.

exchange/bidder_test.go
Fixes #369 
Fixes #103 
`TestBidderTimeout` has still been failing sporadically. This is yet another attempt to make it work reliably.
This fix is inspired by https://stackoverflow.com/a/43954344
The main difference between this try and the last one is that it uses a context whose deadline has _already_ expired. Maybe that'll make it work... who knows?
=> Streamlined one of the unreliable tests, hopefully fixing it.

docs/developers/configuration.md, pbs_light.go, pbs_light_test.go
Viper supports reading configuration options from environment variables, this enables this feature for Prebid Server.
=> Adds environment variable support for configuration

adapters/appnexus/appnexus.go, adapters/appnexus/appnexustest/supplemental/multi-bid.json, adapters/rubicon/rubicon.go, adapters/sovrn/sovrn.go
Fixes the bug found in #413 for other adapters. Added a regression test for the Appnexus adapter.
Thanks @aradilov!
=> Fix pointer bug

pbs_light.go
The missing exchanges error masked the error with exchanges.
=> Yet more fixes

adapters/appnexus/appnexus.go, adapters/appnexus/appnexus_test.go, config/config_test.go, exchange/adapter_map.go, pbs_light.go
Should be no user-facing changes here, given the default set in the code.
=> Made the appnexus endpoint configurable

pbs_light.go, stored_requests/backends/db_fetcher/fetcher.go, stored_requests/backends/empty_fetcher/fetcher.go, stored_requests/backends/file_fetcher/fetcher.go, stored_requests/fetcher.go, stored_requests/multifetcher.go, stored_requests/multifetcher_test.go
This will allow us to compose a fetcher that can pull IDs from multiple datasources.
=> Add Multi-Fetcher functionality to stored config Fetchers

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/auction.go, pbs_light.go, pbsmetrics/go_metrics.go, pbsmetrics/metrics.go, pbsmetrics/metrics_test.go
=> Added metrics for the number of Imps

pbs_light.go
so people know what 200 means...
=> Made a status response

README.md, docs/developers/add-new-bidder.md, docs/endpoints/openrtb2/auction.md
Fixes #385.
Also addressing [this comment](https://github.com/prebid/prebid-server/pull/430#issuecomment-380304229), because I forgot docs on the Bid Adjustments PR.
=> Various docs updates

config/config.go, docs/endpoints/openrtb2/amp.md, endpoints/openrtb2/amp_auction.go
Additional query params will be passed to AMP endpoint (see https://github.com/ampproject/amphtml/pull/14155/files).
This uses some of those parameters to fill/override values in the OpenRTB request.
=> Support some AMP query params

endpoints/openrtb2/amp_auction.go
=> Support AMP RTC slot param

endpoints/openrtb2/auction_benchmark_test.go, endpoints/openrtb2/auction_test.go, pbs_light.go, pbs_light_test.go, stored_requests/backends/empty_fetcher/fetcher.go, stored_requests/backends/empty_fetcher/fetcher_test.go, stored_requests/backends/http_fetcher/fetcher.go, stored_requests/backends/http_fetcher/fetcher_test.go, stored_requests/caches/nil_cache/nil_cache.go, stored_requests/config/config.go, stored_requests/config/config_test.go
I had some time in between real jobs... so I moved some more stuff out of `pbs_light`. 
Unit tests are bare-bones... just enough to get us over the 30% threshold. But there were _no_ tests on all this code before, so... *shrugs*.
Obviously no rush on this at all.
=> Moving Stored Request construction

exchange/exchange.go, pbs_light.go, pbsmetrics/go_metrics.go
Cleaned u some metrics code, shouldn't change anything or fix the blank metrics issue, but perhaps if there is some subtle issue I cannot see.
Also improved the logging to help narrow down where/when the blank metrics are happening.
=> metrics code cleanup and better logging

.travis.yml, validate.sh
Fixes #468. Adds Go 1.10 to our Travis builds.
Thanks @hhhjort!
=> Added Go 1.10 to Travis

adapters/adapterstest/test_json.go
The code is generic enough to allow testing non-OpenRTB compliant
bidders. This patch mostly changes the type of the HttpResponse.Body
from openRTB.BidResponse to json.RawMessage, to avoid having the test
interpreting the response as an OpenRTB one. This wasn't required as
the response is interpreted appropriately by the adapter's MakeBids
method, which take a []byte as the body.
=> Update test_json to work with non-OpenRTB bidders

pbs_light.go
May expand our metrics a little bit.
=> Take adm/nurl metrics from the legacy endpoint too

stored_requests/backends/http_fetcher/fetcher.go, stored_requests/backends/http_fetcher/fetcher_test.go
This is a breaking change for the API the http stored request fetcher uses. As it is not a user facing API change, I am not sure if this should have the "breaking api change" tag or not.
Oh, possibly needs docs ... I am not seeing any docs currently describing the http fetcher API, so maybe?
=> Enhances the API used by the http stored request fetcher

pbs_light.go
Followup to https://github.com/prebid/prebid-server/pull/517
=> added gdpr params to Rubicon sync url

Gopkg.lock, Gopkg.toml, gdpr/impl.go
Slightly simpler code using the function added in https://github.com/prebid/go-gdpr/pull/9
=> Small GDPR parsing improvement

server/listener.go
This is an absolutely ridiculous solution to an absolutely ridiculous problem.
TCP connections can be closed by callers. If that happens, then the server gets an error when _it_ tries to close the connection.
This fragile and hacky workaround is the best I found in [five and a half years of discussion](https://github.com/golang/go/issues/4373). It even appears [in the standard libs](https://github.com/golang/net/blob/master/http2/server.go#L626).
I just want the app logs to be filled with messages that mean things  ¯\\_(ツ)_/¯
=> Silenced some false positive errors

docs/developers/gdpr.md, docs/endpoints/cookieSync.md
Just summarizing the behavior under GDPR, and linking to some of the relevant docs.
You can see the rendered version here: https://github.com/prebid/prebid-server/blob/gdpr-dev-docs/docs/developers/gdpr.md
=> Added a general GDPR doc

docs/endpoints/openrtb2/amp.md, endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/amp_auction_test.go
This includes the changes from #470, fixed a few inconsistencies with https://github.com/prebid/prebid-server/issues/420#issuecomment-383087697, and closes #420.
=> Resolve AMP size query params

static/bidder-params/rubicon.json
This patch fixes a valid openrtb request that currently fails with a data type error:
```
{
"id": "7b3e93dc-10cc-42cd-b855-76ddea2e3f7d",
"source": {
"tid": "7b3e93dc-10cc-42cd-b855-76ddea2e3f7d"
},
"tmax": 1000,
"imp": [
{
"id": "test-div",
"ext": {
"rubicon": {
"accountId": 1001,
"siteId": 113932,
"zoneId": 535510,
"inventory": {
"rating": [
"5-star"
],
"prodtype": [
"tech",
"mobile"
]
},
"visitor": {
"ucat": [
"new"
],
"search": [
"iphone"
]
}
}
},
"secure": 0,
"banner": {
"format": [
{
"w": 300,
"h": 250
},
{
"w": 300,
"h": 600
}
]
}
}
],
"test": 1,
"site": {
"publisher": {
"id": "1001"
},
"page": "http://localhost/prebid_server_test_1001_gdpr.html"
},
"user": {
"ext": {
"digitrust": {
"id": "B+pL2o/72Ece/VNhE1FjdK1hDI99YIQ5DAN/BQTjdgWKiqKIkh49YTC4jJnwuXXxC9Chg036stdDBpJujn0z9pt4D4xEwg …
```
=> Fixing inventory/visitor data types

config/stored_requests.go
=> Use the cache type to determine if no cache was available

config/config_test.go, usersync/usersyncers/brightroll.go, usersync/usersyncers/brightroll_test.go
Description:
Updated Brightroll cookie sync URL to add the expecting gdpr signals as URL parameters.
=> Cookie sync URL gdpr support for Brightroll adapter

adapters/brightroll/brightroll.go, adapters/brightroll/brightrolltest/exemplary/banner-and-audio.json, adapters/brightroll/brightrolltest/exemplary/banner-and-video.json, adapters/brightroll/brightrolltest/exemplary/banner-native-audio.json, adapters/brightroll/brightrolltest/exemplary/banner-video-native.json, adapters/brightroll/brightrolltest/exemplary/simple-banner.json, adapters/brightroll/brightrolltest/exemplary/simple-video.json, adapters/brightroll/brightrolltest/exemplary/valid-extension.json, adapters/brightroll/brightrolltest/exemplary/video-and-audio.json, adapters/brightroll/brightrolltest/params/race/banner.json, adapters/brightroll/brightrolltest/params/race/video.json, adapters/brightroll/brightrolltest/supplemental/audio.json, adapters/brightroll/brightrolltest/supplemental/bad-request.json, adapters/brightroll/brightrolltest/supplemental/invalid-extension.json, adapters/brightroll/brightrolltest/supplemental/invalid-imp.json, adapters/brightroll/brightrolltest/supplemental/missing-param.json, adapters/brightroll/brightrolltest/supplemental/native.json, adapters/brightroll/params_test.go, openrtb_ext/imp_brightroll.go, static/bidder-params/brightroll.json
Description:
Changing Brightroll adapter's custom parameter name from "publisherName" to "publisher"
=> Changing custom parameter name

docs/endpoints/openrtb2/auction.md, endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go
Fixes #569, #570.
This can be reviewed... but should wait for @bretg to see it before we merge anything.
=> Infer imp.secure state

Gopkg.lock, Gopkg.toml
To pick up the latest bugfix from that library.
=> Bump gdpr version

adapters/pubmatic/pubmatic.go
Populating bidType in the pubmatic adapter's response as we are facing this issue: #600
=> Added creative media type check in pubmatic adapter

Gopkg.lock, pbs_light.go
Fixes #17.
I assume this was being used at some point a long time ago... but it's dead code now.
=> Removed some unused code & gosigar dependency

exchange/auction.go, exchange/exchangetest/targeting-cache-zero.json
Fixes #199... by un-fixing it.
Surprisingly, it looks like we didn't have a test for this... so I added one.
=> Cache bids which round to 0.00 CPM

README.md
IMO these are important enough to link here... everyone's always asking stuff about the adapters.
=> Linked to the Bidder docs

adapters/beachfront/beachfront.go, adapters/beachfront/beachfronttest/supplemental/minimal-site-banner.json
Resolves a panic for any request whose site.page does not include the protocol piece.
=> Beachfront panic fix

endpoints/cookie_sync_test.go, endpoints/openrtb2/auction_benchmark_test.go, endpoints/setuid_test.go, exchange/exchange.go, exchange/exchange_test.go, exchange/gdpr.go, exchange/gdpr_test.go, exchange/targeting_test.go, exchange/utils.go, gdpr/gdpr.go, gdpr/impl.go, gdpr/impl_test.go, pbs_light.go, pbs_light_test.go
This will remove some Personally Identifying information from bid requests sent to bidder adapters if GDPR consent is missing.
=> GDPR enhancements

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/amp_auction_test.go
=> Send the right Domain for AMP requests

config/config.go, exchange/auction.go, exchange/auction_test.go, exchange/cachetest/defaultbanner.json, exchange/cachetest/defaultvideo.json, exchange/cachetest/multibid.json, exchange/exchange.go
Default is only used if no other TTLs are provided
=> Default ttl per media type

endpoints/openrtb2/amp_auction_test.go
A few of those recent commits broke the build... this should fix it.
=> Fixing the build

adapters/appnexus/appnexus.go, adapters/appnexus/appnexustest/supplemental/displaymanager-test.json, docs/bidders/appnexus.md, docs/endpoints/openrtb2/auction.md, endpoints/openrtb2/auction.go, endpoints/openrtb2/sample-requests/invalid-whole/app-bad-ext.json, endpoints/openrtb2/sample-requests/valid-whole/supplementary/app.json, openrtb_ext/app.go
Simple little addition to the Appnexus adapter
=> Adds support for generating imp.displaymanagerver for AppNexus

adapters/rubicon/rubicon.go, adapters/rubicon/rubicon_test.go
Rubicon XAPI doesn't accept currencies.
=> Suppress currencies in OpenRTB request to Rubicon exchange

README.md, adapters/adkernelAdn/adkernelAdn.go, adapters/bidder.go, adapters/conversant/conversant.go, adapters/conversant/conversant_test.go, adapters/ix/ix_test.go, config/config.go, endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/auction_test.go, endpoints/version.go, errortypes/errortypes.go, exchange/bidder.go, exchange/gdpr.go, exchange/validation_test.go, openrtb_ext/request.go, pbsmetrics/prometheus/prometheus.go, pbsmetrics/prometheus/prometheus_test.go, stored_requests/caches/memory/maps.go
Stumbled on this elsewhere... thought it was pretty cool.
It also turned up a whole bunch of misspellings and typos, so... fixed those.
=> Added a Go report card badge

exchange/adapter_map.go, exchange/adapter_map_test.go
to account for audienceNetwork -> audiencenetwork in the config structure
=> Fixes the disable bidder code 

config/config.go, pbsmetrics/prometheus/prometheus_test.go
I don't see this config value actually used in the code anywhere... so just deleting the dead code.
=> Removed an unused prometheus config param

adapters/brightroll/brightroll.go
Accommodating some customized bid request changes for brightroll bidder
=> Brightroll bidder changes for customized request

Gopkg.lock, Gopkg.toml, adapters/adkernelAdn/adkernelAdn.go, adapters/syncer.go, config/config.go, config/config_test.go, docs/bidders/audienceNetwork.md, docs/bidders/rubicon.md, macros/macros.go, macros/macros_test.go, util/macros.go
* Validate adapter endpoints and user sync URLs at start up
=> PBS-68: Disable Rubicon and AudienceNetwork adapters by default

config/config.go, config/stored_requests.go, config/stored_requests_test.go, router/router.go, stored_requests/config/config.go, stored_requests/config/config_test.go, stored_requests/fetcher.go
-Returns single general fetcher instead of two specific
-Now uses to create category mapping fetcher
=> NewFetchers code refactoring:

endpoints/openrtb2/video_auction.go, endpoints/openrtb2/video_auction_test.go, openrtb_ext/bid_response_video.go
Validation refactoring
-Added pod level error: return error for that particular pod. process the good pods normally
-Added validation for 0 and negative ad pod duration
-Added mime types clean up
-Added validation for duplicated pod ids
-Added validation for missing pod ids
-Added pod config id handling
-Added handler for the case when all pods are incorrect
=> Video endpoint request validation refactoring

adapters/conversant/conversant.go, adapters/conversant/conversant_test.go, static/bidder-info/conversant.yaml
Allow inapp requests for banner and video to be send to the Conversant servers
=> Allow app requests for Conversant

adapters/sonobi/usersync_test.go, config/config.go
Changed the UID replacement macro from $UID to [UID]
=> Sonobi Adapter- change UID replacement macro

cache/postgrescache/postgrescache.go, config/structlog.go, endpoints/currency_rates.go, endpoints/info/bidders.go, endpoints/openrtb2/auction.go, endpoints/status.go, endpoints/version.go, exchange/exchange.go, exchange/legacy.go, gdpr/vendorlist-fetching.go, pbs/pbsrequest.go, prebid_cache_client/client.go, router/router.go, stored_requests/backends/db_fetcher/fetcher.go, stored_requests/config/config.go, stored_requests/events/http/http.go, usersync/usersyncers/syncer.go
- Merging if statements with nested one wherever possible
- Remove/replace unused function parameters with blank identier
=> Address Sonar Analysis comments (Severity: Major)

adapters/conversant/conversant.go, adapters/conversant/conversant_test.go
Need to get the id from the conversant parameters not the incoming request.app.id
=> Get the app id from the parameters for Conversant

adapters/vrtcal/params_test.go, adapters/vrtcal/usersync.go, adapters/vrtcal/usersync_test.go, adapters/vrtcal/vrtcal.go, adapters/vrtcal/vrtcal_test.go, adapters/vrtcal/vrtcaltest/exemplary/simple-banner.json, config/config.go, exchange/adapter_map.go, openrtb_ext/bidders.go, openrtb_ext/imp_vrtcal.go, static/bidder-info/vrtcal.yaml, static/bidder-params/vrtcal.json, usersync/usersyncers/syncer.go, usersync/usersyncers/syncer_test.go
Vrtcal Markets, Inc Adapter Integration
=> Vrtcal Markets, Inc Adapter Integration

endpoints/openrtb2/video_auction.go, endpoints/openrtb2/video_auction_test.go, openrtb_ext/bid_request_video.go
-Added null checks for Site and App
-Added required fields validation: Site: id or page, App: id or bundle
=> Minor fix:

Dockerfile
as discussed here https://github.com/prebid/prebid-server/issues/981
=> Dockerfile: update go 1.11.11 => 1.12.7

config/config.go
Hi,
we have updated our default user sync url.
=> VIS.X: update default user sync url

docs/bidders/tappx.md
Added requested documentation (https://github.com/prebid/prebid-server/pull/957)
=> Add Tappx bidder doc

static/bidder-info/unruly.yaml
Updated email address for Unruly adapter
=> chore(unruly): update Unruly contact details

adapters/adkernelAdn/adkernelAdn.go, adapters/adkernelAdn/adkerneladntest/exemplary/multiformat-impression.json, adapters/adkernelAdn/adkerneladntest/exemplary/single-banner-impression.json, adapters/adkernelAdn/adkerneladntest/supplemental/204status.json, adapters/adkernelAdn/adkerneladntest/supplemental/http-err-status.json, adapters/adkernelAdn/adkerneladntest/supplemental/native-impression.json, adapters/adkernelAdn/adkerneladntest/supplemental/two-impressions-two-seatbids.json, static/bidder-info/adkernelAdn.yaml
- Fixed multi-format impression issue #862 
- Removed imp.tagId = imp.id duplication
- Updated maintainer contact
=> AdkernelAdn multi-format imp issue

pbs_light.go, pbs_light_test.go
=> [lint] applying go-lint suggestions

endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go
=> Fix leaking host cookie to all bidders

endpoints/info/bidders_test.go
Following PR #989, this CL to improve the test clarity as stated in a
review comment:
https://github.com/prebid/prebid-server/pull/989#discussion_r318296542
=> [improvement] make testing disabled bidders clearer

adapters/unruly/usersync.go, adapters/unruly/usersync_test.go
Change Unruly usersync to iframe
=> feat(unruly): Change Unruly usersync to iframe

config/config.go, config/config_test.go, pbsmetrics/config/metrics.go
This pull request is intended to make the Influx metrics collection rate configurable via an environment variable.
=> Make InfluxDB collection rate configurable

pbsmetrics/prometheus/prometheus.go
This will allow Prometheus to record account level metrics. Account-Adapter metrics are still completely unsupported.
=> Add/enable account metrics for Prometheus

Dockerfile, Makefile
This CL adds a proxy to ease Go modules usage
=> [Go Modules] Add proxy

usersync/cookie_test.go
This CL only fix a misspell in tests.
=> [misspell] fix a misspell

adapters/yieldmo/usersync.go, adapters/yieldmo/usersync_test.go
Adding Yieldmo's GDPR vendor id to our usersync.
=> Adding Yieldmo vendor id to usersync

endpoints/openrtb2/video_auction.go, endpoints/openrtb2/video_auction_test.go, openrtb_ext/bid_request_video.go
addresses https://github.com/prebid/prebid-server/issues/1185
=> Adding copying of gdpr consent string to openrtb bid request

adapters/openx/openx.go, adapters/openx/openx_test.go
it was always set to the default USD before
=> openx adapter: forward bid response currency in openx adapter if set

static/bidder-info/33across.yaml, static/bidder-info/adoppler.yaml, static/bidder-info/advangelists.yaml, static/bidder-info/brightroll.yaml, static/bidder-info/conversant.yaml, static/bidder-info/datablocks.yaml, static/bidder-info/engagebdr.yaml, static/bidder-info/gamoshi.yaml, static/bidder-info/gumgum.yaml, static/bidder-info/openx.yaml, static/bidder-info/rtbhouse.yaml, static/bidder-info/sonobi.yaml, static/bidder-info/verizonmedia.yaml, static/bidder-info/visx.yaml, static/bidder-info/yieldmo.yaml, static/bidder-info/zeroclickfraud.yaml
Went though the spreadsheet of maintainer info and updated the data stored in the YAML files.
=> aligning maintainer info

docs/bidders/kidoz.md
got this info from email communication with kidoz
=> Add kidoz bidder info

adapters/rubicon/rubicon.go, adapters/rubicon/rubicon_test.go
=> Add Cropping of BAdv for Rubicon Adapter

docs/bidders/pubmatic.md, static/bidder-info/pubmatic.yaml
Add PubMatic bidder doc file
Add app video capability to PubMatic bidder info file
=> Add PubMatic bidder doc file and in-app video to bidder info

static/bidder-info/openx.yaml
* Enable app video for OpenX adapter.
=> OpenX adapter: Enable video for app

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, endpoints/openrtb2/video_auction.go, endpoints/openrtb2/video_auction_test.go, exchange/auction.go, exchange/auction_test.go, exchange/cachetest/debuglog_disabled.json, exchange/cachetest/debuglog_enabled.json, exchange/exchange.go, exchange/exchange_test.go, exchange/exchangetest/debuglog_disabled.json, exchange/exchangetest/debuglog_enabled.json, router/router.go
This PR fixes the formatting of the debug log, specifically for browsers. It also fixes an issue where deal support and cache errors were not being appended to the response.
=> Fix debug log error messages

adapters/rubicon/rubicon.go, adapters/rubicon/rubicon_test.go, config/config.go, openrtb_ext/imp_rubicon.go
Change placement of cpm**o**verride to 
`ext.**prebid.bidders**.rubicon.debug.cpmoverride`
`imp[].ext.prebid.rubicon.debug.cpmoverride`
=> Change placement of cpmoverride for Rubicon

.github/stale.yml
Followup to https://github.com/prebid/prebid-server/issues/1293
=> increasing the stale period to 2 months

docs/endpoints/openrtb2/auction.md
Addresses: https://github.com/prebid/prebid-server/issues/1335
FYI: @MartianTribe
=> Update Auction OpenRTB Sample

config/config.go
Update conversant end point in config.go to new standard
=> Updating Conversant endpoint url

config/config.go
Resolves https://github.com/prebid/prebid-server/issues/1389
=> Fix Previous Merge Conflict

endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, endpoints/openrtb2/sample-requests/valid-whole/supplementary/site-has-dnt.json
Addresses https://github.com/prebid/prebid-server/issues/1372
=> Set OpenRTB DNT From HTTP Header

static/bidder-info/adtelligent.yaml
Added Video mediatype for InApp requests for Adtelligent bidder
=> Adtlelligent: add video for InApp support

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/amp_auction_test.go
- Parse Site.Publisher.ID from Amp Auction HTTP Req Query Parameter "account"
=> Parse Site.Publisher.ID from Amp Auction HTTP Req Query Parameter

adapters/adgeneration/adgeneration.go, adapters/adgeneration/adgeneration_test.go, adapters/adgeneration/adgenerationtest/exemplary/single-banner.json, adapters/adgeneration/adgenerationtest/supplemental/204-bid-response.json, adapters/adgeneration/adgenerationtest/supplemental/400-bid-response.json, adapters/adgeneration/adgenerationtest/supplemental/no-bid-response.json
fix the following contents
https://github.com/prebid/prebid-server/pull/1253#discussion_r448985371
Change currency of ad-generation's bidResponse according to bidRequest
Maintainer: ssp-ope@supership.jp
=> fix: Change currency of ad-generation's bidResponse according to bidRequest

go.mod, go.sum
The library just got a bugfix, so we want the update in.
=> update to the latest go-gdpr release

exchange/exchange.go, exchange/exchange_test.go
Detect duplicated bids by category only (or hb_pb_dur) and dedupe bid with lower price
=> [WIP] Bid deduplication enhancement

adapters/rubicon/rubicon.go
Added new size 640x360 (Id: 198)
=> Added new size 640x360 (Id: 198)

adapters/rubicon/rubicon.go
This reverts commit fa23f5c226df99a9a4ef318100fdb7d84d3e40fa.
=> Revert "Added new size 640x360 (Id: 198) (#1490)"

config/config.go
Hello,
This is a very small PR to update the default smartadserver endpoints (auction&sync).
Thank you !
=> Updating smartadserver endpoint configuration.

adapters/rubicon/rubicon.go
Add new size 500x1000 (ID: 548)
=> Add new size 500x1000 (ID: 548)

endpoints/openrtb2/sample-requests/video/video_valid_sample_appendbiddernames.json, endpoints/openrtb2/video_auction.go, endpoints/openrtb2/video_auction_test.go, exchange/exchange.go, exchange/exchange_test.go, exchange/exchangetest/append-bidder-names.json, openrtb_ext/bid_request_video.go, openrtb_ext/request.go
Original issue and more info for this change: https://github.com/prebid/prebid-server/issues/1458
=> Add bidder name key support

adapters/datablocks/usersync.go
Removing the GVL id for Datablocks as per:
https://github.com/prebid/prebid-server/issues/1301
=> update Datablocks usersync.go

adapters/eplanning/usersync.go, adapters/eplanning/usersync_test.go
Updating GVL ID to 90 as requested on https://github.com/prebid/prebid-server/issues/1301
=> Updated ePlanning GVL ID

adapters/adpone/usersync.go
Update Adpone GVL ID to 799
EDIT: Resolved part of https://github.com/prebid/prebid-server/issues/1301.
=> update adpone GVL vendor id

adapters/adtelligent/usersync.go, adapters/adtelligent/usersync_test.go
Update Adtelligent GVL ID 410
EDIT: Resolves part of  https://github.com/prebid/prebid-server/issues/1301.
=> Update Adtelligent GVL ID 410

static/bidder-info/kubient.yaml
Related with this issue #https://github.com/prebid/prebid-server/issues/1594#issuecomment-743406798
I tested prebid@kubient.com works
=> Set Kubient email to prebid@kubient.com

static/bidder-params/nobid.json
paramerter -> parameter, oprional -> optional
=> Fix typos in nobid.json

static/bidder-params/adform.json
=> Fix Typo In Adform Bidder Params

static/bidder-params/connectad.json
=> Typo fix for connectad bidder params

static/bidder-params/invibes.json
=> Typo fix for invibes bidder params

static/bidder-params/nanointeractive.json
=> Typo fix nanointeractive bidder params

adapters/pangle/pangle.go
Fixes a merge conflict between https://github.com/prebid/prebid-server/pull/1697 and https://github.com/prebid/prebid-server/pull/1692. Automated tools missed this conflict due to timing of the PRs.
=> Fix Merge Conflict

adapters/rhythmone/rhythmone.go, exchange/bidder.go, exchange/bidder_test.go, exchange/exchange.go, exchange/exchange_test.go, exchange/exchangetest/bid-ext-prebid-collision.json, exchange/exchangetest/bid-ext.json, exchange/seatbid.go, openrtb_ext/bid.go
Implements https://github.com/prebid/prebid-server/issues/1676
=> No Longer Move bid.ext To bid.ext.bidder

static/bidder-params/adyoulike.json
=> Typo fix: adyoulike bidder param debug description

README.md
https://github.com/prebid/prebid-server/issues/1740
=> Add request for registration

static/bidder-params/rtbhouse.json
PR addresses stale / non up to date params requirements by RTB House adapter
=> RTB House: update parameters

config/config.go
Update the AdYouLike endpoint to go live on this S2S integration.
=> Update Adyoulike endpoint to hit production servers

adapters/adocean/adocean.go, adapters/adocean/adoceantest/exemplary/multi-banner-impression.json, adapters/adocean/adoceantest/exemplary/single-banner-impression.json, adapters/adocean/adoceantest/supplemental/app.json, adapters/adocean/adoceantest/supplemental/bad-response.json, adapters/adocean/adoceantest/supplemental/encode-error.json, adapters/adocean/adoceantest/supplemental/network-error.json, adapters/adocean/adoceantest/supplemental/no-bid.json, adapters/adocean/adoceantest/supplemental/no-sizes.json, adapters/adocean/adoceantest/supplemental/requests-merge.json, static/bidder-info/adocean.yaml
This pull request is adding support for in app auctions for AdOcean adapter.
=> AdOcean adapter - add support for mobile apps

adapters/viewdeos/usersync.go, adapters/viewdeos/usersync_test.go, config/config.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/viewdeos.yaml, static/bidder-params/viewdeos.json, usersync/usersyncers/syncer.go, usersync/usersyncers/syncer_test.go
=> New Adapter: Viewdeos (Alias Of Adtelligent)

.github/workflows/release.yml, README.md
Implements https://github.com/prebid/prebid-server/issues/1845
=> Better Support For Go Modules

adapters/adapterstest/test_json.go, adapters/appnexus/appnexus.go, adapters/appnexus/appnexus_test.go, adapters/appnexus/appnexustest/video/video-no-adpodid-two-imps-different-pod.json, adapters/appnexus/appnexustest/video/video-same-adpodid-two-imps-same-pod.json, adapters/appnexus/appnexustest/videosupplemental/video-different-adpodid-two-imps-different-pods.json, adapters/appnexus/appnexustest/videosupplemental/video-different-adpodid-two-imps-same-pod.json, openrtb_ext/imp_appnexus.go, static/bidder-params/appnexus.json
Docs PR: https://github.com/prebid/prebid.github.io/pull/2836
=> AppNexus: Make Ad Pod Id Optional

adapters/bidder.go, adapters/bidder_test.go, currency/aggregate_conversions.go, currency/aggregate_conversions_test.go, currency/constant_rates.go, currency/errors.go, currency/rates.go, exchange/bidder_test.go, exchange/exchange.go, exchange/exchange_test.go
Implements https://github.com/prebid/prebid-server/issues/1482
=> Currency Conversion Utility Function

go.mod, go.sum
Upgrade a dependency as a result of a recent vulnerability scan.
=> Fix CVE-2020-35381

adapters/visx/visx.go, adapters/visx/visxtest/exemplary/simple-video.json, adapters/visx/visxtest/supplemental/wrong_imp_type.json, adapters/visx/visxtest/supplemental/wrong_impid.json, config/config.go, static/bidder-info/visx.yaml
Hi, we've added instream video support in our server adapter.
=> VIS.X: add video instream support

adapters/improvedigital/improvedigital.go, adapters/improvedigital/improvedigitaltest/exemplary/app-multi.json, adapters/improvedigital/improvedigitaltest/exemplary/site-multi.json
Split multi-imp request in multiple Improve Digital requests - this is to overcome the current Improve Digital backend limitations.
=> Improve Digital: Split multi-imp request in multiple requests

endpoints/info/bidders.go, endpoints/info/bidders_test.go
Implements https://github.com/prebid/prebid-server/issues/1788
=> /info/bidders endpoint consistency

config/config.go, config/config_test.go
Resolves https://github.com/prebid/prebid-server/issues/1999.
=> Fix GDPR EEACountries

config/config.go, config/config_test.go
Implements phase 2 of https://github.com/prebid/prebid-server/issues/2011.
=> Disable Legacy /auction Endpoint By Default

static/bidder-info/smaato.yaml
=> Smaato: Add userSync url

config/config.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/streamkey.yaml, static/bidder-params/streamkey.json
Ads streamkey bidder as alias of adtelligent
Doc update: https://github.com/prebid/prebid.github.io/pull/3383
=> New Adapter: Streamkey (Alias to Adtelligent)

adapters/rubicon/rubicon.go, adapters/rubicon/rubicon_test.go, adapters/rubicon/rubicontest/exemplary/app-imp-fpd.json, adapters/rubicon/rubicontest/exemplary/simple-video.json, adapters/rubicon/rubicontest/exemplary/site-imp-fpd.json, adapters/rubicon/rubicontest/exemplary/user-fpd.json
Changes from #https://github.com/prebid/prebid-server-java/pull/1583
=> Rubicon: update fpd fields resolving

config/config.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/janet.yaml, static/bidder-params/janet.json
Docs: https://github.com/prebid/prebid.github.io/pull/3591
=> New Adapter: add JANet alias 

util/task/ticker_task_test.go
Refactored the TickerTask tests to better avoid race conditions, per https://github.com/prebid/prebid-server/issues/2190.
=> Test Hardening For TickerTask

adapters/improvedigital/improvedigital.go, adapters/improvedigital/improvedigitaltest/supplemental/addtl-consent.json
Transform Google additional consent into format understood by the Improve Digital ad server
=> Improve Digital adapter: Google additional consent support

adapters/automatad/automatad.go, adapters/automatad/automatad_test.go, adapters/automatad/automatadtest/exemplary/simple-banner.json, adapters/automatad/automatadtest/supplemental/bad-request.json, adapters/automatad/automatadtest/supplemental/error-500-request.json, adapters/automatad/automatadtest/supplemental/no-content.json, adapters/automatad/params_test.go, config/config.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_automatad.go, static/bidder-info/automatad.yaml, static/bidder-params/automatad.json
* Added the adapter implementation code for Automatad.
=> New Adapter: Automatad

adapters/adnuntius/adnuntius.go, adapters/adnuntius/adnuntiustest/supplemental/check-gdpr.json, adapters/adnuntius/adnuntiustest/supplemental/check-userId.json, adapters/adnuntius/adnuntiustest/supplemental/empty-regs-ext.json, adapters/adnuntius/adnuntiustest/supplemental/empty-regs.json, adapters/adnuntius/adnuntiustest/supplemental/height-error.json, adapters/adnuntius/adnuntiustest/supplemental/native-error.json, adapters/adnuntius/adnuntiustest/supplemental/send-header-information.json, adapters/adnuntius/adnuntiustest/supplemental/status-400.json, adapters/adnuntius/adnuntiustest/supplemental/test-networks.json, adapters/adnuntius/adnuntiustest/supplemental/video-error.json
Just a quick fix that will not look for values in Regs if it's present but empty.
=> Adnuntius: Bug Fix for regs being empty

config/config.go, exchange/adapter_builders.go, static/bidder-info/mediafuse.yaml, static/bidder-params/mediafuse.json
Review required from @balajimediafuse before merging is permitted. Created on their behalf. I've confirmed with Mediafuse that they currently have no traffic using their existing alias, so no breaking change to publishers is expected.
=> MediaFuse: Change To Alias AppNexus

endpoints/openrtb2/interstitial.go, endpoints/openrtb2/interstitial_test.go
Resolve https://github.com/prebid/prebid-server/issues/2267
=> handle nil when device ext does not contain prebid settings for interstitial

adapters/visx/visx.go, adapters/visx/visxtest/exemplary/headers_ipv4.json, adapters/visx/visxtest/exemplary/headers_ipv6.json
Hi,
We've added X-Forwarded-For to the bid request headers.
=> VIS.X: add X-Forwarded-For header

config/config.go
I missed a few environment variable bindings when I initially added this config.
=> Add ENV Bindings For Top Level UserSync

adapters/smartadserver/smartadserver.go, adapters/smartadserver/smartadservertest/exemplary/native-app.json, adapters/smartadserver/smartadservertest/exemplary/native-web.json, static/bidder-info/smartadserver.yaml
Recreated changes from https://github.com/prebid/prebid-server/pull/2288
=> SmartAdServer: Added native support

amp/parse.go, amp/parse_test.go, endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/amp_auction_test.go, exchange/utils.go, exchange/utils_test.go
Implementation for https://github.com/prebid/prebid-server/issues/1727
=>  AMP targeting query string

static/bidder-info/nextmillennium.yaml
received an updated contact alias from them
=> nextmillennium contact info

adapters/triplelift/triplelift.go, adapters/triplelift/triplelifttest/supplemental/video-format-11.json, adapters/triplelift/triplelifttest/supplemental/video-format-12.json, adapters/triplelift/triplelifttest/supplemental/video-format-17.json
Created on behalf of Triplelift.
=> Triplelift: Expand Video Formats

config/config.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/oftmedia.yaml, static/bidder-params/oftmedia.json
Adding new adapter alias
Doc: https://github.com/prebid/prebid-server/pull/2302
=> New Adapter: Oftmedia (alias of adtelligent)

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, exchange/bidder.go, exchange/bidder_test.go, exchange/exchange.go, exchange/utils.go, openrtb_ext/imp.go, stored_responses/stored_responses.go, stored_responses/stored_responses_test.go
Implementation of "replaceImpid" from issue https://github.com/prebid/prebid-server/issues/2210
=> Added replace imp id to stored bid responses

endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go
Hi, 
This is the fix proposal for  #2300
=> Fix for missed Http.Referer

firstpartydata/first_party_data.go, firstpartydata/first_party_data_test.go, firstpartydata/tests/extractfpdforbidders/req-empty-user-fpd-not-empty-user.json, firstpartydata/tests/extractfpdforbidders/two-bidders-with-incorrect-fpd.json
Fix for fpd bidder specific user and no user in request, 
https://github.com/prebid/prebid-server/issues/2234
=> FPD bidder specific user 

adapters/boldwin/boldwin.go, adapters/boldwin/boldwin_test.go, adapters/boldwin/boldwintest/exemplary/endpointId.json, adapters/boldwin/boldwintest/exemplary/simple-banner.json, adapters/boldwin/boldwintest/exemplary/simple-native.json, adapters/boldwin/boldwintest/exemplary/simple-video.json, adapters/boldwin/boldwintest/exemplary/simple-web-banner.json, adapters/boldwin/boldwintest/supplemental/bad_media_type.json, adapters/boldwin/boldwintest/supplemental/bad_response.json, adapters/boldwin/boldwintest/supplemental/status-204.json, adapters/boldwin/boldwintest/supplemental/status-not-200.json, adapters/boldwin/params_test.go, config/config.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_boldwin.go, static/bidder-info/boldwin.yaml, static/bidder-params/boldwin.json
doc - https://github.com/prebid/prebid.github.io/pull/3921
=> New Adapter: Boldwin

adapters/pubmatic/pubmatic.go, adapters/pubmatic/pubmatic_test.go, adapters/pubmatic/pubmatictest/exemplary/banner.json
- allow new param `prebiddealpriority`
- minor refactor
=> pubmatic adapter: add param prebiddealpriority

adapters/consumable/consumable.go, adapters/consumable/consumable/supplemental/simple-banner-eids.json
This PR adds support for User Ids
=> consumable adapter: add eid support

static/bidder-info/logicad.yaml
This is Logicad.
I am sending a pull request to update our user sync domain. Please confirm.
=> Logicad - Update user sync domain

adapters/pubmatic/pubmatic.go, adapters/pubmatic/pubmatic_test.go, adapters/pubmatic/pubmatictest/exemplary/banner.json, adapters/pubmatic/pubmatictest/exemplary/native.json, adapters/pubmatic/pubmatictest/exemplary/video.json, adapters/pubmatic/pubmatictest/supplemental/app.json, adapters/pubmatic/pubmatictest/supplemental/dctrAndPmZoneID.json, adapters/pubmatic/pubmatictest/supplemental/extra-bid.json, adapters/pubmatic/pubmatictest/supplemental/gptSlotNameInImpExt.json, adapters/pubmatic/pubmatictest/supplemental/gptSlotNameInImpExtPbAdslot.json, adapters/pubmatic/pubmatictest/supplemental/multiplemedia.json, adapters/pubmatic/pubmatictest/supplemental/native_invalid_adm.json, adapters/pubmatic/pubmatictest/supplemental/nilReqExt.json, adapters/pubmatic/pubmatictest/supplemental/noAdSlot.json, adapters/pubmatic/pubmatictest/supplemental/pmZoneIDInKeywords.json, adapters/pubmatic/pubmatictest/supplemental/reqBidderParams.json, adapters/pubmatic/pubmatictest/supplemental/trimPublisherID.json, exchange/exchange.go
- PubMatic adapter: Pass alternatebiddercodes list to SSP
- PubMatic adapter: Bug fix, do not omit request.ext.prebid
=> pubmatic: pass alternatebiddercodes to its adserver

adapters/yieldone/yieldone.go
=> Set Currency to bidResponse for yieldone

adapters/smaato/native.go, adapters/smaato/native_test.go, adapters/smaato/smaato.go, adapters/smaato/smaatotest/exemplary/multiple-impressions.json, adapters/smaato/smaatotest/exemplary/multiple-media-types.json, adapters/smaato/smaatotest/exemplary/native.json, adapters/smaato/smaatotest/exemplary/simple-banner-app.json, adapters/smaato/smaatotest/exemplary/simple-banner-richMedia-app.json, adapters/smaato/smaatotest/exemplary/simple-banner-richMedia.json, adapters/smaato/smaatotest/exemplary/simple-banner.json, adapters/smaato/smaatotest/exemplary/video-app.json, adapters/smaato/smaatotest/supplemental/adtype-header-response.json, adapters/smaato/smaatotest/supplemental/bad-adm-response.json, adapters/smaato/smaatotest/supplemental/bad-adtype-header-response.json, adapters/smaato/smaatotest/supplemental/bad-expires-header-response.json, adapters/smaato/smaatotest/supplemental/bad-media-type-request.json, adapters/smaato/smaatotest/supplemental/bad-status-code-response.json, adapters/smaato/smaatotest/supplemental/banner-w-and-h.json, adapters/smaato/smaatotest/supplemental/expires-header-response.json, adapters/smaato/smaatotest/supplemental/no-bid-response.json, adapters/smaato/smaatotest/supplemental/no-consent-info-request.json, adapters/smaato/smaatotest/supplemental/outdated-expires-header-response.json, adapters/smaato/smaatotest/video/multiple-adpods.json, adapters/smaato/smaatotest/video/single-adpod.json, adapters/smaato/smaatotest/videosupplemental/bad-adm-response.json, adapters/smaato/smaatotest/videosupplemental/bad-bid-ext-response.json, static/bidder-info/smaato.yaml
=> Smaato: Add Native

static/bidder-info/triplelift_native.yaml
Adding Triplelift's native endpoint to our config
cc: @nllerandi3lift
=> Triplelift: adding native endpoint

gdpr/impl.go, gdpr/impl_test.go
Currently the GDPR logic blocks bid requests and strips geo information if the consent string is empty or malformed.
Instead, according to the requirements, in these scenarios we should:
- only block bid requests if purpose 2 enforcement is enabled
- only strip geo information if feature 1 enforcement is enabled
=> GDPR: allow bid requests if purpose 2 enforcement is disabled

adapters/bliink/params_test.go, openrtb_ext/imp_bliink.go, static/bidder-params/bliink.json
Bliink bidder parameters added
=> bliink: bidder parameters added

static/bidder-info/synacormedia.yaml
=> Removed iframe/redirect usersync urls in synacormedia config

.github/workflows/cross-repo-issue.yml
The PBS version of the workflow added in https://github.com/prebid/prebid-cache/pull/123
=> cross-repo workflow

exchange/price_granularity.go, exchange/price_granularity_test.go
Fix for https://github.com/prebid/prebid-server/issues/2469
=> Changed price bucket calculation logic to start increment at bucketMin

adapters/openx/openx.go, adapters/openx/openxtest/exemplary/fledge-no-bids.json, adapters/openx/openxtest/exemplary/fledge.json
Add FLEDGE support in openx adapter, following up on #2445
=> openx: add FLEDGE support

.github/workflows/issue_prioritization.yml
Update the issue tracker action to reflect changes in the GH API. See also https://github.com/prebid/Prebid.js/pull/9466/
=> Issue tracker fix

adapters/adsinteractive/adsinteractive.go, adapters/adsinteractive/adsinteractive_test.go, adapters/adsinteractive/adsinteractivetest/exemplary/banner.json, adapters/adsinteractive/adsinteractivetest/supplemental/bad-request-400.json, adapters/adsinteractive/adsinteractivetest/supplemental/bad-response.json, adapters/adsinteractive/adsinteractivetest/supplemental/no-content-204.json, adapters/adsinteractive/adsinteractivetest/supplemental/service-unavailable-503.json, adapters/adsinteractive/params_test.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_adsinteractive.go, static/bidder-info/adsinteractive.yaml, static/bidder-params/adsinteractive.json
Dear Prebid Team!
This is our first attempt on registering an adapter to the Prebid Server. Please review the code, and send us any suggestions you seem appropriate. Thank you in advance
=> New Adapter: Adsinteractive

adapters/kiviads/kiviads.go, adapters/kiviads/kiviads_test.go, adapters/kiviads/kiviadstest/exemplary/endpointId.json, adapters/kiviads/kiviadstest/exemplary/simple-banner.json, adapters/kiviads/kiviadstest/exemplary/simple-native.json, adapters/kiviads/kiviadstest/exemplary/simple-video.json, adapters/kiviads/kiviadstest/exemplary/simple-web-banner.json, adapters/kiviads/kiviadstest/supplemental/bad_media_type.json, adapters/kiviads/kiviadstest/supplemental/bad_response.json, adapters/kiviads/kiviadstest/supplemental/status-204.json, adapters/kiviads/kiviadstest/supplemental/status-not-200.json, adapters/kiviads/params_test.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_kiviads.go, static/bidder-info/kiviads.yaml, static/bidder-params/kiviads.json
doc - https://github.com/prebid/prebid.github.io/pull/4126
=> New Adapter: KiviAds

adapters/smaato/smaatotest/exemplary/native.json, adapters/smaato/smaatotest/exemplary/simple-banner.json, adapters/smaato/smaatotest/exemplary/video.json
Added a test for Smaato adapter to ensure that gpp data is being sent when set
=> Smaato: add gpp and gpp_sid into json to ensure it is being sent

.github/workflows/cross-repo-issue.yml
researched why forked repos weren't happy with this workflow. Have reason to believe this may fix it.
=> cross-repo workflow update

adapters/criteo/criteo_test.go, adapters/criteo/criteotest/exemplary/simple-banner-cookie-uid.json, adapters/criteo/criteotest/exemplary/simple-banner-inapp.json, adapters/criteo/criteotest/exemplary/simple-banner-multiple-bids.json, adapters/criteo/criteotest/exemplary/simple-banner-uid.json, adapters/criteo/criteotest/supplemental/204-response-from-target.json, adapters/criteo/criteotest/supplemental/400-response-from-target.json, adapters/criteo/criteotest/supplemental/500-response-from-target.json, adapters/criteo/criteotest/supplemental/simple-banner-with-ipv6.json, static/bidder-info/criteo.yaml
Update production endpoint.
Setup the redirect url.
=> Criteo : Add user sync url for criteo

endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, ortb/default.go, ortb/default_test.go, util/httputil/httputil.go, util/httputil/httputil_test.go
Implements https://github.com/synta/prebid-server/issues/2478
=> Default imp.secure To 1

endpoints/cookie_sync.go, endpoints/cookie_sync_test.go, usersync/chooser.go, usersync/chooser_test.go
The syncer key wasn't properly provided to the syncer specific metric.
=> Fix syncer_requests Metric

adapters/appnexus/appnexus.go, adapters/appnexus/models.go
This PR also removes unused struct in the adapter.
=> AppNexus adapter - move struct to its own file

static/bidder-info/between.yaml
* Change the gdpr_consent get parameter: `gdpr_consent` —> `consent`
=> Between: change a get parameter in userSync url

adapters/appnexus/appnexustest/exemplary/simple-banner.json, adapters/appnexus/appnexustest/supplemental/legacy-params.json, adapters/appnexus/appnexustest/supplemental/multiple-member-ids.json, adapters/appnexus/appnexustest/supplemental/no-placementId-and-member-invcode.json, adapters/appnexus/appnexustest/supplemental/status-400.json
This PR adds test cases to cover all the possible code paths in the appnexus adapter code.
=> Appnexus: Increase Code Coverage

static/bidder-info/madvertise.yaml
Fixing https://github.com/prebid/prebid-server/issues/2626
=> Madvertise adapter: update email

static/bidder-info/adyoulike.yaml
=> adyoulike: update endpoint

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/amp_auction_test.go, exchange/exchange.go, exchange/exchangetest/firstpartydata-amp-imp-ext-one-prebid-bidder.json
Implementation of https://github.com/prebid/prebid-server/issues/1727
=> FPD for amp endpoint

static/bidder-info/adsinteractive.yaml
Dear Prebid Team!
We added  a usersync endpoint to our existing adapter, please review and let us know if there's anything further we must set in order for it to work.
=> adsinteractive: added usersync endpoint

.github/workflows/security.yml, .github/workflows/validate-merge.yml, .github/workflows/validate.yml
The workflows are tested on the [forked repo](https://github.com/Sonali-More-Xandr/prebid-server/actions)
=> Update actions to use newer version to support node.js 16

adapters/axis/axis.go, adapters/axis/axis_test.go, adapters/axis/axistest/exemplary/simple-banner.json, adapters/axis/axistest/exemplary/simple-native.json, adapters/axis/axistest/exemplary/simple-video.json, adapters/axis/axistest/exemplary/simple-web-banner.json, adapters/axis/axistest/supplemental/bad_media_type.json, adapters/axis/axistest/supplemental/bad_response.json, adapters/axis/axistest/supplemental/status-204.json, adapters/axis/axistest/supplemental/status-not-200.json, adapters/axis/params_test.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_axis.go, static/bidder-info/axis.yaml, static/bidder-params/axis.json
doc - https://github.com/prebid/prebid.github.io/pull/4424
=> New Adapter: Axis

exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/adsyield.yaml, static/bidder-params/adsyield.json
Docs: https://github.com/prebid/prebid.github.io/pull/4533
=> New adapter: Adsyield

exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/copper6.yaml, static/bidder-params/copper6.json
Doc: https://github.com/prebid/prebid.github.io/pull/4587
=> New Alias: copper6 (adtelligent alias)

adapters/appnexus/appnexus.go, adapters/appnexus/appnexustest/supplemental/multiple-member-ids.json
This PR 
1. adds capacity to memberIds and uniqueMemberIds
2. returns error in case of multiple memberIds
=> Appnexus: Return error in case of multiple memberIds

adapters/huaweiads/huaweiads.go, adapters/huaweiads/huaweiadstest/exemplary/banner2.json
modified the function convertCountryCode to accept Alpha2 country code
=> HuaweiAds: accept Alpha2 country code

adapters/huaweiads/huaweiads.go, adapters/huaweiads/huaweiadstest/exemplary/banner1_without_userext.json
=> HuaweiAds: Handle getDeviceIDFromUserExt when ifa and user.ext are set

adapters/smaato/smaato.go, adapters/smaato/smaatotest/exemplary/multiple-impressions-skadn.json, adapters/smaato/smaatotest/exemplary/multiple-media-types-skadn.json, adapters/smaato/smaatotest/exemplary/multiple-media-types.json, adapters/smaato/smaatotest/exemplary/native.json, adapters/smaato/smaatotest/exemplary/simple-banner-app.json, adapters/smaato/smaatotest/exemplary/simple-banner-richMedia-app.json, adapters/smaato/smaatotest/exemplary/simple-banner-richMedia.json, adapters/smaato/smaatotest/exemplary/simple-banner-skadn.json, adapters/smaato/smaatotest/exemplary/video-app.json, adapters/smaato/smaatotest/exemplary/video.json, adapters/smaato/smaatotest/supplemental/adtype-header-response.json, adapters/smaato/smaatotest/supplemental/bad-adm-response.json, adapters/smaato/smaatotest/supplemental/bad-adtype-header-response.json, adapters/smaato/smaatotest/supplemental/bad-expires-header-response.json, adapters/smaato/smaatotest/supplemental/bad-skadn-format-request.json, adapters/smaato/smaatotest/supplemental/bad-status-code-response.json, adapters/smaato/smaatotest/supplemental/banner-w-and-h.json, adapters/smaato/smaatotest/supplemental/expires-header-response.json, adapters/smaato/smaatotest/supplemental/no-bid-response.json, adapters/smaato/smaatotest/supplemental/no-consent-info-request.json, adapters/smaato/smaatotest/supplemental/outdated-expires-header-response.json, adapters/smaato/smaatotest/video/multiple-adpods-skadn.json, adapters/smaato/smaatotest/video/single-adpod-skadn.json, adapters/smaato/smaatotest/video/single-adpod.json, adapters/smaato/smaatotest/videosupplemental/bad-adm-response.json, adapters/smaato/smaatotest/videosupplemental/bad-bid-ext-response.json, adapters/smaato/smaatotest/videosupplemental/bad-skadn-format-request.json, openrtb_ext/imp_smaato.go
=> Smaato: Add SKAdNetwork

static/bidder-info/smartadserver.yaml
I have confirmed that the old email is dead and the new one is responsive.
=> Update SmartAdserver email contact

static/bidder-info/ucfunnel.yaml
found this out the hard way, confirmed with the maintainers.
=> UCFunnel: added note about requiring registration

adapters/consumable/consumable.go, adapters/consumable/consumable/supplemental/simple-banner-gpp.json, static/bidder-info/consumable.yaml
=> Consumable adapter: add gpp support

adapters/pwbid/pwbid_test.go, adapters/pwbid/pwbidtest/exemplary/banner.json, adapters/pwbid/pwbidtest/exemplary/native.json, adapters/pwbid/pwbidtest/exemplary/optional-params.json, adapters/pwbid/pwbidtest/exemplary/video.json, adapters/pwbid/pwbidtest/supplemental/response-200-without-body.json, adapters/pwbid/pwbidtest/supplemental/response-204.json, adapters/pwbid/pwbidtest/supplemental/response-400.json, adapters/pwbid/pwbidtest/supplemental/response-500.json, static/bidder-info/pwbid.yaml
This update changes the default bidder endpoint for PWBID to the current default.
=> PWBID: Update Default Endpoint

static/bidder-info/adkernel.yaml
Added GPP info forwarding for user syncs.
=> Adkernel Adaptor: GPP support

.github/workflows/semgrep.yml
PR makes changes to limit semgrep action write permission to pull request
=> limit semgrep  permission to pull request

.github/workflows/semgrep.yml
PR updates semgrep check to specify which branch to check out
=> specify branch to check out

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/auction.go, endpoints/openrtb2/video_auction.go, exchange/exchange.go, exchange/exchange_test.go, metrics/prometheus/prometheus.go
PR makes changes, to record `AuctionResponse` preparation time
=> record  `PBS-auction-response` preparation time

adapters/rtbhouse/rtbhouse.go, adapters/rtbhouse/rtbhousetest/exemplary/currency-conversion.json, adapters/rtbhouse/rtbhousetest/exemplary/simple-banner.json, adapters/rtbhouse/rtbhousetest/supplemental/bad_response.json, adapters/rtbhouse/rtbhousetest/supplemental/currency-missing-conversion.json, adapters/rtbhouse/rtbhousetest/supplemental/status_204.json, adapters/rtbhouse/rtbhousetest/supplemental/status_400.json, adapters/rtbhouse/rtbhousetest/supplemental/status_418.json, openrtb_ext/imp_rtbhouse.go, static/bidder-info/rtbhouse.yaml, static/bidder-params/rtbhouse.json
- currency and floors support
- bidder params update
- bidder config update
=> RTB House: currency and floors support & config update

adapters/screencore/params_test.go, adapters/screencore/screencore.go, adapters/screencore/screencore_test.go, adapters/screencore/screencoretest/exemplary/banner-app.json, adapters/screencore/screencoretest/exemplary/banner-web.json, adapters/screencore/screencoretest/exemplary/native-app.json, adapters/screencore/screencoretest/exemplary/native-web.json, adapters/screencore/screencoretest/exemplary/video-app.json, adapters/screencore/screencoretest/exemplary/video-web.json, adapters/screencore/screencoretest/supplemental/bad_media_type.json, adapters/screencore/screencoretest/supplemental/empty-imp-array.json, adapters/screencore/screencoretest/supplemental/empty-seatbid-array.json, adapters/screencore/screencoretest/supplemental/invalid-bidder-ext-object.json, adapters/screencore/screencoretest/supplemental/invalid-response.json, adapters/screencore/screencoretest/supplemental/invalid-screencore-ext-object.json, adapters/screencore/screencoretest/supplemental/status-code-bad-request.json, adapters/screencore/screencoretest/supplemental/status-code-no-content.json, adapters/screencore/screencoretest/supplemental/status-code-other-error.json, adapters/screencore/screencoretest/supplemental/status-code-service-unavailable.json, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_screencore.go, static/bidder-info/screencore.yaml, static/bidder-params/screencore.json
Link to doc - https://github.com/prebid/prebid.github.io/pull/4760
=> New adapter: Screencore

static/bidder-info/conversant.yaml
Add consent tags to the Conversant sync endpoint
=> Conversant: Add consent strings to the user sync pixel

adapters/ix/ix.go, adapters/ix/ixtest/exemplary/app-site-id.json, adapters/ix/ixtest/supplemental/app-site-id-publisher.json, adapters/ix/ixtest/supplemental/sid.json
Signals app.publisher.id in IX Bid Adapter
Related to issue: https://github.com/prebid/prebid-server/issues/2849
=> IX Bid Adapter:  support signaling app.publisher.id

exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/xtrmqb.yaml, static/bidder-params/xtrmqb.json
Docs: https://github.com/prebid/prebid.github.io/pull/4772
=> New adapter: XTRM QB

adapters/adkernel/adkernel.go, adapters/adkernel/adkerneltest/exemplary/single-banner-impression.json
Populate pbs bid currency from adkernel response
=> Adkernel Adapter:  Add currency response forwarding

static/bidder-info/huaweiads.yaml
Fixing https://github.com/prebid/prebid-server/issues/2626
=> Update HuaweiAds email

exchange/adapter_builders.go, openrtb_ext/bidders.go, static/bidder-info/greedygame.yaml, static/bidder-params/greedygame.json
Docs: https://github.com/prebid/prebid.github.io/pull/4850
=> New adapter: GreedyGame

config/account.go, exchange/exchange.go, exchange/utils.go, exchange/utils_test.go
This pr contains changes to adjust the  imp.BidFloor for each bidder request  using the BidAdjustmentFactors
PRD:
https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0/edit#heading=h.6lovavdxmitt
=> Adjust imp.BidFloor using BidAdjustment

exchange/adapter_util.go, exchange/adapter_util_test.go
This PR enables adapter alias feature.
=> Enable adapter alias feature

adapters/lemmadigital/lemmadigital.go, adapters/lemmadigital/lemmadigital_test.go, adapters/lemmadigital/lemmadigitaltest/exemplary/banner.json, adapters/lemmadigital/lemmadigitaltest/exemplary/multi-imp.json, adapters/lemmadigital/lemmadigitaltest/exemplary/video.json, adapters/lemmadigital/lemmadigitaltest/supplemental/empty-imps.json, adapters/lemmadigital/lemmadigitaltest/supplemental/empty-seatbid-array.json, adapters/lemmadigital/lemmadigitaltest/supplemental/invalid-ld-ext-bidder-object.json, adapters/lemmadigital/lemmadigitaltest/supplemental/invalid-ld-ext-object.json, adapters/lemmadigital/lemmadigitaltest/supplemental/invalid-response.json, adapters/lemmadigital/lemmadigitaltest/supplemental/status-code-bad-request.json, adapters/lemmadigital/lemmadigitaltest/supplemental/status-code-no-content.json, adapters/lemmadigital/lemmadigitaltest/supplemental/status-code-other-error.json, adapters/lemmadigital/params_test.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_lemmadigital.go, static/bidder-info/lemmadigital.yaml, static/bidder-params/lemmadigital.json
=> New Adapter: LemmaDigital

static/bidder-info/liftoff.yaml
=> Liftoff: Update contact email address

static/bidder-info/indicue.yaml
add indicue alias
Doc: https://github.com/prebid/prebid.github.io/pull/4981
=> New Adapter: Indicue

static/bidder-info/embimedia.yaml
Docs: https://github.com/prebid/prebid.github.io/pull/4998
=> New Adapter: Embi media

adapters/dxkulture/dxkulture_test.go, adapters/dxkulture/dxkulturetest/exemplary/banner.json, adapters/dxkulture/dxkulturetest/exemplary/empty-site-domain-ref.json, adapters/dxkulture/dxkulturetest/exemplary/ipv6.json, adapters/dxkulture/dxkulturetest/exemplary/video-test-request.json, adapters/dxkulture/dxkulturetest/exemplary/video.json, adapters/dxkulture/dxkulturetest/supplemental/invalid-response.json, adapters/dxkulture/dxkulturetest/supplemental/no-mtype.json, adapters/dxkulture/dxkulturetest/supplemental/status-code-bad-request.json, adapters/dxkulture/dxkulturetest/supplemental/status-code-no-content.json, adapters/dxkulture/dxkulturetest/supplemental/status-code-other-error.json, static/bidder-info/dxkulture.yaml
Changes:
1. Change domain from `kulture.media` to `dxkulture.com`
2. Change contact email address from `devops@kulture.media` to `devops@dxkulture.com`
=> DXKulture: Change domain

static/bidder-info/rise.yaml
Resolves issue https://github.com/prebid/prebid-server/issues/3356
I confirmed with Rise this is ok.
=> Rise: Allow vast modification

static/bidder-info/smartyads.yaml
Hi, I've updated smartyads.yaml file with gvlVendorID
=> Smartyads: add Vendor id

adapters/yandex/params_test.go, adapters/yandex/yandex.go, adapters/yandex/yandex_test.go, adapters/yandex/yandextest/exemplary/native.json, adapters/yandex/yandextest/exemplary/simple-banner.json, adapters/yandex/yandextest/supplemental/multiple-imps-some-malformed.json, adapters/yandex/yandextest/supplemental/multiple-imps.json, adapters/yandex/yandextest/supplemental/simple-banner-empty-response.json, adapters/yandex/yandextest/supplemental/simple-banner-empty-seatbid.json, adapters/yandex/yandextest/supplemental/simple-banner-sizes.json, adapters/yandex/yandextest/supplemental/simple-banner-status-400.json, adapters/yandex/yandextest/supplemental/simple-banner-unknown-imp.json, adapters/yandex/yandextest/supplemental/simple-banner-unparsable-body.json, adapters/yandex/yandextest/supplemental/unknown-banner.json, exchange/adapter_builders.go, macros/macros.go, openrtb_ext/bidders.go, openrtb_ext/imp_yandex.go, static/bidder-info/yandex.yaml, static/bidder-params/yandex.json
PBS Go Docs: https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html
PBS Java Docs: https://docs.prebid.org/prebid-server/developers/add-new-bidder-java.html
PBS Java Yandex Adapter: https://github.com/prebid/prebid-server-java/blob/master/src/main/java/org/prebid/server/bidder/yandex/YandexBidder.java
Closes #2693
=> Yandex: add adapter

analytics/build/build.go
Fixes an incompatbility in the master branch after merging in https://github.com/prebid/prebid-server/pull/3387.
=> Fix OpenRTB 202309 Merge Conflict

exchange/bidder.go, exchange/bidder_validate_bids.go, exchange/bidder_validate_bids_test.go, exchange/exchange.go, exchange/exchange_test.go
Addresses https://github.com/prebid/prebid-server/issues/1973
=> Add $0 Bid Price Warning only if in Debug Mode

adapters/nextmillennium/nextmillennium.go, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-empty-group-id.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-group-id.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-group-id_app.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-only-width.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-with-wh.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-wo-domain.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner-wo-size.json, adapters/nextmillennium/nextmillenniumtest/exemplary/banner.json, adapters/nextmillennium/nextmillenniumtest/exemplary/empty-banner-obj.json, adapters/nextmillennium/nextmillenniumtest/exemplary/video.json, adapters/nextmillennium/nextmillenniumtest/supplemental/empty-seatbid.json, adapters/nextmillennium/nextmillenniumtest/supplemental/error-response.json, adapters/nextmillennium/nextmillenniumtest/supplemental/no-content.json, static/bidder-info/nextmillennium.yaml
- added video support for adapter
- fixed missing server object in ext.prebid field
=> Nextmillennium: add video support & fix server object

adapters/ix/ixtest/supplemental/dsa-request.json
This PR adds a test case for passing through / returning DSA information
=> IX: Add DSA test

dsa/validate.go, dsa/validate_test.go, errortypes/code.go, exchange/exchange.go, exchange/exchange_test.go, openrtb_ext/bid.go, openrtb_ext/regs.go, openrtb_ext/request_wrapper_test.go
=> DSA: Bid response adrender, behalf & paid validations

static/bidder-info/rtbhouse.yaml
Regional endpoints made available.
Relates to https://github.com/prebid/prebid-server-java/pull/3023
Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).
=> RTB House: regional endpoints

adapters/iqzone/iqzone.go, adapters/iqzone/iqzonetest/exemplary/endpointId.json, adapters/iqzone/iqzonetest/exemplary/simple-banner.json, adapters/iqzone/iqzonetest/exemplary/simple-native.json, adapters/iqzone/iqzonetest/exemplary/simple-video.json, adapters/iqzone/iqzonetest/exemplary/simple-web-banner.json, adapters/iqzone/iqzonetest/supplemental/bad_media_type.json
Hi! 
We need to support getting bid media type from seatbid.mtype
=> iqzone get media type from mtype bid property

analytics/build/build.go, analytics/build/build_test.go
NPE fix for nil request coming to the analytics module in case of invalid request (like bidder params incorrect type)
=> Fix for NPE for nil request in analytics module

adapters/smrtconnect/smrtconnect.go, adapters/smrtconnect/smrtconnect_test.go, adapters/smrtconnect/smrtconnecttest/exemplary/audio-app.json, adapters/smrtconnect/smrtconnecttest/exemplary/audio-web.json, adapters/smrtconnect/smrtconnecttest/exemplary/banner-app.json, adapters/smrtconnect/smrtconnecttest/exemplary/banner-multiple-bids.json, adapters/smrtconnect/smrtconnecttest/exemplary/banner-web.json, adapters/smrtconnect/smrtconnecttest/exemplary/native-app.json, adapters/smrtconnect/smrtconnecttest/exemplary/native-web.json, adapters/smrtconnect/smrtconnecttest/exemplary/video-app.json, adapters/smrtconnect/smrtconnecttest/exemplary/video-web.json, adapters/smrtconnect/smrtconnecttest/supplemental/empty-seatbid-array.json, adapters/smrtconnect/smrtconnecttest/supplemental/invalid-aceex-ext-object.json, adapters/smrtconnect/smrtconnecttest/supplemental/invalid-response.json, adapters/smrtconnect/smrtconnecttest/supplemental/status-code-bad-request.json, adapters/smrtconnect/smrtconnecttest/supplemental/status-code-no-content.json, adapters/smrtconnect/smrtconnecttest/supplemental/status-code-other-error.json, adapters/smrtconnect/smrtconnecttest/supplemental/status-code-service-unavailable.json, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_smrtconnect.go, static/bidder-info/smrtconnect.yaml, static/bidder-params/smrtconnect.json
=> New adapter: Smrtconnect

static/bidder-info/axonix.yaml
Added `userSync` section for Axonix adapter.
=> Axonix: Add userSync

static/bidder-info/ix.yaml
Indicates support for openrtb 2.6 fox IX adapter
=> IX: indicate support for OpenRTB 2.6

static/bidder-info/cpmstar.yaml
CPMStar: Use iframe based usersync
=> CPMStar: use iframe based usersync

adapters/rubicon/rubicon.go
@AntoxaAntoxic Please provide your review
=> Rubicon: Remove `buyeruid` logic

static/bidder-info/mabidder.yaml
=> Mabidder Adapter: set geoscope to CAN

adapters/yeahmobi/yeahmobi.go, adapters/yeahmobi/yeahmobitest/exemplary/simple-video.json
=> Yeahmobi: Fix video bug

adapters/driftpixel/driftpixel.go, adapters/driftpixel/driftpixel_test.go, adapters/driftpixel/driftpixeltest/exemplary/banner.json, adapters/driftpixel/driftpixeltest/exemplary/multi-format.json, adapters/driftpixel/driftpixeltest/exemplary/multi-imp-banner.json, adapters/driftpixel/driftpixeltest/exemplary/native.json, adapters/driftpixel/driftpixeltest/exemplary/video.json, adapters/driftpixel/driftpixeltest/supplemental/bad-response.json, adapters/driftpixel/driftpixeltest/supplemental/empty-mediatype.json, adapters/driftpixel/driftpixeltest/supplemental/empty-seatbid-0-bid.json, adapters/driftpixel/driftpixeltest/supplemental/empty-seatbid.json, adapters/driftpixel/driftpixeltest/supplemental/invalid-ext-bidder-object.json, adapters/driftpixel/driftpixeltest/supplemental/invalid-ext-object.json, adapters/driftpixel/driftpixeltest/supplemental/invalid-mediatype.json, adapters/driftpixel/driftpixeltest/supplemental/status-204.json, adapters/driftpixel/driftpixeltest/supplemental/status-400.json, adapters/driftpixel/driftpixeltest/supplemental/status-503.json, adapters/driftpixel/driftpixeltest/supplemental/unexpected-status.json, adapters/driftpixel/params_test.go, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_driftpixel.go, static/bidder-info/driftpixel.yaml, static/bidder-params/driftpixel.json
Dev docs: https://github.com/prebid/prebid.github.io/pull/5302
=> New Adapter: Driftpixel

static/bidder-info/ownadx.yaml
We are going to compatible for Cookie sync
=> OwnAdx: Add cookie sync

static/bidder-info/conversant.yaml, static/bidder-info/epsilon.yaml
Updating yaml descriptions for Epsilon/Conversant bidder to show updated support
=> Epsilon / Conversant: Endpoint & supported openrtb version update

static/bidder-info/filmzie.yaml
Docs PR: https://github.com/prebid/prebid.github.io/pull/5438
=> New Adapter: Filmzie

adapters/adnuntius/adnuntius.go, adapters/adnuntius/adnuntiustest/exemplary/simple-banner.json, adapters/adnuntius/adnuntiustest/supplemental/check-dealId.json, adapters/adnuntius/adnuntiustest/supplemental/check-gdpr.json, adapters/adnuntius/adnuntiustest/supplemental/check-gross-bids.json, adapters/adnuntius/adnuntiustest/supplemental/check-net-bids.json, adapters/adnuntius/adnuntiustest/supplemental/check-noCookies-parameter.json, adapters/adnuntius/adnuntiustest/supplemental/check-noCookies.json, adapters/adnuntius/adnuntiustest/supplemental/check-order-multi-imp.json, adapters/adnuntius/adnuntiustest/supplemental/check-userId.json, adapters/adnuntius/adnuntiustest/supplemental/empty-regs-ext.json, adapters/adnuntius/adnuntiustest/supplemental/empty-regs.json, adapters/adnuntius/adnuntiustest/supplemental/height-error.json, adapters/adnuntius/adnuntiustest/supplemental/max-deals-test.json, adapters/adnuntius/adnuntiustest/supplemental/send-header-information.json, adapters/adnuntius/adnuntiustest/supplemental/site-ext.json, adapters/adnuntius/adnuntiustest/supplemental/size-check.json, adapters/adnuntius/adnuntiustest/supplemental/status-400.json, adapters/adnuntius/adnuntiustest/supplemental/test-networks.json, adapters/adnuntius/adnuntiustest/supplemental/user-ext.json, adapters/adnuntius/adnuntiustest/supplemental/width-error.json
Instead of `format=json`, use `format=prebid` in adserver requests.
=> Adnuntius: Use format=prebid on adserver requests.

adapters/pubrise/params_test.go, adapters/pubrise/pubrise.go, adapters/pubrise/pubrise_test.go, adapters/pubrise/pubrisetest/exemplary/endpointId.json, adapters/pubrise/pubrisetest/exemplary/multi-format.json, adapters/pubrise/pubrisetest/exemplary/multi-imp.json, adapters/pubrise/pubrisetest/exemplary/simple-banner.json, adapters/pubrise/pubrisetest/exemplary/simple-native.json, adapters/pubrise/pubrisetest/exemplary/simple-video.json, adapters/pubrise/pubrisetest/exemplary/simple-web-banner.json, adapters/pubrise/pubrisetest/supplemental/bad_media_type.json, adapters/pubrise/pubrisetest/supplemental/bad_response.json, adapters/pubrise/pubrisetest/supplemental/no-valid-impressions.json, adapters/pubrise/pubrisetest/supplemental/status-204.json, adapters/pubrise/pubrisetest/supplemental/status-not-200.json, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_pubrise.go, static/bidder-info/pubrise.yaml, static/bidder-params/pubrise.json
doc - https://github.com/prebid/prebid.github.io/pull/5520
=> New Adapter: Pubrise

static/bidder-info/smartx.yaml
denote that Smartclip is openrtb 2.6 compliant
=> Smartx: Declare OpenRTB 2.6 support

static/bidder-info/embimedia.yaml, static/bidder-info/tgm.yaml
Docs: https://github.com/prebid/prebid.github.io/pull/5535
=> New Adapter: TGM

static/bidder-info/embimedia.yaml, static/bidder-info/streamlyn.yaml
Docs https://github.com/prebid/prebid.github.io/pull/5579
=> New Adapter: Streamlyn 

endpoints/openrtb2/amp_auction.go, endpoints/openrtb2/amp_auction_test.go, endpoints/openrtb2/auction.go, endpoints/openrtb2/sample-requests/invalid-whole/regs-ext-malformed.json, endpoints/openrtb2/sample-requests/invalid-whole/user-ext-consent-int.json, endpoints/openrtb2/sample-requests/invalid-whole/user-gdpr-consent-invalid.json, endpoints/openrtb2/sample-requests/valid-whole/supplementary/gdpr-conflict.json, endpoints/openrtb2/sample-requests/valid-whole/supplementary/gdpr-conflict2.json, endpoints/openrtb2/video_auction.go, endpoints/openrtb2/video_auction_test.go
Merge after https://github.com/prebid/prebid-server/pull/3953 is merged
=> Upconvert unit tests fixes

exchange/utils.go
This is the first `CleanOpenRTBRequests` refactoring step in preparation for ORTB2.6 support.
=> Refactor: Remove getAuctionBidderRequests

static/bidder-info/triplelift.yaml, static/bidder-info/triplelift_native.yaml
Triplelift adapter adding support for OpenRTB 2.6 requests.
=> Triplelift: Adding flag for 2.6 support

static/bidder-info/sovrn.yaml
Purpose of this PR is to enable Gzip compression support for Sovrn.
=> Sovrn: Enable Gzip compression

static/bidder-info/gumgum.yaml
GumGum Adapter - Adding support for OpenRTB 2.6.
=> GumGum: Declare ORTB 2.6 support

static/bidder-info/algorix.yaml
update for add Algorix gvl Vender ID.
=> AlgoriX: Add GVL vendor ID

floors/fetcher.go, floors/fetcher_test.go, floors/floors.go, floors/floors_test.go, openrtb_ext/floors.go
Modified the variable name from `fetchrate` to `usefetchdatarate`
=> Floors: Modify fetchrate to usefetchdatarate

static/bidder-info/pubmatic.yaml
PubMatic Adapter - Adding support for OpenRTB 2.6.
=> PubMatic: Declare support for OpenRTB 2.6

static/bidder-info/medianet.yaml
[prebid-server-java PR](https://github.com/prebid/prebid-server-java/pull/3661)
=> Medianet: Sanitize usersync iframe url

static/bidder-info/vrtcal.yaml
oRTB 2.6 support flag updated due to the back end now supporting
=> vrtcal: Declare ORTB 2.6 support

static/bidder-info/addigi.yaml
Add new Addigi adapter/alias
Docs:  https://github.com/prebid/prebid.github.io/pull/5836
=> New Adapter: Addigi - Attekmi (SmartHub) Alias

static/bidder-info/jambojar.yaml
Docs: https://github.com/prebid/prebid.github.io/pull/5874
=> New Adapter: Jambojar - Attekmi (SmartHub) Alias

static/bidder-info/adinify.yaml
Please add new Adinify adapter/alias 
Docs: https://github.com/prebid/prebid.github.io/pull/5822
=> New Adapter: Adinify - Attekmi (SmartHub) alias

static/bidder-info/artechnology.yaml
Please add new adapter/alias Artechnology
Docs: https://github.com/prebid/prebid.github.io/pull/5913
=> New Adapter: Artechnology - Attekmi (SmartHub) alias

static/bidder-info/embimedia.yaml, static/bidder-info/streamvision.yaml
https://github.com/prebid/prebid.github.io/pull/5880
=> New Adapter: Streamvision - Limelight Alias

static/bidder-info/embimedia.yaml, static/bidder-info/orangeclickmedia.yaml
https://github.com/prebid/prebid.github.io/pull/5880
=> New Adapter: OCM Media - Limelight Alias

static/bidder-info/embimedia.yaml, static/bidder-info/velonium.yaml
https://github.com/prebid/prebid.github.io/pull/5880
=> New Adapter: Velonium - Limelight Alias

static/bidder-info/trustedstack.yaml
[prebid-server-java PR](https://github.com/prebid/prebid-server-java/pull/3764)
=> Trustedstack: Add iframe usersync

static/bidder-info/iionads.yaml
https://github.com/prebid/prebid.github.io/pull/5870
=> IIon: Add GVL ID

static/bidder-info/nextmillennium.yaml
Added flat to compress requests to NextMillennium
=> Nextmillennium: Add gzip compression

adapters/smaato/smaato.go, adapters/smaato/smaatotest/exemplary/multiple-impressions-skadn.json, adapters/smaato/smaatotest/exemplary/multiple-impressions.json, adapters/smaato/smaatotest/exemplary/multiple-media-types-skadn.json, adapters/smaato/smaatotest/exemplary/multiple-media-types.json, adapters/smaato/smaatotest/exemplary/native.json, adapters/smaato/smaatotest/exemplary/simple-banner-app.json, adapters/smaato/smaatotest/exemplary/simple-banner-dooh.json, adapters/smaato/smaatotest/exemplary/simple-banner-eids.json, adapters/smaato/smaatotest/exemplary/simple-banner-skadn.json, adapters/smaato/smaatotest/exemplary/simple-banner.json, adapters/smaato/smaatotest/exemplary/video-app.json, adapters/smaato/smaatotest/exemplary/video-dooh.json, adapters/smaato/smaatotest/exemplary/video.json, adapters/smaato/smaatotest/supplemental/bad-adtype-header-response.json, adapters/smaato/smaatotest/supplemental/bad-expires-header-response.json, adapters/smaato/smaatotest/supplemental/bad-status-code-response.json, adapters/smaato/smaatotest/supplemental/banner-w-and-h.json, adapters/smaato/smaatotest/supplemental/curl-nil-response.json, adapters/smaato/smaatotest/supplemental/expires-header-response.json, adapters/smaato/smaatotest/supplemental/no-bid-response.json, adapters/smaato/smaatotest/supplemental/no-consent-info-request.json, adapters/smaato/smaatotest/supplemental/outdated-expires-header-response.json, adapters/smaato/smaatotest/video/multiple-adpods-skadn.json, adapters/smaato/smaatotest/video/multiple-adpods.json, adapters/smaato/smaatotest/video/single-adpod-skadn.json, adapters/smaato/smaatotest/video/single-adpod.json, adapters/smaato/smaatotest/videosupplemental/bad-adtype-header-response.json, adapters/smaato/smaatotest/videosupplemental/bad-bid-ext-response.json, static/bidder-info/smaato.yaml
Adding iframe url to userSync for Smaato Bid adapter
=> Smaato: Add iframe user sync

adapters/algorix/algorixtest/exemplary/sample-banner-web.json, adapters/algorix/algorixtest/exemplary/sample-native-web.json, adapters/algorix/algorixtest/exemplary/sample-video-web.json, static/bidder-info/algorix.yaml
=> Algorix: Add site support

static/bidder-info/improvedigital.yaml
Improve Digital adapter: add iframe user sync
=> Improve Digital: Add iframe user sync

static/bidder-info/inmobi.yaml
Adding support for redirect in the usersync
=> InMobi : Add redirect usersync

modules/prebid/rulesengine/cache.go, modules/prebid/rulesengine/cache_test.go, modules/prebid/rulesengine/tree_manager.go
Implements a thread safe cache as discussed offline. Substitutes #4330
=> Rules Engine Module: Cache

adapters/conversant/conversant.go, adapters/conversant/conversanttest/exemplary/simple-native.json, static/bidder-info/conversant.yaml
Add support for native requests to the conversant prebid-server adapter
=> Conversant: Enable native requests

rules/schema_functions.go, rules/schema_functions_test.go
These changes are made in accordance with https://github.com/prebid/prebid-server/pull/4346#pullrequestreview-2884450989
=> Rules Engine Module: Schema function changes

adapters/rubicon/rubicon.go, adapters/rubicon/rubicon_test.go, adapters/rubicon/rubicontest/exemplary/25-26-transition-period.json, adapters/rubicon/rubicontest/exemplary/app-imp-fpd.json, adapters/rubicon/rubicontest/exemplary/bidonmultiformat.json, adapters/rubicon/rubicontest/exemplary/flexible-schema.json, adapters/rubicon/rubicontest/exemplary/hardcode-secure.json, adapters/rubicon/rubicontest/exemplary/non-bidonmultiformat.json, adapters/rubicon/rubicontest/exemplary/simple-banner.json, adapters/rubicon/rubicontest/exemplary/simple-native.json, adapters/rubicon/rubicontest/exemplary/simple-video.json, adapters/rubicon/rubicontest/exemplary/site-imp-fpd.json, adapters/rubicon/rubicontest/exemplary/user-fpd.json, adapters/rubicon/rubicontest/supplemental/no-site-content-data.json, adapters/rubicon/rubicontest/supplemental/no-site-content.json, openrtb_ext/bid.go
Port from PBS Java: https://github.com/prebid/prebid-server-java/pull/3587
=> Rubicon: Add Bid Meta Seat

adapters/sparteo/params_test.go, adapters/sparteo/sparteo.go, adapters/sparteo/sparteo_test.go, adapters/sparteo/sparteotest/exemplary/banner.json, adapters/sparteo/sparteotest/exemplary/native.json, adapters/sparteo/sparteotest/exemplary/video.json, adapters/sparteo/sparteotest/supplemental/filter-empty-seat-bids.json, adapters/sparteo/sparteotest/supplemental/filter-invalid-bid-type.json, adapters/sparteo/sparteotest/supplemental/filter-no-seat-bids.json, adapters/sparteo/sparteotest/supplemental/invalid-bidder-ext.json, adapters/sparteo/sparteotest/supplemental/invalid-json-response.json, adapters/sparteo/sparteotest/supplemental/invalid-publisher-ext.json, adapters/sparteo/sparteotest/supplemental/status_204.json, adapters/sparteo/sparteotest/supplemental/status_400.json, adapters/sparteo/sparteotest/supplemental/status_500.json, exchange/adapter_builders.go, openrtb_ext/bidders.go, openrtb_ext/imp_sparteo.go, static/bidder-info/sparteo.yaml, static/bidder-params/sparteo.json
Prebid Docs Initial PR: https://github.com/prebid/prebid.github.io/pull/4917
Prebid Docs Update PR: https://github.com/prebid/prebid.github.io/pull/5644
=> New Adapter: Sparteo

adapters/missena/missena.go, adapters/missena/missenatest/exemplary/bid-floor-currency.json, adapters/missena/missenatest/exemplary/multiple-imps.json, adapters/missena/missenatest/exemplary/simple-banner-ipv6.json, adapters/missena/missenatest/exemplary/simple-banner.json, adapters/missena/missenatest/exemplary/valid-imp-error-imp.json, adapters/missena/missenatest/supplemental/status-204.json, adapters/missena/missenatest/supplemental/status-400.json, adapters/missena/missenatest/supplemental/status-not-200.json
update payload in order to use openrtb 2 request directly
=> Missena: Pass full openrtb request

static/bidder-info/zeta_global_ssp.yaml
Related pull request in prebid.github.io: https://github.com/prebid/prebid.github.io/pull/6101
=> Zeta Global SSP: Declare OpenRTB 2.6 and GPP support

adapters/tappx/tappx.go, adapters/tappx/tappx_test.go, adapters/tappx/tappxtest/exemplary/single-banner-impression-extra.json, adapters/tappx/tappxtest/exemplary/single-banner-impression-future-feature.json, adapters/tappx/tappxtest/exemplary/single-banner-impression.json, adapters/tappx/tappxtest/exemplary/single-banner-site.json, adapters/tappx/tappxtest/exemplary/single-video-impression.json, adapters/tappx/tappxtest/exemplary/single-video-site.json, adapters/tappx/tappxtest/supplemental/204status.json, adapters/tappx/tappxtest/supplemental/bidfloor.json, adapters/tappx/tappxtest/supplemental/gpid.json, adapters/tappx/tappxtest/supplemental/http-err-status.json, adapters/tappx/tappxtest/supplemental/http-err-status2.json
- Added GPID in the 'ext' object.
- Added test to check the obtention of GPID.
- Changed bidder version.
=> Tappx: Add GPID support

static/bidder-info/kuantyx.yaml
PBS support is already in [the docs](https://docs.prebid.org/dev-docs/bidders/kuantyx.html)
=> New Adapter: Kuantyx - Aso alias

static/bidder-info/ogury.yaml
- Add GPP for Ogury Sync for iFrame
- Add Redirect support for Ogury sync
=> Ogury: Support gpp for cookie sync

adapters/yieldlab/yieldlab.go, adapters/yieldlab/yieldlabtest/exemplary/banner.json, adapters/yieldlab/yieldlabtest/exemplary/dsa.json, adapters/yieldlab/yieldlabtest/exemplary/gdpr.json, adapters/yieldlab/yieldlabtest/exemplary/mixed_types.json, adapters/yieldlab/yieldlabtest/exemplary/multiple_impressions.json, adapters/yieldlab/yieldlabtest/exemplary/schain.json, adapters/yieldlab/yieldlabtest/exemplary/schain_multiple_nodes.json, adapters/yieldlab/yieldlabtest/exemplary/video.json, adapters/yieldlab/yieldlabtest/exemplary/video_app.json, adapters/yieldlab/yieldlabtest/supplemental/dsa_empty.json, adapters/yieldlab/yieldlabtest/supplemental/dsa_empty_transparency.json
Forward adomain from yieldlab response to openRtb bid response
A review and approval from a member of the Yieldlab team are required. (@brushmate, @flanaras, @nkloeber or @william-harris)
=> Yieldlab: Forward ADomain to OpenRTB bid

config/bidderinfo.go, config/bidderinfo_test.go, endpoints/info/bidders.go, endpoints/info/bidders_detail.go, endpoints/info/bidders_detail_test.go, endpoints/info/bidders_test.go, endpoints/openrtb2/auction.go, endpoints/openrtb2/auction_test.go, exchange/adapter_util.go, exchange/adapter_util_test.go, usersync/syncersbuilder.go, usersync/syncersbuilder_test.go
=> Define An Adapter As White Label Only

static/bidder-info/zmaticoo.yaml
action: change zmaticoo.yaml endpoint
from: bid.zmaticoo.com
to: rtbbid.zmaticoo.com
=> zMaticoo: Update endpoint

endpoints/openrtb2/test_utils.go, hooks/hookexecution/executor.go, hooks/hookexecution/mocks_test.go, hooks/hookstage/exitpoint.go, hooks/plan_test.go
Fixed Typo `ExitpointPaylaod` -> `ExitpointPayload`
=> Modules: Exitpoint Hook typo fix
